
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 15 2025 22:01:34 -03 (Sep 16 2025 01:01:34 UTC)

// Verification Directory fv/Square_root 

module Square_root(valor_i, clk, rst_n, ready_o, root_o);
  input [15:0] valor_i;
  input clk, rst_n;
  output ready_o;
  output [7:0] root_o;
  wire [15:0] valor_i;
  wire clk, rst_n;
  wire ready_o;
  wire [7:0] root_o;
  wire [1:0] DATA_PATH_S2_o_feedback_s;
  wire [12:0] DATA_PATH_S4_o_square_s;
  wire [8:0] DATA_PATH_S3_o_square_s;
  wire [3:0] DATA_PATH_S2_o_root_s;
  wire [11:0] DATA_PATH_S2_o_A_s;
  wire [16:0] DATA_PATH_S1_o_square_s;
  wire [7:0] DATA_PATH_S3_o_A_s;
  wire [7:0] DATA_PATH_S2_o_input_s;
  wire [3:0] DATA_PATH_S4_o_A_s;
  wire [7:0] DATA_PATH_S3_o_B_s;
  wire [11:0] DATA_PATH_S2_o_B_s;
  wire [7:0] DATA_PATH_S1_o_root_s;
  wire [3:0] DATA_PATH_S2_o_root_h_s;
  wire [7:0] DATA_PATH_S2_o_square_c_s;
  wire [4:0] DATA_PATH_S2_o_square_s;
  wire [15:0] DATA_PATH_S1_o_input_s;
  wire [2:0] CONTROL_PATH_CurrentState;
  wire DATA_PATH_S2_o_co_root_s, DATA_PATH_S2_o_co_square_s,
       DATA_PATH_S3_o_co_square_s, DATA_PATH_S4_o_co_square_s, N_s,
       UNCONNECTED, UNCONNECTED0, UNCONNECTED1;
  wire UNCONNECTED2, UNCONNECTED3, UNCONNECTED4, UNCONNECTED5,
       UNCONNECTED6, UNCONNECTED7, UNCONNECTED8, UNCONNECTED9;
  wire UNCONNECTED10, UNCONNECTED11, UNCONNECTED12, mux_root_s, n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_212, n_213, n_214, n_215, n_216;
  wire n_217, n_218, n_219, n_220, n_221, n_222, n_223, n_224;
  wire n_225, n_226, n_227, n_228, n_229, n_230, n_231, n_232;
  wire n_233, n_234, n_235, n_236, n_237, n_238, n_239, n_240;
  wire n_241, n_242, n_243, n_244, n_245, n_246, n_247, n_248;
  wire n_249, n_250, n_251, n_252, n_253, n_254, n_255, n_256;
  wire n_257, n_258, n_259, n_260, n_261, n_262, n_263, n_264;
  wire n_265, n_266, n_267, n_268, n_269, n_270, n_271, n_272;
  wire n_273, n_274, n_275, n_276, n_277, n_278, n_279, n_280;
  wire n_281, n_282, n_283, n_284, n_285, n_286, n_287, n_288;
  wire n_289, n_290, n_291, n_292, n_293, n_294, n_295, n_296;
  wire n_297, n_298, n_299, n_300, n_301, n_302, n_303, n_304;
  wire n_305, n_306, n_307, n_308, n_309, n_310, n_311, n_312;
  wire n_313, n_314, n_315, n_316, n_317, n_318, n_319, n_320;
  wire n_321, n_322, n_323, n_324, n_325, n_326, n_327, n_328;
  wire n_329, n_330, n_331, n_332, n_333, n_334, n_335, n_336;
  wire n_337, n_338, n_339, n_340, n_341, n_342, n_343, n_344;
  wire n_345, n_346, n_347, n_348, n_349, n_350, n_351, n_370;
  wire n_371, n_372, n_373, n_374, n_375, n_376, n_378, n_380;
  wire n_381, n_383, n_385, n_387, n_388;
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_S2_feedback_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_351), .Q
       (DATA_PATH_S2_o_feedback_s[0]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_S2_feedback_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_350), .Q
       (DATA_PATH_S2_o_feedback_s[1]));
  OAI2BB2X4 g8301__2398(.A0N (DATA_PATH_S2_o_feedback_s[0]), .A1N
       (n_242), .B0 (n_181), .B1 (n_347), .Y (n_351));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE4_square_sum_S4_reg_reg_array[12].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_348), .Q
       (DATA_PATH_S4_o_square_s[12]));
  DFFRHQX1 DATA_PATH_PIPELINE_STAGE3_S3_N_reg_sig_q_reg(.RN (rst_n),
       .CK (clk), .D (n_349), .Q (N_s));
  OAI22X4 g8300__5107(.A0 (n_199), .A1 (n_346), .B0 (n_50), .B1
       (n_335), .Y (n_350));
  DFFRHQX2
       \DATA_PATH_PIPELINE_STAGE1_S1_root_reg_reg_array[7].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_344), .Q (root_o[7]));
  DFFRHQX2
       \DATA_PATH_PIPELINE_STAGE1_S1_root_reg_reg_array[6].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_345), .Q (root_o[6]));
  OR2X6 g8316__6260(.A (n_182), .B (n_341), .Y (n_349));
  OAI21X4 g8260__4319(.A0 (n_202), .A1 (n_334), .B0 (n_332), .Y
       (n_348));
  DFFRX2 DATA_PATH_PIPELINE_STAGE3_Co_Square_S3_reg_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_339), .Q (DATA_PATH_S3_o_co_square_s),
       .QN (UNCONNECTED));
  DFFRHQX2 DATA_PATH_PIPELINE_STAGE4_Co_Square_S4_reg_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_337), .Q (DATA_PATH_S4_o_co_square_s));
  DFFRHQX1
       DATA_PATH_PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_7_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_342), .Q (DATA_PATH_S3_o_square_s[7]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE4_square_sum_S4_reg_reg_array[11].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_338), .Q
       (DATA_PATH_S4_o_square_s[11]));
  DFFRHQX1
       DATA_PATH_PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_8_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_336), .Q (DATA_PATH_S3_o_square_s[8]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE1_S1_root_reg_reg_array[5].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_340), .Q (root_o[5]));
  CLKINVX4 g8315(.A (n_346), .Y (n_347));
  OAI21X4 g8281__8428(.A0 (n_343), .A1 (n_327), .B0 (n_236), .Y
       (n_345));
  OAI21X4 g8282__5526(.A0 (n_343), .A1 (n_329), .B0 (n_235), .Y
       (n_344));
  DFFRX2 DATA_PATH_PIPELINE_STAGE2_S2_Co_Root_reg_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_333), .Q (DATA_PATH_S2_o_co_root_s),
       .QN (UNCONNECTED0));
  MX3X1 g8293__6783(.A (n_144), .B (n_145), .C
       (DATA_PATH_S3_o_square_s[7]), .S0 (n_195), .S1 (n_312), .Y
       (n_342));
  CLKAND2X2 g8336__3680(.A (n_328), .B (n_228), .Y (n_341));
  OAI22X4 g8287__1617(.A0 (n_197), .A1 (n_317), .B0 (n_3), .B1 (n_193),
       .Y (n_340));
  CLKMX2X3 g8268__2802(.A (DATA_PATH_S3_o_co_square_s), .B (n_300), .S0
       (n_184), .Y (n_339));
  AOI21X4 g8320__1705(.A0 (n_214), .A1 (n_262), .B0 (n_151), .Y
       (n_346));
  NAND2X2 g8269__5122(.A (n_273), .B (n_331), .Y (n_338));
  NAND2X2 g8270__8246(.A (n_207), .B (n_326), .Y (n_337));
  OAI22X4 g8283__7098(.A0 (n_198), .A1 (n_314), .B0 (n_8), .B1 (n_335),
       .Y (n_336));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE4_square_sum_S4_reg_reg_array[10].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_325), .Q
       (DATA_PATH_S4_o_square_s[10]));
  DFFRHQX1
       DATA_PATH_PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_6_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_322), .Q (DATA_PATH_S3_o_square_s[6]));
  DFFRHQX1
       DATA_PATH_PIPELINE_STAGE2_S2_root_reg_Reg_Root_S2_3_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_324), .Q (DATA_PATH_S2_o_root_s[3]));
  NOR2X6 g8274__6131(.A (n_204), .B (n_255), .Y (n_334));
  MX2X1 g8310__1881(.A (DATA_PATH_S2_o_co_root_s), .B (n_231), .S0
       (n_275), .Y (n_333));
  AOI2BB2X4 g8263__5115(.A0N (n_1), .A1N (n_323), .B0 (n_330), .B1
       (n_205), .Y (n_332));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE2_S2_A_high_S2_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_257), .Q (DATA_PATH_S2_o_A_s[2]));
  DFFSHQX1
       DATA_PATH_PIPELINE_STAGE4_square_sum_S4_reg_RegSumLow_0_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_258), .Q (DATA_PATH_S4_o_square_s[0]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_302), .Q
       (DATA_PATH_S1_o_square_s[0]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE3_S3_A_high_S2_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_266), .Q (DATA_PATH_S3_o_A_s[4]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE3_S3_A_high_S2_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_268), .Q (DATA_PATH_S3_o_A_s[5]));
  DFFRHQX4 DATA_PATH_PIPELINE_STAGE2_Co_Square_S2_reg_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_253), .Q (DATA_PATH_S2_o_co_square_s));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_S2_A_high_S2_reg_reg[8].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_254), .Q (DATA_PATH_S2_o_A_s[8]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_S2_A_high_S2_reg_reg[9].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_256), .Q (DATA_PATH_S2_o_A_s[9]));
  DFFRHQX1
       DATA_PATH_PIPELINE_STAGE2_S2_root_reg_Reg_Root_S2_0_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_285), .Q (DATA_PATH_S2_o_root_s[0]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE2_S2_input_high_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_287), .Q
       (DATA_PATH_S2_o_input_s[2]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE3_S3_A_high_S2_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_269), .Q (DATA_PATH_S3_o_A_s[7]));
  DFFRHQX8
       \DATA_PATH_PIPELINE_STAGE1_S1_root_reg_reg_array[4].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_276), .Q (root_o[4]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE4_S3_A_high_S2_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_315), .Q (DATA_PATH_S4_o_A_s[2]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE3_S3_A_high_S2_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_265), .Q (DATA_PATH_S3_o_A_s[3]));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE3_S3_B_high_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_271), .Q (DATA_PATH_S3_o_B_s[1]),
       .QN (UNCONNECTED1));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE2_S2_B_high_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_296), .Q (DATA_PATH_S2_o_B_s[5]),
       .QN (UNCONNECTED2));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[16].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_307), .Q
       (DATA_PATH_S1_o_square_s[16]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[15].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_283), .Q
       (DATA_PATH_S1_o_square_s[15]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[13].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_277), .Q
       (DATA_PATH_S1_o_square_s[13]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[10].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_252), .Q
       (DATA_PATH_S1_o_square_s[10]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[12].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_260), .Q
       (DATA_PATH_S1_o_square_s[12]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE3_S3_A_high_S2_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_280), .Q (DATA_PATH_S3_o_A_s[0]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[14].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_274), .Q
       (DATA_PATH_S1_o_square_s[14]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE3_S3_B_high_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_270), .Q (DATA_PATH_S3_o_B_s[0]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[11].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_259), .Q
       (DATA_PATH_S1_o_square_s[11]));
  DFFRHQX8
       \DATA_PATH_PIPELINE_STAGE1_S1_root_reg_reg_array[2].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_293), .Q (root_o[2]));
  DFFRHQX2
       \DATA_PATH_PIPELINE_STAGE1_S1_root_reg_reg_array[3].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_291), .Q
       (DATA_PATH_S1_o_root_s[3]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE2_S2_A_high_S2_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_278), .Q (DATA_PATH_S2_o_A_s[1]));
  DFFRHQX2
       \DATA_PATH_PIPELINE_STAGE2_S2_B_high_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_311), .Q (DATA_PATH_S2_o_B_s[0]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE2_S2_input_high_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_286), .Q
       (DATA_PATH_S2_o_input_s[3]));
  DFFRX2
       \DATA_PATH_PIPELINE_STAGE2_S2_input_high_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_289), .Q
       (DATA_PATH_S2_o_input_s[1]), .QN (UNCONNECTED3));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE4_square_sum_S4_reg_reg_array[3].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_305), .Q
       (DATA_PATH_S4_o_square_s[3]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE4_square_sum_S4_reg_reg_array[8].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_320), .Q
       (DATA_PATH_S4_o_square_s[8]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE4_square_sum_S4_reg_reg_array[2].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_309), .Q
       (DATA_PATH_S4_o_square_s[2]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE4_square_sum_S4_reg_reg_array[5].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_304), .Q
       (DATA_PATH_S4_o_square_s[5]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE4_square_sum_S4_reg_reg_array[6].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_267), .Q
       (DATA_PATH_S4_o_square_s[6]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE4_square_sum_S4_reg_reg_array[7].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_297), .Q
       (DATA_PATH_S4_o_square_s[7]));
  DFFRX2
       \DATA_PATH_PIPELINE_STAGE4_S3_A_high_S2_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_316), .Q (DATA_PATH_S4_o_A_s[1]),
       .QN (UNCONNECTED4));
  DFFRHQX2
       \DATA_PATH_PIPELINE_STAGE4_S3_A_high_S2_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_319), .Q (DATA_PATH_S4_o_A_s[0]));
  DFFRX2
       \DATA_PATH_PIPELINE_STAGE2_S2_input_high_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_281), .Q
       (DATA_PATH_S2_o_input_s[5]), .QN (UNCONNECTED5));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE2_S2_input_high_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_279), .Q
       (DATA_PATH_S2_o_input_s[7]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE2_S2_input_high_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_263), .Q
       (DATA_PATH_S2_o_input_s[6]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE2_S2_B_high_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_313), .Q (DATA_PATH_S2_o_B_s[1]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[9].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_284), .Q
       (DATA_PATH_S1_o_square_s[9]));
  DFFSHQX4
       DATA_PATH_PIPELINE_STAGE1_S1_root_reg_Reg_Root_S1_inst_0_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_251), .Q (DATA_PATH_S1_o_root_s[0]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE2_S2_A_high_S2_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_272), .Q (DATA_PATH_S2_o_A_s[0]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[8].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_288), .Q
       (DATA_PATH_S1_o_square_s[8]));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_295), .Q
       (DATA_PATH_S1_o_square_s[3]), .QN (UNCONNECTED6));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_292), .Q
       (DATA_PATH_S1_o_square_s[4]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE2_S2_B_high_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_321), .Q
       (DATA_PATH_S2_o_root_h_s[2]));
  DFFRX2
       \DATA_PATH_PIPELINE_STAGE3_S3_A_high_S2_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_264), .Q (DATA_PATH_S3_o_A_s[2]),
       .QN (UNCONNECTED7));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE1_S1_root_reg_reg_array[1].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_294), .Q
       (DATA_PATH_S1_o_root_s[1]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE2_S2_B_high_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_303), .Q (DATA_PATH_S2_o_B_s[3]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE2_S2_square_high_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_261), .Q
       (DATA_PATH_S2_o_square_c_s[2]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE2_S2_B_high_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_306), .Q (DATA_PATH_S2_o_B_s[2]));
  NAND2X4 g8273__7482(.A (n_190), .B (n_330), .Y (n_331));
  CLKXOR2X2 g8302__4733(.A (n_69), .B (n_213), .Y (n_329));
  NOR2X4 g8344__6161(.A (n_189), .B (n_250), .Y (n_328));
  CLKXOR2X2 g8299__9315(.A (n_128), .B (n_212), .Y (n_327));
  NAND2X4 g8280__9945(.A (n_203), .B (n_330), .Y (n_326));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_S2_A_high_S2_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_221), .Q (DATA_PATH_S2_o_A_s[3]));
  DFFRX2
       \DATA_PATH_PIPELINE_STAGE2_S2_input_high_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_240), .Q
       (DATA_PATH_S2_o_input_s[0]), .QN (UNCONNECTED8));
  DFFRHQX8
       \DATA_PATH_PIPELINE_STAGE2_S2_input_high_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_238), .Q
       (DATA_PATH_S2_o_input_s[4]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_225), .Q
       (DATA_PATH_S1_o_square_s[2]));
  DFFRHQX1
       DATA_PATH_PIPELINE_STAGE2_S2_root_reg_Reg_Root_S2_2_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_234), .Q (DATA_PATH_S2_o_root_s[2]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE4_square_sum_S4_reg_reg_array[9].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_232), .Q
       (DATA_PATH_S4_o_square_s[9]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_239), .Q
       (DATA_PATH_S1_o_square_s[7]));
  DFFSHQX1
       DATA_PATH_PIPELINE_STAGE2_square_sum_S2_reg_RegSumLow_3_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_237), .Q (DATA_PATH_S2_o_square_s[3]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_S2_A_high_S2_reg_reg[11].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_249), .Q
       (DATA_PATH_S2_o_A_s[11]));
  DFFSHQX1
       DATA_PATH_PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_2_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_220), .Q (DATA_PATH_S3_o_square_s[2]));
  DFFRX2
       \DATA_PATH_PIPELINE_STAGE2_S2_square_high_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_223), .Q
       (DATA_PATH_S2_o_square_c_s[0]), .QN (UNCONNECTED9));
  DFFRX2
       \DATA_PATH_PIPELINE_STAGE3_S3_A_high_S2_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_229), .Q (DATA_PATH_S3_o_A_s[1]),
       .QN (UNCONNECTED10));
  CLKMX2X3 g8284__2883(.A (DATA_PATH_S4_o_square_s[10]), .B (n_208),
       .S0 (n_282), .Y (n_325));
  CLKMX2X3 g8271__2346(.A (DATA_PATH_S2_o_root_s[3]), .B (n_201), .S0
       (n_323), .Y (n_324));
  CLKMX2X3 g8311__1666(.A (DATA_PATH_S3_o_square_s[6]), .B (n_200), .S0
       (n_323), .Y (n_322));
  DFFRHQX1
       DATA_PATH_PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_3_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_218), .Q (DATA_PATH_S3_o_square_s[3]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_S2_A_high_S2_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_219), .Q (DATA_PATH_S2_o_A_s[4]));
  DFFSHQX8 DATA_PATH_PIPELINE_STAGE4_S4_ready_reg_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_224), .Q (ready_o));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE3_S3_A_high_S2_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_230), .Q (DATA_PATH_S3_o_A_s[6]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE4_S3_A_high_S2_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_248), .Q (DATA_PATH_S4_o_A_s[3]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_S2_square_high_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_226), .Q
       (DATA_PATH_S2_o_square_c_s[3]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_S2_A_high_S2_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_215), .Q (DATA_PATH_S2_o_A_s[7]));
  DFFRHQX1
       DATA_PATH_PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_4_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_246), .Q (DATA_PATH_S3_o_square_s[4]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_S2_square_high_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_227), .Q
       (DATA_PATH_S2_o_square_c_s[4]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_S2_A_high_S2_reg_reg[10].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_241), .Q
       (DATA_PATH_S2_o_A_s[10]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE4_square_sum_S4_reg_reg_array[4].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_245), .Q
       (DATA_PATH_S4_o_square_s[4]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_244), .Q
       (DATA_PATH_S1_o_square_s[5]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_243), .Q
       (DATA_PATH_S1_o_square_s[6]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_S2_A_high_S2_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_216), .Q (DATA_PATH_S2_o_A_s[6]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_S2_A_high_S2_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_217), .Q (DATA_PATH_S2_o_A_s[5]));
  MX2X1 g8515__7410(.A (root_o[6]), .B (DATA_PATH_S2_o_root_h_s[2]),
       .S0 (n_318), .Y (n_321));
  MX2X1 g8498__6417(.A (DATA_PATH_S3_o_square_s[8]), .B
       (DATA_PATH_S4_o_square_s[8]), .S0 (n_308), .Y (n_320));
  MX2X1 g8501__5477(.A (DATA_PATH_S3_o_A_s[4]), .B
       (DATA_PATH_S4_o_A_s[0]), .S0 (n_318), .Y (n_319));
  XNOR2X2 g8313__2398(.A (n_387), .B (n_188), .Y (n_317));
  MX2X1 g8502__5107(.A (DATA_PATH_S3_o_A_s[5]), .B
       (DATA_PATH_S4_o_A_s[1]), .S0 (n_310), .Y (n_316));
  MX2X1 g8503__6260(.A (DATA_PATH_S3_o_A_s[6]), .B
       (DATA_PATH_S4_o_A_s[2]), .S0 (n_318), .Y (n_315));
  XNOR2X2 g8314__4319(.A (n_299), .B (n_298), .Y (n_314));
  MX2X1 g8506__8428(.A (n_290), .B (DATA_PATH_S2_o_B_s[1]), .S0
       (n_312), .Y (n_313));
  MX2X1 g8507__5526(.A (root_o[2]), .B (DATA_PATH_S2_o_B_s[0]), .S0
       (n_310), .Y (n_311));
  MX2X1 g8508__6783(.A (DATA_PATH_S3_o_square_s[2]), .B
       (DATA_PATH_S4_o_square_s[2]), .S0 (n_308), .Y (n_309));
  CLKMX2X3 g8272__3680(.A (DATA_PATH_S1_o_square_s[16]), .B (n_187),
       .S0 (n_323), .Y (n_307));
  MX2X1 g8509__1617(.A (root_o[4]), .B (DATA_PATH_S2_o_B_s[2]), .S0
       (n_312), .Y (n_306));
  MX2X1 g8510__2802(.A (DATA_PATH_S3_o_square_s[3]), .B
       (DATA_PATH_S4_o_square_s[3]), .S0 (n_301), .Y (n_305));
  MX2X1 g8512__1705(.A (DATA_PATH_S3_o_square_s[5]), .B
       (DATA_PATH_S4_o_square_s[5]), .S0 (n_308), .Y (n_304));
  MX2X1 g8513__5122(.A (root_o[5]), .B (DATA_PATH_S2_o_B_s[3]), .S0
       (n_318), .Y (n_303));
  MX2X1 g8514__8246(.A (DATA_PATH_S4_o_square_s[0]), .B
       (DATA_PATH_S1_o_square_s[0]), .S0 (n_301), .Y (n_302));
  OAI21X4 g8286__7098(.A0 (n_299), .A1 (n_298), .B0 (n_109), .Y
       (n_300));
  MX2X1 g8516__6131(.A (DATA_PATH_S3_o_square_s[7]), .B
       (DATA_PATH_S4_o_square_s[7]), .S0 (n_301), .Y (n_297));
  MX2X1 g8517__1881(.A (root_o[7]), .B (DATA_PATH_S2_o_B_s[5]), .S0
       (n_312), .Y (n_296));
  MX2X1 g8518__5115(.A (DATA_PATH_S4_o_square_s[3]), .B
       (DATA_PATH_S1_o_square_s[3]), .S0 (n_301), .Y (n_295));
  MX2X1 g8519__7482(.A (DATA_PATH_S2_o_root_s[1]), .B (n_147), .S0
       (n_318), .Y (n_294));
  MX2X1 g8520__4733(.A (DATA_PATH_S2_o_root_s[2]), .B (root_o[2]), .S0
       (n_318), .Y (n_293));
  MX2X1 g8521__6161(.A (DATA_PATH_S4_o_square_s[4]), .B
       (DATA_PATH_S1_o_square_s[4]), .S0 (n_312), .Y (n_292));
  MX2X1 g8523__9315(.A (DATA_PATH_S2_o_root_s[3]), .B (n_290), .S0
       (n_318), .Y (n_291));
  MX2X1 g8527__9945(.A (DATA_PATH_S1_o_input_s[1]), .B
       (DATA_PATH_S2_o_input_s[1]), .S0 (n_318), .Y (n_289));
  MX2X1 g8528__2883(.A (DATA_PATH_S4_o_square_s[8]), .B
       (DATA_PATH_S1_o_square_s[8]), .S0 (n_312), .Y (n_288));
  MX2X1 g8529__2346(.A (DATA_PATH_S1_o_input_s[2]), .B
       (DATA_PATH_S2_o_input_s[2]), .S0 (n_312), .Y (n_287));
  MX2X1 g8530__1666(.A (DATA_PATH_S1_o_input_s[3]), .B
       (DATA_PATH_S2_o_input_s[3]), .S0 (n_312), .Y (n_286));
  MX2X1 g8396__7410(.A (n_70), .B (DATA_PATH_S2_o_root_s[0]), .S0
       (n_308), .Y (n_285));
  MX2X1 g8532__6417(.A (DATA_PATH_S4_o_square_s[9]), .B
       (DATA_PATH_S1_o_square_s[9]), .S0 (n_310), .Y (n_284));
  MX2X1 g8291__5477(.A (DATA_PATH_S1_o_square_s[15]), .B (n_174), .S0
       (n_282), .Y (n_283));
  MX2X1 g8533__2398(.A (DATA_PATH_S1_o_input_s[5]), .B
       (DATA_PATH_S2_o_input_s[5]), .S0 (n_318), .Y (n_281));
  MX2X1 g8446__5107(.A (DATA_PATH_S2_o_A_s[4]), .B
       (DATA_PATH_S3_o_A_s[0]), .S0 (n_310), .Y (n_280));
  MX2X1 g8535__6260(.A (DATA_PATH_S1_o_input_s[7]), .B
       (DATA_PATH_S2_o_input_s[7]), .S0 (n_312), .Y (n_279));
  MX2X1 g8536__4319(.A (DATA_PATH_S1_o_square_s[6]), .B (n_63), .S0
       (n_318), .Y (n_278));
  MX2X1 g8398__8428(.A (n_56), .B (DATA_PATH_S1_o_square_s[13]), .S0
       (n_310), .Y (n_277));
  MX2X1 g8325__5526(.A (root_o[4]), .B (n_170), .S0 (n_275), .Y
       (n_276));
  MX2X1 g8328__6783(.A (n_115), .B (DATA_PATH_S1_o_square_s[14]), .S0
       (n_310), .Y (n_274));
  AOI22X4 g8279__3680(.A0 (n_233), .A1 (n_192), .B0
       (DATA_PATH_S4_o_square_s[11]), .B1 (n_178), .Y (n_273));
  MX2X1 g8435__1617(.A (DATA_PATH_S1_o_square_s[5]), .B
       (DATA_PATH_S2_o_A_s[0]), .S0 (n_318), .Y (n_272));
  MX2X1 g8436__2802(.A (DATA_PATH_S2_o_B_s[5]), .B
       (DATA_PATH_S3_o_B_s[1]), .S0 (n_318), .Y (n_271));
  MX2X1 g8437__1705(.A (DATA_PATH_S2_o_root_h_s[2]), .B
       (DATA_PATH_S3_o_B_s[0]), .S0 (n_310), .Y (n_270));
  MX2X1 g8438__5122(.A (DATA_PATH_S2_o_A_s[11]), .B
       (DATA_PATH_S3_o_A_s[7]), .S0 (n_301), .Y (n_269));
  MX2X1 g8440__8246(.A (DATA_PATH_S2_o_A_s[9]), .B
       (DATA_PATH_S3_o_A_s[5]), .S0 (n_301), .Y (n_268));
  MX2X1 g8441__7098(.A (DATA_PATH_S3_o_square_s[6]), .B
       (DATA_PATH_S4_o_square_s[6]), .S0 (n_308), .Y (n_267));
  MX2X1 g8442__6131(.A (DATA_PATH_S2_o_A_s[8]), .B
       (DATA_PATH_S3_o_A_s[4]), .S0 (n_308), .Y (n_266));
  MX2X1 g8443__1881(.A (DATA_PATH_S2_o_A_s[7]), .B
       (DATA_PATH_S3_o_A_s[3]), .S0 (n_301), .Y (n_265));
  MX2X1 g8444__5115(.A (DATA_PATH_S2_o_A_s[6]), .B
       (DATA_PATH_S3_o_A_s[2]), .S0 (n_318), .Y (n_264));
  MX2X1 g8534__7482(.A (DATA_PATH_S1_o_input_s[6]), .B
       (DATA_PATH_S2_o_input_s[6]), .S0 (n_318), .Y (n_263));
  NAND2X8 g8346__4733(.A (n_180), .B (n_206), .Y (n_262));
  MX2X1 g8449__6161(.A (DATA_PATH_S1_o_square_s[2]), .B
       (DATA_PATH_S2_o_square_c_s[2]), .S0 (n_310), .Y (n_261));
  MX2X1 g8451__9315(.A (DATA_PATH_S4_o_square_s[12]), .B
       (DATA_PATH_S1_o_square_s[12]), .S0 (n_312), .Y (n_260));
  MX2X1 g8457__9945(.A (DATA_PATH_S4_o_square_s[11]), .B
       (DATA_PATH_S1_o_square_s[11]), .S0 (n_312), .Y (n_259));
  OAI2BB1X2 g8463__2883(.A0N (DATA_PATH_S4_o_square_s[0]), .A1N
       (n_312), .B0 (n_222), .Y (n_258));
  MX2X1 g8487__2346(.A (DATA_PATH_S1_o_square_s[7]), .B (n_58), .S0
       (n_312), .Y (n_257));
  MX2X1 g8497__1666(.A (DATA_PATH_S1_o_square_s[14]), .B
       (DATA_PATH_S2_o_A_s[9]), .S0 (n_308), .Y (n_256));
  CLKINVX4 g8285(.A (n_330), .Y (n_255));
  MX2X1 g8496__7410(.A (DATA_PATH_S1_o_square_s[13]), .B
       (DATA_PATH_S2_o_A_s[8]), .S0 (n_308), .Y (n_254));
  MX2X1 g8309__6417(.A (DATA_PATH_S2_o_co_square_s), .B (n_165), .S0
       (n_282), .Y (n_253));
  MX2X1 g8486__5477(.A (DATA_PATH_S4_o_square_s[10]), .B
       (DATA_PATH_S1_o_square_s[10]), .S0 (n_312), .Y (n_252));
  MX2X1 g8493__2398(.A (DATA_PATH_S2_o_root_s[0]), .B (n_87), .S0
       (n_301), .Y (n_251));
  DFFRHQX1
       DATA_PATH_PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_5_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_196), .Q (DATA_PATH_S3_o_square_s[5]));
  DFFRHQX1
       DATA_PATH_PIPELINE_STAGE2_square_sum_S2_reg_RegSumLow_4_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_194), .Q (DATA_PATH_S2_o_square_s[4]));
  DFFSHQX1
       DATA_PATH_PIPELINE_STAGE2_S2_root_reg_Reg_Root_S2_1_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_209), .Q (DATA_PATH_S2_o_root_s[1]));
  NAND2X4 g8404__5107(.A (n_168), .B (n_183), .Y (n_250));
  MX2X1 g8500__6260(.A (DATA_PATH_S1_o_square_s[16]), .B
       (DATA_PATH_S2_o_A_s[11]), .S0 (n_247), .Y (n_249));
  MX2X1 g8504__4319(.A (DATA_PATH_S3_o_A_s[7]), .B
       (DATA_PATH_S4_o_A_s[3]), .S0 (n_247), .Y (n_248));
  MX2X1 g8505__8428(.A (DATA_PATH_S2_o_square_s[4]), .B
       (DATA_PATH_S3_o_square_s[4]), .S0 (n_247), .Y (n_246));
  MX2X1 g8511__5526(.A (DATA_PATH_S3_o_square_s[4]), .B
       (DATA_PATH_S4_o_square_s[4]), .S0 (n_247), .Y (n_245));
  MX2X1 g8522__6783(.A (DATA_PATH_S4_o_square_s[5]), .B
       (DATA_PATH_S1_o_square_s[5]), .S0 (n_247), .Y (n_244));
  MX2X1 g8524__3680(.A (DATA_PATH_S4_o_square_s[6]), .B
       (DATA_PATH_S1_o_square_s[6]), .S0 (n_242), .Y (n_243));
  MX2X1 g8499__1617(.A (DATA_PATH_S1_o_square_s[15]), .B
       (DATA_PATH_S2_o_A_s[10]), .S0 (n_247), .Y (n_241));
  MX2X1 g8525__2802(.A (DATA_PATH_S1_o_input_s[0]), .B
       (DATA_PATH_S2_o_input_s[0]), .S0 (n_242), .Y (n_240));
  MX2X1 g8526__1705(.A (DATA_PATH_S4_o_square_s[7]), .B
       (DATA_PATH_S1_o_square_s[7]), .S0 (n_247), .Y (n_239));
  MX2X1 g8531__5122(.A (DATA_PATH_S1_o_input_s[4]), .B
       (DATA_PATH_S2_o_input_s[4]), .S0 (n_247), .Y (n_238));
  MX2X1 g8397__8246(.A (n_88), .B (DATA_PATH_S2_o_square_s[3]), .S0
       (n_247), .Y (n_237));
  NAND2X2 g8545__7098(.A (root_o[6]), .B (n_318), .Y (n_236));
  NAND2X2 g8547__6131(.A (root_o[7]), .B (n_318), .Y (n_235));
  MX2X1 g8292__1881(.A (DATA_PATH_S2_o_root_s[2]), .B (n_166), .S0
       (n_323), .Y (n_234));
  NAND2X8 g8290__5115(.A (n_85), .B (n_233), .Y (n_330));
  MX2X1 g8326__7482(.A (DATA_PATH_S4_o_square_s[9]), .B (n_171), .S0
       (n_323), .Y (n_232));
  OAI21X4 g8334__4733(.A0 (n_155), .A1 (n_173), .B0 (n_78), .Y (n_231));
  MX2X1 g8439__6161(.A (DATA_PATH_S2_o_A_s[10]), .B
       (DATA_PATH_S3_o_A_s[6]), .S0 (n_247), .Y (n_230));
  MX2X1 g8445__9315(.A (DATA_PATH_S2_o_A_s[5]), .B
       (DATA_PATH_S3_o_A_s[1]), .S0 (n_242), .Y (n_229));
  OAI31X4 g8345__9945(.A0 (n_55), .A1 (n_108), .A2 (n_139), .B0
       (n_162), .Y (n_228));
  MX2X1 g8447__2883(.A (DATA_PATH_S1_o_square_s[4]), .B (n_54), .S0
       (n_247), .Y (n_227));
  MX2X1 g8448__2346(.A (DATA_PATH_S1_o_square_s[3]), .B (n_138), .S0
       (n_247), .Y (n_226));
  MX2X1 g8450__1666(.A (DATA_PATH_S4_o_square_s[2]), .B
       (DATA_PATH_S1_o_square_s[2]), .S0 (n_247), .Y (n_225));
  AO21X1 g8460__7410(.A0 (ready_o), .A1 (n_242), .B0
       (CONTROL_PATH_CurrentState[0]), .Y (n_224));
  OAI2BB1X1 g8462__6417(.A0N (DATA_PATH_S2_o_square_c_s[0]), .A1N
       (n_242), .B0 (n_222), .Y (n_223));
  MX2X1 g8488__5477(.A (DATA_PATH_S1_o_square_s[8]), .B
       (DATA_PATH_S2_o_A_s[3]), .S0 (n_242), .Y (n_221));
  MX2X1 g8489__2398(.A (DATA_PATH_S2_o_square_c_s[2]), .B
       (DATA_PATH_S3_o_square_s[2]), .S0 (n_242), .Y (n_220));
  MX2X1 g8490__5107(.A (DATA_PATH_S1_o_square_s[9]), .B
       (DATA_PATH_S2_o_A_s[4]), .S0 (n_247), .Y (n_219));
  MX2X1 g8491__6260(.A (DATA_PATH_S2_o_square_s[3]), .B
       (DATA_PATH_S3_o_square_s[3]), .S0 (n_247), .Y (n_218));
  MX2X1 g8492__4319(.A (DATA_PATH_S1_o_square_s[10]), .B
       (DATA_PATH_S2_o_A_s[5]), .S0 (n_247), .Y (n_217));
  MX2X1 g8494__8428(.A (DATA_PATH_S1_o_square_s[11]), .B
       (DATA_PATH_S2_o_A_s[6]), .S0 (n_242), .Y (n_216));
  MX2X1 g8495__5526(.A (DATA_PATH_S1_o_square_s[12]), .B
       (DATA_PATH_S2_o_A_s[7]), .S0 (n_242), .Y (n_215));
  AOI2BB2X4 g8399__6783(.A0N (n_142), .A1N (n_149), .B0 (n_179), .B1
       (n_132), .Y (n_214));
  AOI2BB2X4 g8318__3680(.A0N (n_374), .A1N (n_73), .B0 (n_210), .B1
       (n_129), .Y (n_213));
  AOI2BB2X4 g8321__1617(.A0N (n_371), .A1N (n_72), .B0 (n_210), .B1
       (n_388), .Y (n_212));
  MX2X1 g8323__2802(.A (DATA_PATH_S2_o_root_s[1]), .B (n_148), .S0
       (n_323), .Y (n_209));
  CLKXOR2X1 g8312__1705(.A (n_186), .B (n_185), .Y (n_208));
  NAND2X2 g8544__5122(.A (DATA_PATH_S4_o_co_square_s), .B (n_167), .Y
       (n_207));
  NAND2X8 g8400__8246(.A (n_169), .B (n_164), .Y (n_206));
  NOR3X4 g8546__7098(.A (DATA_PATH_S3_o_A_s[3]), .B (n_204), .C
       (n_191), .Y (n_205));
  NOR2X4 g8454__6131(.A (n_204), .B (n_202), .Y (n_203));
  CLKXOR2X1 g8294__1881(.A (n_172), .B (n_156), .Y (n_201));
  XNOR2X1 g8335__5115(.A (n_177), .B (n_158), .Y (n_200));
  INVX3 g8602(.A (n_282), .Y (n_199));
  INVX3 g8604(.A (n_275), .Y (n_198));
  INVX2 g8605(.A (n_275), .Y (n_197));
  MX2X1 g8337__7482(.A (DATA_PATH_S3_o_square_s[5]), .B (n_135), .S0
       (n_323), .Y (n_196));
  OAI21X2 g8338__4733(.A0 (n_124), .A1 (n_140), .B0 (n_157), .Y
       (n_195));
  MX2X1 g8324__6161(.A (DATA_PATH_S2_o_square_s[4]), .B (n_153), .S0
       (n_323), .Y (n_194));
  INVX2 g8596(.A (n_242), .Y (n_193));
  NOR2X2 g8401__9315(.A (n_86), .B (n_191), .Y (n_192));
  NOR2X2 g8543__9945(.A (DATA_PATH_S3_o_A_s[2]), .B (n_189), .Y
       (n_190));
  NOR2X4 g8330__2883(.A (n_385), .B (n_210), .Y (n_188));
  XNOR2X1 g8295__2346(.A (n_6), .B (n_122), .Y (n_187));
  NAND2X6 g8317__1666(.A (n_186), .B (n_185), .Y (n_233));
  NAND2X2 g8557__7410(.A (DATA_PATH_S1_o_square_s[0]), .B (n_160), .Y
       (n_222));
  BUFX2 g8597(.A (n_242), .Y (n_343));
  CLKINVX6 g8603(.A (n_176), .Y (n_282));
  CLKINVX12 g8611(.A (n_184), .Y (n_301));
  CLKINVX16 g8615(.A (n_175), .Y (n_312));
  AOI31X4 g8453__6417(.A0 (n_47), .A1 (DATA_PATH_S2_o_input_s[5]), .A2
       (n_161), .B0 (DATA_PATH_S2_o_feedback_s[0]), .Y (n_183));
  MX2X1 g8466__5477(.A (n_51), .B (N_s), .S0 (n_159), .Y (n_182));
  NOR2X1 g8465__2398(.A (n_150), .B (n_152), .Y (n_181));
  CLKAND2X6 g8456__5107(.A (n_34), .B (n_179), .Y (n_180));
  INVX3 g8609(.A (n_184), .Y (n_178));
  AOI21X4 g8339__6260(.A0 (n_125), .A1 (n_177), .B0 (n_143), .Y
       (n_298));
  BUFX2 g8610(.A (n_184), .Y (n_335));
  CLKINVX6 g8606(.A (n_176), .Y (n_275));
  CLKINVX12 g8608(.A (n_184), .Y (n_308));
  CLKINVX12 g8612(.A (n_184), .Y (n_310));
  CLKINVX16 g8614(.A (n_175), .Y (n_318));
  CLKXOR2X1 g8322__4319(.A (DATA_PATH_S4_o_A_s[2]), .B (n_83), .Y
       (n_174));
  AOI21X4 g8403__8428(.A0 (n_29), .A1 (n_172), .B0 (n_146), .Y (n_173));
  XNOR2X1 g8392__5526(.A (n_141), .B (n_113), .Y (n_171));
  CLKXOR2X1 g8394__6783(.A (n_136), .B (DATA_PATH_S2_o_co_root_s), .Y
       (n_170));
  NAND2X4 g8551__3680(.A (n_66), .B (n_134), .Y (n_169));
  NAND2X4 g8556__1617(.A (DATA_PATH_S3_o_A_s[3]), .B (n_137), .Y
       (n_202));
  INVX8 g8613(.A (n_189), .Y (n_184));
  CLKINVX16 g8599(.A (n_163), .Y (n_247));
  ACHCONX2 g8464__2802(.A (DATA_PATH_S2_o_input_s[7]), .B (n_24), .CI
       (n_64), .CON (n_168));
  INVX2 g8594(.A (n_323), .Y (n_167));
  XNOR2X1 g8327__1705(.A (root_o[2]), .B (n_154), .Y (n_166));
  NAND2BX1 g8329__5122(.AN (n_67), .B (n_120), .Y (n_165));
  NAND2X4 g8458__8246(.A (n_93), .B (n_130), .Y (n_164));
  CLKINVX8 g8616(.A (n_189), .Y (n_175));
  BUFX6 g8607(.A (n_189), .Y (n_176));
  DFFRHQX8 \CONTROL_PATH_CurrentState_reg[1] (.RN (rst_n), .CK (clk),
       .D (n_121), .Q (mux_root_s));
  CLKINVX12 g8598(.A (n_163), .Y (n_242));
  AND2X1 g8552__7098(.A (n_161), .B (n_89), .Y (n_162));
  CLKINVX4 g8593(.A (n_159), .Y (n_160));
  NAND2X2 g8589__6131(.A (n_157), .B (n_84), .Y (n_158));
  NOR2X4 g8331__1881(.A (n_155), .B (n_154), .Y (n_156));
  XNOR2X1 g8395__5115(.A (n_119), .B (n_118), .Y (n_153));
  NAND2X2 g8542__7482(.A (n_92), .B (n_133), .Y (n_152));
  OR2X2 g8548__4733(.A (DATA_PATH_S1_o_square_s[16]), .B (n_126), .Y
       (n_151));
  NAND2X2 g8550__6161(.A (n_131), .B (n_149), .Y (n_150));
  AO21X1 g8402__9315(.A0 (n_147), .A1 (n_146), .B0 (n_154), .Y (n_148));
  INVX2 g8577(.A (n_144), .Y (n_145));
  OAI21X4 g8555__9945(.A0 (n_157), .A1 (n_123), .B0 (n_117), .Y
       (n_143));
  NOR2X6 g8574__2883(.A (n_142), .B (n_94), .Y (n_179));
  OAI21X4 g8333__2346(.A0 (n_141), .A1 (n_112), .B0 (n_26), .Y (n_185));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_116), .Q
       (DATA_PATH_S1_o_input_s[3]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_103), .Q
       (DATA_PATH_S1_o_input_s[4]));
  CLKINVX8 g8600(.A (n_159), .Y (n_163));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[15].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_90), .Q
       (DATA_PATH_S1_o_input_s[15]));
  CLKINVX6 g8595(.A (n_159), .Y (n_323));
  CLKINVX4 g8347(.A (n_177), .Y (n_140));
  AOI21X4 g8459__1666(.A0 (n_138), .A1 (n_76), .B0 (n_71), .Y (n_139));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_96), .Q
       (DATA_PATH_S1_o_input_s[7]));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[12].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_104), .Q
       (DATA_PATH_S1_o_input_s[12]), .QN (UNCONNECTED11));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_95), .Q
       (DATA_PATH_S1_o_input_s[2]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[14].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_97), .Q
       (DATA_PATH_S1_o_input_s[14]));
  CLKINVX6 g8618(.A (n_137), .Y (n_191));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_107), .Q
       (DATA_PATH_S1_o_input_s[1]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_106), .Q
       (DATA_PATH_S1_o_input_s[0]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_100), .Q
       (DATA_PATH_S1_o_input_s[6]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[13].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_111), .Q
       (DATA_PATH_S1_o_input_s[13]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_101), .Q
       (DATA_PATH_S1_o_input_s[5]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[9].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_98), .Q
       (DATA_PATH_S1_o_input_s[9]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[11].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_105), .Q
       (DATA_PATH_S1_o_input_s[11]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[8].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_99), .Q
       (DATA_PATH_S1_o_input_s[8]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[10].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_102), .Q
       (DATA_PATH_S1_o_input_s[10]));
  CLKAND2X6 g8476__7410(.A (DATA_PATH_S2_o_co_root_s), .B (n_136), .Y
       (n_210));
  CLKINVX8 g8617(.A (n_137), .Y (n_189));
  ADDFHX4 g8348__6417(.A (DATA_PATH_S2_o_co_square_s), .B
       (DATA_PATH_S2_o_A_s[0]), .CI (DATA_PATH_S2_o_B_s[0]), .CO
       (n_177), .S (n_135));
  INVX3 g8576(.A (n_133), .Y (n_134));
  INVX2 g8575(.A (n_131), .Y (n_132));
  OAI21X4 g8554__5477(.A0 (n_40), .A1 (n_57), .B0 (n_91), .Y (n_130));
  CLKAND2X6 g8549__2398(.A (n_128), .B (n_127), .Y (n_129));
  CLKINVX8 g8619(.A (n_126), .Y (n_137));
  BUFX6 g8601(.A (n_126), .Y (n_159));
  NOR2X4 g8580__5107(.A (n_124), .B (n_123), .Y (n_125));
  NOR2BX2 g8332__6260(.AN (DATA_PATH_S4_o_A_s[2]), .B (n_82), .Y
       (n_122));
  OAI21X1 g8461__4319(.A0 (CONTROL_PATH_CurrentState[2]), .A1 (n_49),
       .B0 (n_61), .Y (n_121));
  NAND2BX2 g8452__8428(.AN (n_119), .B (n_118), .Y (n_120));
  NOR2BX2 g8587__5526(.AN (n_117), .B (n_123), .Y (n_144));
  DFFRX2 \CONTROL_PATH_CurrentState_reg[2] (.RN (rst_n), .CK (clk), .D
       (n_62), .Q (CONTROL_PATH_CurrentState[2]), .QN (UNCONNECTED12));
  MX2X1 g8560__6783(.A (DATA_PATH_S1_o_input_s[3]), .B (valor_i[3]),
       .S0 (n_110), .Y (n_116));
  CLKXOR2X1 g8393__3680(.A (DATA_PATH_S4_o_A_s[1]), .B (n_59), .Y
       (n_115));
  INVX1 g8538(.A (n_112), .Y (n_113));
  MX2X1 g8569__1617(.A (DATA_PATH_S1_o_input_s[13]), .B (valor_i[13]),
       .S0 (n_110), .Y (n_111));
  INVX2 g8540(.A (n_79), .Y (n_109));
  AOI222X2 g8553__2802(.A0 (DATA_PATH_S2_o_square_c_s[3]), .A1 (n_75),
       .B0 (DATA_PATH_S2_o_square_c_s[2]), .B1 (n_74), .C0
       (DATA_PATH_S2_o_square_c_s[0]), .C1 (n_19), .Y (n_108));
  MX2X1 g8558__1705(.A (DATA_PATH_S1_o_input_s[1]), .B (valor_i[1]),
       .S0 (n_110), .Y (n_107));
  MX2X1 g8559__5122(.A (DATA_PATH_S1_o_input_s[0]), .B (valor_i[0]),
       .S0 (n_110), .Y (n_106));
  MX2X1 g8568__8246(.A (DATA_PATH_S1_o_input_s[11]), .B (valor_i[11]),
       .S0 (n_110), .Y (n_105));
  MX2X1 g8561__7098(.A (DATA_PATH_S1_o_input_s[12]), .B (valor_i[12]),
       .S0 (n_110), .Y (n_104));
  MX2X1 g8562__6131(.A (DATA_PATH_S1_o_input_s[4]), .B (valor_i[4]),
       .S0 (n_110), .Y (n_103));
  MX2X1 g8563__1881(.A (DATA_PATH_S1_o_input_s[10]), .B (valor_i[10]),
       .S0 (n_110), .Y (n_102));
  MX2X1 g8564__5115(.A (DATA_PATH_S1_o_input_s[5]), .B (valor_i[5]),
       .S0 (n_110), .Y (n_101));
  MX2X1 g8565__7482(.A (DATA_PATH_S1_o_input_s[6]), .B (valor_i[6]),
       .S0 (n_110), .Y (n_100));
  MX2X1 g8566__4733(.A (DATA_PATH_S1_o_input_s[8]), .B (valor_i[8]),
       .S0 (n_110), .Y (n_99));
  MX2X1 g8567__6161(.A (DATA_PATH_S1_o_input_s[9]), .B (valor_i[9]),
       .S0 (n_110), .Y (n_98));
  INVX2 g8539(.A (n_80), .Y (n_299));
  NOR2X6 g8485__9315(.A (DATA_PATH_S1_o_root_s[1]), .B (n_146), .Y
       (n_154));
  MX2X1 g8570__9945(.A (DATA_PATH_S1_o_input_s[14]), .B (valor_i[14]),
       .S0 (n_110), .Y (n_97));
  MX2X1 g8572__2883(.A (DATA_PATH_S1_o_input_s[7]), .B (valor_i[7]),
       .S0 (n_110), .Y (n_96));
  MX2X1 g8573__2346(.A (DATA_PATH_S1_o_input_s[2]), .B (valor_i[2]),
       .S0 (n_110), .Y (n_95));
  OAI2BB1X4 g8578__1666(.A0N (DATA_PATH_S1_o_square_s[14]), .A1N
       (n_36), .B0 (n_52), .Y (n_94));
  NOR2X4 g8582__7410(.A (n_41), .B (n_65), .Y (n_93));
  CLKAND2X2 g8584__6417(.A (n_22), .B (n_91), .Y (n_92));
  MX2X1 g8571__5477(.A (DATA_PATH_S1_o_input_s[15]), .B (valor_i[15]),
       .S0 (n_110), .Y (n_90));
  AOI21X4 g8621__2398(.A0 (DATA_PATH_S2_o_square_c_s[4]), .A1 (n_53),
       .B0 (n_48), .Y (n_89));
  AO21X1 g8622__5107(.A0 (n_87), .A1 (DATA_PATH_S1_o_square_s[3]), .B0
       (n_119), .Y (n_88));
  NAND2X2 g8455__6260(.A (DATA_PATH_S3_o_A_s[2]), .B (n_85), .Y (n_86));
  INVX3 g8636(.A (n_124), .Y (n_84));
  CLKINVX2 g8340(.A (n_82), .Y (n_83));
  NOR2X4 g8626__4319(.A (n_39), .B (n_45), .Y (n_161));
  AOI2BB1X4 g8628__8428(.A0N (mux_root_s), .A1N (n_30), .B0 (n_77), .Y
       (n_172));
  AOI2BB1X4 g8631__5526(.A0N (DATA_PATH_S2_o_B_s[2]), .A1N
       (mux_root_s), .B0 (n_81), .Y (n_136));
  NOR2X4 g8588__6783(.A (n_37), .B (n_44), .Y (n_149));
  AOI2BB1X4 g8585__3680(.A0N (DATA_PATH_S1_o_square_s[12]), .A1N
       (n_33), .B0 (n_43), .Y (n_131));
  NOR2X4 g8586__1617(.A (n_46), .B (n_35), .Y (n_133));
  NOR2X6 g8634__2802(.A (CONTROL_PATH_CurrentState[0]), .B (n_38), .Y
       (n_126));
  ADDHX1 g8541__1705(.A (DATA_PATH_S2_o_B_s[3]), .B
       (DATA_PATH_S2_o_A_s[3]), .CO (n_79), .S (n_80));
  CLKINVX1 g8537(.A (n_77), .Y (n_78));
  OR3X4 g8579__5122(.A (DATA_PATH_S2_o_square_c_s[2]), .B (n_75), .C
       (n_74), .Y (n_76));
  CLKAND2X2 g8583__8246(.A (n_72), .B (n_68), .Y (n_73));
  OA21X1 g8581__7098(.A0 (DATA_PATH_S2_o_square_c_s[2]), .A1 (n_74),
       .B0 (n_75), .Y (n_71));
  XNOR2X1 g8623__6131(.A (n_27), .B (n_374), .Y (n_70));
  XNOR2X1 g8625__1881(.A (DATA_PATH_S2_o_B_s[5]), .B (n_372), .Y
       (n_69));
  AOI2BB1X2 g8632__5115(.A0N (DATA_PATH_S3_o_B_s[1]), .A1N
       (DATA_PATH_S3_o_A_s[1]), .B0 (n_31), .Y (n_186));
  OAI2BB1X4 g8630__7482(.A0N (DATA_PATH_S3_o_B_s[0]), .A1N
       (DATA_PATH_S3_o_A_s[0]), .B0 (n_21), .Y (n_112));
  AOI2BB1X4 g8629__4733(.A0N (n_68), .A1N (n_380), .B0 (n_20), .Y
       (n_128));
  AOI2BB1X2 g8627__6161(.A0N (DATA_PATH_S1_o_root_s[1]), .A1N
       (DATA_PATH_S1_o_square_s[4]), .B0 (n_67), .Y (n_118));
  INVX2 g8657(.A (n_65), .Y (n_66));
  NOR2X4 g8669__9315(.A (n_11), .B (n_63), .Y (n_64));
  INVX1 g8635(.A (n_61), .Y (n_62));
  BUFX2 g8694(.A (root_o[3]), .Y (n_290));
  NAND2X4 g8480__9945(.A (DATA_PATH_S4_o_A_s[1]), .B (n_59), .Y (n_82));
  NAND2X4 g8671__2883(.A (DATA_PATH_S2_o_B_s[2]), .B (n_58), .Y
       (n_117));
  NOR2X6 g8653__2346(.A (DATA_PATH_S2_o_B_s[1]), .B (n_63), .Y (n_124));
  NAND2X8 g8655__1666(.A (DATA_PATH_S2_o_B_s[1]), .B (n_63), .Y
       (n_157));
  NOR2X4 g8654__7410(.A (DATA_PATH_S2_o_B_s[2]), .B (n_58), .Y (n_123));
  CLKMX2X3 g8633__6417(.A (DATA_PATH_S2_o_B_s[3]), .B (n_2), .S0
       (mux_root_s), .Y (n_127));
  DFFRHQX4 \CONTROL_PATH_CurrentState_reg[0] (.RN (rst_n), .CK (clk),
       .D (n_23), .Q (CONTROL_PATH_CurrentState[0]));
  NOR2X4 g8641__5477(.A (DATA_PATH_S1_o_input_s[8]), .B (n_5), .Y
       (n_57));
  CLKXOR2X1 g8624__2398(.A (DATA_PATH_S4_o_A_s[0]), .B
       (DATA_PATH_S4_o_co_square_s), .Y (n_56));
  NOR2X2 g8638__5107(.A (n_53), .B (n_54), .Y (n_55));
  NAND2X4 g8639__6260(.A (DATA_PATH_S1_o_square_s[13]), .B (n_42), .Y
       (n_52));
  NOR2X1 g8640__4319(.A (DATA_PATH_S2_o_feedback_s[0]), .B (n_50), .Y
       (n_51));
  AOI21X1 g8620__8428(.A0 (CONTROL_PATH_CurrentState[0]), .A1 (N_s),
       .B0 (n_373), .Y (n_49));
  NOR2X4 g8643__5526(.A (n_47), .B (DATA_PATH_S2_o_input_s[5]), .Y
       (n_48));
  NOR2X6 g8644__6783(.A (DATA_PATH_S1_o_square_s[11]), .B (n_12), .Y
       (n_46));
  NOR2X4 g8645__3680(.A (DATA_PATH_S2_o_input_s[6]), .B (n_16), .Y
       (n_45));
  NOR2X4 g8646__1617(.A (DATA_PATH_S1_o_square_s[15]), .B (n_4), .Y
       (n_44));
  NOR2X2 g8647__2802(.A (DATA_PATH_S1_o_square_s[13]), .B (n_42), .Y
       (n_43));
  NOR2X4 g8673__1705(.A (n_17), .B (n_383), .Y (n_77));
  NOR2X4 g8649__5122(.A (DATA_PATH_S1_o_input_s[15]), .B (n_10), .Y
       (n_142));
  NOR2X2 g8637__8246(.A (DATA_PATH_S1_o_input_s[10]), .B (n_7), .Y
       (n_41));
  NOR2X4 g8668__7098(.A (DATA_PATH_S1_o_input_s[9]), .B (n_32), .Y
       (n_40));
  NOR2X4 g8667__6131(.A (DATA_PATH_S2_o_input_s[7]), .B (n_15), .Y
       (n_39));
  NOR2X4 g8663__1881(.A (CONTROL_PATH_CurrentState[2]), .B (n_381), .Y
       (n_38));
  NOR2X2 g8664__5115(.A (DATA_PATH_S1_o_square_s[14]), .B (n_36), .Y
       (n_37));
  NOR2X6 g8665__7482(.A (DATA_PATH_S1_o_square_s[10]), .B (n_13), .Y
       (n_35));
  NAND2X2 g8666__4733(.A (DATA_PATH_S1_o_square_s[12]), .B (n_33), .Y
       (n_34));
  NAND2X4 g8652__6161(.A (DATA_PATH_S1_o_input_s[9]), .B (n_32), .Y
       (n_91));
  NOR2X4 g8670__9315(.A (DATA_PATH_S1_o_input_s[11]), .B (n_0), .Y
       (n_65));
  NOR2X8 g8674__9945(.A (n_14), .B (n_380), .Y (n_81));
  INVX2 g8658(.A (n_31), .Y (n_85));
  BUFX6 g8695(.A (n_30), .Y (root_o[3]));
  OR2X1 g8650__2883(.A (CONTROL_PATH_CurrentState[0]), .B (n_376), .Y
       (n_61));
  NOR2X6 g8677__2346(.A (n_9), .B (n_383), .Y (n_146));
  INVX2 g8721(.A (n_25), .Y (n_29));
  BUFX6 g8716(.A (n_27), .Y (root_o[0]));
  NAND2X2 g8662__1666(.A (DATA_PATH_S3_o_B_s[0]), .B
       (DATA_PATH_S3_o_A_s[0]), .Y (n_26));
  BUFX2 g8717(.A (n_27), .Y (n_87));
  INVX2 g8720(.A (n_25), .Y (n_147));
  CLKAND2X6 g8676__7410(.A (DATA_PATH_S4_o_A_s[0]), .B
       (DATA_PATH_S4_o_co_square_s), .Y (n_59));
  CLKAND2X3 g8675__6417(.A (DATA_PATH_S3_o_B_s[1]), .B
       (DATA_PATH_S3_o_A_s[1]), .Y (n_31));
  AND2X6 g8672__5477(.A (DATA_PATH_S1_o_root_s[1]), .B
       (DATA_PATH_S1_o_square_s[4]), .Y (n_67));
  CLKINVX8 g8703(.A (n_24), .Y (n_58));
  NOR2X6 g8678__2398(.A (CONTROL_PATH_CurrentState[0]), .B (n_370), .Y
       (n_110));
  NOR2X1 g8660__5107(.A (CONTROL_PATH_CurrentState[2]), .B (n_375), .Y
       (n_23));
  NAND2BX1 g8642__6260(.AN (DATA_PATH_S1_o_square_s[8]), .B
       (DATA_PATH_S1_o_input_s[8]), .Y (n_22));
  OR2X6 g8659__4319(.A (DATA_PATH_S3_o_B_s[0]), .B
       (DATA_PATH_S3_o_A_s[0]), .Y (n_21));
  NOR2X2 g8661__8428(.A (DATA_PATH_S2_o_root_h_s[2]), .B (mux_root_s),
       .Y (n_20));
  NOR2X2 g8648__5526(.A (DATA_PATH_S2_o_input_s[1]), .B
       (DATA_PATH_S2_o_input_s[0]), .Y (n_19));
  CLKINVX6 g8722(.A (n_25), .Y (root_o[1]));
  NOR2X4 g8651__6783(.A (DATA_PATH_S2_o_B_s[2]), .B
       (DATA_PATH_S2_o_B_s[3]), .Y (n_72));
  INVX2 g8696(.A (n_17), .Y (n_30));
  NOR2X2 g8656__3680(.A (DATA_PATH_S1_o_root_s[0]), .B
       (DATA_PATH_S1_o_square_s[3]), .Y (n_119));
  CLKINVX6 g8698(.A (n_16), .Y (n_63));
  INVX2 g8702(.A (DATA_PATH_S2_o_A_s[2]), .Y (n_15));
  CLKINVX4 g8701(.A (DATA_PATH_S2_o_B_s[2]), .Y (n_14));
  INVX3 g8687(.A (DATA_PATH_S1_o_input_s[10]), .Y (n_13));
  CLKINVX4 g8688(.A (DATA_PATH_S1_o_input_s[11]), .Y (n_12));
  INVX2 g8708(.A (DATA_PATH_S2_o_input_s[6]), .Y (n_11));
  INVX2 g8710(.A (DATA_PATH_S1_o_square_s[15]), .Y (n_10));
  INVX2 g8719(.A (DATA_PATH_S1_o_root_s[0]), .Y (n_9));
  INVX1 g8706(.A (DATA_PATH_S3_o_square_s[8]), .Y (n_8));
  CLKINVX4 g8692(.A (DATA_PATH_S1_o_square_s[10]), .Y (n_7));
  CLKINVX6 g8699(.A (DATA_PATH_S2_o_A_s[1]), .Y (n_16));
  CLKINVX3 g8714(.A (DATA_PATH_S2_o_root_h_s[2]), .Y (n_68));
  CLKINVX6 g8704(.A (DATA_PATH_S2_o_A_s[2]), .Y (n_24));
  INVX3 g8724(.A (DATA_PATH_S2_o_A_s[0]), .Y (n_47));
  INVX3 g8697(.A (DATA_PATH_S1_o_root_s[3]), .Y (n_17));
  INVX2 g8679(.A (DATA_PATH_S2_o_feedback_s[1]), .Y (n_50));
  CLKINVX6 g8686(.A (DATA_PATH_S1_o_input_s[13]), .Y (n_42));
  INVX2 g8723(.A (DATA_PATH_S1_o_root_s[1]), .Y (n_25));
  INVX2 g8700(.A (DATA_PATH_S3_o_A_s[2]), .Y (n_204));
  INVX1 g8684(.A (DATA_PATH_S4_o_A_s[3]), .Y (n_6));
  INVX2 g8691(.A (DATA_PATH_S1_o_square_s[8]), .Y (n_5));
  INVX2 g8709(.A (DATA_PATH_S1_o_input_s[15]), .Y (n_4));
  INVX2 g8683(.A (root_o[5]), .Y (n_3));
  CLKINVX4 g8715(.A (DATA_PATH_S2_o_B_s[3]), .Y (n_2));
  INVX1 g8707(.A (DATA_PATH_S4_o_square_s[12]), .Y (n_1));
  INVX3 g8711(.A (DATA_PATH_S1_o_square_s[11]), .Y (n_0));
  INVX2 g8725(.A (root_o[2]), .Y (n_155));
  INVX3 g8689(.A (DATA_PATH_S1_o_input_s[12]), .Y (n_33));
  CLKINVX6 g8693(.A (DATA_PATH_S1_o_square_s[9]), .Y (n_32));
  BUFX2 g8680(.A (DATA_PATH_S2_o_square_c_s[3]), .Y (n_138));
  INVX2 g8681(.A (DATA_PATH_S2_o_input_s[4]), .Y (n_53));
  INVX2 g8690(.A (DATA_PATH_S3_o_co_square_s), .Y (n_141));
  BUFX2 g8685(.A (DATA_PATH_S2_o_square_c_s[4]), .Y (n_54));
  CLKINVX4 g8682(.A (DATA_PATH_S1_o_input_s[14]), .Y (n_36));
  CLKINVX3 g8712(.A (DATA_PATH_S2_o_input_s[2]), .Y (n_74));
  BUFX2 g8718(.A (DATA_PATH_S1_o_root_s[0]), .Y (n_27));
  INVX3 g8713(.A (DATA_PATH_S2_o_input_s[3]), .Y (n_75));
  CLKINVX8 fopt(.A (n_371), .Y (n_370));
  CLKINVX4 fopt1(.A (n_378), .Y (n_371));
  CLKINVX6 fopt2(.A (n_378), .Y (n_372));
  CLKINVX4 fopt3(.A (n_374), .Y (n_373));
  CLKINVX2 fopt4(.A (n_376), .Y (n_375));
  BUFX6 fopt5(.A (n_374), .Y (n_376));
  CLKINVX6 fopt6(.A (n_378), .Y (n_374));
  BUFX6 fopt7(.A (mux_root_s), .Y (n_378));
  INVX12 fopt8(.A (mux_root_s), .Y (n_380));
  CLKINVX4 fopt9(.A (mux_root_s), .Y (n_381));
  CLKINVX3 fopt10(.A (mux_root_s), .Y (n_383));
  CLKBUFX4 fopt8846(.A (n_81), .Y (n_385));
  INVX3 fopt8847(.A (n_388), .Y (n_387));
  BUFX6 fopt8848(.A (n_127), .Y (n_388));
endmodule

