
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 15 2025 22:35:24 -03 (Sep 16 2025 01:35:24 UTC)

// Verification Directory fv/Square_root 

module DataPath(clk, rst_n, input_i, root_o, ready_o, wr_input_i,
     en_pipe_i, ready_i, mux_root_i, N_o);
  input clk, rst_n, wr_input_i, en_pipe_i, ready_i, mux_root_i;
  input [15:0] input_i;
  output [7:0] root_o;
  output ready_o, N_o;
  wire clk, rst_n, wr_input_i, en_pipe_i, ready_i, mux_root_i;
  wire [15:0] input_i;
  wire [7:0] root_o;
  wire ready_o, N_o;
  wire [16:0] S1_input_ext_s;
  wire [15:0] S1_o_input_s;
  wire [16:0] S1_o_square_s;
  wire [7:0] S1_o_root_s;
  wire [11:0] S2_o_A_s;
  wire [11:0] S2_o_B_s;
  wire [3:0] S2_o_root_h_s;
  wire [3:0] S2_o_root_s;
  wire [4:0] S2_o_square_s;
  wire [7:0] S3_o_A_s;
  wire [7:0] S3_o_B_s;
  wire [8:0] S3_o_square_s;
  wire [3:0] S4_o_A_s;
  wire [12:0] S4_o_square_s;
  wire S1_N_s, S2_o_co_root_s, S2_o_co_square_s, S3_o_co_square_s,
       S4_o_co_square_s, n_6, n_7, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_92, n_93, n_94, n_95, n_96, n_97, n_98;
  wire n_99, n_100, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_140, n_141, n_142, n_143, n_144, n_145, n_146;
  wire n_147, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179, n_180, n_181, n_182, n_183, n_184, n_185, n_186;
  wire n_187, n_188, n_189, n_190, n_191, n_192, n_193, n_194;
  wire n_195, n_196, n_197, n_198, n_199, n_200, n_201, n_202;
  wire n_256, n_257, n_258, n_260, n_261, n_262, n_264, n_265;
  wire n_266;
  assign S1_input_ext_s[16] = 1'b0;
  Comparator COMPARATOR(.A_i ({S1_input_ext_s[16], S1_o_input_s[15:1],
       S1_input_ext_s[0]}), .B_i (S1_o_square_s), .A_less_than_B_o
       (S1_N_s));
  DFFSHQX8 PIPELINE_STAGE1_S1_root_reg_Reg_Root_S1_inst_0_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_21), .Q (root_o[0]));
  DFFRHQX4
       \PIPELINE_STAGE1_S1_root_reg_reg_array[1].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_59), .Q (S1_o_root_s[1]));
  DFFRHQX4
       \PIPELINE_STAGE1_S1_root_reg_reg_array[2].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_50), .Q (S1_o_root_s[2]));
  DFFRHQX4
       \PIPELINE_STAGE1_S1_root_reg_reg_array[3].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_45), .Q (S1_o_root_s[3]));
  DFFRHQX8
       \PIPELINE_STAGE1_S1_root_reg_reg_array[4].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_164), .Q (root_o[4]));
  DFFRHQX8
       \PIPELINE_STAGE1_S1_root_reg_reg_array[5].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_181), .Q (root_o[5]));
  DFFRHQX8
       \PIPELINE_STAGE1_S1_root_reg_reg_array[6].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_184), .Q (root_o[6]));
  DFFRHQX8
       \PIPELINE_STAGE1_S1_root_reg_reg_array[7].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_186), .Q (root_o[7]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_36), .Q (S1_input_ext_s[0]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_37), .Q (S1_o_input_s[1]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[2].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_35), .Q (S1_o_input_s[2]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_34), .Q (S1_o_input_s[3]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[4].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_33), .Q (S1_o_input_s[4]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[5].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_32), .Q (S1_o_input_s[5]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[6].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_31), .Q (S1_o_input_s[6]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[7].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_30), .Q (S1_o_input_s[7]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[8].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_29), .Q (S1_o_input_s[8]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[9].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_28), .Q (S1_o_input_s[9]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[10].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_27), .Q (S1_o_input_s[10]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[11].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_26), .Q (S1_o_input_s[11]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[12].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_25), .Q (S1_o_input_s[12]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[13].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_24), .Q (S1_o_input_s[13]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[14].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_23), .Q (S1_o_input_s[14]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[15].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_22), .Q (S1_o_input_s[15]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_44), .Q (S1_o_square_s[0]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_43), .Q (S1_o_square_s[1]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[2].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_39), .Q (S1_o_square_s[2]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_38), .Q (S1_o_square_s[3]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[4].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_108), .Q (S1_o_square_s[4]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[5].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_107), .Q (S1_o_square_s[5]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[6].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_106), .Q (S1_o_square_s[6]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[7].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_104), .Q (S1_o_square_s[7]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[8].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_100), .Q (S1_o_square_s[8]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[9].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_98), .Q (S1_o_square_s[9]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[10].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_94), .Q (S1_o_square_s[10]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[11].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_92), .Q (S1_o_square_s[11]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[12].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_88), .Q (S1_o_square_s[12]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[13].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_139), .Q (S1_o_square_s[13]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[14].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_161), .Q (S1_o_square_s[14]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[15].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_178), .Q (S1_o_square_s[15]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[16].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_185), .Q (S1_o_square_s[16]));
  DFFRHQX1 PIPELINE_STAGE2_Co_Square_S2_reg_sig_q_reg(.RN (rst_n), .CK
       (clk), .D (n_169), .Q (S2_o_co_square_s));
  DFFRHQX1 PIPELINE_STAGE2_N_S2_reg_sig_q_reg(.RN (rst_n), .CK (clk),
       .D (n_73), .Q (N_o));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_72), .Q (S2_o_A_s[0]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_84), .Q (S2_o_A_s[1]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[2].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_68), .Q (S2_o_A_s[2]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_109), .Q (S2_o_A_s[3]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[4].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_61), .Q (S2_o_A_s[4]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[5].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_60), .Q (S2_o_A_s[5]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[6].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_58), .Q (S2_o_A_s[6]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[7].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_57), .Q (S2_o_A_s[7]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[8].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_56), .Q (S2_o_A_s[8]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[9].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_55), .Q (S2_o_A_s[9]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[10].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_54), .Q (S2_o_A_s[10]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[11].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_53), .Q (S2_o_A_s[11]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_B_high_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_52), .Q (S2_o_B_s[0]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_B_high_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_51), .Q (S2_o_B_s[1]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_B_high_reg_reg[2].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_49), .Q (S2_o_B_s[2]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_B_high_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_48), .Q (S2_o_B_s[3]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_B_high_reg_reg[4].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_47), .Q (S2_o_root_h_s[2]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_B_high_reg_reg[5].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_46), .Q (S2_o_B_s[5]));
  DFFRHQX1 PIPELINE_STAGE2_S2_Co_Root_reg_sig_q_reg(.RN (rst_n), .CK
       (clk), .D (n_165), .Q (S2_o_co_root_s));
  DFFSHQX1 PIPELINE_STAGE2_S2_root_reg_Reg_Root_S2_1_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_138), .Q (S2_o_root_s[1]));
  DFFRHQX1 PIPELINE_STAGE2_S2_root_reg_Reg_Root_S2_2_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_153), .Q (S2_o_root_s[2]));
  DFFRHQX1 PIPELINE_STAGE2_S2_root_reg_Reg_Root_S2_3_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_170), .Q (S2_o_root_s[3]));
  DFFSHQX1 PIPELINE_STAGE2_square_sum_S2_reg_RegSumLow_0_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_42), .Q (S2_o_square_s[0]));
  DFFRHQX1 PIPELINE_STAGE2_square_sum_S2_reg_RegSumLow_1_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_41), .Q (S2_o_square_s[1]));
  DFFRHQX1 PIPELINE_STAGE2_square_sum_S2_reg_RegSumLow_2_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_40), .Q (S2_o_square_s[2]));
  DFFSHQX1 PIPELINE_STAGE2_square_sum_S2_reg_RegSumLow_3_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_137), .Q (S2_o_square_s[3]));
  DFFRHQX1 PIPELINE_STAGE2_square_sum_S2_reg_RegSumLow_4_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_159), .Q (S2_o_square_s[4]));
  DFFRHQX1 PIPELINE_STAGE3_Co_Square_S3_reg_sig_q_reg(.RN (rst_n), .CK
       (clk), .D (n_202), .Q (S3_o_co_square_s));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_105), .Q (S3_o_A_s[0]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_103), .Q (S3_o_A_s[1]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[2].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_102), .Q (S3_o_A_s[2]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_101), .Q (S3_o_A_s[3]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[4].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_99), .Q (S3_o_A_s[4]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[5].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_97), .Q (S3_o_A_s[5]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[6].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_96), .Q (S3_o_A_s[6]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[7].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_95), .Q (S3_o_A_s[7]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_B_high_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_93), .Q (S3_o_B_s[0]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_B_high_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_91), .Q (S3_o_B_s[1]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_0_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_90), .Q (S3_o_square_s[0]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_1_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_89), .Q (S3_o_square_s[1]));
  DFFSHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_2_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_87), .Q (S3_o_square_s[2]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_3_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_86), .Q (S3_o_square_s[3]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_4_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_85), .Q (S3_o_square_s[4]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_5_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_160), .Q (S3_o_square_s[5]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_6_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_183), .Q (S3_o_square_s[6]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_7_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_195), .Q (S3_o_square_s[7]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_8_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_201), .Q (S3_o_square_s[8]));
  DFFRHQX1 PIPELINE_STAGE4_Co_Square_S4_reg_sig_q_reg(.RN (rst_n), .CK
       (clk), .D (n_196), .Q (S4_o_co_square_s));
  DFFRHQX1 \PIPELINE_STAGE4_S3_A_high_S2_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_82), .Q (S4_o_A_s[0]));
  DFFRHQX1 \PIPELINE_STAGE4_S3_A_high_S2_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_80), .Q (S4_o_A_s[1]));
  DFFRHQX1 \PIPELINE_STAGE4_S3_A_high_S2_reg_reg[2].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_79), .Q (S4_o_A_s[2]));
  DFFRHQX1 \PIPELINE_STAGE4_S3_A_high_S2_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_78), .Q (S4_o_A_s[3]));
  DFFSHQX8 PIPELINE_STAGE4_S4_ready_reg_sig_q_reg(.SN (rst_n), .CK
       (clk), .D (n_77), .Q (ready_o));
  DFFSHQX1 PIPELINE_STAGE4_square_sum_S4_reg_RegSumLow_0_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_76), .Q (S4_o_square_s[0]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[1].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_83), .Q (S4_o_square_s[1]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[2].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_81), .Q (S4_o_square_s[2]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[3].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_75), .Q (S4_o_square_s[3]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[4].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_74), .Q (S4_o_square_s[4]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[5].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_67), .Q (S4_o_square_s[5]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[6].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_71), .Q (S4_o_square_s[6]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[7].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_70), .Q (S4_o_square_s[7]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[8].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_69), .Q (S4_o_square_s[8]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[9].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_162), .Q (S4_o_square_s[9]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[10].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_182), .Q (S4_o_square_s[10]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[11].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_194), .Q (S4_o_square_s[11]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[12].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_197), .Q (S4_o_square_s[12]));
  MX2X1 g4910__2398(.A (S3_o_co_square_s), .B (n_200), .S0 (en_pipe_i),
       .Y (n_202));
  MX2X1 g4911__5107(.A (S3_o_square_s[8]), .B (n_199), .S0 (en_pipe_i),
       .Y (n_201));
  OR2X1 g4913__6260(.A (n_122), .B (n_198), .Y (n_200));
  ADDHX1 g4914__4319(.A (n_123), .B (n_192), .CO (n_198), .S (n_199));
  MX2X1 g4915__8428(.A (S4_o_square_s[12]), .B (n_193), .S0
       (en_pipe_i), .Y (n_197));
  OAI2BB1X1 g4919__5526(.A0N (S4_o_co_square_s), .A1N (n_6), .B0
       (n_191), .Y (n_196));
  MX2X1 g4920__6783(.A (S3_o_square_s[7]), .B (n_189), .S0 (en_pipe_i),
       .Y (n_195));
  MX2X1 g4921__3680(.A (S4_o_square_s[11]), .B (n_187), .S0
       (en_pipe_i), .Y (n_194));
  CLKXOR2X1 g4922__1617(.A (S3_o_A_s[3]), .B (n_190), .Y (n_193));
  OR2X1 g4923__2802(.A (n_127), .B (n_188), .Y (n_192));
  NAND3X1 g4924__1705(.A (S3_o_A_s[3]), .B (en_pipe_i), .C (n_190), .Y
       (n_191));
  ADDHX1 g4925__5122(.A (n_128), .B (n_179), .CO (n_188), .S (n_189));
  ADDHX1 g4926__8246(.A (S3_o_A_s[2]), .B (n_180), .CO (n_190), .S
       (n_187));
  MX2X1 g4931__7098(.A (n_177), .B (root_o[7]), .S0 (n_6), .Y (n_186));
  MX2X1 g4932__6131(.A (S1_o_square_s[16]), .B (n_176), .S0
       (en_pipe_i), .Y (n_185));
  MX2X1 g4936__1881(.A (n_173), .B (root_o[6]), .S0 (n_6), .Y (n_184));
  MX2X1 g4937__5115(.A (S3_o_square_s[6]), .B (n_167), .S0 (en_pipe_i),
       .Y (n_183));
  MX2X1 g4938__7482(.A (S4_o_square_s[10]), .B (n_175), .S0
       (en_pipe_i), .Y (n_182));
  MX2X1 g4939__4733(.A (root_o[5]), .B (n_168), .S0 (en_pipe_i), .Y
       (n_181));
  OR2X1 g4940__6161(.A (n_120), .B (n_174), .Y (n_180));
  AO21X1 g4941__9315(.A0 (n_133), .A1 (n_157), .B0 (n_129), .Y (n_179));
  MX2X1 g4942__9945(.A (S1_o_square_s[15]), .B (n_172), .S0
       (en_pipe_i), .Y (n_178));
  CLKXOR2X1 g4943__2883(.A (n_20), .B (n_166), .Y (n_177));
  CLKXOR2X1 g4944__2346(.A (S4_o_A_s[3]), .B (n_171), .Y (n_176));
  ADDHX1 g4945__1666(.A (n_121), .B (n_152), .CO (n_174), .S (n_175));
  CLKXOR2X1 g4947__7410(.A (n_130), .B (n_163), .Y (n_173));
  ADDHX1 g4949__6417(.A (S4_o_A_s[2]), .B (n_149), .CO (n_171), .S
       (n_172));
  MX2X1 g4955__5477(.A (S2_o_root_s[3]), .B (n_155), .S0 (en_pipe_i),
       .Y (n_170));
  MX2X1 g4956__2398(.A (S2_o_co_square_s), .B (n_154), .S0 (en_pipe_i),
       .Y (n_169));
  CLKXOR2X1 g4957__5107(.A (n_65), .B (n_156), .Y (n_168));
  CLKXOR2X1 g4958__6260(.A (n_133), .B (n_157), .Y (n_167));
  AOI211XL g4959__4319(.A0 (n_130), .A1 (n_158), .B0 (n_117), .C0
       (n_110), .Y (n_166));
  MX2X1 g4961__8428(.A (S2_o_co_root_s), .B (n_140), .S0 (en_pipe_i),
       .Y (n_165));
  MX2X1 g4962__5526(.A (root_o[4]), .B (n_144), .S0 (en_pipe_i), .Y
       (n_164));
  OR2X1 g4964__6783(.A (n_110), .B (n_158), .Y (n_163));
  MX2X1 g4965__3680(.A (S4_o_square_s[9]), .B (n_146), .S0 (en_pipe_i),
       .Y (n_162));
  MX2X1 g4966__1617(.A (S1_o_square_s[14]), .B (n_150), .S0
       (en_pipe_i), .Y (n_161));
  MX2X1 g4967__2802(.A (S3_o_square_s[5]), .B (n_143), .S0 (en_pipe_i),
       .Y (n_160));
  MX2X1 g4968__1705(.A (n_148), .B (S2_o_square_s[4]), .S0 (n_6), .Y
       (n_159));
  NOR2X1 g4969__5122(.A (n_124), .B (n_151), .Y (n_156));
  NOR2BX1 g4970__8246(.AN (n_151), .B (n_65), .Y (n_158));
  OR2X1 g4971__7098(.A (n_111), .B (n_142), .Y (n_157));
  OAI2BB1X1 g4972__6131(.A0N (mux_root_i), .A1N (n_134), .B0 (n_141),
       .Y (n_155));
  OR2X1 g4973__1881(.A (n_118), .B (n_147), .Y (n_154));
  MX2X1 g4974__5115(.A (S2_o_root_s[2]), .B (n_136), .S0 (en_pipe_i),
       .Y (n_153));
  OR2X1 g4975__7482(.A (n_115), .B (n_145), .Y (n_152));
  ADDHX1 g4976__4733(.A (S4_o_A_s[1]), .B (n_113), .CO (n_149), .S
       (n_150));
  ADDHX1 g4977__6161(.A (n_19), .B (n_119), .CO (n_147), .S (n_148));
  ADDHX1 g4978__9315(.A (S3_o_co_square_s), .B (n_116), .CO (n_145), .S
       (n_146));
  ADDHX1 g4979__9945(.A (S2_o_co_root_s), .B (n_125), .CO (n_151), .S
       (n_144));
  ADDHX1 g4980__2883(.A (S2_o_co_square_s), .B (n_112), .CO (n_142), .S
       (n_143));
  AOI31X1 g4984__2346(.A0 (n_132), .A1 (n_63), .A2 (n_64), .B0 (n_135),
       .Y (n_141));
  OAI32X1 g4985__1666(.A0 (n_131), .A1 (n_62), .A2 (n_64), .B0 (n_18),
       .B1 (n_7), .Y (n_140));
  MX2X1 g4986__7410(.A (S1_o_square_s[13]), .B (n_114), .S0
       (en_pipe_i), .Y (n_139));
  MX2X1 g4987__6417(.A (S2_o_root_s[1]), .B (n_126), .S0 (en_pipe_i),
       .Y (n_138));
  MX2X1 g4988__5477(.A (S2_o_square_s[3]), .B (n_66), .S0 (en_pipe_i),
       .Y (n_137));
  XNOR2X1 g4989__2398(.A (n_132), .B (n_62), .Y (n_136));
  AOI211XL g4990__5107(.A0 (n_262), .A1 (n_63), .B0 (mux_root_i), .C0
       (n_64), .Y (n_135));
  XNOR2X1 g4991__6260(.A (n_257), .B (n_64), .Y (n_134));
  INVX1 g4992(.A (n_132), .Y (n_131));
  ADDHX1 g4993__4319(.A (S2_o_B_s[1]), .B (S2_o_A_s[1]), .CO (n_129),
       .S (n_133));
  ADDHX1 g4994__8428(.A (S2_o_B_s[2]), .B (S2_o_A_s[2]), .CO (n_127),
       .S (n_128));
  ADDHX1 g4995__5526(.A (n_261), .B (n_7), .CO (n_132), .S (n_126));
  ADDHX1 g4996__6783(.A (S2_o_B_s[2]), .B (mux_root_i), .CO (n_124), .S
       (n_125));
  ADDHX1 g4997__3680(.A (S2_o_B_s[3]), .B (S2_o_A_s[3]), .CO (n_122),
       .S (n_123));
  ADDHX1 g4998__1617(.A (S3_o_B_s[1]), .B (S3_o_A_s[1]), .CO (n_120),
       .S (n_121));
  ADDHX1 g4999__2802(.A (S1_o_square_s[4]), .B (n_260), .CO (n_118), .S
       (n_119));
  ADDHX1 g5000__1705(.A (S2_o_root_h_s[2]), .B (mux_root_i), .CO
       (n_117), .S (n_130));
  ADDHX1 g5001__5122(.A (S3_o_B_s[0]), .B (S3_o_A_s[0]), .CO (n_115),
       .S (n_116));
  ADDHX1 g5002__8246(.A (S4_o_A_s[0]), .B (S4_o_co_square_s), .CO
       (n_113), .S (n_114));
  ADDHX1 g5003__7098(.A (S2_o_B_s[0]), .B (S2_o_A_s[0]), .CO (n_111),
       .S (n_112));
  MX2X1 g5088__6131(.A (S2_o_A_s[3]), .B (S1_o_square_s[8]), .S0
       (en_pipe_i), .Y (n_109));
  MX2X1 g5089__1881(.A (S1_o_square_s[4]), .B (S4_o_square_s[4]), .S0
       (en_pipe_i), .Y (n_108));
  MX2X1 g5090__5115(.A (S1_o_square_s[5]), .B (S4_o_square_s[5]), .S0
       (en_pipe_i), .Y (n_107));
  MX2X1 g5091__7482(.A (S1_o_square_s[6]), .B (S4_o_square_s[6]), .S0
       (en_pipe_i), .Y (n_106));
  MX2X1 g5092__4733(.A (S3_o_A_s[0]), .B (S2_o_A_s[4]), .S0
       (en_pipe_i), .Y (n_105));
  MX2X1 g5093__6161(.A (S1_o_square_s[7]), .B (S4_o_square_s[7]), .S0
       (en_pipe_i), .Y (n_104));
  MX2X1 g5094__9315(.A (S3_o_A_s[1]), .B (S2_o_A_s[5]), .S0
       (en_pipe_i), .Y (n_103));
  MX2X1 g5095__9945(.A (S3_o_A_s[2]), .B (S2_o_A_s[6]), .S0
       (en_pipe_i), .Y (n_102));
  MX2X1 g5096__2883(.A (S3_o_A_s[3]), .B (S2_o_A_s[7]), .S0
       (en_pipe_i), .Y (n_101));
  MX2X1 g5097__2346(.A (S1_o_square_s[8]), .B (S4_o_square_s[8]), .S0
       (en_pipe_i), .Y (n_100));
  MX2X1 g5098__1666(.A (S3_o_A_s[4]), .B (S2_o_A_s[8]), .S0
       (en_pipe_i), .Y (n_99));
  MX2X1 g5099__7410(.A (S1_o_square_s[9]), .B (S4_o_square_s[9]), .S0
       (en_pipe_i), .Y (n_98));
  MX2X1 g5100__6417(.A (S3_o_A_s[5]), .B (S2_o_A_s[9]), .S0
       (en_pipe_i), .Y (n_97));
  MX2X1 g5101__5477(.A (S3_o_A_s[6]), .B (S2_o_A_s[10]), .S0
       (en_pipe_i), .Y (n_96));
  MX2X1 g5102__2398(.A (S3_o_A_s[7]), .B (S2_o_A_s[11]), .S0
       (en_pipe_i), .Y (n_95));
  MX2X1 g5103__5107(.A (S1_o_square_s[10]), .B (S4_o_square_s[10]), .S0
       (en_pipe_i), .Y (n_94));
  MX2X1 g5104__6260(.A (S3_o_B_s[0]), .B (S2_o_root_h_s[2]), .S0
       (en_pipe_i), .Y (n_93));
  MX2X1 g5105__4319(.A (S1_o_square_s[11]), .B (S4_o_square_s[11]), .S0
       (en_pipe_i), .Y (n_92));
  MX2X1 g5106__8428(.A (S3_o_B_s[1]), .B (S2_o_B_s[5]), .S0
       (en_pipe_i), .Y (n_91));
  MX2X1 g5107__5526(.A (S3_o_square_s[0]), .B (S2_o_square_s[0]), .S0
       (en_pipe_i), .Y (n_90));
  MX2X1 g5108__6783(.A (S3_o_square_s[1]), .B (S2_o_square_s[1]), .S0
       (en_pipe_i), .Y (n_89));
  MX2X1 g5109__3680(.A (S1_o_square_s[12]), .B (S4_o_square_s[12]), .S0
       (en_pipe_i), .Y (n_88));
  MX2X1 g5110__1617(.A (S3_o_square_s[2]), .B (S2_o_square_s[2]), .S0
       (en_pipe_i), .Y (n_87));
  MX2X1 g5111__2802(.A (S3_o_square_s[3]), .B (S2_o_square_s[3]), .S0
       (en_pipe_i), .Y (n_86));
  MX2X1 g5112__1705(.A (S3_o_square_s[4]), .B (S2_o_square_s[4]), .S0
       (en_pipe_i), .Y (n_85));
  MX2X1 g5113__5122(.A (S2_o_A_s[1]), .B (S1_o_square_s[6]), .S0
       (en_pipe_i), .Y (n_84));
  MX2X1 g5114__8246(.A (S4_o_square_s[1]), .B (S3_o_square_s[1]), .S0
       (en_pipe_i), .Y (n_83));
  MX2X1 g5115__7098(.A (S4_o_A_s[0]), .B (S3_o_A_s[4]), .S0
       (en_pipe_i), .Y (n_82));
  MX2X1 g5116__6131(.A (S4_o_square_s[2]), .B (S3_o_square_s[2]), .S0
       (en_pipe_i), .Y (n_81));
  MX2X1 g5117__1881(.A (S4_o_A_s[1]), .B (S3_o_A_s[5]), .S0
       (en_pipe_i), .Y (n_80));
  MX2X1 g5118__5115(.A (S4_o_A_s[2]), .B (S3_o_A_s[6]), .S0
       (en_pipe_i), .Y (n_79));
  MX2X1 g5119__7482(.A (S4_o_A_s[3]), .B (S3_o_A_s[7]), .S0
       (en_pipe_i), .Y (n_78));
  MX2X1 g5120__4733(.A (ready_o), .B (ready_i), .S0 (en_pipe_i), .Y
       (n_77));
  MX2X1 g5121__6161(.A (S4_o_square_s[0]), .B (S3_o_square_s[0]), .S0
       (en_pipe_i), .Y (n_76));
  MX2X1 g5122__9315(.A (S4_o_square_s[3]), .B (S3_o_square_s[3]), .S0
       (en_pipe_i), .Y (n_75));
  MX2X1 g5123__9945(.A (S4_o_square_s[4]), .B (S3_o_square_s[4]), .S0
       (en_pipe_i), .Y (n_74));
  MX2X1 g5124__2883(.A (N_o), .B (S1_N_s), .S0 (en_pipe_i), .Y (n_73));
  MX2X1 g5125__2346(.A (S2_o_A_s[0]), .B (S1_o_square_s[5]), .S0
       (en_pipe_i), .Y (n_72));
  MX2X1 g5126__1666(.A (S4_o_square_s[6]), .B (S3_o_square_s[6]), .S0
       (en_pipe_i), .Y (n_71));
  MX2X1 g5127__7410(.A (S4_o_square_s[7]), .B (S3_o_square_s[7]), .S0
       (en_pipe_i), .Y (n_70));
  MX2X1 g5128__6417(.A (S4_o_square_s[8]), .B (S3_o_square_s[8]), .S0
       (en_pipe_i), .Y (n_69));
  MX2X1 g5129__5477(.A (S2_o_A_s[2]), .B (S1_o_square_s[7]), .S0
       (en_pipe_i), .Y (n_68));
  MX2X1 g5130__2398(.A (S4_o_square_s[5]), .B (S3_o_square_s[5]), .S0
       (en_pipe_i), .Y (n_67));
  OAI2BB1X1 g5131__5107(.A0N (S1_o_square_s[3]), .A1N (root_o[0]), .B0
       (n_19), .Y (n_66));
  AOI2BB1X1 g5132__6260(.A0N (S2_o_B_s[2]), .A1N (S2_o_B_s[3]), .B0
       (n_7), .Y (n_110));
  INVX1 g5133(.A (n_63), .Y (n_62));
  MX2X1 g5134__4319(.A (S2_o_A_s[4]), .B (S1_o_square_s[9]), .S0
       (en_pipe_i), .Y (n_61));
  MX2X1 g5135__8428(.A (S2_o_A_s[5]), .B (S1_o_square_s[10]), .S0
       (en_pipe_i), .Y (n_60));
  MX2X1 g5136__5526(.A (n_260), .B (S2_o_root_s[1]), .S0 (en_pipe_i),
       .Y (n_59));
  MX2X1 g5137__6783(.A (S2_o_A_s[6]), .B (S1_o_square_s[11]), .S0
       (en_pipe_i), .Y (n_58));
  MX2X1 g5138__3680(.A (S2_o_A_s[7]), .B (S1_o_square_s[12]), .S0
       (en_pipe_i), .Y (n_57));
  MX2X1 g5139__1617(.A (S2_o_A_s[8]), .B (S1_o_square_s[13]), .S0
       (en_pipe_i), .Y (n_56));
  MX2X1 g5140__2802(.A (S2_o_A_s[9]), .B (S1_o_square_s[14]), .S0
       (en_pipe_i), .Y (n_55));
  MX2X1 g5141__1705(.A (S2_o_A_s[10]), .B (S1_o_square_s[15]), .S0
       (en_pipe_i), .Y (n_54));
  MX2X1 g5142__5122(.A (S2_o_A_s[11]), .B (S1_o_square_s[16]), .S0
       (en_pipe_i), .Y (n_53));
  MX2X1 g5143__8246(.A (S2_o_B_s[0]), .B (n_256), .S0 (en_pipe_i), .Y
       (n_52));
  MX2X1 g5144__7098(.A (S2_o_B_s[1]), .B (n_264), .S0 (en_pipe_i), .Y
       (n_51));
  MX2X1 g5145__6131(.A (n_256), .B (S2_o_root_s[2]), .S0 (en_pipe_i),
       .Y (n_50));
  MX2X1 g5146__1881(.A (S2_o_B_s[2]), .B (root_o[4]), .S0 (en_pipe_i),
       .Y (n_49));
  MX2X1 g5147__5115(.A (S2_o_B_s[3]), .B (root_o[5]), .S0 (en_pipe_i),
       .Y (n_48));
  MX2X1 g5148__7482(.A (S2_o_root_h_s[2]), .B (root_o[6]), .S0
       (en_pipe_i), .Y (n_47));
  MX2X1 g5149__4733(.A (S2_o_B_s[5]), .B (root_o[7]), .S0 (en_pipe_i),
       .Y (n_46));
  MX2X1 g5150__6161(.A (n_264), .B (S2_o_root_s[3]), .S0 (en_pipe_i),
       .Y (n_45));
  MX2X1 g5151__9315(.A (S1_o_square_s[0]), .B (S4_o_square_s[0]), .S0
       (en_pipe_i), .Y (n_44));
  MX2X1 g5152__9945(.A (S1_o_square_s[1]), .B (S4_o_square_s[1]), .S0
       (en_pipe_i), .Y (n_43));
  MX2X1 g5153__2883(.A (S2_o_square_s[0]), .B (S1_o_square_s[0]), .S0
       (en_pipe_i), .Y (n_42));
  MX2X1 g5154__2346(.A (S2_o_square_s[1]), .B (S1_o_square_s[1]), .S0
       (en_pipe_i), .Y (n_41));
  MX2X1 g5155__1666(.A (S2_o_square_s[2]), .B (S1_o_square_s[2]), .S0
       (en_pipe_i), .Y (n_40));
  MX2X1 g5156__7410(.A (S1_o_square_s[2]), .B (S4_o_square_s[2]), .S0
       (en_pipe_i), .Y (n_39));
  MX2X1 g5157__6417(.A (S1_o_square_s[3]), .B (S4_o_square_s[3]), .S0
       (en_pipe_i), .Y (n_38));
  CLKMX2X3 g5158__5477(.A (S1_o_input_s[1]), .B (input_i[1]), .S0
       (wr_input_i), .Y (n_37));
  CLKMX2X3 g5159__2398(.A (S1_input_ext_s[0]), .B (input_i[0]), .S0
       (wr_input_i), .Y (n_36));
  CLKMX2X3 g5160__5107(.A (S1_o_input_s[2]), .B (input_i[2]), .S0
       (wr_input_i), .Y (n_35));
  CLKMX2X3 g5161__6260(.A (S1_o_input_s[3]), .B (input_i[3]), .S0
       (wr_input_i), .Y (n_34));
  CLKMX2X3 g5162__4319(.A (S1_o_input_s[4]), .B (input_i[4]), .S0
       (wr_input_i), .Y (n_33));
  CLKMX2X3 g5163__8428(.A (S1_o_input_s[5]), .B (input_i[5]), .S0
       (wr_input_i), .Y (n_32));
  CLKMX2X3 g5164__5526(.A (S1_o_input_s[6]), .B (input_i[6]), .S0
       (wr_input_i), .Y (n_31));
  CLKMX2X3 g5165__6783(.A (S1_o_input_s[7]), .B (input_i[7]), .S0
       (wr_input_i), .Y (n_30));
  CLKMX2X3 g5166__3680(.A (S1_o_input_s[8]), .B (input_i[8]), .S0
       (wr_input_i), .Y (n_29));
  CLKMX2X3 g5167__1617(.A (S1_o_input_s[9]), .B (input_i[9]), .S0
       (wr_input_i), .Y (n_28));
  CLKMX2X3 g5168__2802(.A (S1_o_input_s[10]), .B (input_i[10]), .S0
       (wr_input_i), .Y (n_27));
  CLKMX2X3 g5169__1705(.A (S1_o_input_s[11]), .B (input_i[11]), .S0
       (wr_input_i), .Y (n_26));
  CLKMX2X3 g5170__5122(.A (S1_o_input_s[12]), .B (input_i[12]), .S0
       (wr_input_i), .Y (n_25));
  CLKMX2X3 g5171__8246(.A (S1_o_input_s[13]), .B (input_i[13]), .S0
       (wr_input_i), .Y (n_24));
  CLKMX2X3 g5172__7098(.A (S1_o_input_s[14]), .B (input_i[14]), .S0
       (wr_input_i), .Y (n_23));
  CLKMX2X3 g5173__6131(.A (S1_o_input_s[15]), .B (input_i[15]), .S0
       (wr_input_i), .Y (n_22));
  XNOR2X1 g5174__1881(.A (root_o[0]), .B (n_6), .Y (n_21));
  XNOR2X1 g5175__5115(.A (mux_root_i), .B (S2_o_B_s[5]), .Y (n_20));
  XNOR2X1 g5176__7482(.A (S2_o_B_s[3]), .B (mux_root_i), .Y (n_65));
  XNOR2X1 g5177__4733(.A (n_266), .B (mux_root_i), .Y (n_64));
  XNOR2X1 g5178__6161(.A (n_258), .B (n_7), .Y (n_63));
  OR2X1 g5179__9315(.A (S1_o_square_s[3]), .B (root_o[0]), .Y (n_19));
  NOR2X1 g5180__9945(.A (n_257), .B (n_265), .Y (n_18));
  INVX1 g5191(.A (mux_root_i), .Y (n_7));
  INVX1 g5192(.A (en_pipe_i), .Y (n_6));
  CLKBUFX3 fopt(.A (n_257), .Y (n_256));
  BUFX6 fopt1(.A (n_258), .Y (n_257));
  CLKBUFX3 fopt2(.A (root_o[2]), .Y (n_258));
  BUFX20 fopt3(.A (S1_o_root_s[2]), .Y (root_o[2]));
  CLKBUFX3 fopt5199(.A (n_261), .Y (n_260));
  CLKBUFX3 fopt5200(.A (n_262), .Y (n_261));
  CLKBUFX3 fopt5201(.A (root_o[1]), .Y (n_262));
  BUFX20 fopt5202(.A (S1_o_root_s[1]), .Y (root_o[1]));
  CLKBUFX3 fopt5203(.A (n_265), .Y (n_264));
  CLKBUFX3 fopt5204(.A (n_266), .Y (n_265));
  CLKBUFX3 fopt5205(.A (root_o[3]), .Y (n_266));
  BUFX20 fopt5206(.A (S1_o_root_s[3]), .Y (root_o[3]));
endmodule

module Square_root(valor_i, clk, rst_n, ready_o, root_o);
  input [15:0] valor_i;
  input clk, rst_n;
  output ready_o;
  output [7:0] root_o;
  wire [15:0] valor_i;
  wire clk, rst_n;
  wire ready_o;
  wire [7:0] root_o;
  wire [2:0] CONTROL_PATH_CurrentState;
  wire N_s, en_pipe_s, mux_root_s, n_0, n_1, n_2, n_3, n_4;
  wire n_5, ready_s, wr_input_s;
  DataPath DATA_PATH(.clk (clk), .rst_n (rst_n), .input_i (valor_i),
       .root_o (root_o), .ready_o (ready_o), .wr_input_i (wr_input_s),
       .en_pipe_i (en_pipe_s), .ready_i (ready_s), .mux_root_i
       (mux_root_s), .N_o (N_s));
  OR2X6 g118__2883(.A (CONTROL_PATH_CurrentState[0]), .B (n_5), .Y
       (en_pipe_s));
  OR2X1 g119__2346(.A (CONTROL_PATH_CurrentState[2]), .B
       (CONTROL_PATH_CurrentState[0]), .Y (ready_s));
  NOR2BX1 g120__1666(.AN (mux_root_s), .B
       (CONTROL_PATH_CurrentState[2]), .Y (n_5));
  NOR2X2 g121__7410(.A (mux_root_s), .B (CONTROL_PATH_CurrentState[0]),
       .Y (wr_input_s));
  DFFRHQX4 \CONTROL_PATH_CurrentState_reg[1] (.RN (rst_n), .CK (clk),
       .D (n_4), .Q (mux_root_s));
  OAI21X1 g141__6417(.A0 (CONTROL_PATH_CurrentState[2]), .A1 (n_3), .B0
       (n_0), .Y (n_4));
  DFFRHQX1 \CONTROL_PATH_CurrentState_reg[0] (.RN (rst_n), .CK (clk),
       .D (n_2), .Q (CONTROL_PATH_CurrentState[0]));
  AOI21X1 g143__5477(.A0 (CONTROL_PATH_CurrentState[0]), .A1 (N_s), .B0
       (mux_root_s), .Y (n_3));
  DFFRHQX1 \CONTROL_PATH_CurrentState_reg[2] (.RN (rst_n), .CK (clk),
       .D (n_1), .Q (CONTROL_PATH_CurrentState[2]));
  NOR2X1 g145__2398(.A (mux_root_s), .B (CONTROL_PATH_CurrentState[2]),
       .Y (n_2));
  INVX1 g146(.A (n_0), .Y (n_1));
  NAND2BX1 g147__5107(.AN (CONTROL_PATH_CurrentState[0]), .B
       (mux_root_s), .Y (n_0));
endmodule

