
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep  5 2025 10:27:41 -03 (Sep  5 2025 13:27:41 UTC)

// Verification Directory fv/square_root 

module square_root(valor_i, clk, rst_n, ready_o, root_o);
  input [15:0] valor_i;
  input clk, rst_n;
  output ready_o;
  output [7:0] root_o;
  wire [15:0] valor_i;
  wire clk, rst_n;
  wire ready_o;
  wire [7:0] root_o;
  wire [16:0] DATA_PATH_2_square_s;
  wire [16:0] DATA_PATH_1_square_s;
  wire [1:0] CONTROL_PATH_CurrentState;
  wire [15:0] valor_s;
  wire [7:0] root_2_s;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, n_0, n_1,
       n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_114, n_115, n_116, n_117;
  wire n_118, n_119, n_120, n_121, n_122, n_123, n_124, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_132, n_133;
  wire n_134, n_135, n_136, n_137, n_138, n_139, n_140, n_141;
  wire n_142, n_143, n_144, n_145, n_146, n_147, n_148, n_149;
  wire n_150, n_151, n_152, n_153, n_154, n_155, n_156, n_157;
  wire n_158, n_159, n_160, n_161, n_162, n_163, n_164, n_165;
  wire n_166, n_167, n_168, n_169, n_170, n_171, n_172, n_173;
  wire n_174, n_175, n_176, n_177, n_178, n_179, n_180, n_181;
  wire n_182, n_183, n_184, n_185, n_186, n_187, n_188, n_189;
  wire n_190, n_191, n_192, n_193, n_194, n_195, n_196, n_197;
  wire n_198, n_199, n_200, n_201, n_202, n_203, n_204, n_205;
  wire n_206, n_207, n_208, n_209, n_210, n_211, n_212, n_213;
  wire n_214, n_215, n_216, n_217, n_218, n_219, n_220, n_221;
  wire n_222, n_223, n_224, n_225, n_226, n_227, n_228, n_229;
  wire n_230, n_231, n_232, n_233, n_234, n_235, n_236, n_237;
  wire n_238, n_239, n_240, n_241, n_242, n_243, n_244, n_245;
  wire n_246, n_247, n_248, n_249, n_250, n_251, n_252, n_253;
  wire n_254, n_255, n_256, n_257, n_258, n_259, n_260, n_261;
  wire n_262, n_263, n_264, n_265, n_266, n_267, n_268, n_269;
  wire n_270, n_271, n_272, n_273, n_274, n_275, n_276, n_277;
  wire n_278, n_279, n_280, n_281, n_282, n_283, n_284, n_285;
  wire n_286, n_287, n_288, n_289, n_290, n_291, n_292, n_293;
  wire n_294, n_295, n_296, n_297, n_298, n_299, n_300, n_301;
  wire n_302, n_303, n_304, n_305, n_306, n_307, n_308, n_309;
  wire n_310, n_311, n_312, n_313, n_314, n_315, n_316, n_317;
  wire n_318, n_319, n_320, n_321, n_322, n_323, n_324, n_325;
  wire n_326, n_327, n_328, n_329, n_330, n_331, n_332, n_333;
  wire n_334, n_335, n_336, n_337, n_338, n_339, n_340, n_341;
  wire n_342, n_343, n_344, n_345, n_346, n_347, n_348, n_349;
  wire n_350, n_351, n_352, n_353, n_354, n_355, n_356, n_357;
  wire n_358, n_359, n_360, n_361, n_362, n_363, n_364, n_365;
  wire n_366, n_367, n_368, n_369, n_370, n_371, n_372, n_373;
  wire n_374, n_375, n_376, n_377, n_378, n_379, n_380, n_381;
  wire n_382, n_383, n_384, n_385, n_386, n_387, n_388, n_389;
  wire n_390, n_391, n_392, n_393, n_394, n_395, n_396, n_397;
  wire n_398, n_399, n_400, root_reg_s;
  DFFRHQX1 \DATA_PATH_2_SQUARE_REG_reg[15].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_400), .Q (DATA_PATH_2_square_s[15]));
  AO22X1 g9058__2398(.A0 (n_397), .A1 (n_399), .B0
       (DATA_PATH_2_square_s[15]), .B1 (n_396), .Y (n_400));
  DFFRHQX1 \DATA_PATH_2_SQUARE_REG_reg[14].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_398), .Q (DATA_PATH_2_square_s[14]));
  XNOR2X1 g9061__5107(.A (n_165), .B (n_392), .Y (n_399));
  DFFRHQX1 \DATA_PATH_1_SQUARE_REG_reg[15].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_394), .Q (DATA_PATH_1_square_s[15]));
  AO22X1 g9060__6260(.A0 (n_397), .A1 (n_393), .B0
       (DATA_PATH_2_square_s[14]), .B1 (n_396), .Y (n_398));
  DFFRHQX1 \DATA_PATH_1_SQUARE_REG_reg[14].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_395), .Q (DATA_PATH_1_square_s[14]));
  DFFRHQX8 \DATA_PATH_1_ROOT_REG_reg[3].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_391), .Q (root_o[3]));
  DFFRHQX8 \DATA_PATH_1_ROOT_REG_reg[7].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_386), .Q (root_o[7]));
  DFFRHQX8 \DATA_PATH_1_ROOT_REG_reg[5].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_385), .Q (root_o[5]));
  DFFRHQX8 \DATA_PATH_1_ROOT_REG_reg[4].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_387), .Q (root_o[4]));
  DFFRHQX8 \DATA_PATH_1_ROOT_REG_reg[1].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_383), .Q (root_o[1]));
  DFFRHQX8 \DATA_PATH_1_ROOT_REG_reg[2].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_384), .Q (root_o[2]));
  DFFRHQX8 \DATA_PATH_1_ROOT_REG_reg[6].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_390), .Q (root_o[6]));
  AO22X1 g9084__4319(.A0 (n_397), .A1 (n_379), .B0
       (DATA_PATH_1_square_s[14]), .B1 (n_396), .Y (n_395));
  AO22X1 g9085__8428(.A0 (n_397), .A1 (n_378), .B0
       (DATA_PATH_1_square_s[15]), .B1 (n_396), .Y (n_394));
  DFFRHQX1 \DATA_PATH_2_SQUARE_REG_reg[13].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_382), .Q (DATA_PATH_2_square_s[13]));
  ADDHX1 g9062__5526(.A (n_156), .B (n_374), .CO (n_392), .S (n_393));
  AO22X1 g9077__6783(.A0 (n_123), .A1 (n_389), .B0 (root_o[3]), .B1
       (n_388), .Y (n_391));
  AO22X1 g9076__3680(.A0 (n_298), .A1 (n_389), .B0 (root_o[6]), .B1
       (n_388), .Y (n_390));
  AO22X1 g9072__1617(.A0 (n_186), .A1 (n_389), .B0 (root_o[4]), .B1
       (n_388), .Y (n_387));
  DFFRHQX1 \DATA_PATH_1_SQUARE_REG_reg[11].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_381), .Q (DATA_PATH_1_square_s[11]));
  AO22X1 g9079__2802(.A0 (n_318), .A1 (n_389), .B0 (root_o[7]), .B1
       (n_388), .Y (n_386));
  AO22X1 g9078__1705(.A0 (n_262), .A1 (n_389), .B0 (root_o[5]), .B1
       (n_388), .Y (n_385));
  AO22X1 g9071__5122(.A0 (n_52), .A1 (n_389), .B0 (root_o[2]), .B1
       (n_388), .Y (n_384));
  MX2X1 g9080__8246(.A (n_389), .B (n_388), .S0 (root_o[1]), .Y
       (n_383));
  DFFRHQX1 \DATA_PATH_1_SQUARE_REG_reg[13].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_380), .Q (DATA_PATH_1_square_s[13]));
  AO22X1 g9073__7098(.A0 (n_397), .A1 (n_375), .B0
       (DATA_PATH_2_square_s[13]), .B1 (n_396), .Y (n_382));
  DFFRHQX1 \CONTROL_PATH_CurrentState_reg[0] (.RN (rst_n), .CK (clk),
       .D (n_377), .Q (CONTROL_PATH_CurrentState[0]));
  AO22X1 g9093__6131(.A0 (n_397), .A1 (n_369), .B0
       (DATA_PATH_1_square_s[11]), .B1 (n_396), .Y (n_381));
  DFFRHQX1 \ROOT_REG_reg[0].dffn_sig_q_reg (.RN (rst_n), .CK (clk), .D
       (n_373), .Q (root_reg_s));
  AO22X1 g9103__1881(.A0 (n_397), .A1 (n_372), .B0
       (DATA_PATH_1_square_s[13]), .B1 (n_396), .Y (n_380));
  XNOR2X1 g9104__5115(.A (n_237), .B (n_371), .Y (n_379));
  XNOR2X1 g9105__7482(.A (n_238), .B (n_370), .Y (n_378));
  NAND2X1 g9089__4733(.A (n_396), .B (n_376), .Y (n_377));
  DFFRHQX1 \DATA_PATH_1_SQUARE_REG_reg[16].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_364), .Q (DATA_PATH_1_square_s[16]));
  DFFRHQX1 \DATA_PATH_2_SQUARE_REG_reg[11].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_365), .Q (DATA_PATH_2_square_s[11]));
  DFFRHQX1 \DATA_PATH_1_SQUARE_REG_reg[10].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_366), .Q (DATA_PATH_1_square_s[10]));
  ADDHX1 g9088__6161(.A (n_202), .B (n_351), .CO (n_374), .S (n_375));
  MX2X1 g9096__9315(.A (n_358), .B (root_reg_s), .S0 (n_209), .Y
       (n_373));
  DFFRHQX1 \DATA_PATH_2_SQUARE_REG_reg[9].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_360), .Q (DATA_PATH_2_square_s[9]));
  DFFRHQX1 \DATA_PATH_2_SQUARE_REG_reg[16].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_361), .Q (DATA_PATH_2_square_s[16]));
  ADDHX1 g9118__9945(.A (n_168), .B (n_346), .CO (n_371), .S (n_372));
  NAND4BX2 g9126__2883(.AN (n_368), .B (n_345), .C (n_213), .D (n_367),
       .Y (n_370));
  XNOR2X1 g9116__2346(.A (n_368), .B (n_367), .Y (n_369));
  AO22X1 g9114__1666(.A0 (n_397), .A1 (n_355), .B0
       (DATA_PATH_1_square_s[10]), .B1 (n_396), .Y (n_366));
  AO22X1 g9094__7410(.A0 (n_397), .A1 (n_353), .B0
       (DATA_PATH_2_square_s[11]), .B1 (n_396), .Y (n_365));
  AO22X1 g9095__6417(.A0 (n_397), .A1 (n_363), .B0
       (DATA_PATH_1_square_s[16]), .B1 (n_396), .Y (n_364));
  DFFRHQX1 \DATA_PATH_2_SQUARE_REG_reg[10].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_359), .Q (DATA_PATH_2_square_s[10]));
  OR3X4 g9097__5477(.A (n_182), .B (n_362), .C (n_363), .Y (n_376));
  DFFRHQX1 \DATA_PATH_2_SQUARE_REG_reg[12].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_357), .Q (DATA_PATH_2_square_s[12]));
  DFFRX2 \DATA_PATH_1_SQUARE_REG_reg[9].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_356), .Q (DATA_PATH_1_square_s[9]), .QN
       (UNCONNECTED));
  NOR3X4 g9106__2398(.A (n_207), .B (n_354), .C (n_362), .Y (n_389));
  AO22X1 g9115__5107(.A0 (n_397), .A1 (n_362), .B0
       (DATA_PATH_2_square_s[16]), .B1 (n_396), .Y (n_361));
  AO22X1 g9102__6260(.A0 (n_397), .A1 (n_347), .B0
       (DATA_PATH_2_square_s[9]), .B1 (n_396), .Y (n_360));
  AO22X1 g9108__4319(.A0 (n_397), .A1 (n_338), .B0
       (DATA_PATH_2_square_s[10]), .B1 (n_396), .Y (n_359));
  INVX1 g9112(.A (n_363), .Y (n_358));
  AO22X1 g9124__8428(.A0 (n_397), .A1 (n_340), .B0
       (DATA_PATH_2_square_s[12]), .B1 (n_396), .Y (n_357));
  AO22X1 g9107__5526(.A0 (n_397), .A1 (n_341), .B0
       (DATA_PATH_1_square_s[9]), .B1 (n_396), .Y (n_356));
  DFFRHQX1 \DATA_PATH_1_SQUARE_REG_reg[12].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_348), .Q (DATA_PATH_1_square_s[12]));
  ADDHX1 g9127__6783(.A (n_143), .B (n_344), .CO (n_367), .S (n_355));
  MXI2X1 g9109__3680(.A (n_184), .B (n_225), .S0 (n_352), .Y (n_354));
  CLKXOR2X1 g9113__1617(.A (n_350), .B (n_349), .Y (n_353));
  CLKXOR2X1 g9117__2802(.A (n_224), .B (n_352), .Y (n_363));
  AND3X6 g9121__1705(.A (n_350), .B (n_339), .C (n_349), .Y (n_351));
  DFFRHQX1 \DATA_PATH_2_SQUARE_REG_reg[7].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_343), .Q (DATA_PATH_2_square_s[7]));
  DFFRHQX2 \DATA_PATH_1_SQUARE_REG_reg[8].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_342), .Q (DATA_PATH_1_square_s[8]));
  AO22X1 g9123__5122(.A0 (n_397), .A1 (n_332), .B0
       (DATA_PATH_1_square_s[12]), .B1 (n_396), .Y (n_348));
  XNOR2X1 g9125__8246(.A (n_244), .B (n_333), .Y (n_347));
  XNOR2X2 g9135__7098(.A (n_180), .B (n_331), .Y (n_362));
  AND3XL g9152__6131(.A (n_345), .B (n_266), .C (n_344), .Y (n_346));
  DFFRHQX1 \DATA_PATH_2_SQUARE_REG_reg[6].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_336), .Q (DATA_PATH_2_square_s[6]));
  DFFRHQX1 \DATA_PATH_2_SQUARE_REG_reg[8].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_337), .Q (DATA_PATH_2_square_s[8]));
  AO22X1 g9128__1881(.A0 (n_397), .A1 (n_326), .B0
       (DATA_PATH_2_square_s[7]), .B1 (n_396), .Y (n_343));
  AO22X1 g9132__5115(.A0 (n_397), .A1 (n_325), .B0
       (DATA_PATH_1_square_s[8]), .B1 (n_396), .Y (n_342));
  XNOR2X1 g9134__7482(.A (n_329), .B (n_327), .Y (n_341));
  CLKXOR2X1 g9139__4733(.A (n_339), .B (n_323), .Y (n_340));
  XNOR2X1 g9140__6161(.A (n_335), .B (n_334), .Y (n_338));
  DFFRHQX1 \DATA_PATH_1_SQUARE_REG_reg[7].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_330), .Q (DATA_PATH_1_square_s[7]));
  AO22X1 g9133__9315(.A0 (n_397), .A1 (n_322), .B0
       (DATA_PATH_2_square_s[8]), .B1 (n_396), .Y (n_337));
  AOI2BB1X4 g9131__9945(.A0N (n_214), .A1N (n_317), .B0 (n_268), .Y
       (n_352));
  AO22X1 g9136__2883(.A0 (n_397), .A1 (n_319), .B0
       (DATA_PATH_2_square_s[6]), .B1 (n_396), .Y (n_336));
  NOR2BX4 g9146__2346(.AN (n_335), .B (n_334), .Y (n_349));
  DFFRHQX1 \DATA_PATH_1_SQUARE_REG_reg[6].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_328), .Q (DATA_PATH_1_square_s[6]));
  NOR2X1 g9138__1666(.A (n_245), .B (n_321), .Y (n_333));
  XNOR2X1 g9141__7410(.A (n_345), .B (n_315), .Y (n_332));
  DFFRHQX1 \DATA_PATH_2_SQUARE_REG_reg[5].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_320), .Q (DATA_PATH_2_square_s[5]));
  AOI21X2 g9151__6417(.A0 (n_278), .A1 (n_300), .B0 (n_316), .Y
       (n_331));
  AO22X1 g9159__5477(.A0 (n_397), .A1 (n_309), .B0
       (DATA_PATH_1_square_s[7]), .B1 (n_396), .Y (n_330));
  OAI21X2 g9158__2398(.A0 (n_329), .A1 (n_308), .B0 (n_235), .Y
       (n_344));
  AO22X1 g9137__5107(.A0 (n_397), .A1 (n_306), .B0 (n_31), .B1 (n_396),
       .Y (n_328));
  OAI2BB1X1 g9144__6260(.A0N (n_324), .A1N (n_305), .B0 (n_241), .Y
       (n_327));
  CLKXOR2X1 g9149__4319(.A (n_243), .B (n_302), .Y (n_326));
  CLKXOR2X1 g9150__8428(.A (n_324), .B (n_303), .Y (n_325));
  NAND2X1 g9155__5526(.A (n_299), .B (n_311), .Y (n_323));
  NOR2X6 g9157__6783(.A (n_260), .B (n_312), .Y (n_334));
  ADDHX1 g9143__3680(.A (n_203), .B (n_288), .CO (n_321), .S (n_322));
  AO22X1 g9160__1617(.A0 (n_397), .A1 (n_292), .B0
       (DATA_PATH_2_square_s[5]), .B1 (n_396), .Y (n_320));
  XNOR2X1 g9162__2802(.A (n_301), .B (n_294), .Y (n_319));
  CLKXOR2X1 g9142__1705(.A (root_o[7]), .B (n_297), .Y (n_318));
  AOI211X4 g9148__5122(.A0 (n_314), .A1 (n_296), .B0 (n_173), .C0
       (n_313), .Y (n_317));
  OAI21X2 g9154__8246(.A0 (n_279), .A1 (n_291), .B0 (n_269), .Y
       (n_316));
  AOI21X1 g9163__7098(.A0 (n_314), .A1 (n_304), .B0 (n_313), .Y
       (n_315));
  AOI21X4 g9168__6131(.A0 (n_286), .A1 (n_310), .B0 (n_249), .Y
       (n_312));
  OAI2BB1X1 g9169__1881(.A0N (n_253), .A1N (n_310), .B0 (n_282), .Y
       (n_311));
  CLKXOR2X1 g9178__5115(.A (n_255), .B (n_307), .Y (n_309));
  AOI21X2 g9172__7482(.A0 (n_192), .A1 (n_307), .B0 (n_240), .Y
       (n_308));
  DFFRHQX1 \DATA_PATH_1_SQUARE_REG_reg[5].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_295), .Q (DATA_PATH_1_square_s[5]));
  DFFRHQX1 \DATA_PATH_2_SQUARE_REG_reg[4].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_290), .Q (DATA_PATH_2_square_s[4]));
  XNOR2X1 g9161__4733(.A (n_197), .B (n_281), .Y (n_306));
  OR2X1 g9164__6161(.A (n_265), .B (n_304), .Y (n_305));
  NAND2BX1 g9166__9315(.AN (n_304), .B (n_289), .Y (n_303));
  OAI2BB1X1 g9171__9945(.A0N (n_301), .A1N (n_293), .B0 (n_242), .Y
       (n_302));
  NAND2X2 g9193__2883(.A (n_283), .B (n_299), .Y (n_300));
  ADDHX1 g9153__2346(.A (root_o[6]), .B (n_261), .CO (n_297), .S
       (n_298));
  OAI21X4 g9165__1666(.A0 (n_211), .A1 (n_257), .B0 (n_284), .Y
       (n_296));
  AO22X1 g9170__7410(.A0 (n_397), .A1 (n_275), .B0
       (DATA_PATH_1_square_s[5]), .B1 (n_396), .Y (n_295));
  NOR2X1 g9173__6417(.A (n_195), .B (n_293), .Y (n_294));
  CLKXOR2X1 g9180__5477(.A (n_200), .B (n_273), .Y (n_292));
  AOI2BB1X4 g9179__2398(.A0N (n_177), .A1N (n_287), .B0 (n_285), .Y
       (n_291));
  AO22X1 g9177__5107(.A0 (n_397), .A1 (n_274), .B0
       (DATA_PATH_2_square_s[4]), .B1 (n_396), .Y (n_290));
  OAI21X4 g9194__6260(.A0 (n_234), .A1 (n_289), .B0 (n_267), .Y
       (n_313));
  OAI221X1 g9175__4319(.A0 (n_277), .A1 (n_287), .B0 (n_276), .B1
       (n_194), .C0 (n_286), .Y (n_288));
  CLKINVX4 g9182(.A (n_285), .Y (n_310));
  INVX2 g9176(.A (n_284), .Y (n_304));
  AOI21X2 g9199__8428(.A0 (n_263), .A1 (n_282), .B0 (n_163), .Y
       (n_283));
  AOI2BB2X2 g9208__5526(.A0N (n_250), .A1N (n_259), .B0 (n_282), .B1
       (n_264), .Y (n_299));
  NAND2X2 g9190__6783(.A (n_247), .B (n_271), .Y (n_307));
  DFFRX2 \DATA_PATH_1_SQUARE_REG_reg[4].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_270), .Q (DATA_PATH_1_square_s[4]), .QN
       (UNCONNECTED0));
  NOR2X1 g9174__3680(.A (n_198), .B (n_280), .Y (n_281));
  NAND2X2 g9181__1617(.A (n_172), .B (n_280), .Y (n_284));
  DFFRHQX1 \DATA_PATH_2_SQUARE_REG_reg[3].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_254), .Q (DATA_PATH_2_square_s[3]));
  NOR2X6 g9184__2802(.A (n_287), .B (n_272), .Y (n_285));
  NAND2X2 g9215__1705(.A (n_278), .B (n_282), .Y (n_279));
  DFFRHQX1 \DATA_PATH_2_SQUARE_REG_reg[2].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_252), .Q (DATA_PATH_2_square_s[2]));
  OAI21X1 g9185__5122(.A0 (n_152), .A1 (n_277), .B0 (n_276), .Y
       (n_293));
  DFFRHQX1 \DATA_PATH_1_SQUARE_REG_reg[3].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_258), .Q (DATA_PATH_1_square_s[3]));
  XNOR2X1 g9192__8246(.A (n_251), .B (n_151), .Y (n_275));
  XNOR2X1 g9191__7098(.A (n_175), .B (n_212), .Y (n_274));
  INVX1 g9186(.A (n_272), .Y (n_273));
  NAND2X4 g9196__6131(.A (n_248), .B (n_210), .Y (n_271));
  AO22X1 g9201__1881(.A0 (n_397), .A1 (n_216), .B0
       (DATA_PATH_1_square_s[4]), .B1 (n_396), .Y (n_270));
  AOI31X1 g9219__5115(.A0 (n_110), .A1 (n_201), .A2 (n_188), .B0
       (n_167), .Y (n_269));
  OR2X1 g9221__7482(.A (n_189), .B (n_239), .Y (n_268));
  NAND2X2 g9220__4733(.A (n_266), .B (n_236), .Y (n_267));
  NOR2X4 g9203__6161(.A (n_205), .B (n_265), .Y (n_289));
  NOR2X2 g9207__9315(.A (n_264), .B (n_263), .Y (n_286));
  ADDHX1 g9183__9945(.A (root_o[5]), .B (n_185), .CO (n_261), .S
       (n_262));
  INVX1 g9218(.A (n_259), .Y (n_260));
  AO22X1 g9231__2883(.A0 (n_397), .A1 (n_256), .B0
       (DATA_PATH_1_square_s[3]), .B1 (n_396), .Y (n_258));
  NAND3X2 g9227__2346(.A (n_256), .B (n_191), .C (n_255), .Y (n_257));
  AO22X1 g9200__1666(.A0 (n_397), .A1 (n_171), .B0
       (DATA_PATH_2_square_s[3]), .B1 (n_396), .Y (n_254));
  INVX1 g9211(.A (n_263), .Y (n_253));
  OAI2BB1X1 g9217__7410(.A0N (DATA_PATH_2_square_s[2]), .A1N (n_396),
       .B0 (n_208), .Y (n_252));
  DFFRHQX1 \INPUT_REG_reg[1].dffn_sig_q_reg (.RN (rst_n), .CK (clk), .D
       (n_229), .Q (valor_s[1]));
  NOR2X6 g9197__6417(.A (n_187), .B (n_251), .Y (n_280));
  DFFRHQX1 \INPUT_REG_reg[9].dffn_sig_q_reg (.RN (rst_n), .CK (clk), .D
       (n_220), .Q (valor_s[9]));
  DFFRHQX1 \INPUT_REG_reg[3].dffn_sig_q_reg (.RN (rst_n), .CK (clk), .D
       (n_227), .Q (valor_s[3]));
  NOR2X6 g9187__5477(.A (n_196), .B (n_246), .Y (n_272));
  NOR2X4 g9225__2398(.A (n_250), .B (n_249), .Y (n_282));
  DFFRHQX1 \INPUT_REG_reg[4].dffn_sig_q_reg (.RN (rst_n), .CK (clk), .D
       (n_226), .Q (valor_s[4]));
  DFFRHQX1 \INPUT_REG_reg[15].dffn_sig_q_reg (.RN (rst_n), .CK (clk),
       .D (n_206), .Q (valor_s[15]));
  DFFRHQX1 \INPUT_REG_reg[0].dffn_sig_q_reg (.RN (rst_n), .CK (clk), .D
       (n_230), .Q (valor_s[0]));
  DFFRHQX1 \INPUT_REG_reg[11].dffn_sig_q_reg (.RN (rst_n), .CK (clk),
       .D (n_218), .Q (valor_s[11]));
  DFFRHQX1 \INPUT_REG_reg[5].dffn_sig_q_reg (.RN (rst_n), .CK (clk), .D
       (n_233), .Q (valor_s[5]));
  DFFRHQX1 \INPUT_REG_reg[6].dffn_sig_q_reg (.RN (rst_n), .CK (clk), .D
       (n_223), .Q (valor_s[6]));
  DFFRHQX1 \INPUT_REG_reg[7].dffn_sig_q_reg (.RN (rst_n), .CK (clk), .D
       (n_222), .Q (valor_s[7]));
  DFFRHQX1 \INPUT_REG_reg[8].dffn_sig_q_reg (.RN (rst_n), .CK (clk), .D
       (n_231), .Q (valor_s[8]));
  DFFRHQX1 \INPUT_REG_reg[10].dffn_sig_q_reg (.RN (rst_n), .CK (clk),
       .D (n_219), .Q (valor_s[10]));
  DFFRHQX1 \INPUT_REG_reg[14].dffn_sig_q_reg (.RN (rst_n), .CK (clk),
       .D (n_221), .Q (valor_s[14]));
  DFFRHQX1 \INPUT_REG_reg[2].dffn_sig_q_reg (.RN (rst_n), .CK (clk), .D
       (n_228), .Q (valor_s[2]));
  DFFRHQX1 \INPUT_REG_reg[13].dffn_sig_q_reg (.RN (rst_n), .CK (clk),
       .D (n_215), .Q (valor_s[13]));
  DFFRHQX1 \INPUT_REG_reg[12].dffn_sig_q_reg (.RN (rst_n), .CK (clk),
       .D (n_217), .Q (valor_s[12]));
  CLKINVX6 g9206(.A (n_251), .Y (n_248));
  NOR2X2 g9212__5107(.A (n_142), .B (n_247), .Y (n_265));
  INVX2 g9195(.A (n_246), .Y (n_277));
  AOI21X4 g9223__6260(.A0 (n_245), .A1 (n_244), .B0 (n_160), .Y
       (n_259));
  NOR2BX4 g9213__4319(.AN (n_243), .B (n_242), .Y (n_263));
  INVX1 g9226(.A (n_240), .Y (n_241));
  NOR4BX2 g9245__8428(.AN (n_238), .B (n_106), .C (n_237), .D (n_169),
       .Y (n_239));
  OAI21X2 g9248__5526(.A0 (n_204), .A1 (n_329), .B0 (n_235), .Y
       (n_236));
  INVX3 g9244(.A (n_234), .Y (n_314));
  DFFRHQX4 \CONTROL_PATH_CurrentState_reg[1] (.RN (rst_n), .CK (clk),
       .D (n_396), .Q (CONTROL_PATH_CurrentState[1]));
  DFFRX2 \DATA_PATH_1_SQUARE_REG_reg[0].dffn_sig_q_reg (.RN (rst_n),
       .CK (clk), .D (n_199), .Q (root_2_s[0]), .QN (UNCONNECTED1));
  MX2X1 g9340__6783(.A (n_18), .B (valor_s[5]), .S0 (n_232), .Y
       (n_233));
  MX2X1 g9334__3680(.A (n_3), .B (valor_s[8]), .S0 (n_232), .Y (n_231));
  MX2X1 g9335__1617(.A (n_13), .B (valor_s[0]), .S0 (n_232), .Y
       (n_230));
  MX2X1 g9336__2802(.A (n_6), .B (valor_s[1]), .S0 (n_232), .Y (n_229));
  MX2X1 g9337__1705(.A (n_5), .B (valor_s[2]), .S0 (n_232), .Y (n_228));
  MX2X1 g9338__5122(.A (n_17), .B (valor_s[3]), .S0 (n_232), .Y
       (n_227));
  MX2X1 g9339__8246(.A (n_16), .B (n_29), .S0 (n_232), .Y (n_226));
  AND2X1 g9291__7098(.A (n_224), .B (n_158), .Y (n_225));
  MX2X1 g9341__6131(.A (n_22), .B (valor_s[6]), .S0 (n_232), .Y
       (n_223));
  MX2X1 g9342__1881(.A (n_1), .B (valor_s[7]), .S0 (n_232), .Y (n_222));
  MX2X1 g9343__5115(.A (n_12), .B (valor_s[14]), .S0 (n_232), .Y
       (n_221));
  MX2X1 g9344__7482(.A (n_2), .B (valor_s[9]), .S0 (n_232), .Y (n_220));
  MX2X1 g9345__4733(.A (n_11), .B (valor_s[10]), .S0 (n_232), .Y
       (n_219));
  MX2X1 g9346__6161(.A (n_14), .B (valor_s[11]), .S0 (n_232), .Y
       (n_218));
  MX2X1 g9347__9315(.A (n_9), .B (valor_s[12]), .S0 (n_232), .Y
       (n_217));
  CLKXOR2X1 g9228__9945(.A (n_190), .B (n_128), .Y (n_216));
  MX2X1 g9349__2883(.A (n_4), .B (valor_s[13]), .S0 (n_232), .Y
       (n_215));
  NAND3X1 g9270__2346(.A (n_345), .B (n_238), .C (n_213), .Y (n_214));
  NOR2X1 g9204__1666(.A (n_149), .B (n_179), .Y (n_212));
  INVX2 g9235(.A (n_210), .Y (n_211));
  NAND2X1 g9400__7410(.A (CONTROL_PATH_CurrentState[0]), .B (n_183), .Y
       (n_209));
  AOI21X1 g9229__6417(.A0 (n_397), .A1 (n_176), .B0 (n_207), .Y
       (n_208));
  MX2X1 g9348__5477(.A (n_8), .B (valor_s[15]), .S0 (n_232), .Y
       (n_206));
  OAI21X4 g9198__2398(.A0 (n_140), .A1 (n_178), .B0 (n_141), .Y
       (n_246));
  OAI2BB1X1 g9233__5107(.A0N (n_205), .A1N (n_324), .B0 (n_204), .Y
       (n_240));
  NAND2X4 g9240__6260(.A (n_203), .B (n_244), .Y (n_249));
  NAND3X2 g9250__4319(.A (n_266), .B (n_324), .C (n_174), .Y (n_234));
  AND3X1 g9272__8428(.A (n_339), .B (n_202), .C (n_201), .Y (n_278));
  NOR2X6 g9209__5526(.A (n_130), .B (n_181), .Y (n_251));
  NAND2X4 g9224__6783(.A (n_200), .B (n_193), .Y (n_287));
  NAND2BX1 g9359__3680(.AN (root_2_s[0]), .B (n_232), .Y (n_199));
  AOI21X4 g9234__1617(.A0 (n_198), .A1 (n_197), .B0 (n_145), .Y
       (n_247));
  NAND2X1 g9222__2802(.A (n_200), .B (n_196), .Y (n_276));
  AOI21X2 g9232__1705(.A0 (n_195), .A1 (n_301), .B0 (n_146), .Y
       (n_242));
  INVX1 g9236(.A (n_193), .Y (n_194));
  AND2X1 g9239__5122(.A (n_255), .B (n_324), .Y (n_192));
  CLKAND2X2 g9246__8246(.A (n_118), .B (n_190), .Y (n_191));
  OAI32X1 g9276__7098(.A0 (n_166), .A1 (n_131), .A2 (n_135), .B0
       (n_164), .B1 (n_100), .Y (n_189));
  OAI2BB1X1 g9271__6131(.A0N (valor_s[13]), .A1N (n_93), .B0 (n_159),
       .Y (n_188));
  NOR2X6 g9242__1881(.A (n_153), .B (n_187), .Y (n_210));
  ADDHX1 g9202__5115(.A (root_o[4]), .B (n_122), .CO (n_185), .S
       (n_186));
  ADDHX1 g9265__7482(.A (n_44), .B (n_155), .CO (n_245), .S (n_203));
  ADDHX1 g9309__4733(.A (n_111), .B (n_7), .CO (n_184), .S (n_224));
  INVX1 g9462(.A (n_182), .Y (n_183));
  NOR2X6 g9247__6161(.A (n_127), .B (n_150), .Y (n_181));
  XNOR2X1 g9384__9315(.A (DATA_PATH_2_square_s[16]), .B (n_154), .Y
       (n_180));
  INVX1 g9210(.A (n_178), .Y (n_179));
  NAND4X1 g9216__9945(.A (n_78), .B (n_170), .C (n_176), .D (n_175), .Y
       (n_177));
  INVX2 g9409(.A (n_232), .Y (n_207));
  INVX3 g9290(.A (n_174), .Y (n_329));
  OAI32X1 g9275__2883(.A0 (DATA_PATH_1_square_s[10]), .A1 (n_162), .A2
       (n_368), .B0 (n_161), .B1 (n_95), .Y (n_173));
  AND2X1 g9238__2346(.A (n_197), .B (n_255), .Y (n_172));
  CLKXOR2X1 g9230__1666(.A (n_148), .B (n_170), .Y (n_171));
  AOI22X1 g9269__7410(.A0 (n_117), .A1 (n_168), .B0 (valor_s[13]), .B1
       (n_132), .Y (n_169));
  OAI32X1 g9273__6417(.A0 (n_166), .A1 (n_133), .A2 (n_165), .B0
       (n_164), .B1 (n_114), .Y (n_167));
  OAI32X1 g9274__5477(.A0 (n_162), .A1 (n_113), .A2 (n_121), .B0
       (n_161), .B1 (n_94), .Y (n_163));
  CLKAND2X3 g9243__2398(.A (n_301), .B (n_243), .Y (n_193));
  ADDHX4 g9267__5107(.A (n_85), .B (n_107), .CO (n_160), .S (n_244));
  NAND3X1 g9292__6260(.A (valor_s[12]), .B (n_112), .C (n_202), .Y
       (n_159));
  INVX1 g9464(.A (n_147), .Y (n_158));
  INVX2 g9408(.A (n_397), .Y (n_157));
  AOI2BB1X2 g9298__4319(.A0N (n_137), .A1N (n_101), .B0 (n_126), .Y
       (n_256));
  AOI21X4 g9303__8428(.A0 (n_69), .A1 (n_108), .B0 (n_125), .Y (n_174));
  NOR2BX2 g9293__5526(.AN (n_156), .B (n_165), .Y (n_201));
  AOI2BB1X4 g9304__6783(.A0N (n_72), .A1N (n_155), .B0 (n_139), .Y
       (n_324));
  OR2X4 g9417__3680(.A (CONTROL_PATH_CurrentState[0]), .B (n_154), .Y
       (n_232));
  INVX2 g9252(.A (n_197), .Y (n_153));
  INVX1 g9253(.A (n_200), .Y (n_152));
  INVX1 g9251(.A (n_187), .Y (n_151));
  CLKINVX4 g9255(.A (n_150), .Y (n_190));
  AND2X2 g9241__1617(.A (n_149), .B (n_175), .Y (n_196));
  NOR2BX4 g9295__2802(.AN (n_168), .B (n_237), .Y (n_213));
  NAND2X6 g9249__1705(.A (n_148), .B (n_170), .Y (n_178));
  BUFX2 g9463(.A (n_147), .Y (n_182));
  ADDHX2 g9268__5122(.A (n_144), .B (n_87), .CO (n_146), .S (n_301));
  ADDHX4 g9260__8246(.A (n_60), .B (n_144), .CO (n_145), .S (n_197));
  ADDHX2 g9261__7098(.A (n_119), .B (n_82), .CO (n_195), .S (n_200));
  NAND2X8 g9300__6131(.A (n_116), .B (n_129), .Y (n_150));
  BUFX2 g9465(.A (n_154), .Y (n_147));
  NAND2X1 g9294__1881(.A (n_350), .B (n_335), .Y (n_250));
  NAND2X8 g9301__5115(.A (n_120), .B (n_134), .Y (n_187));
  CLKAND2X3 g9299__7482(.A (n_143), .B (n_102), .Y (n_266));
  INVX2 g9254(.A (n_255), .Y (n_142));
  INVX1 g9257(.A (n_136), .Y (n_141));
  INVX2 g9256(.A (n_175), .Y (n_140));
  INVX2 g9331(.A (n_139), .Y (n_204));
  AND2X4 g9416__4733(.A (CONTROL_PATH_CurrentState[0]), .B (n_124), .Y
       (n_397));
  ADDHX4 g9262__6161(.A (n_61), .B (n_138), .CO (n_205), .S (n_255));
  ADDHX4 g9263__9315(.A (n_58), .B (n_138), .CO (n_264), .S (n_243));
  ADDHX2 g9259__9945(.A (n_48), .B (n_137), .CO (n_149), .S (n_170));
  ADDHX2 g9266__2883(.A (n_103), .B (n_67), .CO (n_136), .S (n_175));
  ADDHX2 g9264__2346(.A (n_74), .B (n_56), .CO (n_148), .S (n_176));
  INVX1 g9306(.A (n_238), .Y (n_135));
  INVX3 g9305(.A (n_134), .Y (n_198));
  NAND2X2 g9318__1666(.A (n_166), .B (n_133), .Y (n_156));
  OR2X2 g9328__7410(.A (n_62), .B (n_132), .Y (n_168));
  AND2X2 g9320__6417(.A (n_166), .B (n_131), .Y (n_237));
  NAND2X2 g9325__5477(.A (n_91), .B (n_99), .Y (n_345));
  INVX2 g9330(.A (n_129), .Y (n_130));
  INVX1 g9258(.A (n_127), .Y (n_128));
  INVX3 g9333(.A (n_127), .Y (n_126));
  OAI22X2 g9351__2398(.A0 (DATA_PATH_1_square_s[8]), .A1 (n_104), .B0
       (n_71), .B1 (n_105), .Y (n_139));
  INVX2 g9332(.A (n_125), .Y (n_235));
  BUFX2 g9466(.A (n_124), .Y (n_154));
  ADDHX1 g9237__5107(.A (root_o[3]), .B (n_51), .CO (n_122), .S
       (n_123));
  INVX1 g9308(.A (n_350), .Y (n_121));
  OR2X4 g9311__6260(.A (n_119), .B (n_115), .Y (n_120));
  NOR2X1 g9312__4319(.A (n_54), .B (n_84), .Y (n_118));
  AND2X1 g9313__8428(.A (valor_s[12]), .B (n_98), .Y (n_117));
  NAND2X4 g9314__5526(.A (n_79), .B (n_77), .Y (n_116));
  NAND2X2 g9316__6783(.A (n_162), .B (n_88), .Y (n_143));
  NAND2X6 g9315__3680(.A (n_119), .B (n_115), .Y (n_134));
  AND2X4 g9319__1617(.A (n_164), .B (n_114), .Y (n_165));
  NAND2X2 g9321__2802(.A (n_162), .B (n_113), .Y (n_335));
  OR2X1 g9317__1705(.A (n_90), .B (n_112), .Y (n_339));
  INVX1 g9459(.A (n_109), .Y (n_111));
  INVX1 g9460(.A (n_109), .Y (n_110));
  INVX2 g9355(.A (n_107), .Y (n_108));
  OAI22X4 g9352__5122(.A0 (DATA_PATH_1_square_s[9]), .A1 (n_96), .B0
       (n_10), .B1 (n_97), .Y (n_125));
  BUFX2 g9467(.A (n_106), .Y (n_124));
  NAND2X4 g9366__8246(.A (n_105), .B (n_104), .Y (n_155));
  NAND2X4 g9350__7098(.A (n_80), .B (n_103), .Y (n_129));
  INVX2 g9307(.A (n_102), .Y (n_368));
  NAND2X4 g9323__6131(.A (n_63), .B (n_92), .Y (n_202));
  NAND2X8 g9353__1881(.A (n_137), .B (n_101), .Y (n_127));
  NAND2X2 g9324__5115(.A (n_164), .B (n_100), .Y (n_238));
  INVX1 g9354(.A (n_98), .Y (n_99));
  MX2X1 g9362__7482(.A (n_70), .B (n_64), .S0
       (DATA_PATH_1_square_s[13]), .Y (n_132));
  NAND2X6 g9369__4733(.A (n_97), .B (n_96), .Y (n_107));
  NAND2X2 g9326__6161(.A (n_161), .B (n_95), .Y (n_102));
  NAND2X4 g9327__9315(.A (n_161), .B (n_94), .Y (n_350));
  INVX1 g9376(.A (n_92), .Y (n_93));
  INVX1 g9406(.A (n_90), .Y (n_91));
  BUFX2 g9468(.A (n_89), .Y (n_106));
  BUFX2 g9461(.A (n_89), .Y (n_109));
  NAND2X4 g9415__9945(.A (valor_s[14]), .B (n_65), .Y (n_166));
  XNOR2X1 g9358__2883(.A (DATA_PATH_1_square_s[10]), .B (n_81), .Y
       (n_88));
  CLKXOR2X1 g9365__2346(.A (DATA_PATH_2_square_s[6]), .B (n_41), .Y
       (n_87));
  OR2X8 g9398__1666(.A (CONTROL_PATH_CurrentState[0]), .B (n_76), .Y
       (ready_o));
  XNOR2X1 g9394__7410(.A (DATA_PATH_2_square_s[9]), .B (n_83), .Y
       (n_85));
  NOR3X1 g9357__6417(.A (valor_s[0]), .B (valor_s[1]), .C (n_40), .Y
       (n_84));
  OAI22X2 g9361__5477(.A0 (n_34), .A1 (DATA_PATH_1_square_s[12]), .B0
       (n_21), .B1 (n_45), .Y (n_98));
  XNOR2X1 g9364__2398(.A (DATA_PATH_2_square_s[12]), .B (n_83), .Y
       (n_112));
  MX2X1 g9388__5107(.A (n_55), .B (n_49), .S0
       (DATA_PATH_2_square_s[14]), .Y (n_133));
  OAI22X4 g9373__6260(.A0 (n_0), .A1 (n_73), .B0 (n_23), .B1 (n_46), .Y
       (n_144));
  CLKMX2X3 g9381__4319(.A (n_53), .B (n_83), .S0
       (DATA_PATH_1_square_s[3]), .Y (n_101));
  CLKMX2X2 g9385__8428(.A (n_42), .B (n_68), .S0
       (DATA_PATH_2_square_s[15]), .Y (n_114));
  CLKXOR2X1 g9386__5526(.A (DATA_PATH_2_square_s[5]), .B (n_81), .Y
       (n_82));
  INVX3 g9377(.A (n_79), .Y (n_80));
  INVX1 g9458(.A (n_75), .Y (n_78));
  INVX3 g9356(.A (n_103), .Y (n_77));
  NAND2X4 g9411__6783(.A (root_o[6]), .B (n_50), .Y (n_105));
  AND2X1 g9412__3680(.A (valor_s[12]), .B (n_76), .Y (n_90));
  XNOR2X1 g9382__1617(.A (DATA_PATH_1_square_s[15]), .B (n_81), .Y
       (n_100));
  BUFX2 g9469(.A (n_75), .Y (n_89));
  CLKMX2X2 g9389__2802(.A (n_81), .B (n_37), .S0
       (DATA_PATH_1_square_s[5]), .Y (n_115));
  CLKMX2X3 g9387__1705(.A (n_83), .B (n_47), .S0
       (DATA_PATH_2_square_s[13]), .Y (n_92));
  NAND2X4 g9404__5122(.A (valor_s[10]), .B (n_43), .Y (n_162));
  MX2X1 g9368__8246(.A (valor_s[2]), .B (root_2_s[0]), .S0 (n_73), .Y
       (n_74));
  XNOR2X1 g9378__7098(.A (n_71), .B (n_70), .Y (n_72));
  XNOR2X1 g9379__6131(.A (DATA_PATH_1_square_s[9]), .B (n_70), .Y
       (n_69));
  CLKMX2X3 g9372__1881(.A (valor_s[7]), .B (root_o[5]), .S0 (n_36), .Y
       (n_138));
  MX2X1 g9363__5115(.A (n_57), .B (n_70), .S0
       (DATA_PATH_1_square_s[14]), .Y (n_131));
  XNOR2X2 g9380__7482(.A (DATA_PATH_1_square_s[11]), .B (n_68), .Y
       (n_95));
  XNOR2X1 g9360__4733(.A (DATA_PATH_2_square_s[10]), .B (n_70), .Y
       (n_113));
  CLKMX2X3 g9371__6161(.A (root_o[3]), .B (valor_s[5]), .S0 (n_66), .Y
       (n_119));
  CLKMX2X3 g9374__9315(.A (valor_s[3]), .B (root_o[1]), .S0 (n_24), .Y
       (n_137));
  OAI22X4 g9370__9945(.A0 (n_28), .A1 (n_59), .B0 (n_20), .B1 (n_26),
       .Y (n_103));
  NAND2X2 g9405__2883(.A (valor_s[11]), .B (n_38), .Y (n_161));
  CLKXOR2X1 g9397__2346(.A (DATA_PATH_2_square_s[4]), .B (n_66), .Y
       (n_67));
  INVX2 g9474(.A (n_64), .Y (n_65));
  INVX1 g9407(.A (n_62), .Y (n_63));
  XNOR2X1 g9391__1666(.A (DATA_PATH_1_square_s[7]), .B (n_73), .Y
       (n_61));
  OAI22X2 g9392__7410(.A0 (n_59), .A1 (DATA_PATH_1_square_s[6]), .B0
       (n_33), .B1 (n_30), .Y (n_60));
  XNOR2X1 g9393__6417(.A (DATA_PATH_2_square_s[7]), .B (n_57), .Y
       (n_58));
  CLKXOR2X1 g9367__5477(.A (DATA_PATH_2_square_s[2]), .B (n_68), .Y
       (n_56));
  OAI22X4 g9390__2398(.A0 (DATA_PATH_1_square_s[4]), .A1 (n_27), .B0
       (n_55), .B1 (n_15), .Y (n_79));
  BUFX2 g9470(.A (n_54), .Y (n_75));
  XNOR2X1 g9383__5107(.A (DATA_PATH_2_square_s[11]), .B (n_53), .Y
       (n_94));
  NAND2X4 g9402__6260(.A (root_o[7]), .B (n_39), .Y (n_97));
  NAND2X2 g9403__4319(.A (valor_s[15]), .B (n_35), .Y (n_164));
  ADDHX1 g9310__8428(.A (root_o[1]), .B (root_o[2]), .CO (n_51), .S
       (n_52));
  INVX2 g9450(.A (n_49), .Y (n_50));
  XNOR2X1 g9396__5526(.A (DATA_PATH_2_square_s[3]), .B (n_55), .Y
       (n_48));
  NAND2X2 g9401__6783(.A (valor_s[8]), .B (n_47), .Y (n_104));
  INVX3 g9475(.A (n_46), .Y (n_64));
  INVX2 g9471(.A (n_45), .Y (n_54));
  XNOR2X1 g9395__3680(.A (DATA_PATH_2_square_s[8]), .B (n_55), .Y
       (n_44));
  INVX2 g9442(.A (n_42), .Y (n_43));
  AND2X4 g9414__1617(.A (valor_s[13]), .B (n_70), .Y (n_62));
  NAND2X2 g9413__2802(.A (valor_s[9]), .B (n_47), .Y (n_96));
  BUFX3 g9448(.A (n_41), .Y (n_76));
  NAND2X1 g9410__1705(.A (root_2_s[0]), .B (n_19), .Y (n_40));
  INVX3 g9436(.A (n_68), .Y (n_39));
  INVX2 g9455(.A (n_37), .Y (n_38));
  CLKINVX4 g9449(.A (n_59), .Y (n_41));
  CLKINVX6 g9476(.A (n_73), .Y (n_46));
  INVX3 g9472(.A (n_36), .Y (n_45));
  INVX2 g9479(.A (n_57), .Y (n_35));
  INVX1 g9453(.A (n_47), .Y (n_34));
  CLKINVX4 g9451(.A (n_59), .Y (n_49));
  CLKINVX4 g9443(.A (n_33), .Y (n_42));
  CLKINVX6 g9457(.A (n_36), .Y (n_81));
  CLKINVX4 g9438(.A (n_66), .Y (n_83));
  AND2X4 g9399__5122(.A (root_reg_s), .B (root_2_s[0]), .Y (root_o[0]));
  INVX1 g9431(.A (n_30), .Y (n_31));
  INVX1 g9428(.A (n_28), .Y (n_29));
  CLKINVX6 g9441(.A (n_25), .Y (n_27));
  INVX3 g9456(.A (n_26), .Y (n_37));
  CLKINVX6 g9473(.A (n_26), .Y (n_36));
  CLKINVX8 g9452(.A (n_26), .Y (n_59));
  CLKINVX4 g9437(.A (n_25), .Y (n_68));
  INVX3 g9478(.A (n_26), .Y (n_24));
  INVX2 g9446(.A (n_55), .Y (n_53));
  CLKINVX4 g9444(.A (n_25), .Y (n_33));
  CLKINVX8 g9439(.A (n_25), .Y (n_66));
  INVX3 g9480(.A (n_26), .Y (n_57));
  BUFX6 g9454(.A (n_26), .Y (n_47));
  CLKINVX8 g9477(.A (n_26), .Y (n_73));
  CLKINVX6 g9440(.A (n_25), .Y (n_70));
  INVX2 g9492(.A (root_o[4]), .Y (n_23));
  BUFX2 g9420(.A (valor_i[6]), .Y (n_22));
  INVX1 g9490(.A (DATA_PATH_1_square_s[12]), .Y (n_21));
  INVX2 g9491(.A (root_o[2]), .Y (n_20));
  INVX1 g9430(.A (valor_s[2]), .Y (n_19));
  BUFX2 g9421(.A (valor_i[5]), .Y (n_18));
  BUFX2 g9424(.A (valor_i[3]), .Y (n_17));
  BUFX2 g9418(.A (valor_i[4]), .Y (n_16));
  INVX1 g9433(.A (DATA_PATH_1_square_s[4]), .Y (n_15));
  BUFX2 g9423(.A (valor_i[11]), .Y (n_14));
  BUFX2 g9426(.A (valor_i[0]), .Y (n_13));
  BUFX2 g9488(.A (valor_i[14]), .Y (n_12));
  BUFX2 g9484(.A (valor_i[10]), .Y (n_11));
  INVX1 g9435(.A (DATA_PATH_1_square_s[9]), .Y (n_10));
  INVX2 g9432(.A (DATA_PATH_1_square_s[6]), .Y (n_30));
  BUFX2 g9487(.A (valor_i[12]), .Y (n_9));
  BUFX2 g9486(.A (valor_i[15]), .Y (n_8));
  INVX1 g9489(.A (DATA_PATH_1_square_s[16]), .Y (n_7));
  BUFX2 g9485(.A (valor_i[1]), .Y (n_6));
  BUFX2 g9483(.A (valor_i[2]), .Y (n_5));
  BUFX2 g9425(.A (valor_i[13]), .Y (n_4));
  BUFX2 g9482(.A (valor_i[8]), .Y (n_3));
  BUFX2 g9422(.A (valor_i[9]), .Y (n_2));
  BUFX2 g9419(.A (valor_i[7]), .Y (n_1));
  INVX1 g9427(.A (valor_s[6]), .Y (n_0));
  INVX2 g9429(.A (valor_s[4]), .Y (n_28));
  INVX1 g9434(.A (DATA_PATH_1_square_s[8]), .Y (n_71));
  BUFX12 g9445(.A (CONTROL_PATH_CurrentState[1]), .Y (n_25));
  BUFX6 g9447(.A (CONTROL_PATH_CurrentState[1]), .Y (n_55));
  CLKINVX12 g9481(.A (CONTROL_PATH_CurrentState[1]), .Y (n_26));
  AND2X8 g9552__8246(.A (n_232), .B (n_376), .Y (n_388));
  ADDHX4 g9554__7098(.A (n_157), .B (n_232), .CO (n_396), .S
       (UNCONNECTED2));
endmodule

