
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point data_serial_i[31] data_serial_i[31] -type PI PI
add mapped point data_serial_i[30] data_serial_i[30] -type PI PI
add mapped point data_serial_i[29] data_serial_i[29] -type PI PI
add mapped point data_serial_i[28] data_serial_i[28] -type PI PI
add mapped point data_serial_i[27] data_serial_i[27] -type PI PI
add mapped point data_serial_i[26] data_serial_i[26] -type PI PI
add mapped point data_serial_i[25] data_serial_i[25] -type PI PI
add mapped point data_serial_i[24] data_serial_i[24] -type PI PI
add mapped point data_serial_i[23] data_serial_i[23] -type PI PI
add mapped point data_serial_i[22] data_serial_i[22] -type PI PI
add mapped point data_serial_i[21] data_serial_i[21] -type PI PI
add mapped point data_serial_i[20] data_serial_i[20] -type PI PI
add mapped point data_serial_i[19] data_serial_i[19] -type PI PI
add mapped point data_serial_i[18] data_serial_i[18] -type PI PI
add mapped point data_serial_i[17] data_serial_i[17] -type PI PI
add mapped point data_serial_i[16] data_serial_i[16] -type PI PI
add mapped point data_serial_i[15] data_serial_i[15] -type PI PI
add mapped point data_serial_i[14] data_serial_i[14] -type PI PI
add mapped point data_serial_i[13] data_serial_i[13] -type PI PI
add mapped point data_serial_i[12] data_serial_i[12] -type PI PI
add mapped point data_serial_i[11] data_serial_i[11] -type PI PI
add mapped point data_serial_i[10] data_serial_i[10] -type PI PI
add mapped point data_serial_i[9] data_serial_i[9] -type PI PI
add mapped point data_serial_i[8] data_serial_i[8] -type PI PI
add mapped point data_serial_i[7] data_serial_i[7] -type PI PI
add mapped point data_serial_i[6] data_serial_i[6] -type PI PI
add mapped point data_serial_i[5] data_serial_i[5] -type PI PI
add mapped point data_serial_i[4] data_serial_i[4] -type PI PI
add mapped point data_serial_i[3] data_serial_i[3] -type PI PI
add mapped point data_serial_i[2] data_serial_i[2] -type PI PI
add mapped point data_serial_i[1] data_serial_i[1] -type PI PI
add mapped point data_serial_i[0] data_serial_i[0] -type PI PI

//output ports
add mapped point data_serial_o[31] data_serial_o[31] -type PO PO
add mapped point data_serial_o[30] data_serial_o[30] -type PO PO
add mapped point data_serial_o[29] data_serial_o[29] -type PO PO
add mapped point data_serial_o[28] data_serial_o[28] -type PO PO
add mapped point data_serial_o[27] data_serial_o[27] -type PO PO
add mapped point data_serial_o[26] data_serial_o[26] -type PO PO
add mapped point data_serial_o[25] data_serial_o[25] -type PO PO
add mapped point data_serial_o[24] data_serial_o[24] -type PO PO
add mapped point data_serial_o[23] data_serial_o[23] -type PO PO
add mapped point data_serial_o[22] data_serial_o[22] -type PO PO
add mapped point data_serial_o[21] data_serial_o[21] -type PO PO
add mapped point data_serial_o[20] data_serial_o[20] -type PO PO
add mapped point data_serial_o[19] data_serial_o[19] -type PO PO
add mapped point data_serial_o[18] data_serial_o[18] -type PO PO
add mapped point data_serial_o[17] data_serial_o[17] -type PO PO
add mapped point data_serial_o[16] data_serial_o[16] -type PO PO
add mapped point data_serial_o[15] data_serial_o[15] -type PO PO
add mapped point data_serial_o[14] data_serial_o[14] -type PO PO
add mapped point data_serial_o[13] data_serial_o[13] -type PO PO
add mapped point data_serial_o[12] data_serial_o[12] -type PO PO
add mapped point data_serial_o[11] data_serial_o[11] -type PO PO
add mapped point data_serial_o[10] data_serial_o[10] -type PO PO
add mapped point data_serial_o[9] data_serial_o[9] -type PO PO
add mapped point data_serial_o[8] data_serial_o[8] -type PO PO
add mapped point data_serial_o[7] data_serial_o[7] -type PO PO
add mapped point data_serial_o[6] data_serial_o[6] -type PO PO
add mapped point data_serial_o[5] data_serial_o[5] -type PO PO
add mapped point data_serial_o[4] data_serial_o[4] -type PO PO
add mapped point data_serial_o[3] data_serial_o[3] -type PO PO
add mapped point data_serial_o[2] data_serial_o[2] -type PO PO
add mapped point data_serial_o[1] data_serial_o[1] -type PO PO
add mapped point data_serial_o[0] data_serial_o[0] -type PO PO
add mapped point ready_o ready_o -type PO PO

//inout ports




//Sequential Pins
add mapped point DATA_PATH/SF_0_s[1]/q DATA_PATH_SF_0_s_reg[1]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[2]/q DATA_PATH_SF_0_s_reg[2]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[3]/q DATA_PATH_SF_0_s_reg[3]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[4]/q DATA_PATH_SF_0_s_reg[4]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[5]/q DATA_PATH_SF_0_s_reg[5]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[6]/q DATA_PATH_SF_0_s_reg[6]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[7]/q DATA_PATH_SF_0_s_reg[7]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[8]/q DATA_PATH_SF_0_s_reg[8]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[9]/q DATA_PATH_SF_0_s_reg[9]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[10]/q DATA_PATH_SF_0_s_reg[10]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[11]/q DATA_PATH_SF_0_s_reg[11]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[12]/q DATA_PATH_SF_0_s_reg[12]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[13]/q DATA_PATH_SF_0_s_reg[13]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[14]/q DATA_PATH_SF_0_s_reg[14]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[15]/q DATA_PATH_SF_0_s_reg[15]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[16]/q DATA_PATH_SF_0_s_reg[16]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[17]/q DATA_PATH_SF_0_s_reg[17]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[18]/q DATA_PATH_SF_0_s_reg[18]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[19]/q DATA_PATH_SF_0_s_reg[19]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[20]/q DATA_PATH_SF_0_s_reg[20]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[21]/q DATA_PATH_SF_0_s_reg[21]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[22]/q DATA_PATH_SF_0_s_reg[22]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[23]/q DATA_PATH_SF_0_s_reg[23]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[24]/q DATA_PATH_SF_0_s_reg[24]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[25]/q DATA_PATH_SF_0_s_reg[25]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[26]/q DATA_PATH_SF_0_s_reg[26]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[27]/q DATA_PATH_SF_0_s_reg[27]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[28]/q DATA_PATH_SF_0_s_reg[28]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[29]/q DATA_PATH_SF_0_s_reg[29]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[30]/q DATA_PATH_SF_0_s_reg[30]/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[31]/q DATA_PATH_SF_0_s_reg[31]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[0]/q DATA_PATH_SF_1_s_reg[0]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[1]/q DATA_PATH_SF_1_s_reg[1]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[2]/q DATA_PATH_SF_1_s_reg[2]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[3]/q DATA_PATH_SF_1_s_reg[3]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[4]/q DATA_PATH_SF_1_s_reg[4]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[5]/q DATA_PATH_SF_1_s_reg[5]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[6]/q DATA_PATH_SF_1_s_reg[6]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[7]/q DATA_PATH_SF_1_s_reg[7]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[8]/q DATA_PATH_SF_1_s_reg[8]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[9]/q DATA_PATH_SF_1_s_reg[9]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[10]/q DATA_PATH_SF_1_s_reg[10]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[11]/q DATA_PATH_SF_1_s_reg[11]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[12]/q DATA_PATH_SF_1_s_reg[12]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[13]/q DATA_PATH_SF_1_s_reg[13]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[14]/q DATA_PATH_SF_1_s_reg[14]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[15]/q DATA_PATH_SF_1_s_reg[15]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[16]/q DATA_PATH_SF_1_s_reg[16]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[17]/q DATA_PATH_SF_1_s_reg[17]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[18]/q DATA_PATH_SF_1_s_reg[18]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[19]/q DATA_PATH_SF_1_s_reg[19]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[20]/q DATA_PATH_SF_1_s_reg[20]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[21]/q DATA_PATH_SF_1_s_reg[21]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[22]/q DATA_PATH_SF_1_s_reg[22]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[23]/q DATA_PATH_SF_1_s_reg[23]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[24]/q DATA_PATH_SF_1_s_reg[24]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[25]/q DATA_PATH_SF_1_s_reg[25]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[26]/q DATA_PATH_SF_1_s_reg[26]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[27]/q DATA_PATH_SF_1_s_reg[27]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[28]/q DATA_PATH_SF_1_s_reg[28]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[29]/q DATA_PATH_SF_1_s_reg[29]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[30]/q DATA_PATH_SF_1_s_reg[30]/Q -type DFF DFF
add mapped point DATA_PATH/SF_1_s[31]/q DATA_PATH_SF_1_s_reg[31]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[0]/q DATA_PATH_SF_2_s_reg[0]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[1]/q DATA_PATH_SF_2_s_reg[1]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[2]/q DATA_PATH_SF_2_s_reg[2]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[3]/q DATA_PATH_SF_2_s_reg[3]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[4]/q DATA_PATH_SF_2_s_reg[4]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[5]/q DATA_PATH_SF_2_s_reg[5]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[6]/q DATA_PATH_SF_2_s_reg[6]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[7]/q DATA_PATH_SF_2_s_reg[7]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[8]/q DATA_PATH_SF_2_s_reg[8]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[9]/q DATA_PATH_SF_2_s_reg[9]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[10]/q DATA_PATH_SF_2_s_reg[10]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[11]/q DATA_PATH_SF_2_s_reg[11]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[12]/q DATA_PATH_SF_2_s_reg[12]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[13]/q DATA_PATH_SF_2_s_reg[13]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[14]/q DATA_PATH_SF_2_s_reg[14]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[15]/q DATA_PATH_SF_2_s_reg[15]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[16]/q DATA_PATH_SF_2_s_reg[16]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[17]/q DATA_PATH_SF_2_s_reg[17]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[18]/q DATA_PATH_SF_2_s_reg[18]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[19]/q DATA_PATH_SF_2_s_reg[19]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[20]/q DATA_PATH_SF_2_s_reg[20]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[21]/q DATA_PATH_SF_2_s_reg[21]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[22]/q DATA_PATH_SF_2_s_reg[22]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[23]/q DATA_PATH_SF_2_s_reg[23]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[24]/q DATA_PATH_SF_2_s_reg[24]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[25]/q DATA_PATH_SF_2_s_reg[25]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[26]/q DATA_PATH_SF_2_s_reg[26]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[27]/q DATA_PATH_SF_2_s_reg[27]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[28]/q DATA_PATH_SF_2_s_reg[28]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[29]/q DATA_PATH_SF_2_s_reg[29]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[30]/q DATA_PATH_SF_2_s_reg[30]/Q -type DFF DFF
add mapped point DATA_PATH/SF_2_s[31]/q DATA_PATH_SF_2_s_reg[31]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[0]/q DATA_PATH_SF_4_s_reg[0]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[1]/q DATA_PATH_SF_4_s_reg[1]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[2]/q DATA_PATH_SF_4_s_reg[2]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[3]/q DATA_PATH_SF_4_s_reg[3]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[4]/q DATA_PATH_SF_4_s_reg[4]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[5]/q DATA_PATH_SF_4_s_reg[5]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[6]/q DATA_PATH_SF_4_s_reg[6]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[7]/q DATA_PATH_SF_4_s_reg[7]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[8]/q DATA_PATH_SF_4_s_reg[8]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[9]/q DATA_PATH_SF_4_s_reg[9]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[10]/q DATA_PATH_SF_4_s_reg[10]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[11]/q DATA_PATH_SF_4_s_reg[11]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[12]/q DATA_PATH_SF_4_s_reg[12]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[13]/q DATA_PATH_SF_4_s_reg[13]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[14]/q DATA_PATH_SF_4_s_reg[14]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[15]/q DATA_PATH_SF_4_s_reg[15]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[16]/q DATA_PATH_SF_4_s_reg[16]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[17]/q DATA_PATH_SF_4_s_reg[17]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[18]/q DATA_PATH_SF_4_s_reg[18]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[19]/q DATA_PATH_SF_4_s_reg[19]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[20]/q DATA_PATH_SF_4_s_reg[20]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[21]/q DATA_PATH_SF_4_s_reg[21]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[22]/q DATA_PATH_SF_4_s_reg[22]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[23]/q DATA_PATH_SF_4_s_reg[23]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[24]/q DATA_PATH_SF_4_s_reg[24]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[25]/q DATA_PATH_SF_4_s_reg[25]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[26]/q DATA_PATH_SF_4_s_reg[26]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[27]/q DATA_PATH_SF_4_s_reg[27]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[28]/q DATA_PATH_SF_4_s_reg[28]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[29]/q DATA_PATH_SF_4_s_reg[29]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[30]/q DATA_PATH_SF_4_s_reg[30]/Q -type DFF DFF
add mapped point DATA_PATH/SF_4_s[31]/q DATA_PATH_SF_4_s_reg[31]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[0]/q DATA_PATH_SF_5_s_reg[0]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[1]/q DATA_PATH_SF_5_s_reg[1]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[2]/q DATA_PATH_SF_5_s_reg[2]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[3]/q DATA_PATH_SF_5_s_reg[3]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[4]/q DATA_PATH_SF_5_s_reg[4]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[5]/q DATA_PATH_SF_5_s_reg[5]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[6]/q DATA_PATH_SF_5_s_reg[6]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[7]/q DATA_PATH_SF_5_s_reg[7]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[8]/q DATA_PATH_SF_5_s_reg[8]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[9]/q DATA_PATH_SF_5_s_reg[9]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[10]/q DATA_PATH_SF_5_s_reg[10]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[11]/q DATA_PATH_SF_5_s_reg[11]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[12]/q DATA_PATH_SF_5_s_reg[12]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[13]/q DATA_PATH_SF_5_s_reg[13]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[14]/q DATA_PATH_SF_5_s_reg[14]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[15]/q DATA_PATH_SF_5_s_reg[15]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[16]/q DATA_PATH_SF_5_s_reg[16]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[17]/q DATA_PATH_SF_5_s_reg[17]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[18]/q DATA_PATH_SF_5_s_reg[18]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[19]/q DATA_PATH_SF_5_s_reg[19]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[20]/q DATA_PATH_SF_5_s_reg[20]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[21]/q DATA_PATH_SF_5_s_reg[21]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[22]/q DATA_PATH_SF_5_s_reg[22]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[23]/q DATA_PATH_SF_5_s_reg[23]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[24]/q DATA_PATH_SF_5_s_reg[24]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[25]/q DATA_PATH_SF_5_s_reg[25]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[26]/q DATA_PATH_SF_5_s_reg[26]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[27]/q DATA_PATH_SF_5_s_reg[27]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[28]/q DATA_PATH_SF_5_s_reg[28]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[29]/q DATA_PATH_SF_5_s_reg[29]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[30]/q DATA_PATH_SF_5_s_reg[30]/Q -type DFF DFF
add mapped point DATA_PATH/SF_5_s[31]/q DATA_PATH_SF_5_s_reg[31]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[0]/q DATA_PATH_SF_6_s_reg[0]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[1]/q DATA_PATH_SF_6_s_reg[1]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[2]/q DATA_PATH_SF_6_s_reg[2]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[3]/q DATA_PATH_SF_6_s_reg[3]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[4]/q DATA_PATH_SF_6_s_reg[4]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[5]/q DATA_PATH_SF_6_s_reg[5]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[6]/q DATA_PATH_SF_6_s_reg[6]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[7]/q DATA_PATH_SF_6_s_reg[7]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[8]/q DATA_PATH_SF_6_s_reg[8]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[9]/q DATA_PATH_SF_6_s_reg[9]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[10]/q DATA_PATH_SF_6_s_reg[10]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[11]/q DATA_PATH_SF_6_s_reg[11]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[12]/q DATA_PATH_SF_6_s_reg[12]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[13]/q DATA_PATH_SF_6_s_reg[13]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[14]/q DATA_PATH_SF_6_s_reg[14]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[15]/q DATA_PATH_SF_6_s_reg[15]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[16]/q DATA_PATH_SF_6_s_reg[16]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[17]/q DATA_PATH_SF_6_s_reg[17]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[18]/q DATA_PATH_SF_6_s_reg[18]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[19]/q DATA_PATH_SF_6_s_reg[19]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[20]/q DATA_PATH_SF_6_s_reg[20]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[21]/q DATA_PATH_SF_6_s_reg[21]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[22]/q DATA_PATH_SF_6_s_reg[22]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[23]/q DATA_PATH_SF_6_s_reg[23]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[24]/q DATA_PATH_SF_6_s_reg[24]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[25]/q DATA_PATH_SF_6_s_reg[25]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[26]/q DATA_PATH_SF_6_s_reg[26]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[27]/q DATA_PATH_SF_6_s_reg[27]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[28]/q DATA_PATH_SF_6_s_reg[28]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[29]/q DATA_PATH_SF_6_s_reg[29]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[30]/q DATA_PATH_SF_6_s_reg[30]/Q -type DFF DFF
add mapped point DATA_PATH/SF_6_s[31]/q DATA_PATH_SF_6_s_reg[31]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[0]/q DATA_PATH_SF_7_s_reg[0]/Q -type DFF DFF
add mapped point CONTROL_PATH/CurrentState[0]/q CONTROL_PATH_CurrentState_reg[0]/Q -type DFF DFF
add mapped point CONTROL_PATH/CurrentState[1]/q CONTROL_PATH_CurrentState_reg[1]/Q -type DFF DFF
add mapped point CONTROL_PATH/CurrentState[2]/q CONTROL_PATH_CurrentState_reg[2]/Q -type DFF DFF
add mapped point DATA_PATH/C_SF_0_s/q DATA_PATH_C_SF_0_s_reg/Q -type DFF DFF
add mapped point DATA_PATH/SF_0_s[0]/q DATA_PATH_SF_0_s_reg[0]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[1]/q DATA_PATH_SF_8_s_reg[1]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[2]/q DATA_PATH_SF_8_s_reg[2]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[3]/q DATA_PATH_SF_8_s_reg[3]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[4]/q DATA_PATH_SF_8_s_reg[4]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[5]/q DATA_PATH_SF_8_s_reg[5]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[6]/q DATA_PATH_SF_8_s_reg[6]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[7]/q DATA_PATH_SF_8_s_reg[7]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[8]/q DATA_PATH_SF_8_s_reg[8]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[9]/q DATA_PATH_SF_8_s_reg[9]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[10]/q DATA_PATH_SF_8_s_reg[10]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[11]/q DATA_PATH_SF_8_s_reg[11]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[12]/q DATA_PATH_SF_8_s_reg[12]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[13]/q DATA_PATH_SF_8_s_reg[13]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[14]/q DATA_PATH_SF_8_s_reg[14]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[15]/q DATA_PATH_SF_8_s_reg[15]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[16]/q DATA_PATH_SF_8_s_reg[16]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[17]/q DATA_PATH_SF_8_s_reg[17]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[18]/q DATA_PATH_SF_8_s_reg[18]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[19]/q DATA_PATH_SF_8_s_reg[19]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[20]/q DATA_PATH_SF_8_s_reg[20]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[21]/q DATA_PATH_SF_8_s_reg[21]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[22]/q DATA_PATH_SF_8_s_reg[22]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[23]/q DATA_PATH_SF_8_s_reg[23]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[24]/q DATA_PATH_SF_8_s_reg[24]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[25]/q DATA_PATH_SF_8_s_reg[25]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[26]/q DATA_PATH_SF_8_s_reg[26]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[27]/q DATA_PATH_SF_8_s_reg[27]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[28]/q DATA_PATH_SF_8_s_reg[28]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[29]/q DATA_PATH_SF_8_s_reg[29]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[30]/q DATA_PATH_SF_8_s_reg[30]/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[31]/q DATA_PATH_SF_8_s_reg[31]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[0]/q DATA_PATH_SF_9_s_reg[0]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[1]/q DATA_PATH_SF_9_s_reg[1]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[2]/q DATA_PATH_SF_9_s_reg[2]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[3]/q DATA_PATH_SF_9_s_reg[3]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[4]/q DATA_PATH_SF_9_s_reg[4]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[5]/q DATA_PATH_SF_9_s_reg[5]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[6]/q DATA_PATH_SF_9_s_reg[6]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[7]/q DATA_PATH_SF_9_s_reg[7]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[8]/q DATA_PATH_SF_9_s_reg[8]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[9]/q DATA_PATH_SF_9_s_reg[9]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[10]/q DATA_PATH_SF_9_s_reg[10]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[11]/q DATA_PATH_SF_9_s_reg[11]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[12]/q DATA_PATH_SF_9_s_reg[12]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[13]/q DATA_PATH_SF_9_s_reg[13]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[14]/q DATA_PATH_SF_9_s_reg[14]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[15]/q DATA_PATH_SF_9_s_reg[15]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[16]/q DATA_PATH_SF_9_s_reg[16]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[17]/q DATA_PATH_SF_9_s_reg[17]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[18]/q DATA_PATH_SF_9_s_reg[18]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[19]/q DATA_PATH_SF_9_s_reg[19]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[20]/q DATA_PATH_SF_9_s_reg[20]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[21]/q DATA_PATH_SF_9_s_reg[21]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[22]/q DATA_PATH_SF_9_s_reg[22]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[23]/q DATA_PATH_SF_9_s_reg[23]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[24]/q DATA_PATH_SF_9_s_reg[24]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[25]/q DATA_PATH_SF_9_s_reg[25]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[26]/q DATA_PATH_SF_9_s_reg[26]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[27]/q DATA_PATH_SF_9_s_reg[27]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[28]/q DATA_PATH_SF_9_s_reg[28]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[29]/q DATA_PATH_SF_9_s_reg[29]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[30]/q DATA_PATH_SF_9_s_reg[30]/Q -type DFF DFF
add mapped point DATA_PATH/SF_9_s[31]/q DATA_PATH_SF_9_s_reg[31]/Q -type DFF DFF
add mapped point en_cg_s/q en_cg_s_reg/Q -type DLAT DLAT
add mapped point DATA_PATH/SF_3_s[6]/q DATA_PATH_SF_3_s_reg[6]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[20]/q DATA_PATH_SF_3_s_reg[20]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[19]/q DATA_PATH_SF_3_s_reg[19]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[18]/q DATA_PATH_SF_3_s_reg[18]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[1]/q DATA_PATH_SF_7_s_reg[1]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[17]/q DATA_PATH_SF_3_s_reg[17]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[16]/q DATA_PATH_SF_3_s_reg[16]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[15]/q DATA_PATH_SF_3_s_reg[15]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[25]/q DATA_PATH_SF_7_s_reg[25]/Q -type DFF DFF
add mapped point DATA_PATH/C_SF_9_s/q DATA_PATH_C_SF_9_s_reg/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[0]/q DATA_PATH_SF_3_s_reg[0]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[1]/q DATA_PATH_SF_3_s_reg[1]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[21]/q DATA_PATH_SF_7_s_reg[21]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[2]/q DATA_PATH_SF_3_s_reg[2]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[3]/q DATA_PATH_SF_3_s_reg[3]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[4]/q DATA_PATH_SF_3_s_reg[4]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[17]/q DATA_PATH_SF_7_s_reg[17]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[5]/q DATA_PATH_SF_3_s_reg[5]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[5]/q DATA_PATH_SF_7_s_reg[5]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[7]/q DATA_PATH_SF_3_s_reg[7]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[8]/q DATA_PATH_SF_3_s_reg[8]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[9]/q DATA_PATH_SF_3_s_reg[9]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[10]/q DATA_PATH_SF_3_s_reg[10]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[11]/q DATA_PATH_SF_3_s_reg[11]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[9]/q DATA_PATH_SF_7_s_reg[9]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[12]/q DATA_PATH_SF_3_s_reg[12]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[13]/q DATA_PATH_SF_3_s_reg[13]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[14]/q DATA_PATH_SF_3_s_reg[14]/Q -type DFF DFF
add mapped point DATA_PATH/C_SF_5_s/q DATA_PATH_C_SF_5_s_reg/Q -type DFF DFF
add mapped point DATA_PATH/C_SF_8_s/q DATA_PATH_C_SF_8_s_reg/Q -type DFF DFF
add mapped point DATA_PATH/C_SF_7_s/q DATA_PATH_C_SF_7_s_reg/Q -type DFF DFF
add mapped point DATA_PATH/C_SF_6_s/q DATA_PATH_C_SF_6_s_reg/Q -type DFF DFF
add mapped point DATA_PATH/C_SF_1_s/q DATA_PATH_C_SF_1_s_reg/Q -type DFF DFF
add mapped point DATA_PATH/C_SF_4_s/q DATA_PATH_C_SF_4_s_reg/Q -type DFF DFF
add mapped point DATA_PATH/C_SF_3_s/q DATA_PATH_C_SF_3_s_reg/Q -type DFF DFF
add mapped point DATA_PATH/C_SF_2_s/q DATA_PATH_C_SF_2_s_reg/Q -type DFF DFF
add mapped point DATA_PATH/SF_8_s[0]/q DATA_PATH_SF_8_s_reg[0]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[22]/q DATA_PATH_SF_3_s_reg[22]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[23]/q DATA_PATH_SF_3_s_reg[23]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[24]/q DATA_PATH_SF_3_s_reg[24]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[25]/q DATA_PATH_SF_3_s_reg[25]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[26]/q DATA_PATH_SF_3_s_reg[26]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[27]/q DATA_PATH_SF_3_s_reg[27]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[28]/q DATA_PATH_SF_3_s_reg[28]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[29]/q DATA_PATH_SF_3_s_reg[29]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[30]/q DATA_PATH_SF_3_s_reg[30]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[31]/q DATA_PATH_SF_3_s_reg[31]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[2]/q DATA_PATH_SF_7_s_reg[2]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[3]/q DATA_PATH_SF_7_s_reg[3]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[4]/q DATA_PATH_SF_7_s_reg[4]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[6]/q DATA_PATH_SF_7_s_reg[6]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[7]/q DATA_PATH_SF_7_s_reg[7]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[8]/q DATA_PATH_SF_7_s_reg[8]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[10]/q DATA_PATH_SF_7_s_reg[10]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[11]/q DATA_PATH_SF_7_s_reg[11]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[12]/q DATA_PATH_SF_7_s_reg[12]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[13]/q DATA_PATH_SF_7_s_reg[13]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[14]/q DATA_PATH_SF_7_s_reg[14]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[15]/q DATA_PATH_SF_7_s_reg[15]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[16]/q DATA_PATH_SF_7_s_reg[16]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[18]/q DATA_PATH_SF_7_s_reg[18]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[19]/q DATA_PATH_SF_7_s_reg[19]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[20]/q DATA_PATH_SF_7_s_reg[20]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[22]/q DATA_PATH_SF_7_s_reg[22]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[23]/q DATA_PATH_SF_7_s_reg[23]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[24]/q DATA_PATH_SF_7_s_reg[24]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[26]/q DATA_PATH_SF_7_s_reg[26]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[27]/q DATA_PATH_SF_7_s_reg[27]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[28]/q DATA_PATH_SF_7_s_reg[28]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[29]/q DATA_PATH_SF_7_s_reg[29]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[30]/q DATA_PATH_SF_7_s_reg[30]/Q -type DFF DFF
add mapped point DATA_PATH/SF_7_s[31]/q DATA_PATH_SF_7_s_reg[31]/Q -type DFF DFF
add mapped point DATA_PATH/SF_3_s[21]/q DATA_PATH_SF_3_s_reg[21]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
