
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Oct 16 2025 12:47:26 -03 (Oct 16 2025 15:47:26 UTC)

// Verification Directory fv/BubbleSort 

module BubbleSort(clk, rst, data_serial_i, data_serial_o, ready_o);
  input clk, rst;
  input [31:0] data_serial_i;
  output [31:0] data_serial_o;
  output ready_o;
  wire clk, rst;
  wire [31:0] data_serial_i;
  wire [31:0] data_serial_o;
  wire ready_o;
  wire [2:0] CONTROL_PATH_CurrentState;
  wire [31:0] DATA_PATH_SF_0_s;
  wire [31:0] DATA_PATH_SF_1_s;
  wire [31:0] DATA_PATH_SF_2_s;
  wire [31:0] DATA_PATH_SF_4_s;
  wire [31:0] DATA_PATH_SF_5_s;
  wire [31:0] DATA_PATH_SF_6_s;
  wire [31:0] DATA_PATH_SF_7_s;
  wire [31:0] DATA_PATH_SF_8_s;
  wire [31:0] DATA_PATH_SF_9_s;
  wire DATA_PATH_C_SF_0_s, DATA_PATH_C_SF_1_s, DATA_PATH_C_SF_2_s,
       DATA_PATH_C_SF_3_s, DATA_PATH_C_SF_4_s, DATA_PATH_C_SF_5_s,
       DATA_PATH_C_SF_6_s, DATA_PATH_C_SF_7_s;
  wire DATA_PATH_C_SF_9_s, UNCONNECTED, UNCONNECTED0, UNCONNECTED1,
       UNCONNECTED2, UNCONNECTED3, UNCONNECTED4, clk_gated_s;
  wire en_cg_s, is_nine_s, n_0, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_130, n_131, n_132, n_133, n_134;
  wire n_135, n_136, n_137, n_138, n_139, n_140, n_141, n_142;
  wire n_143, n_144, n_145, n_146, n_147, n_148, n_149, n_150;
  wire n_151, n_152, n_153, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_169, n_170, n_171, n_172, n_173, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_180, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_207, n_208, n_209, n_210, n_211, n_212, n_213, n_214;
  wire n_215, n_216, n_217, n_218, n_219, n_220, n_221, n_222;
  wire n_223, n_224, n_225, n_226, n_227, n_228, n_229, n_230;
  wire n_231, n_232, n_233, n_234, n_235, n_236, n_237, n_238;
  wire n_239, n_240, n_241, n_242, n_243, n_244, n_245, n_246;
  wire n_247, n_248, n_249, n_250, n_251, n_252, n_286, n_319;
  wire n_354, n_355, n_356, n_357, n_358, n_359, n_361, n_369;
  wire n_378, n_379, n_380, n_381, n_382, n_383, n_384, n_385;
  wire n_386, n_387, n_388, n_389, n_390, n_391, n_392, n_393;
  wire n_394, n_395, n_396, n_397, n_398, n_399, n_400, n_401;
  wire n_402, n_403, n_404, n_405, n_406, n_407, n_408, n_409;
  wire n_410, n_416, n_417, n_418, n_421, n_427, n_429, n_444;
  wire n_1839_BAR;
  INVX2 g1631(.A (CONTROL_PATH_CurrentState[1]), .Y (n_286));
  DFFRHQX1 DATA_PATH_C_SF_0_s_reg(.RN (n_60), .CK (clk_gated_s), .D
       (n_176), .Q (DATA_PATH_C_SF_0_s));
  DFFRHQX1 DATA_PATH_C_SF_1_s_reg(.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_C_SF_0_s), .Q (DATA_PATH_C_SF_1_s));
  DFFRHQX1 DATA_PATH_C_SF_2_s_reg(.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_C_SF_1_s), .Q (DATA_PATH_C_SF_2_s));
  DFFRHQX1 DATA_PATH_C_SF_3_s_reg(.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_C_SF_2_s), .Q (DATA_PATH_C_SF_3_s));
  DFFRHQX1 DATA_PATH_C_SF_4_s_reg(.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_C_SF_3_s), .Q (DATA_PATH_C_SF_4_s));
  DFFRHQX1 DATA_PATH_C_SF_5_s_reg(.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_C_SF_4_s), .Q (DATA_PATH_C_SF_5_s));
  DFFRHQX1 DATA_PATH_C_SF_6_s_reg(.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_C_SF_5_s), .Q (DATA_PATH_C_SF_6_s));
  DFFRHQX1 DATA_PATH_C_SF_7_s_reg(.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_C_SF_6_s), .Q (DATA_PATH_C_SF_7_s));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[0] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[0]), .Q (DATA_PATH_SF_1_s[0]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[1] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[1]), .Q (DATA_PATH_SF_1_s[1]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[2] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[2]), .Q (DATA_PATH_SF_1_s[2]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[3] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[3]), .Q (DATA_PATH_SF_1_s[3]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[4] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[4]), .Q (DATA_PATH_SF_1_s[4]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[5] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[5]), .Q (DATA_PATH_SF_1_s[5]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[6] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[6]), .Q (DATA_PATH_SF_1_s[6]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[7] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[7]), .Q (DATA_PATH_SF_1_s[7]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[8] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[8]), .Q (DATA_PATH_SF_1_s[8]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[9] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[9]), .Q (DATA_PATH_SF_1_s[9]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[10] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[10]), .Q (DATA_PATH_SF_1_s[10]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[11] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[11]), .Q (DATA_PATH_SF_1_s[11]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[12] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[12]), .Q (DATA_PATH_SF_1_s[12]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[13] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[13]), .Q (DATA_PATH_SF_1_s[13]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[14] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[14]), .Q (DATA_PATH_SF_1_s[14]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[15] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[15]), .Q (DATA_PATH_SF_1_s[15]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[16] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[16]), .Q (DATA_PATH_SF_1_s[16]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[17] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[17]), .Q (DATA_PATH_SF_1_s[17]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[18] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[18]), .Q (DATA_PATH_SF_1_s[18]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[19] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[19]), .Q (DATA_PATH_SF_1_s[19]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[20] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[20]), .Q (DATA_PATH_SF_1_s[20]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[21] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[21]), .Q (DATA_PATH_SF_1_s[21]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[22] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[22]), .Q (DATA_PATH_SF_1_s[22]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[23] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[23]), .Q (DATA_PATH_SF_1_s[23]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[24] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[24]), .Q (DATA_PATH_SF_1_s[24]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[25] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[25]), .Q (DATA_PATH_SF_1_s[25]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[26] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[26]), .Q (DATA_PATH_SF_1_s[26]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[27] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[27]), .Q (DATA_PATH_SF_1_s[27]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[28] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[28]), .Q (DATA_PATH_SF_1_s[28]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[29] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[29]), .Q (DATA_PATH_SF_1_s[29]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[30] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[30]), .Q (DATA_PATH_SF_1_s[30]));
  DFFRHQX1 \DATA_PATH_SF_1_s_reg[31] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_0_s[31]), .Q (DATA_PATH_SF_1_s[31]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[0] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[0]), .Q (DATA_PATH_SF_2_s[0]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[1] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[1]), .Q (DATA_PATH_SF_2_s[1]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[2] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[2]), .Q (DATA_PATH_SF_2_s[2]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[3] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[3]), .Q (DATA_PATH_SF_2_s[3]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[4] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[4]), .Q (DATA_PATH_SF_2_s[4]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[5] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[5]), .Q (DATA_PATH_SF_2_s[5]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[6] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[6]), .Q (DATA_PATH_SF_2_s[6]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[7] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[7]), .Q (DATA_PATH_SF_2_s[7]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[8] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[8]), .Q (DATA_PATH_SF_2_s[8]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[9] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[9]), .Q (DATA_PATH_SF_2_s[9]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[10] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[10]), .Q (DATA_PATH_SF_2_s[10]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[11] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[11]), .Q (DATA_PATH_SF_2_s[11]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[12] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[12]), .Q (DATA_PATH_SF_2_s[12]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[13] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[13]), .Q (DATA_PATH_SF_2_s[13]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[14] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[14]), .Q (DATA_PATH_SF_2_s[14]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[15] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[15]), .Q (DATA_PATH_SF_2_s[15]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[16] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[16]), .Q (DATA_PATH_SF_2_s[16]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[17] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[17]), .Q (DATA_PATH_SF_2_s[17]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[18] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[18]), .Q (DATA_PATH_SF_2_s[18]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[19] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[19]), .Q (DATA_PATH_SF_2_s[19]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[20] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[20]), .Q (DATA_PATH_SF_2_s[20]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[21] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[21]), .Q (DATA_PATH_SF_2_s[21]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[22] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[22]), .Q (DATA_PATH_SF_2_s[22]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[23] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[23]), .Q (DATA_PATH_SF_2_s[23]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[24] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[24]), .Q (DATA_PATH_SF_2_s[24]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[25] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[25]), .Q (DATA_PATH_SF_2_s[25]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[26] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[26]), .Q (DATA_PATH_SF_2_s[26]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[27] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[27]), .Q (DATA_PATH_SF_2_s[27]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[28] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[28]), .Q (DATA_PATH_SF_2_s[28]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[29] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[29]), .Q (DATA_PATH_SF_2_s[29]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[30] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[30]), .Q (DATA_PATH_SF_2_s[30]));
  DFFRHQX1 \DATA_PATH_SF_2_s_reg[31] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_1_s[31]), .Q (DATA_PATH_SF_2_s[31]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[0] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[0]), .Q (data_serial_o[0]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[1] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[1]), .Q (data_serial_o[1]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[2] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[2]), .Q (data_serial_o[2]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[3] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[3]), .Q (data_serial_o[3]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[4] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[4]), .Q (data_serial_o[4]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[5] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[5]), .Q (data_serial_o[5]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[6] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[6]), .Q (data_serial_o[6]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[7] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[7]), .Q (data_serial_o[7]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[8] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[8]), .Q (data_serial_o[8]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[9] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[9]), .Q (data_serial_o[9]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[10] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[10]), .Q (data_serial_o[10]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[11] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[11]), .Q (data_serial_o[11]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[12] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[12]), .Q (data_serial_o[12]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[13] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[13]), .Q (data_serial_o[13]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[14] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[14]), .Q (data_serial_o[14]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[15] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[15]), .Q (data_serial_o[15]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[16] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[16]), .Q (data_serial_o[16]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[17] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[17]), .Q (data_serial_o[17]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[18] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[18]), .Q (data_serial_o[18]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[19] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[19]), .Q (data_serial_o[19]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[20] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[20]), .Q (data_serial_o[20]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[21] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[21]), .Q (data_serial_o[21]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[22] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[22]), .Q (data_serial_o[22]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[23] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[23]), .Q (data_serial_o[23]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[24] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[24]), .Q (data_serial_o[24]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[25] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[25]), .Q (data_serial_o[25]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[26] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[26]), .Q (data_serial_o[26]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[27] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[27]), .Q (data_serial_o[27]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[28] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[28]), .Q (data_serial_o[28]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[29] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[29]), .Q (data_serial_o[29]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[30] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[30]), .Q (data_serial_o[30]));
  DFFRHQX8 \DATA_PATH_SF_3_s_reg[31] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_2_s[31]), .Q (data_serial_o[31]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[0] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[0]), .Q (DATA_PATH_SF_4_s[0]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[1] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[1]), .Q (DATA_PATH_SF_4_s[1]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[2] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[2]), .Q (DATA_PATH_SF_4_s[2]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[3] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[3]), .Q (DATA_PATH_SF_4_s[3]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[4] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[4]), .Q (DATA_PATH_SF_4_s[4]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[5] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[5]), .Q (DATA_PATH_SF_4_s[5]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[6] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[6]), .Q (DATA_PATH_SF_4_s[6]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[7] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[7]), .Q (DATA_PATH_SF_4_s[7]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[8] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[8]), .Q (DATA_PATH_SF_4_s[8]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[9] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[9]), .Q (DATA_PATH_SF_4_s[9]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[10] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[10]), .Q (DATA_PATH_SF_4_s[10]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[11] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[11]), .Q (DATA_PATH_SF_4_s[11]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[12] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[12]), .Q (DATA_PATH_SF_4_s[12]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[13] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[13]), .Q (DATA_PATH_SF_4_s[13]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[14] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[14]), .Q (DATA_PATH_SF_4_s[14]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[15] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[15]), .Q (DATA_PATH_SF_4_s[15]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[16] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[16]), .Q (DATA_PATH_SF_4_s[16]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[17] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[17]), .Q (DATA_PATH_SF_4_s[17]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[18] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[18]), .Q (DATA_PATH_SF_4_s[18]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[19] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[19]), .Q (DATA_PATH_SF_4_s[19]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[20] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[20]), .Q (DATA_PATH_SF_4_s[20]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[21] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[21]), .Q (DATA_PATH_SF_4_s[21]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[22] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[22]), .Q (DATA_PATH_SF_4_s[22]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[23] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[23]), .Q (DATA_PATH_SF_4_s[23]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[24] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[24]), .Q (DATA_PATH_SF_4_s[24]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[25] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[25]), .Q (DATA_PATH_SF_4_s[25]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[26] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[26]), .Q (DATA_PATH_SF_4_s[26]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[27] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[27]), .Q (DATA_PATH_SF_4_s[27]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[28] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[28]), .Q (DATA_PATH_SF_4_s[28]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[29] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[29]), .Q (DATA_PATH_SF_4_s[29]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[30] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[30]), .Q (DATA_PATH_SF_4_s[30]));
  DFFRHQX1 \DATA_PATH_SF_4_s_reg[31] (.RN (n_60), .CK (clk_gated_s), .D
       (data_serial_o[31]), .Q (DATA_PATH_SF_4_s[31]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[0] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[0]), .Q (DATA_PATH_SF_5_s[0]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[1] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[1]), .Q (DATA_PATH_SF_5_s[1]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[2] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[2]), .Q (DATA_PATH_SF_5_s[2]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[3] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[3]), .Q (DATA_PATH_SF_5_s[3]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[4] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[4]), .Q (DATA_PATH_SF_5_s[4]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[5] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[5]), .Q (DATA_PATH_SF_5_s[5]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[6] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[6]), .Q (DATA_PATH_SF_5_s[6]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[7] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[7]), .Q (DATA_PATH_SF_5_s[7]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[8] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[8]), .Q (DATA_PATH_SF_5_s[8]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[9] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[9]), .Q (DATA_PATH_SF_5_s[9]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[10] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[10]), .Q (DATA_PATH_SF_5_s[10]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[11] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[11]), .Q (DATA_PATH_SF_5_s[11]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[12] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[12]), .Q (DATA_PATH_SF_5_s[12]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[13] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[13]), .Q (DATA_PATH_SF_5_s[13]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[14] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[14]), .Q (DATA_PATH_SF_5_s[14]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[15] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[15]), .Q (DATA_PATH_SF_5_s[15]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[16] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[16]), .Q (DATA_PATH_SF_5_s[16]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[17] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[17]), .Q (DATA_PATH_SF_5_s[17]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[18] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[18]), .Q (DATA_PATH_SF_5_s[18]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[19] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[19]), .Q (DATA_PATH_SF_5_s[19]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[20] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[20]), .Q (DATA_PATH_SF_5_s[20]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[21] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[21]), .Q (DATA_PATH_SF_5_s[21]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[22] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[22]), .Q (DATA_PATH_SF_5_s[22]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[23] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[23]), .Q (DATA_PATH_SF_5_s[23]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[24] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[24]), .Q (DATA_PATH_SF_5_s[24]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[25] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[25]), .Q (DATA_PATH_SF_5_s[25]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[26] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[26]), .Q (DATA_PATH_SF_5_s[26]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[27] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[27]), .Q (DATA_PATH_SF_5_s[27]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[28] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[28]), .Q (DATA_PATH_SF_5_s[28]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[29] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[29]), .Q (DATA_PATH_SF_5_s[29]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[30] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[30]), .Q (DATA_PATH_SF_5_s[30]));
  DFFRHQX1 \DATA_PATH_SF_5_s_reg[31] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_4_s[31]), .Q (DATA_PATH_SF_5_s[31]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[0] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[0]), .Q (DATA_PATH_SF_6_s[0]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[1] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[1]), .Q (DATA_PATH_SF_6_s[1]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[2] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[2]), .Q (DATA_PATH_SF_6_s[2]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[3] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[3]), .Q (DATA_PATH_SF_6_s[3]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[4] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[4]), .Q (DATA_PATH_SF_6_s[4]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[5] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[5]), .Q (DATA_PATH_SF_6_s[5]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[6] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[6]), .Q (DATA_PATH_SF_6_s[6]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[7] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[7]), .Q (DATA_PATH_SF_6_s[7]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[8] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[8]), .Q (DATA_PATH_SF_6_s[8]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[9] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[9]), .Q (DATA_PATH_SF_6_s[9]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[10] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[10]), .Q (DATA_PATH_SF_6_s[10]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[11] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[11]), .Q (DATA_PATH_SF_6_s[11]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[12] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[12]), .Q (DATA_PATH_SF_6_s[12]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[13] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[13]), .Q (DATA_PATH_SF_6_s[13]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[14] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[14]), .Q (DATA_PATH_SF_6_s[14]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[15] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[15]), .Q (DATA_PATH_SF_6_s[15]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[16] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[16]), .Q (DATA_PATH_SF_6_s[16]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[17] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[17]), .Q (DATA_PATH_SF_6_s[17]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[18] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[18]), .Q (DATA_PATH_SF_6_s[18]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[19] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[19]), .Q (DATA_PATH_SF_6_s[19]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[20] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[20]), .Q (DATA_PATH_SF_6_s[20]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[21] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[21]), .Q (DATA_PATH_SF_6_s[21]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[22] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[22]), .Q (DATA_PATH_SF_6_s[22]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[23] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[23]), .Q (DATA_PATH_SF_6_s[23]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[24] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[24]), .Q (DATA_PATH_SF_6_s[24]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[25] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[25]), .Q (DATA_PATH_SF_6_s[25]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[26] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[26]), .Q (DATA_PATH_SF_6_s[26]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[27] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[27]), .Q (DATA_PATH_SF_6_s[27]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[28] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[28]), .Q (DATA_PATH_SF_6_s[28]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[29] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[29]), .Q (DATA_PATH_SF_6_s[29]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[30] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[30]), .Q (DATA_PATH_SF_6_s[30]));
  DFFRHQX1 \DATA_PATH_SF_6_s_reg[31] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_5_s[31]), .Q (DATA_PATH_SF_6_s[31]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[0] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[0]), .Q (DATA_PATH_SF_7_s[0]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[1] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[1]), .Q (DATA_PATH_SF_7_s[1]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[2] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[2]), .Q (DATA_PATH_SF_7_s[2]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[3] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[3]), .Q (DATA_PATH_SF_7_s[3]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[4] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[4]), .Q (DATA_PATH_SF_7_s[4]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[5] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[5]), .Q (DATA_PATH_SF_7_s[5]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[6] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[6]), .Q (DATA_PATH_SF_7_s[6]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[7] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[7]), .Q (DATA_PATH_SF_7_s[7]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[8] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[8]), .Q (DATA_PATH_SF_7_s[8]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[9] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[9]), .Q (DATA_PATH_SF_7_s[9]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[10] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[10]), .Q (DATA_PATH_SF_7_s[10]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[11] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[11]), .Q (DATA_PATH_SF_7_s[11]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[12] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[12]), .Q (DATA_PATH_SF_7_s[12]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[13] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[13]), .Q (DATA_PATH_SF_7_s[13]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[14] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[14]), .Q (DATA_PATH_SF_7_s[14]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[15] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[15]), .Q (DATA_PATH_SF_7_s[15]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[16] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[16]), .Q (DATA_PATH_SF_7_s[16]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[17] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[17]), .Q (DATA_PATH_SF_7_s[17]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[18] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[18]), .Q (DATA_PATH_SF_7_s[18]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[19] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[19]), .Q (DATA_PATH_SF_7_s[19]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[20] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[20]), .Q (DATA_PATH_SF_7_s[20]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[21] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[21]), .Q (DATA_PATH_SF_7_s[21]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[22] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[22]), .Q (DATA_PATH_SF_7_s[22]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[23] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[23]), .Q (DATA_PATH_SF_7_s[23]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[24] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[24]), .Q (DATA_PATH_SF_7_s[24]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[25] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[25]), .Q (DATA_PATH_SF_7_s[25]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[26] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[26]), .Q (DATA_PATH_SF_7_s[26]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[27] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[27]), .Q (DATA_PATH_SF_7_s[27]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[28] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[28]), .Q (DATA_PATH_SF_7_s[28]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[29] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[29]), .Q (DATA_PATH_SF_7_s[29]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[30] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[30]), .Q (DATA_PATH_SF_7_s[30]));
  DFFRHQX1 \DATA_PATH_SF_7_s_reg[31] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_6_s[31]), .Q (DATA_PATH_SF_7_s[31]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[0] (.RN (n_60), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[0]), .Q (DATA_PATH_SF_8_s[0]));
  OAI21X4 g4274__2398(.A0 (n_88), .A1 (n_384), .B0 (n_221), .Y (n_252));
  OAI21X4 g4275__5107(.A0 (n_88), .A1 (n_379), .B0 (n_220), .Y (n_251));
  OAI21X4 g4276__6260(.A0 (n_88), .A1 (n_378), .B0 (n_215), .Y (n_250));
  OAI21X4 g4277__4319(.A0 (n_88), .A1 (n_380), .B0 (n_219), .Y (n_249));
  OAI21X4 g4278__8428(.A0 (n_88), .A1 (n_381), .B0 (n_218), .Y (n_248));
  OAI21X4 g4279__5526(.A0 (n_88), .A1 (n_382), .B0 (n_217), .Y (n_247));
  OAI21X4 g4280__6783(.A0 (n_88), .A1 (n_383), .B0 (n_216), .Y (n_246));
  OAI21X4 g4281__3680(.A0 (n_88), .A1 (n_408), .B0 (n_214), .Y (n_245));
  OAI21X4 g4282__1617(.A0 (n_88), .A1 (n_385), .B0 (n_213), .Y (n_244));
  OAI21X4 g4283__2802(.A0 (n_88), .A1 (n_386), .B0 (n_212), .Y (n_243));
  OAI21X4 g4284__1705(.A0 (n_88), .A1 (n_387), .B0 (n_211), .Y (n_242));
  OAI21X4 g4285__5122(.A0 (n_88), .A1 (n_388), .B0 (n_210), .Y (n_241));
  OAI21X4 g4286__8246(.A0 (n_88), .A1 (n_389), .B0 (n_209), .Y (n_240));
  OAI21X4 g4287__7098(.A0 (n_88), .A1 (n_390), .B0 (n_208), .Y (n_239));
  OAI21X4 g4288__6131(.A0 (n_88), .A1 (n_391), .B0 (n_207), .Y (n_238));
  OAI21X4 g4289__1881(.A0 (n_88), .A1 (n_407), .B0 (n_206), .Y (n_237));
  OAI21X4 g4290__5115(.A0 (n_88), .A1 (n_393), .B0 (n_205), .Y (n_236));
  OAI21X4 g4291__7482(.A0 (n_88), .A1 (n_394), .B0 (n_204), .Y (n_235));
  OAI21X4 g4292__4733(.A0 (n_88), .A1 (n_395), .B0 (n_203), .Y (n_234));
  OAI21X4 g4293__6161(.A0 (n_88), .A1 (n_396), .B0 (n_202), .Y (n_233));
  OAI21X4 g4294__9315(.A0 (n_88), .A1 (n_397), .B0 (n_201), .Y (n_232));
  OAI21X4 g4295__9945(.A0 (n_88), .A1 (n_398), .B0 (n_200), .Y (n_231));
  OAI21X4 g4296__2883(.A0 (n_88), .A1 (n_399), .B0 (n_199), .Y (n_230));
  OAI21X4 g4297__2346(.A0 (n_88), .A1 (n_400), .B0 (n_198), .Y (n_229));
  OAI21X4 g4298__1666(.A0 (n_88), .A1 (n_401), .B0 (n_197), .Y (n_228));
  OAI21X4 g4299__7410(.A0 (n_88), .A1 (n_402), .B0 (n_196), .Y (n_227));
  OAI21X4 g4300__6417(.A0 (n_88), .A1 (n_403), .B0 (n_195), .Y (n_226));
  OAI21X4 g4301__5477(.A0 (n_88), .A1 (n_404), .B0 (n_194), .Y (n_225));
  OAI21X4 g4302__2398(.A0 (n_88), .A1 (n_405), .B0 (n_193), .Y (n_224));
  OAI21X4 g4303__5107(.A0 (n_88), .A1 (n_406), .B0 (n_192), .Y (n_223));
  OAI21X4 g4304__6260(.A0 (n_88), .A1 (n_392), .B0 (n_191), .Y (n_222));
  AOI22X1 g4305__4319(.A0 (DATA_PATH_SF_9_s[7]), .A1 (n_369), .B0
       (DATA_PATH_SF_8_s[7]), .B1 (n_429), .Y (n_221));
  AOI22X1 g4306__8428(.A0 (DATA_PATH_SF_9_s[2]), .A1 (n_369), .B0
       (DATA_PATH_SF_8_s[2]), .B1 (n_429), .Y (n_220));
  AOI22X1 g4307__5526(.A0 (DATA_PATH_SF_9_s[3]), .A1 (n_361), .B0
       (DATA_PATH_SF_8_s[3]), .B1 (n_429), .Y (n_219));
  AOI22X1 g4308__6783(.A0 (DATA_PATH_SF_9_s[4]), .A1 (n_361), .B0
       (DATA_PATH_SF_8_s[4]), .B1 (n_429), .Y (n_218));
  AOI22X1 g4309__3680(.A0 (DATA_PATH_SF_9_s[5]), .A1 (n_361), .B0
       (DATA_PATH_SF_8_s[5]), .B1 (n_429), .Y (n_217));
  AOI22X1 g4310__1617(.A0 (DATA_PATH_SF_9_s[6]), .A1 (n_369), .B0
       (DATA_PATH_SF_8_s[6]), .B1 (n_429), .Y (n_216));
  AOI22X1 g4311__2802(.A0 (DATA_PATH_SF_9_s[1]), .A1 (n_361), .B0
       (DATA_PATH_SF_8_s[1]), .B1 (n_429), .Y (n_215));
  AOI22X1 g4312__1705(.A0 (n_92), .A1 (n_369), .B0
       (DATA_PATH_SF_8_s[31]), .B1 (n_429), .Y (n_214));
  AOI22X1 g4313__5122(.A0 (DATA_PATH_SF_9_s[8]), .A1 (n_361), .B0
       (DATA_PATH_SF_8_s[8]), .B1 (n_429), .Y (n_213));
  AOI22X1 g4314__8246(.A0 (DATA_PATH_SF_9_s[9]), .A1 (n_369), .B0
       (DATA_PATH_SF_8_s[9]), .B1 (n_429), .Y (n_212));
  AOI22X1 g4315__7098(.A0 (DATA_PATH_SF_9_s[10]), .A1 (n_369), .B0
       (DATA_PATH_SF_8_s[10]), .B1 (n_429), .Y (n_211));
  AOI22X1 g4316__6131(.A0 (DATA_PATH_SF_9_s[11]), .A1 (n_361), .B0
       (DATA_PATH_SF_8_s[11]), .B1 (n_429), .Y (n_210));
  AOI22X1 g4317__1881(.A0 (DATA_PATH_SF_9_s[12]), .A1 (n_369), .B0
       (DATA_PATH_SF_8_s[12]), .B1 (n_429), .Y (n_209));
  AOI22X1 g4318__5115(.A0 (DATA_PATH_SF_9_s[13]), .A1 (n_361), .B0
       (DATA_PATH_SF_8_s[13]), .B1 (n_429), .Y (n_208));
  AOI22X1 g4319__7482(.A0 (DATA_PATH_SF_9_s[14]), .A1 (n_361), .B0
       (DATA_PATH_SF_8_s[14]), .B1 (n_429), .Y (n_207));
  AOI22X1 g4320__4733(.A0 (DATA_PATH_SF_9_s[30]), .A1 (n_361), .B0
       (DATA_PATH_SF_8_s[30]), .B1 (n_427), .Y (n_206));
  AOI22X1 g4321__6161(.A0 (DATA_PATH_SF_9_s[16]), .A1 (n_369), .B0
       (DATA_PATH_SF_8_s[16]), .B1 (n_429), .Y (n_205));
  AOI22X1 g4322__9315(.A0 (DATA_PATH_SF_9_s[17]), .A1 (n_369), .B0
       (DATA_PATH_SF_8_s[17]), .B1 (n_429), .Y (n_204));
  AOI22X1 g4323__9945(.A0 (DATA_PATH_SF_9_s[18]), .A1 (n_361), .B0
       (DATA_PATH_SF_8_s[18]), .B1 (n_429), .Y (n_203));
  AOI22X1 g4324__2883(.A0 (DATA_PATH_SF_9_s[19]), .A1 (n_361), .B0
       (DATA_PATH_SF_8_s[19]), .B1 (n_429), .Y (n_202));
  AOI22X1 g4325__2346(.A0 (DATA_PATH_SF_9_s[20]), .A1 (n_361), .B0
       (DATA_PATH_SF_8_s[20]), .B1 (n_429), .Y (n_201));
  AOI22X1 g4326__1666(.A0 (DATA_PATH_SF_9_s[21]), .A1 (n_361), .B0
       (DATA_PATH_SF_8_s[21]), .B1 (n_429), .Y (n_200));
  AOI22X1 g4327__7410(.A0 (DATA_PATH_SF_9_s[22]), .A1 (n_369), .B0
       (DATA_PATH_SF_8_s[22]), .B1 (n_429), .Y (n_199));
  AOI22X1 g4328__6417(.A0 (DATA_PATH_SF_9_s[23]), .A1 (n_369), .B0
       (n_95), .B1 (n_429), .Y (n_198));
  AOI22X1 g4329__5477(.A0 (DATA_PATH_SF_9_s[24]), .A1 (n_361), .B0
       (DATA_PATH_SF_8_s[24]), .B1 (n_429), .Y (n_197));
  AOI22X1 g4330__2398(.A0 (DATA_PATH_SF_9_s[25]), .A1 (n_361), .B0
       (DATA_PATH_SF_8_s[25]), .B1 (n_429), .Y (n_196));
  AOI22X1 g4331__5107(.A0 (DATA_PATH_SF_9_s[26]), .A1 (n_369), .B0
       (DATA_PATH_SF_8_s[26]), .B1 (n_429), .Y (n_195));
  AOI22X1 g4332__6260(.A0 (DATA_PATH_SF_9_s[27]), .A1 (n_361), .B0
       (n_90), .B1 (n_429), .Y (n_194));
  AOI22X1 g4333__4319(.A0 (DATA_PATH_SF_9_s[28]), .A1 (n_369), .B0
       (DATA_PATH_SF_8_s[28]), .B1 (n_429), .Y (n_193));
  AOI22X1 g4334__8428(.A0 (DATA_PATH_SF_9_s[29]), .A1 (n_369), .B0
       (DATA_PATH_SF_8_s[29]), .B1 (n_429), .Y (n_192));
  AOI22X1 g4335__5526(.A0 (DATA_PATH_SF_9_s[15]), .A1 (n_369), .B0
       (DATA_PATH_SF_8_s[15]), .B1 (n_429), .Y (n_191));
  AND2X6 g4336__6783(.A (n_88), .B (n_190), .Y (n_1839_BAR));
  NAND2X6 g4341__3680(.A (n_139), .B (n_189), .Y (n_190));
  OAI21X4 g4342__1617(.A0 (n_178), .A1 (n_188), .B0 (n_182), .Y
       (n_189));
  AOI21X4 g4343__2802(.A0 (n_175), .A1 (n_187), .B0 (n_179), .Y
       (n_188));
  OAI2BB1X4 g4344__1705(.A0N (n_162), .A1N (n_186), .B0 (n_174), .Y
       (n_187));
  OAI211X2 g4346__5122(.A0 (DATA_PATH_SF_8_s[3]), .A1 (n_102), .B0
       (n_138), .C0 (n_185), .Y (n_186));
  OAI21X2 g4348__8246(.A0 (DATA_PATH_SF_9_s[1]), .A1 (n_183), .B0
       (n_184), .Y (n_185));
  AOI211X4 g4350__7098(.A0 (DATA_PATH_SF_8_s[1]), .A1
       (DATA_PATH_SF_8_s[0]), .B0 (n_49), .C0 (n_135), .Y (n_184));
  NOR2X1 g4352__6131(.A (DATA_PATH_SF_8_s[1]), .B
       (DATA_PATH_SF_8_s[0]), .Y (n_183));
  AOI21X4 g4355__1881(.A0 (n_177), .A1 (n_181), .B0 (n_180), .Y
       (n_182));
  OAI21X2 g4361__5115(.A0 (n_166), .A1 (n_167), .B0 (n_172), .Y
       (n_181));
  OAI21X2 g4362__7482(.A0 (n_163), .A1 (n_170), .B0 (n_171), .Y
       (n_180));
  OAI21X2 g4363__4733(.A0 (n_164), .A1 (n_168), .B0 (n_169), .Y
       (n_179));
  NAND2X4 g4366__6161(.A (n_173), .B (n_177), .Y (n_178));
  OAI221X1 g4368__9315(.A0 (n_354), .A1 (n_147), .B0 (n_286), .B1
       (n_319), .C0 (n_123), .Y (n_176));
  AOI211X2 g4369__9945(.A0 (DATA_PATH_SF_8_s[8]), .A1 (n_66), .B0
       (n_164), .C0 (n_149), .Y (n_175));
  AOI21X1 g4370__2883(.A0 (n_145), .A1 (n_154), .B0 (n_159), .Y
       (n_174));
  NOR2X2 g4371__2346(.A (n_161), .B (n_166), .Y (n_173));
  NOR2X4 g4372__1666(.A (n_163), .B (n_165), .Y (n_177));
  AOI21X2 g4373__7410(.A0 (n_140), .A1 (n_153), .B0 (n_158), .Y
       (n_172));
  AOI21X2 g4374__6417(.A0 (n_142), .A1 (n_150), .B0 (n_157), .Y
       (n_171));
  AOI21X1 g4375__5477(.A0 (n_144), .A1 (n_148), .B0 (n_156), .Y
       (n_170));
  AOI21X1 g4376__2398(.A0 (n_141), .A1 (n_151), .B0 (n_155), .Y
       (n_169));
  OA21X1 g4377__5107(.A0 (n_146), .A1 (n_149), .B0 (n_160), .Y (n_168));
  AOI211X2 g4378__6260(.A0 (n_137), .A1 (n_152), .B0 (n_130), .C0
       (n_143), .Y (n_167));
  OAI2BB1X2 g4379__4319(.A0N (DATA_PATH_SF_8_s[24]), .A1N (n_64), .B0
       (n_148), .Y (n_165));
  OAI2BB1X4 g4381__8428(.A0N (DATA_PATH_SF_8_s[20]), .A1N (n_71), .B0
       (n_153), .Y (n_166));
  AND2X1 g4382__5526(.A (n_154), .B (n_127), .Y (n_162));
  OAI2BB1X1 g4383__6783(.A0N (DATA_PATH_SF_8_s[16]), .A1N (n_104), .B0
       (n_152), .Y (n_161));
  NAND2X4 g4384__3680(.A (n_121), .B (n_151), .Y (n_164));
  OAI2BB1X2 g4385__1617(.A0N (DATA_PATH_SF_8_s[28]), .A1N (n_69), .B0
       (n_150), .Y (n_163));
  AOI31X1 g4386__2802(.A0 (DATA_PATH_SF_9_s[10]), .A1 (n_63), .A2
       (n_47), .B0 (n_124), .Y (n_160));
  OAI31X1 g4387__1705(.A0 (DATA_PATH_SF_8_s[6]), .A1 (n_65), .A2
       (n_50), .B0 (n_129), .Y (n_159));
  OAI31X2 g4388__5122(.A0 (DATA_PATH_SF_8_s[22]), .A1 (n_70), .A2
       (n_134), .B0 (n_128), .Y (n_158));
  OAI31X2 g4389__8246(.A0 (DATA_PATH_SF_8_s[30]), .A1 (n_67), .A2
       (n_126), .B0 (n_132), .Y (n_157));
  OAI31X2 g4390__7098(.A0 (DATA_PATH_SF_8_s[26]), .A1 (n_68), .A2
       (n_133), .B0 (n_131), .Y (n_156));
  OAI31X2 g4391__6131(.A0 (DATA_PATH_SF_8_s[14]), .A1 (n_101), .A2
       (n_57), .B0 (n_122), .Y (n_155));
  AOI211X2 g4393__1881(.A0 (DATA_PATH_SF_8_s[6]), .A1 (n_65), .B0
       (n_46), .C0 (n_50), .Y (n_154));
  AOI211X4 g4394__5115(.A0 (DATA_PATH_SF_8_s[22]), .A1 (n_70), .B0
       (n_45), .C0 (n_134), .Y (n_153));
  NOR3X2 g4395__7482(.A (n_52), .B (n_55), .C (n_48), .Y (n_152));
  NOR3X4 g4396__4733(.A (n_51), .B (n_53), .C (n_57), .Y (n_151));
  AOI211X4 g4397__6161(.A0 (DATA_PATH_SF_8_s[30]), .A1 (n_67), .B0
       (n_58), .C0 (n_126), .Y (n_150));
  NAND3X4 g4398__9315(.A (n_125), .B (n_56), .C (n_47), .Y (n_149));
  AOI211X2 g4399__9945(.A0 (DATA_PATH_SF_8_s[26]), .A1 (n_68), .B0
       (n_54), .C0 (n_133), .Y (n_148));
  AOI2BB1X1 g4401__2883(.A0N (CONTROL_PATH_CurrentState[0]), .A1N
       (n_88), .B0 (DATA_PATH_C_SF_9_s), .Y (n_147));
  OA22X1 g4402__2346(.A0 (DATA_PATH_SF_8_s[8]), .A1 (n_66), .B0
       (DATA_PATH_SF_8_s[9]), .B1 (n_99), .Y (n_146));
  OAI22X1 g4403__1666(.A0 (DATA_PATH_SF_8_s[4]), .A1 (n_93), .B0
       (DATA_PATH_SF_8_s[5]), .B1 (n_62), .Y (n_145));
  OAI22X1 g4404__7410(.A0 (DATA_PATH_SF_8_s[24]), .A1 (n_64), .B0
       (DATA_PATH_SF_8_s[25]), .B1 (n_96), .Y (n_144));
  NAND3BX1 g4405__6417(.AN (n_357), .B (CONTROL_PATH_CurrentState[0]),
       .C (is_nine_s), .Y (n_319));
  NOR3BX1 g4406__5477(.AN (DATA_PATH_SF_9_s[18]), .B
       (DATA_PATH_SF_8_s[18]), .C (n_48), .Y (n_143));
  OAI22X1 g4407__2398(.A0 (DATA_PATH_SF_8_s[28]), .A1 (n_69), .B0
       (DATA_PATH_SF_8_s[29]), .B1 (n_72), .Y (n_142));
  OAI22X1 g4408__5107(.A0 (DATA_PATH_SF_8_s[12]), .A1 (n_100), .B0
       (DATA_PATH_SF_8_s[13]), .B1 (n_103), .Y (n_141));
  OAI22X1 g4409__6260(.A0 (DATA_PATH_SF_8_s[20]), .A1 (n_71), .B0
       (DATA_PATH_SF_8_s[21]), .B1 (n_97), .Y (n_140));
  NOR3X1 g4410__4319(.A (n_359), .B (is_nine_s), .C (n_286), .Y
       (n_139));
  NAND3BX2 g4411__8428(.AN (DATA_PATH_SF_8_s[2]), .B
       (DATA_PATH_SF_9_s[2]), .C (n_136), .Y (n_138));
  OAI22X1 g4412__5526(.A0 (DATA_PATH_SF_8_s[16]), .A1 (n_104), .B0
       (DATA_PATH_SF_8_s[17]), .B1 (n_61), .Y (n_137));
  INVX2 g4413(.A (n_135), .Y (n_136));
  NAND2BX1 g4414__6783(.AN (DATA_PATH_SF_9_s[31]), .B
       (DATA_PATH_SF_8_s[31]), .Y (n_132));
  NAND2BX1 g4415__3680(.AN (DATA_PATH_SF_8_s[27]), .B
       (DATA_PATH_SF_9_s[27]), .Y (n_131));
  NOR2BX1 g4418__1617(.AN (DATA_PATH_SF_9_s[19]), .B
       (DATA_PATH_SF_8_s[19]), .Y (n_130));
  NAND2BX1 g4420__2802(.AN (DATA_PATH_SF_8_s[7]), .B
       (DATA_PATH_SF_9_s[7]), .Y (n_129));
  NAND2BX1 g4423__1705(.AN (DATA_PATH_SF_8_s[23]), .B
       (DATA_PATH_SF_9_s[23]), .Y (n_128));
  NAND2X1 g4424__5122(.A (DATA_PATH_SF_8_s[4]), .B (n_93), .Y (n_127));
  NOR2X4 g4426__8246(.A (DATA_PATH_SF_9_s[3]), .B (n_98), .Y (n_135));
  NOR2X2 g4427__7098(.A (DATA_PATH_SF_9_s[23]), .B (n_94), .Y (n_134));
  NOR2X4 g4428__6131(.A (DATA_PATH_SF_9_s[27]), .B (n_89), .Y (n_133));
  NAND2X2 g4430__1881(.A (DATA_PATH_SF_8_s[9]), .B (n_99), .Y (n_125));
  NOR2BX1 g4433__5115(.AN (DATA_PATH_SF_9_s[11]), .B
       (DATA_PATH_SF_8_s[11]), .Y (n_124));
  NAND2X1 g4435__7482(.A (CONTROL_PATH_CurrentState[0]), .B
       (DATA_PATH_C_SF_9_s), .Y (n_123));
  NAND2BX1 g4436__4733(.AN (DATA_PATH_SF_8_s[15]), .B
       (DATA_PATH_SF_9_s[15]), .Y (n_122));
  NAND2BX1 g4438__6161(.AN (DATA_PATH_SF_9_s[12]), .B
       (DATA_PATH_SF_8_s[12]), .Y (n_121));
  NOR2X4 g4441__9315(.A (DATA_PATH_SF_8_s[31]), .B (n_91), .Y (n_126));
  CLKAND2X3 g4443__9945(.A (clk), .B (en_cg_s), .Y (clk_gated_s));
  INVX2 g4460(.A (DATA_PATH_SF_9_s[16]), .Y (n_104));
  INVX1 g4461(.A (DATA_PATH_SF_9_s[13]), .Y (n_103));
  INVX1 g4462(.A (DATA_PATH_SF_9_s[3]), .Y (n_102));
  INVX1 g4463(.A (DATA_PATH_SF_9_s[14]), .Y (n_101));
  INVX1 g4464(.A (DATA_PATH_SF_9_s[12]), .Y (n_100));
  INVX1 g4466(.A (DATA_PATH_SF_9_s[9]), .Y (n_99));
  INVX2 g4467(.A (DATA_PATH_SF_8_s[3]), .Y (n_98));
  INVX1 g4470(.A (DATA_PATH_SF_9_s[21]), .Y (n_97));
  INVX1 g4473(.A (DATA_PATH_SF_9_s[25]), .Y (n_96));
  INVX1 g4474(.A (n_94), .Y (n_95));
  INVX2 g4475(.A (DATA_PATH_SF_8_s[23]), .Y (n_94));
  INVX2 g4476(.A (DATA_PATH_SF_9_s[4]), .Y (n_93));
  INVX1 g4477(.A (n_91), .Y (n_92));
  INVX2 g4478(.A (DATA_PATH_SF_9_s[31]), .Y (n_91));
  INVX1 g4481(.A (n_89), .Y (n_90));
  INVX2 g4482(.A (DATA_PATH_SF_8_s[27]), .Y (n_89));
  CLKINVX6 g4483(.A (n_286), .Y (n_88));
  INVX1 g4502(.A (DATA_PATH_SF_9_s[29]), .Y (n_72));
  INVX2 g4505(.A (DATA_PATH_SF_9_s[20]), .Y (n_71));
  INVX1 g4506(.A (DATA_PATH_SF_9_s[22]), .Y (n_70));
  INVX2 g4507(.A (DATA_PATH_SF_9_s[28]), .Y (n_69));
  CLKINVX2 g4508(.A (DATA_PATH_SF_9_s[26]), .Y (n_68));
  INVX1 g4509(.A (DATA_PATH_SF_9_s[30]), .Y (n_67));
  INVX1 g4510(.A (DATA_PATH_SF_9_s[8]), .Y (n_66));
  CLKINVX4 g4511(.A (DATA_PATH_SF_9_s[6]), .Y (n_65));
  INVX2 g4512(.A (DATA_PATH_SF_9_s[24]), .Y (n_64));
  INVX1 g4515(.A (DATA_PATH_SF_8_s[10]), .Y (n_63));
  INVX1 g4516(.A (DATA_PATH_SF_9_s[5]), .Y (n_62));
  INVX1 g4517(.A (DATA_PATH_SF_9_s[17]), .Y (n_61));
  INVXL g4518(.A (rst), .Y (n_60));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[1] (.RN (n_60), .CK (clk_gated_s), .D
       (n_250), .Q (DATA_PATH_SF_0_s[1]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[2] (.RN (n_60), .CK (clk_gated_s), .D
       (n_251), .Q (DATA_PATH_SF_0_s[2]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[3] (.RN (n_60), .CK (clk_gated_s), .D
       (n_249), .Q (DATA_PATH_SF_0_s[3]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[4] (.RN (n_60), .CK (clk_gated_s), .D
       (n_248), .Q (DATA_PATH_SF_0_s[4]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[5] (.RN (n_60), .CK (clk_gated_s), .D
       (n_247), .Q (DATA_PATH_SF_0_s[5]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[6] (.RN (n_60), .CK (clk_gated_s), .D
       (n_246), .Q (DATA_PATH_SF_0_s[6]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[7] (.RN (n_60), .CK (clk_gated_s), .D
       (n_252), .Q (DATA_PATH_SF_0_s[7]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[8] (.RN (n_60), .CK (clk_gated_s), .D
       (n_244), .Q (DATA_PATH_SF_0_s[8]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[9] (.RN (n_60), .CK (clk_gated_s), .D
       (n_243), .Q (DATA_PATH_SF_0_s[9]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[10] (.RN (n_60), .CK (clk_gated_s), .D
       (n_242), .Q (DATA_PATH_SF_0_s[10]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[11] (.RN (n_60), .CK (clk_gated_s), .D
       (n_241), .Q (DATA_PATH_SF_0_s[11]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[12] (.RN (n_60), .CK (clk_gated_s), .D
       (n_240), .Q (DATA_PATH_SF_0_s[12]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[13] (.RN (n_60), .CK (clk_gated_s), .D
       (n_239), .Q (DATA_PATH_SF_0_s[13]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[14] (.RN (n_60), .CK (clk_gated_s), .D
       (n_238), .Q (DATA_PATH_SF_0_s[14]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[15] (.RN (n_60), .CK (clk_gated_s), .D
       (n_222), .Q (DATA_PATH_SF_0_s[15]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[16] (.RN (n_60), .CK (clk_gated_s), .D
       (n_236), .Q (DATA_PATH_SF_0_s[16]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[17] (.RN (n_60), .CK (clk_gated_s), .D
       (n_235), .Q (DATA_PATH_SF_0_s[17]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[18] (.RN (n_60), .CK (clk_gated_s), .D
       (n_234), .Q (DATA_PATH_SF_0_s[18]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[19] (.RN (n_60), .CK (clk_gated_s), .D
       (n_233), .Q (DATA_PATH_SF_0_s[19]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[20] (.RN (n_60), .CK (clk_gated_s), .D
       (n_232), .Q (DATA_PATH_SF_0_s[20]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[21] (.RN (n_60), .CK (clk_gated_s), .D
       (n_231), .Q (DATA_PATH_SF_0_s[21]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[22] (.RN (n_60), .CK (clk_gated_s), .D
       (n_230), .Q (DATA_PATH_SF_0_s[22]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[23] (.RN (n_60), .CK (clk_gated_s), .D
       (n_229), .Q (DATA_PATH_SF_0_s[23]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[24] (.RN (n_60), .CK (clk_gated_s), .D
       (n_228), .Q (DATA_PATH_SF_0_s[24]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[25] (.RN (n_60), .CK (clk_gated_s), .D
       (n_227), .Q (DATA_PATH_SF_0_s[25]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[26] (.RN (n_60), .CK (clk_gated_s), .D
       (n_226), .Q (DATA_PATH_SF_0_s[26]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[27] (.RN (n_60), .CK (clk_gated_s), .D
       (n_225), .Q (DATA_PATH_SF_0_s[27]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[28] (.RN (n_60), .CK (clk_gated_s), .D
       (n_224), .Q (DATA_PATH_SF_0_s[28]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[29] (.RN (n_60), .CK (clk_gated_s), .D
       (n_223), .Q (DATA_PATH_SF_0_s[29]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[30] (.RN (n_60), .CK (clk_gated_s), .D
       (n_237), .Q (DATA_PATH_SF_0_s[30]));
  DFFRHQX1 \DATA_PATH_SF_0_s_reg[31] (.RN (n_60), .CK (clk_gated_s), .D
       (n_245), .Q (DATA_PATH_SF_0_s[31]));
  NOR2BX1 g2__2883(.AN (DATA_PATH_SF_8_s[29]), .B
       (DATA_PATH_SF_9_s[29]), .Y (n_58));
  NOR2BX2 g4519__2346(.AN (DATA_PATH_SF_8_s[15]), .B
       (DATA_PATH_SF_9_s[15]), .Y (n_57));
  NAND2BX1 g4520__1666(.AN (DATA_PATH_SF_9_s[10]), .B
       (DATA_PATH_SF_8_s[10]), .Y (n_56));
  NOR2BX1 g4521__7410(.AN (DATA_PATH_SF_8_s[18]), .B
       (DATA_PATH_SF_9_s[18]), .Y (n_55));
  NOR2BX1 g4522__6417(.AN (DATA_PATH_SF_8_s[25]), .B
       (DATA_PATH_SF_9_s[25]), .Y (n_54));
  NOR2BX1 g4523__5477(.AN (DATA_PATH_SF_8_s[14]), .B
       (DATA_PATH_SF_9_s[14]), .Y (n_53));
  NOR2BX1 g4524__2398(.AN (DATA_PATH_SF_8_s[17]), .B
       (DATA_PATH_SF_9_s[17]), .Y (n_52));
  NOR2BX1 g4525__5107(.AN (DATA_PATH_SF_8_s[13]), .B
       (DATA_PATH_SF_9_s[13]), .Y (n_51));
  NOR2BX2 g4526__6260(.AN (DATA_PATH_SF_8_s[7]), .B
       (DATA_PATH_SF_9_s[7]), .Y (n_50));
  NOR2BX2 g4527__4319(.AN (DATA_PATH_SF_8_s[2]), .B
       (DATA_PATH_SF_9_s[2]), .Y (n_49));
  NOR2BX2 g4528__8428(.AN (DATA_PATH_SF_8_s[19]), .B
       (DATA_PATH_SF_9_s[19]), .Y (n_48));
  NAND2BX2 g4529__5526(.AN (DATA_PATH_SF_9_s[11]), .B
       (DATA_PATH_SF_8_s[11]), .Y (n_47));
  NOR2BX1 g4530__6783(.AN (DATA_PATH_SF_8_s[5]), .B
       (DATA_PATH_SF_9_s[5]), .Y (n_46));
  NOR2BX1 g4531__3680(.AN (DATA_PATH_SF_8_s[21]), .B
       (DATA_PATH_SF_9_s[21]), .Y (n_45));
  DFFRX1 \CONTROL_PATH_CurrentState_reg[0] (.RN (n_0), .CK
       (clk_gated_s), .D (n_42), .Q (CONTROL_PATH_CurrentState[0]), .QN
       (UNCONNECTED));
  DFFRHQX4 \CONTROL_PATH_CurrentState_reg[1] (.RN (n_0), .CK
       (clk_gated_s), .D (n_2), .Q (CONTROL_PATH_CurrentState[1]));
  DFFRHQX4 \CONTROL_PATH_CurrentState_reg[2] (.RN (n_0), .CK
       (clk_gated_s), .D (n_44), .Q (CONTROL_PATH_CurrentState[2]));
  DFFRX2 DATA_PATH_C_SF_8_s_reg(.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_C_SF_7_s), .Q (is_nine_s), .QN (UNCONNECTED0));
  DFFRHQX1 DATA_PATH_C_SF_9_s_reg(.RN (n_0), .CK (clk_gated_s), .D
       (is_nine_s), .Q (DATA_PATH_C_SF_9_s));
  DFFRX1 \DATA_PATH_SF_0_s_reg[0] (.RN (n_0), .CK (clk_gated_s), .D
       (n_40), .Q (DATA_PATH_SF_0_s[0]), .QN (UNCONNECTED1));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[1] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[1]), .Q (DATA_PATH_SF_8_s[1]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[2] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[2]), .Q (DATA_PATH_SF_8_s[2]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[3] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[3]), .Q (DATA_PATH_SF_8_s[3]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[4] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[4]), .Q (DATA_PATH_SF_8_s[4]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[5] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[5]), .Q (DATA_PATH_SF_8_s[5]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[6] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[6]), .Q (DATA_PATH_SF_8_s[6]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[7] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[7]), .Q (DATA_PATH_SF_8_s[7]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[8] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[8]), .Q (DATA_PATH_SF_8_s[8]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[9] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[9]), .Q (DATA_PATH_SF_8_s[9]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[10] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[10]), .Q (DATA_PATH_SF_8_s[10]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[11] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[11]), .Q (DATA_PATH_SF_8_s[11]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[12] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[12]), .Q (DATA_PATH_SF_8_s[12]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[13] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[13]), .Q (DATA_PATH_SF_8_s[13]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[14] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[14]), .Q (DATA_PATH_SF_8_s[14]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[15] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[15]), .Q (DATA_PATH_SF_8_s[15]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[16] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[16]), .Q (DATA_PATH_SF_8_s[16]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[17] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[17]), .Q (DATA_PATH_SF_8_s[17]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[18] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[18]), .Q (DATA_PATH_SF_8_s[18]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[19] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[19]), .Q (DATA_PATH_SF_8_s[19]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[20] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[20]), .Q (DATA_PATH_SF_8_s[20]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[21] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[21]), .Q (DATA_PATH_SF_8_s[21]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[22] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[22]), .Q (DATA_PATH_SF_8_s[22]));
  DFFRHQX2 \DATA_PATH_SF_8_s_reg[23] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[23]), .Q (DATA_PATH_SF_8_s[23]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[24] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[24]), .Q (DATA_PATH_SF_8_s[24]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[25] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[25]), .Q (DATA_PATH_SF_8_s[25]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[26] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[26]), .Q (DATA_PATH_SF_8_s[26]));
  DFFRHQX2 \DATA_PATH_SF_8_s_reg[27] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[27]), .Q (DATA_PATH_SF_8_s[27]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[28] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[28]), .Q (DATA_PATH_SF_8_s[28]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[29] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[29]), .Q (DATA_PATH_SF_8_s[29]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[30] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[30]), .Q (DATA_PATH_SF_8_s[30]));
  DFFRHQX4 \DATA_PATH_SF_8_s_reg[31] (.RN (n_0), .CK (clk_gated_s), .D
       (DATA_PATH_SF_7_s[31]), .Q (DATA_PATH_SF_8_s[31]));
  DFFRHQX1 \DATA_PATH_SF_9_s_reg[0] (.RN (n_0), .CK (clk_gated_s), .D
       (n_21), .Q (DATA_PATH_SF_9_s[0]));
  DFFRX2 \DATA_PATH_SF_9_s_reg[1] (.RN (n_0), .CK (clk_gated_s), .D
       (n_31), .Q (DATA_PATH_SF_9_s[1]), .QN (UNCONNECTED2));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[2] (.RN (n_0), .CK (clk_gated_s), .D
       (n_13), .Q (DATA_PATH_SF_9_s[2]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[3] (.RN (n_0), .CK (clk_gated_s), .D
       (n_20), .Q (DATA_PATH_SF_9_s[3]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[4] (.RN (n_0), .CK (clk_gated_s), .D
       (n_19), .Q (DATA_PATH_SF_9_s[4]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[5] (.RN (n_0), .CK (clk_gated_s), .D
       (n_18), .Q (DATA_PATH_SF_9_s[5]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[6] (.RN (n_0), .CK (clk_gated_s), .D
       (n_17), .Q (DATA_PATH_SF_9_s[6]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[7] (.RN (n_0), .CK (clk_gated_s), .D
       (n_16), .Q (DATA_PATH_SF_9_s[7]));
  DFFRHQX2 \DATA_PATH_SF_9_s_reg[8] (.RN (n_0), .CK (clk_gated_s), .D
       (n_15), .Q (DATA_PATH_SF_9_s[8]));
  DFFRHQX2 \DATA_PATH_SF_9_s_reg[9] (.RN (n_0), .CK (clk_gated_s), .D
       (n_14), .Q (DATA_PATH_SF_9_s[9]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[10] (.RN (n_0), .CK (clk_gated_s), .D
       (n_22), .Q (DATA_PATH_SF_9_s[10]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[11] (.RN (n_0), .CK (clk_gated_s), .D
       (n_12), .Q (DATA_PATH_SF_9_s[11]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[12] (.RN (n_0), .CK (clk_gated_s), .D
       (n_11), .Q (DATA_PATH_SF_9_s[12]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[13] (.RN (n_0), .CK (clk_gated_s), .D
       (n_10), .Q (DATA_PATH_SF_9_s[13]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[14] (.RN (n_0), .CK (clk_gated_s), .D
       (n_9), .Q (DATA_PATH_SF_9_s[14]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[15] (.RN (n_0), .CK (clk_gated_s), .D
       (n_8), .Q (DATA_PATH_SF_9_s[15]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[16] (.RN (n_0), .CK (clk_gated_s), .D
       (n_7), .Q (DATA_PATH_SF_9_s[16]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[17] (.RN (n_0), .CK (clk_gated_s), .D
       (n_6), .Q (DATA_PATH_SF_9_s[17]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[18] (.RN (n_0), .CK (clk_gated_s), .D
       (n_5), .Q (DATA_PATH_SF_9_s[18]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[19] (.RN (n_0), .CK (clk_gated_s), .D
       (n_4), .Q (DATA_PATH_SF_9_s[19]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[20] (.RN (n_0), .CK (clk_gated_s), .D
       (n_34), .Q (DATA_PATH_SF_9_s[20]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[21] (.RN (n_0), .CK (clk_gated_s), .D
       (n_33), .Q (DATA_PATH_SF_9_s[21]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[23] (.RN (n_0), .CK (clk_gated_s), .D
       (n_39), .Q (DATA_PATH_SF_9_s[23]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[24] (.RN (n_0), .CK (clk_gated_s), .D
       (n_30), .Q (DATA_PATH_SF_9_s[24]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[25] (.RN (n_0), .CK (clk_gated_s), .D
       (n_29), .Q (DATA_PATH_SF_9_s[25]));
  DFFRHQX2 \DATA_PATH_SF_9_s_reg[26] (.RN (n_0), .CK (clk_gated_s), .D
       (n_28), .Q (DATA_PATH_SF_9_s[26]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[27] (.RN (n_0), .CK (clk_gated_s), .D
       (n_27), .Q (DATA_PATH_SF_9_s[27]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[28] (.RN (n_0), .CK (clk_gated_s), .D
       (n_26), .Q (DATA_PATH_SF_9_s[28]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[29] (.RN (n_0), .CK (clk_gated_s), .D
       (n_25), .Q (DATA_PATH_SF_9_s[29]));
  DFFRHQX2 \DATA_PATH_SF_9_s_reg[30] (.RN (n_0), .CK (clk_gated_s), .D
       (n_24), .Q (DATA_PATH_SF_9_s[30]));
  DFFRHQX4 \DATA_PATH_SF_9_s_reg[31] (.RN (n_0), .CK (clk_gated_s), .D
       (n_23), .Q (DATA_PATH_SF_9_s[31]));
  TLATNXL en_cg_s_reg(.GN (clk), .D (n_3), .Q (en_cg_s), .QN
       (UNCONNECTED3));
  OA21X1 g2402__1617(.A0 (n_355), .A1 (n_43), .B0
       (CONTROL_PATH_CurrentState[1]), .Y (n_44));
  NOR2X1 g2405__2802(.A (n_41), .B (n_36), .Y (n_43));
  MXI2XL g2406__1705(.A (n_355), .B (n_38), .S0
       (CONTROL_PATH_CurrentState[1]), .Y (n_42));
  NAND4XL g2424__5122(.A (DATA_PATH_C_SF_7_s), .B (DATA_PATH_C_SF_4_s),
       .C (DATA_PATH_C_SF_5_s), .D (n_35), .Y (n_41));
  OAI21X4 g2425__8246(.A0 (CONTROL_PATH_CurrentState[1]), .A1 (n_409),
       .B0 (n_37), .Y (n_40));
  MX2X1 g2441__7098(.A (DATA_PATH_SF_9_s[23]), .B
       (DATA_PATH_SF_8_s[23]), .S0 (n_410), .Y (n_39));
  AND2X1 g2443__6131(.A (n_3), .B (is_nine_s), .Y (n_38));
  AOI22X1 g2444__1881(.A0 (DATA_PATH_SF_9_s[0]), .A1 (n_369), .B0
       (DATA_PATH_SF_8_s[0]), .B1 (n_427), .Y (n_37));
  NAND4BX1 g2445__5115(.AN (CONTROL_PATH_CurrentState[0]), .B
       (DATA_PATH_C_SF_6_s), .C (is_nine_s), .D (DATA_PATH_C_SF_9_s),
       .Y (n_36));
  AND4X1 g2446__7482(.A (DATA_PATH_C_SF_3_s), .B (DATA_PATH_C_SF_2_s),
       .C (DATA_PATH_C_SF_1_s), .D (DATA_PATH_C_SF_0_s), .Y (n_35));
  MX2X1 g2447__4733(.A (DATA_PATH_SF_9_s[20]), .B
       (DATA_PATH_SF_8_s[20]), .S0 (n_410), .Y (n_34));
  MX2X1 g2448__6161(.A (DATA_PATH_SF_9_s[21]), .B
       (DATA_PATH_SF_8_s[21]), .S0 (n_410), .Y (n_33));
  MX2X1 g2449__9315(.A (DATA_PATH_SF_9_s[22]), .B
       (DATA_PATH_SF_8_s[22]), .S0 (n_410), .Y (n_32));
  MX2X1 g2450__9945(.A (DATA_PATH_SF_9_s[1]), .B (DATA_PATH_SF_8_s[1]),
       .S0 (n_410), .Y (n_31));
  MX2X1 g2451__2883(.A (DATA_PATH_SF_9_s[24]), .B
       (DATA_PATH_SF_8_s[24]), .S0 (n_410), .Y (n_30));
  MX2X1 g2452__2346(.A (DATA_PATH_SF_9_s[25]), .B
       (DATA_PATH_SF_8_s[25]), .S0 (n_417), .Y (n_29));
  MX2X1 g2453__1666(.A (DATA_PATH_SF_9_s[26]), .B
       (DATA_PATH_SF_8_s[26]), .S0 (n_410), .Y (n_28));
  MX2X1 g2454__7410(.A (DATA_PATH_SF_9_s[27]), .B
       (DATA_PATH_SF_8_s[27]), .S0 (n_410), .Y (n_27));
  MX2X1 g2455__6417(.A (DATA_PATH_SF_9_s[28]), .B
       (DATA_PATH_SF_8_s[28]), .S0 (n_410), .Y (n_26));
  MX2X1 g2456__5477(.A (DATA_PATH_SF_9_s[29]), .B
       (DATA_PATH_SF_8_s[29]), .S0 (n_410), .Y (n_25));
  MX2X1 g2457__2398(.A (DATA_PATH_SF_9_s[30]), .B
       (DATA_PATH_SF_8_s[30]), .S0 (n_410), .Y (n_24));
  MX2X1 g2458__5107(.A (DATA_PATH_SF_9_s[31]), .B
       (DATA_PATH_SF_8_s[31]), .S0 (n_410), .Y (n_23));
  MX2X1 g2460__6260(.A (DATA_PATH_SF_8_s[10]), .B
       (DATA_PATH_SF_9_s[10]), .S0 (n_421), .Y (n_22));
  MX2X1 g2461__4319(.A (DATA_PATH_SF_8_s[0]), .B (DATA_PATH_SF_9_s[0]),
       .S0 (n_421), .Y (n_21));
  MX2X1 g2462__8428(.A (DATA_PATH_SF_8_s[3]), .B (DATA_PATH_SF_9_s[3]),
       .S0 (n_418), .Y (n_20));
  MX2X1 g2463__5526(.A (DATA_PATH_SF_8_s[4]), .B (DATA_PATH_SF_9_s[4]),
       .S0 (n_421), .Y (n_19));
  MX2X1 g2464__6783(.A (DATA_PATH_SF_8_s[5]), .B (DATA_PATH_SF_9_s[5]),
       .S0 (n_418), .Y (n_18));
  MX2X1 g2465__3680(.A (DATA_PATH_SF_8_s[6]), .B (DATA_PATH_SF_9_s[6]),
       .S0 (n_421), .Y (n_17));
  MX2X1 g2466__1617(.A (DATA_PATH_SF_8_s[7]), .B (DATA_PATH_SF_9_s[7]),
       .S0 (n_421), .Y (n_16));
  MX2X1 g2467__2802(.A (DATA_PATH_SF_8_s[8]), .B (DATA_PATH_SF_9_s[8]),
       .S0 (n_421), .Y (n_15));
  MX2X1 g2468__1705(.A (DATA_PATH_SF_8_s[9]), .B (DATA_PATH_SF_9_s[9]),
       .S0 (n_421), .Y (n_14));
  MX2X1 g2469__5122(.A (DATA_PATH_SF_8_s[2]), .B (DATA_PATH_SF_9_s[2]),
       .S0 (n_421), .Y (n_13));
  MX2X1 g2470__8246(.A (DATA_PATH_SF_8_s[11]), .B
       (DATA_PATH_SF_9_s[11]), .S0 (n_421), .Y (n_12));
  MX2X1 g2471__7098(.A (DATA_PATH_SF_8_s[12]), .B
       (DATA_PATH_SF_9_s[12]), .S0 (n_418), .Y (n_11));
  MX2X1 g2472__6131(.A (DATA_PATH_SF_8_s[13]), .B
       (DATA_PATH_SF_9_s[13]), .S0 (n_416), .Y (n_10));
  MX2X1 g2473__1881(.A (DATA_PATH_SF_8_s[14]), .B
       (DATA_PATH_SF_9_s[14]), .S0 (n_418), .Y (n_9));
  MX2X1 g2474__5115(.A (DATA_PATH_SF_8_s[15]), .B
       (DATA_PATH_SF_9_s[15]), .S0 (n_418), .Y (n_8));
  MX2X1 g2475__7482(.A (DATA_PATH_SF_8_s[16]), .B
       (DATA_PATH_SF_9_s[16]), .S0 (n_421), .Y (n_7));
  MX2X1 g2476__4733(.A (DATA_PATH_SF_8_s[17]), .B
       (DATA_PATH_SF_9_s[17]), .S0 (n_418), .Y (n_6));
  MX2X1 g2477__6161(.A (DATA_PATH_SF_8_s[18]), .B
       (DATA_PATH_SF_9_s[18]), .S0 (n_421), .Y (n_5));
  MX2X1 g2478__9315(.A (DATA_PATH_SF_8_s[19]), .B
       (DATA_PATH_SF_9_s[19]), .S0 (n_421), .Y (n_4));
  NAND2BX1 g2496__9945(.AN (CONTROL_PATH_CurrentState[1]), .B (n_319),
       .Y (n_2));
  NAND2X1 g2512__2883(.A (n_358), .B (CONTROL_PATH_CurrentState[0]), .Y
       (n_3));
  INVXL g2517(.A (rst), .Y (n_0));
  BUFX3 fopt(.A (n_356), .Y (n_354));
  CLKBUFX3 fopt1(.A (n_356), .Y (n_355));
  CLKBUFX3 fopt2(.A (n_357), .Y (n_356));
  CLKBUFX3 fopt3(.A (n_358), .Y (n_357));
  CLKBUFX3 fopt4(.A (n_359), .Y (n_358));
  CLKBUFX3 fopt5(.A (ready_o), .Y (n_359));
  BUFX20 fopt6(.A (CONTROL_PATH_CurrentState[2]), .Y (ready_o));
  BUFX12 fopt4594(.A (n_1839_BAR), .Y (n_361));
  BUFX12 fopt4595(.A (n_1839_BAR), .Y (n_369));
  CLKINVX6 fopt4596(.A (data_serial_i[1]), .Y (n_378));
  CLKINVX6 fopt4597(.A (data_serial_i[2]), .Y (n_379));
  CLKINVX6 fopt4598(.A (data_serial_i[3]), .Y (n_380));
  CLKINVX6 fopt4599(.A (data_serial_i[4]), .Y (n_381));
  CLKINVX6 fopt4600(.A (data_serial_i[5]), .Y (n_382));
  CLKINVX6 fopt4601(.A (data_serial_i[6]), .Y (n_383));
  CLKINVX6 fopt4602(.A (data_serial_i[7]), .Y (n_384));
  CLKINVX6 fopt4603(.A (data_serial_i[8]), .Y (n_385));
  CLKINVX6 fopt4604(.A (data_serial_i[9]), .Y (n_386));
  CLKINVX6 fopt4605(.A (data_serial_i[10]), .Y (n_387));
  CLKINVX6 fopt4606(.A (data_serial_i[11]), .Y (n_388));
  CLKINVX6 fopt4607(.A (data_serial_i[12]), .Y (n_389));
  CLKINVX6 fopt4608(.A (data_serial_i[13]), .Y (n_390));
  CLKINVX6 fopt4609(.A (data_serial_i[14]), .Y (n_391));
  CLKINVX6 fopt4610(.A (data_serial_i[15]), .Y (n_392));
  CLKINVX6 fopt4611(.A (data_serial_i[16]), .Y (n_393));
  CLKINVX6 fopt4612(.A (data_serial_i[17]), .Y (n_394));
  CLKINVX6 fopt4613(.A (data_serial_i[18]), .Y (n_395));
  CLKINVX6 fopt4614(.A (data_serial_i[19]), .Y (n_396));
  CLKINVX6 fopt4615(.A (data_serial_i[20]), .Y (n_397));
  CLKINVX6 fopt4616(.A (data_serial_i[21]), .Y (n_398));
  CLKINVX6 fopt4617(.A (data_serial_i[22]), .Y (n_399));
  CLKINVX6 fopt4618(.A (data_serial_i[23]), .Y (n_400));
  CLKINVX6 fopt4619(.A (data_serial_i[24]), .Y (n_401));
  CLKINVX6 fopt4620(.A (data_serial_i[25]), .Y (n_402));
  CLKINVX6 fopt4621(.A (data_serial_i[26]), .Y (n_403));
  CLKINVX6 fopt4622(.A (data_serial_i[27]), .Y (n_404));
  CLKINVX6 fopt4623(.A (data_serial_i[28]), .Y (n_405));
  CLKINVX6 fopt4624(.A (data_serial_i[29]), .Y (n_406));
  CLKINVX6 fopt4625(.A (data_serial_i[30]), .Y (n_407));
  CLKINVX6 fopt4626(.A (data_serial_i[31]), .Y (n_408));
  CLKINVX6 fopt4627(.A (data_serial_i[0]), .Y (n_409));
  CLKINVX8 fopt4628(.A (n_427), .Y (n_410));
  CLKINVX4 fopt4629(.A (n_417), .Y (n_416));
  CLKINVX8 fopt4630(.A (n_417), .Y (n_418));
  CLKINVX6 fopt4631(.A (n_427), .Y (n_417));
  CLKBUFX16 fopt4632(.A (n_427), .Y (n_421));
  CLKINVX6 fopt4633(.A (n_444), .Y (n_427));
  CLKINVX16 fopt4634(.A (n_444), .Y (n_429));
  BUFX6 fopt7(.A (n_190), .Y (n_444));
  DFFRX4 \DATA_PATH_SF_9_s_reg[22] (.RN (n_0), .CK (clk_gated_s), .D
       (n_32), .Q (DATA_PATH_SF_9_s[22]), .QN (UNCONNECTED4));
endmodule

