
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 15 2025 22:23:11 -03 (Sep 16 2025 01:23:11 UTC)

// Verification Directory fv/Square_root 

module DataPath(clk, rst_n, input_i, root_o, ready_o, wr_input_i,
     en_pipe_i, ready_i, mux_root_i, N_o);
  input clk, rst_n, wr_input_i, en_pipe_i, ready_i, mux_root_i;
  input [15:0] input_i;
  output [7:0] root_o;
  output ready_o, N_o;
  wire clk, rst_n, wr_input_i, en_pipe_i, ready_i, mux_root_i;
  wire [15:0] input_i;
  wire [7:0] root_o;
  wire ready_o, N_o;
  wire [16:0] S1_input_ext_s;
  wire [15:0] S1_o_input_s;
  wire [16:0] S1_o_square_s;
  wire [7:0] S1_o_root_s;
  wire [11:0] S2_o_A_s;
  wire [11:0] S2_o_B_s;
  wire [3:0] S2_o_root_s;
  wire [4:0] S2_o_square_s;
  wire [7:0] S3_o_A_s;
  wire [7:0] S3_o_B_s;
  wire [8:0] S3_o_square_s;
  wire [3:0] S4_o_A_s;
  wire [12:0] S4_o_square_s;
  wire [3:0] S2_o_root_h_s;
  wire S1_N_s, S2_o_co_root_s, S2_o_co_square_s, S3_o_co_square_s,
       S4_o_co_square_s, UNCONNECTED, UNCONNECTED0, UNCONNECTED1;
  wire UNCONNECTED2, UNCONNECTED3, UNCONNECTED4, n_0, n_1, n_2, n_3,
       n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_114, n_115, n_116, n_117;
  wire n_118, n_119, n_120, n_121, n_122, n_123, n_124, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_132, n_133;
  wire n_134, n_135, n_136, n_137, n_138, n_139, n_140, n_141;
  wire n_142, n_143, n_144, n_145, n_146, n_147, n_148, n_149;
  wire n_150, n_151, n_153, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_169, n_170, n_171, n_172, n_173, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_180, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_207, n_208, n_209, n_210, n_211, n_212, n_213, n_214;
  wire n_215, n_216, n_217, n_218, n_219, n_220, n_221, n_222;
  wire n_223, n_224, n_225, n_226, n_227, n_228, n_251, n_262;
  wire n_263, n_264, n_265, n_267, n_268, n_269, n_270, n_271;
  wire n_276;
  assign S1_input_ext_s[16] = 1'b0;
  Comparator COMPARATOR(.A_i ({S1_input_ext_s[16], S1_o_input_s[15:1],
       S1_input_ext_s[0]}), .B_i (S1_o_square_s), .A_less_than_B_o
       (S1_N_s));
  DFFSHQX8 PIPELINE_STAGE1_S1_root_reg_Reg_Root_S1_inst_0_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_44), .Q (root_o[0]));
  DFFRHQX8
       \PIPELINE_STAGE1_S1_root_reg_reg_array[1].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_82), .Q (S1_o_root_s[1]));
  DFFRHQX8
       \PIPELINE_STAGE1_S1_root_reg_reg_array[2].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_74), .Q (S1_o_root_s[2]));
  DFFRHQX1
       \PIPELINE_STAGE1_S1_root_reg_reg_array[3].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_69), .Q (n_224));
  DFFRHQX1
       \PIPELINE_STAGE1_S1_root_reg_reg_array[4].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_198), .Q (n_225));
  DFFRHQX1
       \PIPELINE_STAGE1_S1_root_reg_reg_array[5].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_218), .Q (n_226));
  DFFRHQX1
       \PIPELINE_STAGE1_S1_root_reg_reg_array[6].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_222), .Q (n_227));
  DFFRHQX1
       \PIPELINE_STAGE1_S1_root_reg_reg_array[7].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_221), .Q (n_228));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_85), .Q (S1_input_ext_s[0]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_61), .Q (S1_o_input_s[1]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[2].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_59), .Q (S1_o_input_s[2]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_58), .Q (S1_o_input_s[3]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[4].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_57), .Q (S1_o_input_s[4]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[5].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_56), .Q (S1_o_input_s[5]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[6].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_55), .Q (S1_o_input_s[6]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[7].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_54), .Q (S1_o_input_s[7]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[8].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_53), .Q (S1_o_input_s[8]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[9].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_52), .Q (S1_o_input_s[9]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[10].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_51), .Q (S1_o_input_s[10]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[11].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_50), .Q (S1_o_input_s[11]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[12].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_49), .Q (S1_o_input_s[12]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[13].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_48), .Q (S1_o_input_s[13]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[14].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_47), .Q (S1_o_input_s[14]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[15].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_46), .Q (S1_o_input_s[15]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_67), .Q (S1_o_square_s[0]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_65), .Q (S1_o_square_s[1]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[2].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_63), .Q (S1_o_square_s[2]));
  DFFRX1 \PIPELINE_STAGE1_square_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_62), .Q (S1_o_square_s[3]), .QN
       (UNCONNECTED));
  DFFRHQX2 \PIPELINE_STAGE1_square_reg_reg[4].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_134), .Q (S1_o_square_s[4]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[5].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_133), .Q (S1_o_square_s[5]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[6].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_131), .Q (S1_o_square_s[6]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[7].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_129), .Q (S1_o_square_s[7]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[8].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_125), .Q (S1_o_square_s[8]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[9].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_121), .Q (S1_o_square_s[9]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[10].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_118), .Q (S1_o_square_s[10]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[11].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_141), .Q (S1_o_square_s[11]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[12].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_112), .Q (S1_o_square_s[12]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[13].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_175), .Q (S1_o_square_s[13]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[14].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_196), .Q (S1_o_square_s[14]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[15].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_217), .Q (S1_o_square_s[15]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[16].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_223), .Q (S1_o_square_s[16]));
  DFFRHQX1 PIPELINE_STAGE2_N_S2_reg_sig_q_reg(.RN (rst_n), .CK (clk),
       .D (n_100), .Q (N_o));
  DFFRHQX4 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_97), .Q (S2_o_A_s[0]));
  DFFRHQX2 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[2].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_105), .Q (S2_o_A_s[2]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_135), .Q (S2_o_A_s[3]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[4].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_60), .Q (S2_o_A_s[4]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[5].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_84), .Q (S2_o_A_s[5]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[6].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_83), .Q (S2_o_A_s[6]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[7].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_81), .Q (S2_o_A_s[7]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[8].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_80), .Q (S2_o_A_s[8]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[9].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_79), .Q (S2_o_A_s[9]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[10].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_78), .Q (S2_o_A_s[10]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[11].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_77), .Q (S2_o_A_s[11]));
  DFFRHQX4 \PIPELINE_STAGE2_S2_B_high_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_76), .Q (S2_o_B_s[0]));
  DFFRHQX4 \PIPELINE_STAGE2_S2_B_high_reg_reg[2].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_73), .Q (S2_o_B_s[2]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_B_high_reg_reg[5].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_70), .Q (S2_o_B_s[5]));
  DFFRHQX1 PIPELINE_STAGE2_S2_Co_Root_reg_sig_q_reg(.RN (rst_n), .CK
       (clk), .D (n_212), .Q (S2_o_co_root_s));
  DFFSHQX1 PIPELINE_STAGE2_S2_root_reg_Reg_Root_S2_1_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_176), .Q (S2_o_root_s[1]));
  DFFRHQX1 PIPELINE_STAGE2_S2_root_reg_Reg_Root_S2_2_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_195), .Q (S2_o_root_s[2]));
  DFFSHQX1 PIPELINE_STAGE2_square_sum_S2_reg_RegSumLow_0_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_68), .Q (S2_o_square_s[0]));
  DFFRHQX1 PIPELINE_STAGE2_square_sum_S2_reg_RegSumLow_1_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_66), .Q (S2_o_square_s[1]));
  DFFRHQX1 PIPELINE_STAGE2_square_sum_S2_reg_RegSumLow_2_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_64), .Q (S2_o_square_s[2]));
  DFFSHQX1 PIPELINE_STAGE2_square_sum_S2_reg_RegSumLow_3_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_173), .Q (S2_o_square_s[3]));
  DFFRHQX1 PIPELINE_STAGE2_square_sum_S2_reg_RegSumLow_4_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_194), .Q (S2_o_square_s[4]));
  DFFRHQX4 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_132), .Q (S3_o_A_s[0]));
  DFFRHQX4 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_130), .Q (S3_o_A_s[1]));
  DFFRX2 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[2].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_128), .Q (S3_o_A_s[2]), .QN
       (UNCONNECTED0));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_127), .Q (S3_o_A_s[3]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[4].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_126), .Q (S3_o_A_s[4]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[5].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_124), .Q (S3_o_A_s[5]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[6].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_122), .Q (S3_o_A_s[6]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[7].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_120), .Q (S3_o_A_s[7]));
  DFFRHQX4 \PIPELINE_STAGE3_S3_B_high_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_119), .Q (S3_o_B_s[0]));
  DFFRHQX4 \PIPELINE_STAGE3_S3_B_high_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_117), .Q (S3_o_B_s[1]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_0_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_115), .Q (S3_o_square_s[0]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_1_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_114), .Q (S3_o_square_s[1]));
  DFFSHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_2_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_113), .Q (S3_o_square_s[2]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_3_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_111), .Q (S3_o_square_s[3]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_4_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_110), .Q (S3_o_square_s[4]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_5_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_180), .Q (S3_o_square_s[5]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_6_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_197), .Q (S3_o_square_s[6]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_7_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_220), .Q (S3_o_square_s[7]));
  DFFRHQX4 \PIPELINE_STAGE4_S3_A_high_S2_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_108), .Q (S4_o_A_s[0]));
  DFFSHQX8 PIPELINE_STAGE4_S4_ready_reg_sig_q_reg(.SN (rst_n), .CK
       (clk), .D (n_123), .Q (ready_o));
  DFFSHQX1 PIPELINE_STAGE4_square_sum_S4_reg_RegSumLow_0_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_104), .Q (S4_o_square_s[0]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[1].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_140), .Q (S4_o_square_s[1]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[2].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_103), .Q (S4_o_square_s[2]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[3].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_102), .Q (S4_o_square_s[3]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[4].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_101), .Q (S4_o_square_s[4]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[5].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_99), .Q (S4_o_square_s[5]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[6].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_98), .Q (S4_o_square_s[6]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[7].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_96), .Q (S4_o_square_s[7]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[8].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_95), .Q (S4_o_square_s[8]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[9].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_185), .Q (S4_o_square_s[9]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[10].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_215), .Q (S4_o_square_s[10]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[11].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_211), .Q (S4_o_square_s[11]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[12].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_213), .Q (S4_o_square_s[12]));
  MX2X1 g6195__2398(.A (S1_o_square_s[16]), .B (n_216), .S0 (n_11), .Y
       (n_223));
  MXI3X1 g6200__5107(.A (n_92), .B (n_91), .C (n_22), .S0 (n_199), .S1
       (n_19), .Y (n_222));
  MXI3X1 g6201__6260(.A (n_93), .B (n_94), .C (n_17), .S0 (n_200), .S1
       (n_19), .Y (n_221));
  MX3X1 g6207__4319(.A (n_262), .B (n_263), .C (S3_o_square_s[7]), .S0
       (n_190), .S1 (n_19), .Y (n_220));
  OAI22X4 g6208__8428(.A0 (n_19), .A1 (n_210), .B0 (n_10), .B1 (n_11),
       .Y (n_219));
  OAI22X4 g6209__5526(.A0 (n_19), .A1 (n_205), .B0 (n_23), .B1 (n_12),
       .Y (n_218));
  MX2X1 g6210__6783(.A (S1_o_square_s[15]), .B (n_193), .S0 (n_11), .Y
       (n_217));
  XNOR2X1 g6211__3680(.A (n_14), .B (n_184), .Y (n_216));
  MX3XL g6216__1617(.A (n_156), .B (n_86), .C (S4_o_square_s[10]), .S0
       (n_178), .S1 (n_19), .Y (n_215));
  NAND2X4 g6217__2802(.A (n_206), .B (n_202), .Y (n_214));
  NAND2X4 g6218__1705(.A (n_203), .B (n_204), .Y (n_213));
  CLKMX2X3 g6219__5122(.A (S2_o_co_root_s), .B (n_201), .S0 (n_18), .Y
       (n_212));
  OAI2BB1X2 g6221__8246(.A0N (n_181), .A1N (n_187), .B0 (n_186), .Y
       (n_211));
  XNOR2X2 g6226__7098(.A (n_0), .B (n_189), .Y (n_210));
  OAI21X1 g6227__6131(.A0 (n_167), .A1 (n_188), .B0 (n_174), .Y
       (n_209));
  OAI22X2 g6228__1881(.A0 (n_42), .A1 (n_187), .B0 (n_13), .B1 (n_12),
       .Y (n_208));
  MX2X1 g6229__5115(.A (S2_o_co_square_s), .B (n_192), .S0 (n_18), .Y
       (n_207));
  AOI2BB2X4 g6230__7482(.A0N (n_15), .A1N (n_11), .B0 (n_188), .B1
       (n_168), .Y (n_206));
  XNOR2X2 g6231__4733(.A (n_88), .B (n_191), .Y (n_205));
  AOI2BB1X4 g6232__6161(.A0N (n_32), .A1N (n_187), .B0 (n_36), .Y
       (n_204));
  NAND2BX2 g6233__9315(.AN (n_42), .B (n_187), .Y (n_203));
  OR2X4 g6234__9945(.A (n_164), .B (n_188), .Y (n_202));
  OAI21X4 g6235__2883(.A0 (n_0), .A1 (n_183), .B0 (n_137), .Y (n_201));
  AOI2BB2X4 g6237__2346(.A0N (n_269), .A1N (n_138), .B0 (n_160), .B1
       (n_144), .Y (n_200));
  AOI2BB2X4 g6238__1666(.A0N (n_269), .A1N (n_40), .B0 (n_160), .B1
       (n_89), .Y (n_199));
  MX2X1 g6239__7410(.A (root_o[4]), .B (n_170), .S0 (n_18), .Y (n_198));
  MX2X1 g6240__6417(.A (S3_o_square_s[6]), .B (n_172), .S0 (n_11), .Y
       (n_197));
  MX2X1 g6241__5477(.A (S1_o_square_s[14]), .B (n_2), .S0 (n_11), .Y
       (n_196));
  MX2X1 g6242__2398(.A (S2_o_root_s[2]), .B (n_169), .S0 (n_11), .Y
       (n_195));
  MX2X1 g6243__5107(.A (S2_o_square_s[4]), .B (n_171), .S0 (n_11), .Y
       (n_194));
  CLKXOR2X1 g6244__6260(.A (S4_o_A_s[2]), .B (n_159), .Y (n_193));
  AO21X1 g6245__4319(.A0 (n_24), .A1 (n_90), .B0 (n_29), .Y (n_192));
  NOR2X4 g6246__8428(.A (n_147), .B (n_160), .Y (n_191));
  AOI21X2 g6248__5526(.A0 (n_142), .A1 (n_145), .B0 (n_27), .Y (n_190));
  NOR2X8 g6249__6783(.A (n_148), .B (n_162), .Y (n_189));
  AOI21X2 g6250__3680(.A0 (S4_o_square_s[11]), .A1 (n_19), .B0 (n_3),
       .Y (n_186));
  MX2X1 g6251__1617(.A (S4_o_square_s[9]), .B (n_157), .S0 (n_18), .Y
       (n_185));
  CLKAND2X2 g6252__2802(.A (S4_o_A_s[2]), .B (n_159), .Y (n_184));
  NOR2X6 g6253__1705(.A (n_179), .B (n_182), .Y (n_188));
  OAI21X4 g6254__5122(.A0 (n_161), .A1 (n_177), .B0 (S3_o_A_s[2]), .Y
       (n_187));
  INVX2 g6255(.A (n_162), .Y (n_183));
  AOI21X4 g6257__8246(.A0 (n_153), .A1 (n_165), .B0 (n_264), .Y
       (n_182));
  OA21X1 g6260__7098(.A0 (S3_o_A_s[2]), .A1 (n_161), .B0 (en_pipe_i),
       .Y (n_181));
  MX2X1 g6261__6131(.A (S3_o_square_s[5]), .B (n_158), .S0 (n_11), .Y
       (n_180));
  OAI21X4 g6262__1881(.A0 (n_166), .A1 (n_163), .B0 (n_151), .Y
       (n_179));
  OAI21X2 g6264__5115(.A0 (n_6), .A1 (n_1), .B0 (n_28), .Y (n_178));
  MX2X1 g6266__7482(.A (S2_o_root_s[1]), .B (n_43), .S0 (n_20), .Y
       (n_176));
  MX2X1 g6267__4733(.A (S1_o_square_s[13]), .B (n_45), .S0 (n_11), .Y
       (n_175));
  MX2X1 g6268__6161(.A (n_6), .B (n_149), .S0 (en_pipe_i), .Y (n_174));
  MX2X1 g6269__9315(.A (S2_o_square_s[3]), .B (n_136), .S0 (n_11), .Y
       (n_173));
  OAI21X2 g6270__9945(.A0 (n_28), .A1 (n_86), .B0 (n_4), .Y (n_177));
  CLKXOR2X1 g6272__2883(.A (n_142), .B (n_145), .Y (n_172));
  CLKXOR2X1 g6273__2346(.A (n_24), .B (n_90), .Y (n_171));
  CLKXOR2X1 g6274__1666(.A (n_154), .B (S2_o_co_root_s), .Y (n_170));
  CLKXOR2X1 g6275__7410(.A (n_25), .B (n_155), .Y (n_169));
  INVX2 g6276(.A (n_167), .Y (n_168));
  NAND2X4 g6277__6417(.A (S2_o_co_square_s), .B (n_87), .Y (n_166));
  NAND2X4 g6278__5477(.A (n_39), .B (n_142), .Y (n_165));
  OR2X1 g6279__2398(.A (n_150), .B (n_21), .Y (n_164));
  NAND2X4 g6280__5107(.A (n_143), .B (n_142), .Y (n_163));
  NAND2X4 g6281__6260(.A (en_pipe_i), .B (n_150), .Y (n_167));
  CLKXOR2X1 g6282__4319(.A (S2_o_co_square_s), .B (n_143), .Y (n_158));
  XNOR2X1 g6283__8428(.A (S3_o_co_square_s), .B (n_1), .Y (n_157));
  CLKAND2X6 g6284__5526(.A (n_25), .B (n_155), .Y (n_162));
  CLKAND2X6 g6285__6783(.A (n_139), .B (n_156), .Y (n_161));
  CLKAND2X6 g6286__3680(.A (S2_o_co_root_s), .B (n_154), .Y (n_160));
  NOR2X4 g6287__1617(.A (n_9), .B (n_26), .Y (n_159));
  INVX2 g6288(.A (n_86), .Y (n_156));
  INVX1 g6290(.A (n_27), .Y (n_153));
  INVX1 g6292(.A (n_30), .Y (n_151));
  INVX1 g6293(.A (n_146), .Y (n_149));
  ADDHX2 g6294__2802(.A (S1_o_root_s[2]), .B (mux_root_i), .CO (n_148),
       .S (n_155));
  ADDHX2 g6295__1705(.A (S2_o_B_s[2]), .B (mux_root_i), .CO (n_147), .S
       (n_154));
  ADDHX1 g6296__5122(.A (S2_o_B_s[3]), .B (S2_o_A_s[3]), .CO (n_146),
       .S (n_150));
  CLKAND2X6 g6355__8246(.A (n_92), .B (n_89), .Y (n_144));
  OAI21X4 g6371__7098(.A0 (n_7), .A1 (n_31), .B0 (n_38), .Y (n_145));
  MX2X1 g6383__6131(.A (S1_o_square_s[11]), .B (S4_o_square_s[11]), .S0
       (n_20), .Y (n_141));
  MX2X1 g6384__1881(.A (S4_o_square_s[1]), .B (S3_o_square_s[1]), .S0
       (n_20), .Y (n_140));
  NOR2X2 g6385__5115(.A (n_6), .B (n_41), .Y (n_139));
  AND2X1 g6386__7482(.A (n_8), .B (n_40), .Y (n_138));
  OAI21X1 g6387__4733(.A0 (n_251), .A1 (root_o[3]), .B0 (n_270), .Y
       (n_137));
  OAI2BB1X1 g6388__6161(.A0N (S1_o_square_s[3]), .A1N (root_o[0]), .B0
       (n_24), .Y (n_136));
  MX2X1 g6389__9315(.A (S2_o_A_s[3]), .B (S1_o_square_s[8]), .S0
       (n_18), .Y (n_135));
  MX2X1 g6390__9945(.A (S1_o_square_s[4]), .B (S4_o_square_s[4]), .S0
       (n_18), .Y (n_134));
  MX2X1 g6391__2883(.A (S1_o_square_s[5]), .B (S4_o_square_s[5]), .S0
       (n_18), .Y (n_133));
  MX2X1 g6392__2346(.A (S3_o_A_s[0]), .B (S2_o_A_s[4]), .S0 (n_12), .Y
       (n_132));
  MX2X1 g6393__1666(.A (S1_o_square_s[6]), .B (S4_o_square_s[6]), .S0
       (n_20), .Y (n_131));
  MX2X1 g6394__7410(.A (S3_o_A_s[1]), .B (S2_o_A_s[5]), .S0 (n_18), .Y
       (n_130));
  MX2X1 g6395__6417(.A (S1_o_square_s[7]), .B (S4_o_square_s[7]), .S0
       (n_11), .Y (n_129));
  MX2X1 g6396__5477(.A (S3_o_A_s[2]), .B (S2_o_A_s[6]), .S0 (n_12), .Y
       (n_128));
  MX2X1 g6397__2398(.A (S3_o_A_s[3]), .B (S2_o_A_s[7]), .S0 (n_18), .Y
       (n_127));
  MX2X1 g6398__5107(.A (S3_o_A_s[4]), .B (S2_o_A_s[8]), .S0 (n_18), .Y
       (n_126));
  MX2X1 g6399__6260(.A (S1_o_square_s[8]), .B (S4_o_square_s[8]), .S0
       (n_20), .Y (n_125));
  MX2X1 g6400__4319(.A (S3_o_A_s[5]), .B (S2_o_A_s[9]), .S0 (n_20), .Y
       (n_124));
  MX2X1 g6401__8428(.A (ready_o), .B (ready_i), .S0 (n_12), .Y (n_123));
  MX2X1 g6402__5526(.A (S3_o_A_s[6]), .B (S2_o_A_s[10]), .S0 (n_20), .Y
       (n_122));
  MX2X1 g6403__6783(.A (S1_o_square_s[9]), .B (S4_o_square_s[9]), .S0
       (n_20), .Y (n_121));
  MX2X1 g6404__3680(.A (S3_o_A_s[7]), .B (S2_o_A_s[11]), .S0 (n_20), .Y
       (n_120));
  MX2X1 g6405__1617(.A (S3_o_B_s[0]), .B (S2_o_root_h_s[2]), .S0
       (n_18), .Y (n_119));
  MX2X1 g6406__2802(.A (S1_o_square_s[10]), .B (S4_o_square_s[10]), .S0
       (n_11), .Y (n_118));
  MX2X1 g6407__1705(.A (S3_o_B_s[1]), .B (S2_o_B_s[5]), .S0 (n_18), .Y
       (n_117));
  MX2X1 g6408__5122(.A (S2_o_A_s[1]), .B (S1_o_square_s[6]), .S0
       (n_18), .Y (n_116));
  MX2X1 g6409__8246(.A (S3_o_square_s[0]), .B (S2_o_square_s[0]), .S0
       (n_20), .Y (n_115));
  MX2X1 g6410__7098(.A (S3_o_square_s[1]), .B (S2_o_square_s[1]), .S0
       (n_18), .Y (n_114));
  MX2X1 g6411__6131(.A (S3_o_square_s[2]), .B (S2_o_square_s[2]), .S0
       (n_20), .Y (n_113));
  MX2X1 g6412__1881(.A (S1_o_square_s[12]), .B (S4_o_square_s[12]), .S0
       (n_11), .Y (n_112));
  MX2X1 g6413__5115(.A (S3_o_square_s[3]), .B (S2_o_square_s[3]), .S0
       (n_11), .Y (n_111));
  MX2X1 g6414__7482(.A (S3_o_square_s[4]), .B (S2_o_square_s[4]), .S0
       (n_11), .Y (n_110));
  MX2X1 g6415__4733(.A (S4_o_A_s[3]), .B (S3_o_A_s[7]), .S0 (n_11), .Y
       (n_109));
  MX2X1 g6416__6161(.A (S4_o_A_s[0]), .B (S3_o_A_s[4]), .S0 (n_18), .Y
       (n_108));
  MX2X1 g6417__9315(.A (S4_o_A_s[1]), .B (S3_o_A_s[5]), .S0 (n_18), .Y
       (n_107));
  MX2X1 g6418__9945(.A (S4_o_A_s[2]), .B (S3_o_A_s[6]), .S0 (n_12), .Y
       (n_106));
  MX2X1 g6419__2883(.A (S2_o_A_s[2]), .B (S1_o_square_s[7]), .S0
       (n_18), .Y (n_105));
  MX2X1 g6420__2346(.A (S4_o_square_s[0]), .B (S3_o_square_s[0]), .S0
       (n_11), .Y (n_104));
  MX2X1 g6421__1666(.A (S4_o_square_s[2]), .B (S3_o_square_s[2]), .S0
       (n_11), .Y (n_103));
  MX2X1 g6422__7410(.A (S4_o_square_s[3]), .B (S3_o_square_s[3]), .S0
       (n_20), .Y (n_102));
  MX2X1 g6423__6417(.A (S4_o_square_s[4]), .B (S3_o_square_s[4]), .S0
       (n_11), .Y (n_101));
  MX2X1 g6424__5477(.A (N_o), .B (S1_N_s), .S0 (n_20), .Y (n_100));
  MX2X1 g6425__2398(.A (S4_o_square_s[5]), .B (S3_o_square_s[5]), .S0
       (n_20), .Y (n_99));
  MX2X1 g6426__5107(.A (S4_o_square_s[6]), .B (S3_o_square_s[6]), .S0
       (n_11), .Y (n_98));
  MX2X1 g6427__6260(.A (S2_o_A_s[0]), .B (S1_o_square_s[5]), .S0
       (n_18), .Y (n_97));
  MX2X1 g6428__4319(.A (S4_o_square_s[7]), .B (S3_o_square_s[7]), .S0
       (n_18), .Y (n_96));
  MX2X1 g6429__8428(.A (S4_o_square_s[8]), .B (S3_o_square_s[8]), .S0
       (n_20), .Y (n_95));
  NOR2X4 g6430__5526(.A (n_31), .B (n_39), .Y (n_143));
  NOR2X6 g6432__6783(.A (n_35), .B (n_27), .Y (n_142));
  INVX2 g6433(.A (n_93), .Y (n_94));
  INVX1 g6434(.A (n_92), .Y (n_91));
  INVX1 g6435(.A (n_89), .Y (n_88));
  MX2X1 g6436__3680(.A (S1_input_ext_s[0]), .B (input_i[0]), .S0
       (wr_input_i), .Y (n_85));
  MX2X1 g6437__1617(.A (S2_o_A_s[5]), .B (S1_o_square_s[10]), .S0
       (n_11), .Y (n_84));
  MX2X1 g6438__2802(.A (S2_o_A_s[6]), .B (S1_o_square_s[11]), .S0
       (n_18), .Y (n_83));
  MX2X1 g6439__1705(.A (root_o[1]), .B (S2_o_root_s[1]), .S0 (n_18), .Y
       (n_82));
  MX2X1 g6440__5122(.A (S2_o_A_s[7]), .B (S1_o_square_s[12]), .S0
       (n_11), .Y (n_81));
  MX2X1 g6441__8246(.A (S2_o_A_s[8]), .B (S1_o_square_s[13]), .S0
       (n_11), .Y (n_80));
  MX2X1 g6442__7098(.A (S2_o_A_s[9]), .B (S1_o_square_s[14]), .S0
       (n_11), .Y (n_79));
  MX2X1 g6443__6131(.A (S2_o_A_s[10]), .B (S1_o_square_s[15]), .S0
       (n_11), .Y (n_78));
  MX2X1 g6444__1881(.A (S2_o_A_s[11]), .B (S1_o_square_s[16]), .S0
       (n_18), .Y (n_77));
  MX2X1 g6445__5115(.A (S2_o_B_s[0]), .B (root_o[2]), .S0 (n_18), .Y
       (n_76));
  MX2X1 g6446__7482(.A (S2_o_B_s[1]), .B (root_o[3]), .S0 (n_18), .Y
       (n_75));
  MX2X1 g6447__4733(.A (root_o[2]), .B (S2_o_root_s[2]), .S0 (n_18), .Y
       (n_74));
  MX2X1 g6448__6161(.A (S2_o_B_s[2]), .B (root_o[4]), .S0 (n_12), .Y
       (n_73));
  MX2X1 g6449__9315(.A (S2_o_B_s[3]), .B (root_o[5]), .S0 (n_18), .Y
       (n_72));
  MX2X1 g6450__9945(.A (S2_o_root_h_s[2]), .B (root_o[6]), .S0 (n_18),
       .Y (n_71));
  MX2X1 g6451__2883(.A (S2_o_B_s[5]), .B (root_o[7]), .S0 (n_18), .Y
       (n_70));
  MX2X1 g6452__2346(.A (root_o[3]), .B (S2_o_root_s[3]), .S0 (n_18), .Y
       (n_69));
  MX2X1 g6453__1666(.A (S2_o_square_s[0]), .B (S1_o_square_s[0]), .S0
       (n_12), .Y (n_68));
  MX2X1 g6454__7410(.A (S1_o_square_s[0]), .B (S4_o_square_s[0]), .S0
       (n_20), .Y (n_67));
  MX2X1 g6455__6417(.A (S2_o_square_s[1]), .B (S1_o_square_s[1]), .S0
       (n_11), .Y (n_66));
  MX2X1 g6456__5477(.A (S1_o_square_s[1]), .B (S4_o_square_s[1]), .S0
       (n_18), .Y (n_65));
  MX2X1 g6457__2398(.A (S2_o_square_s[2]), .B (S1_o_square_s[2]), .S0
       (n_18), .Y (n_64));
  MX2X1 g6458__5107(.A (S1_o_square_s[2]), .B (S4_o_square_s[2]), .S0
       (n_18), .Y (n_63));
  MX2X1 g6459__6260(.A (S1_o_square_s[3]), .B (S4_o_square_s[3]), .S0
       (n_12), .Y (n_62));
  MX2X1 g6460__4319(.A (S1_o_input_s[1]), .B (input_i[1]), .S0
       (wr_input_i), .Y (n_61));
  MX2X1 g6461__8428(.A (S2_o_A_s[4]), .B (S1_o_square_s[9]), .S0
       (n_11), .Y (n_60));
  MX2X1 g6462__5526(.A (S1_o_input_s[2]), .B (input_i[2]), .S0
       (wr_input_i), .Y (n_59));
  MX2X1 g6463__6783(.A (S1_o_input_s[3]), .B (input_i[3]), .S0
       (wr_input_i), .Y (n_58));
  MX2X1 g6464__3680(.A (S1_o_input_s[4]), .B (input_i[4]), .S0
       (wr_input_i), .Y (n_57));
  MX2X1 g6465__1617(.A (S1_o_input_s[5]), .B (input_i[5]), .S0
       (wr_input_i), .Y (n_56));
  MX2X1 g6466__2802(.A (S1_o_input_s[6]), .B (input_i[6]), .S0
       (wr_input_i), .Y (n_55));
  MX2X1 g6467__1705(.A (S1_o_input_s[7]), .B (input_i[7]), .S0
       (wr_input_i), .Y (n_54));
  MX2X1 g6468__5122(.A (S1_o_input_s[8]), .B (input_i[8]), .S0
       (wr_input_i), .Y (n_53));
  MX2X1 g6469__8246(.A (S1_o_input_s[9]), .B (input_i[9]), .S0
       (wr_input_i), .Y (n_52));
  MX2X1 g6470__7098(.A (S1_o_input_s[10]), .B (input_i[10]), .S0
       (wr_input_i), .Y (n_51));
  MX2X1 g6471__6131(.A (S1_o_input_s[11]), .B (input_i[11]), .S0
       (wr_input_i), .Y (n_50));
  MX2X1 g6472__1881(.A (S1_o_input_s[12]), .B (input_i[12]), .S0
       (wr_input_i), .Y (n_49));
  MX2X1 g6473__5115(.A (S1_o_input_s[13]), .B (input_i[13]), .S0
       (wr_input_i), .Y (n_48));
  MX2X1 g6474__7482(.A (S1_o_input_s[14]), .B (input_i[14]), .S0
       (wr_input_i), .Y (n_47));
  MX2X1 g6475__4733(.A (S1_o_input_s[15]), .B (input_i[15]), .S0
       (wr_input_i), .Y (n_46));
  XNOR2X1 g6476__6161(.A (S4_o_A_s[0]), .B (n_13), .Y (n_45));
  XNOR2X1 g6477__9315(.A (root_o[0]), .B (n_19), .Y (n_44));
  XNOR2X1 g6478__9945(.A (n_276), .B (n_268), .Y (n_43));
  XNOR2X2 g6479__2883(.A (S2_o_B_s[5]), .B (n_267), .Y (n_93));
  CLKMX2X3 g6480__2346(.A (S2_o_root_h_s[2]), .B (n_8), .S0
       (mux_root_i), .Y (n_92));
  AOI2BB1X4 g6482__1666(.A0N (S1_o_square_s[4]), .A1N (S1_o_root_s[1]),
       .B0 (n_29), .Y (n_90));
  CLKMX2X3 g6483__7410(.A (S2_o_B_s[3]), .B (n_5), .S0 (mux_root_i), .Y
       (n_89));
  NOR2X4 g6484__6417(.A (n_37), .B (n_30), .Y (n_87));
  NAND2X8 g6485__5477(.A (n_4), .B (n_33), .Y (n_86));
  INVX3 g6487(.A (n_38), .Y (n_39));
  NOR2X2 g6488__2398(.A (S2_o_A_s[2]), .B (S2_o_B_s[2]), .Y (n_37));
  AND2X1 g6489__5107(.A (n_19), .B (S4_o_square_s[12]), .Y (n_36));
  NOR2X2 g6490__6260(.A (S2_o_B_s[1]), .B (S2_o_A_s[1]), .Y (n_35));
  NAND2BX2 g6491__4319(.AN (S3_o_A_s[2]), .B (en_pipe_i), .Y (n_34));
  OR2X6 g6492__8428(.A (S3_o_B_s[1]), .B (S3_o_A_s[1]), .Y (n_33));
  OR2X1 g6493__5526(.A (S3_o_A_s[3]), .B (n_21), .Y (n_32));
  NAND2X2 g6494__6783(.A (S3_o_A_s[3]), .B (en_pipe_i), .Y (n_42));
  NOR2X2 g6495__3680(.A (S3_o_B_s[0]), .B (S3_o_A_s[0]), .Y (n_41));
  NOR2X4 g6496__1617(.A (S2_o_B_s[2]), .B (S2_o_B_s[3]), .Y (n_40));
  NAND2X4 g6497__2802(.A (S2_o_B_s[0]), .B (S2_o_A_s[0]), .Y (n_38));
  NOR2X4 g6500__1705(.A (S2_o_B_s[0]), .B (S2_o_A_s[0]), .Y (n_31));
  CLKAND2X3 g6501__5122(.A (S2_o_A_s[2]), .B (S2_o_B_s[2]), .Y (n_30));
  AND2X4 g6502__8246(.A (S1_o_square_s[4]), .B (S1_o_root_s[1]), .Y
       (n_29));
  NAND2X4 g6503__7098(.A (S3_o_B_s[0]), .B (S3_o_A_s[0]), .Y (n_28));
  CLKAND2X3 g6504__6131(.A (S2_o_B_s[1]), .B (S2_o_A_s[1]), .Y (n_27));
  NAND2X4 g6505__1881(.A (S4_o_A_s[0]), .B (S4_o_co_square_s), .Y
       (n_26));
  OR2X6 g6507__5115(.A (S1_o_square_s[3]), .B (root_o[0]), .Y (n_24));
  INVX1 g6509(.A (root_o[5]), .Y (n_23));
  INVX1 g6511(.A (root_o[6]), .Y (n_22));
  INVX3 g6513(.A (en_pipe_i), .Y (n_21));
  CLKBUFX3 g6515(.A (en_pipe_i), .Y (n_12));
  CLKINVX8 g6517(.A (n_19), .Y (n_20));
  CLKINVX16 g6518(.A (n_19), .Y (n_18));
  CLKINVX16 g6522(.A (n_19), .Y (n_11));
  CLKINVX16 g6524(.A (en_pipe_i), .Y (n_19));
  INVX1 g6526(.A (root_o[7]), .Y (n_17));
  DFFRX1 PIPELINE_STAGE2_Co_Square_S2_reg_sig_q_reg(.RN (rst_n), .CK
       (clk), .D (n_207), .Q (S2_o_co_square_s), .QN (n_7));
  DFFRX2 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_116), .Q (S2_o_A_s[1]), .QN
       (UNCONNECTED1));
  DFFRX2 \PIPELINE_STAGE2_S2_B_high_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_75), .Q (S2_o_B_s[1]), .QN
       (UNCONNECTED2));
  DFFRX2 \PIPELINE_STAGE2_S2_B_high_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_72), .Q (S2_o_B_s[3]), .QN (n_5));
  DFFRX2 \PIPELINE_STAGE2_S2_B_high_reg_reg[4].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_71), .Q (S2_o_root_h_s[2]), .QN (n_8));
  DFFRXL PIPELINE_STAGE2_S2_root_reg_Reg_Root_S2_3_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_219), .Q (S2_o_root_s[3]), .QN (n_10));
  DFFRX4 PIPELINE_STAGE3_Co_Square_S3_reg_sig_q_reg(.RN (rst_n), .CK
       (clk), .D (n_209), .Q (S3_o_co_square_s), .QN (n_6));
  DFFRX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_8_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_214), .Q (S3_o_square_s[8]), .QN
       (n_15));
  DFFRX2 PIPELINE_STAGE4_Co_Square_S4_reg_sig_q_reg(.RN (rst_n), .CK
       (clk), .D (n_208), .Q (S4_o_co_square_s), .QN (n_13));
  DFFRX1 \PIPELINE_STAGE4_S3_A_high_S2_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_107), .Q (S4_o_A_s[1]), .QN (n_9));
  DFFRHQX1 \PIPELINE_STAGE4_S3_A_high_S2_reg_reg[2].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_106), .Q (S4_o_A_s[2]));
  DFFRX1 \PIPELINE_STAGE4_S3_A_high_S2_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_109), .Q (S4_o_A_s[3]), .QN (n_14));
  NAND2X6 g6540__7482(.A (S3_o_B_s[1]), .B (S3_o_A_s[1]), .Y (n_4));
  NOR2BX2 g2__4733(.AN (n_177), .B (n_34), .Y (n_3));
  XNOR2X1 g6559__6161(.A (S4_o_A_s[1]), .B (n_26), .Y (n_2));
  NAND2BX4 g6560__9315(.AN (n_41), .B (n_28), .Y (n_1));
  BUFX20 g6568(.A (n_224), .Y (root_o[3]));
  BUFX8 g6569(.A (n_225), .Y (root_o[4]));
  BUFX8 g6570(.A (n_226), .Y (root_o[5]));
  BUFX8 g6571(.A (n_227), .Y (root_o[6]));
  BUFX8 g6572(.A (n_228), .Y (root_o[7]));
  ADDHX4 g6574__9945(.A (n_267), .B (S1_o_root_s[1]), .CO (n_25), .S
       (UNCONNECTED3));
  BUFX6 fopt(.A (n_251), .Y (root_o[2]));
  BUFX6 fopt1(.A (S1_o_root_s[2]), .Y (n_251));
  CLKINVX6 fopt6577(.A (n_263), .Y (n_262));
  BUFX6 fopt6578(.A (n_265), .Y (n_263));
  CLKINVX4 fopt6579(.A (n_265), .Y (n_264));
  BUFX6 fopt6580(.A (n_87), .Y (n_265));
  ADDHX2 g6582__2883(.A (n_267), .B (root_o[3]), .CO (UNCONNECTED4), .S
       (n_0));
  CLKINVX2 fopt6583(.A (n_269), .Y (n_268));
  BUFX6 fopt6584(.A (n_271), .Y (n_269));
  CLKINVX4 fopt6(.A (n_271), .Y (n_270));
  BUFX6 fopt7(.A (n_267), .Y (n_271));
  CLKINVX6 fopt8(.A (mux_root_i), .Y (n_267));
  BUFX6 fopt6585(.A (n_276), .Y (root_o[1]));
  BUFX6 fopt6586(.A (S1_o_root_s[1]), .Y (n_276));
endmodule

module Square_root(valor_i, clk, rst_n, ready_o, root_o);
  input [15:0] valor_i;
  input clk, rst_n;
  output ready_o;
  output [7:0] root_o;
  wire [15:0] valor_i;
  wire clk, rst_n;
  wire ready_o;
  wire [7:0] root_o;
  wire [2:0] CONTROL_PATH_CurrentState;
  wire N_s, en_pipe_s, mux_root_s, n_0, n_1, n_2, n_3, n_5;
  wire n_6, n_7, n_13, n_14, n_41, n_42, n_43, n_44;
  wire n_45, ready_s, wr_input_s;
  DataPath DATA_PATH(.clk (clk), .rst_n (rst_n), .input_i (valor_i),
       .root_o ({root_o[7:3], n_13, n_14, root_o[0]}), .ready_o
       (ready_o), .wr_input_i (wr_input_s), .en_pipe_i (en_pipe_s),
       .ready_i (ready_s), .mux_root_i (mux_root_s), .N_o (N_s));
  OR2X6 g92__2346(.A (CONTROL_PATH_CurrentState[0]), .B (n_6), .Y
       (en_pipe_s));
  OR2X1 g93__1666(.A (CONTROL_PATH_CurrentState[2]), .B
       (CONTROL_PATH_CurrentState[0]), .Y (ready_s));
  NOR2X4 g94__7410(.A (CONTROL_PATH_CurrentState[2]), .B (n_45), .Y
       (n_6));
  DFFRHQX2 \CONTROL_PATH_CurrentState_reg[2] (.RN (rst_n), .CK (clk),
       .D (n_5), .Q (CONTROL_PATH_CurrentState[2]));
  INVX1 g96(.A (n_5), .Y (n_7));
  NOR2X1 g97__6417(.A (CONTROL_PATH_CurrentState[0]), .B (n_44), .Y
       (n_5));
  AND2X4 g98__5477(.A (n_44), .B (n_3), .Y (wr_input_s));
  INVX1 g100(.A (CONTROL_PATH_CurrentState[0]), .Y (n_3));
  DFFRHQX4 \CONTROL_PATH_CurrentState_reg[1] (.RN (rst_n), .CK (clk),
       .D (n_2), .Q (mux_root_s));
  OAI21X1 g102__2398(.A0 (CONTROL_PATH_CurrentState[2]), .A1 (n_1), .B0
       (n_7), .Y (n_2));
  DFFRHQX2 \CONTROL_PATH_CurrentState_reg[0] (.RN (rst_n), .CK (clk),
       .D (n_0), .Q (CONTROL_PATH_CurrentState[0]));
  AOI21X1 g104__5107(.A0 (CONTROL_PATH_CurrentState[0]), .A1 (N_s), .B0
       (n_42), .Y (n_1));
  NOR2X1 g105__6260(.A (n_41), .B (CONTROL_PATH_CurrentState[2]), .Y
       (n_0));
  CLKBUFX20 fopt(.A (n_13), .Y (root_o[2]));
  CLKINVX2 fopt107(.A (n_43), .Y (n_41));
  CLKINVX6 fopt4(.A (n_43), .Y (n_42));
  BUFX6 fopt5(.A (n_44), .Y (n_43));
  BUFX6 fopt6(.A (n_45), .Y (n_44));
  CLKINVX8 fopt7(.A (mux_root_s), .Y (n_45));
  CLKBUFX20 fopt108(.A (n_14), .Y (root_o[1]));
endmodule

