
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 11 2025 00:27:44 -03 (Sep 11 2025 03:27:44 UTC)

// Verification Directory fv/Square_root 

module Square_root(valor_i, clk, rst_n, ready_o, root_o);
  input [15:0] valor_i;
  input clk, rst_n;
  output ready_o;
  output [7:0] root_o;
  wire [15:0] valor_i;
  wire clk, rst_n;
  wire ready_o;
  wire [7:0] root_o;
  wire [8:0] DATA_PATH_S2_o_square_adder_sum_l_s;
  wire [16:0] DATA_PATH_S1_o_square_s;
  wire [7:0] DATA_PATH_S1_o_root_s;
  wire [7:0] DATA_PATH_S2_o_A_high_s;
  wire [15:0] DATA_PATH_S1_o_input_s;
  wire [7:0] DATA_PATH_S2_o_B_high_s;
  wire DATA_PATH_S2_o_square_adder_co_l_s, N_s, UNCONNECTED,
       UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, UNCONNECTED3,
       UNCONNECTED4;
  wire UNCONNECTED5, UNCONNECTED6, UNCONNECTED7, en_pipe_s, mux_root_s,
       n_0, n_1, n_2;
  wire n_4, n_5, n_6, n_7, n_10, n_11, n_12, n_14;
  wire n_16, n_17, n_18, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_32, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_43, n_45;
  wire n_46, n_47, n_48, n_50, n_51, n_52, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_83, n_84, n_85, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_98;
  wire n_99, n_100, n_101, n_102, n_103, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_144, n_145, n_146, n_147, n_148, n_149;
  wire n_150, n_151, n_152, n_153, n_154, n_155, n_156, n_157;
  wire n_158, n_159, n_160, n_161, n_162, n_163, n_164, n_165;
  wire n_166, n_167, n_168, n_169, n_170, n_171, n_172, n_173;
  wire n_174, n_175, n_176, n_177, n_178, n_179, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_238, n_239;
  wire n_240, n_241, n_242, n_243, n_244, n_245, n_246, n_247;
  wire n_248, n_249, n_250, n_251, n_252, n_253, n_254, n_255;
  wire n_256, n_257, n_258, n_259, n_260, n_279, n_280, n_282;
  wire n_283, n_284, n_286, n_287, n_289, n_290, n_292, n_307;
  wire n_322, n_323, n_325, n_326, n_328, n_329, n_330, n_331;
  wire n_335, n_336, n_337, n_338, n_339, n_340, n_341, n_342;
  wire n_344, n_346, n_348, n_349, n_351, n_352, n_353, n_355;
  wire n_357, n_358, n_359, n_361, n_362, n_363, n_364, n_365;
  wire n_366, n_367, n_368, n_369;
  DFFRHQX2 DATA_PATH_PIPELINE_STAGE2_Co_reg_sig_q_reg(.RN (rst_n), .CK
       (clk), .D (n_260), .Q (DATA_PATH_S2_o_square_adder_co_l_s));
  DFFRHQX1 DATA_PATH_PIPELINE_STAGE2_N_reg_sig_q_reg(.RN (rst_n), .CK
       (clk), .D (n_259), .Q (N_s));
  OAI22X4 g6180__2398(.A0 (n_40), .A1 (n_254), .B0 (n_366), .B1
       (n_249), .Y (n_260));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg_array[8].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_258), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[8]));
  CLKMX2X3 g6196__5107(.A (N_s), .B (n_255), .S0 (n_256), .Y (n_259));
  DFFRHQX8 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_257), .Q (root_o[7]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg_array[7].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_248), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[7]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[16].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_252), .Q
       (DATA_PATH_S1_o_square_s[16]));
  MXI3X1 g6183__6260(.A (n_253), .B (n_157), .C (n_4), .S0 (n_231), .S1
       (n_247), .Y (n_258));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg_array[6].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_246), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[6]));
  OAI22X4 g6209__4319(.A0 (n_251), .A1 (n_241), .B0 (n_1), .B1 (n_256),
       .Y (n_257));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[6].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_245), .Q (DATA_PATH_S1_o_root_s[6]),
       .QN (UNCONNECTED));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_243), .Q
       (DATA_PATH_S1_o_root_s[5]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg_array[5].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_242), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[5]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[14].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_236), .Q
       (DATA_PATH_S1_o_square_s[14]));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[12].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_237), .Q
       (DATA_PATH_S1_o_square_s[12]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[15].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_238), .Q
       (DATA_PATH_S1_o_square_s[15]));
  OAI21X4 g6213__8428(.A0 (n_226), .A1 (n_235), .B0 (n_250), .Y
       (n_255));
  AOI21X4 g6185__5526(.A0 (n_253), .A1 (n_232), .B0 (n_155), .Y
       (n_254));
  OAI22X4 g6197__6783(.A0 (n_251), .A1 (n_234), .B0 (n_250), .B1
       (n_249), .Y (n_252));
  MXI3X1 g6186__3680(.A (n_211), .B (n_149), .C (n_5), .S0 (n_224), .S1
       (n_247), .Y (n_248));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_240), .Q
       (DATA_PATH_S1_o_root_s[4]));
  MX3XL g6181__1617(.A (n_150), .B (n_166), .C
       (DATA_PATH_S2_o_square_adder_sum_l_s[6]), .S0 (n_205), .S1
       (n_244), .Y (n_246));
  MXI3X1 g6207__2802(.A (n_159), .B (n_108), .C (n_98), .S0 (n_213),
       .S1 (n_244), .Y (n_245));
  MX2X1 g6218__1705(.A (n_43), .B (n_230), .S0 (n_256), .Y (n_243));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_233), .Q
       (DATA_PATH_S1_o_root_s[3]));
  MX2X1 g6188__5122(.A (DATA_PATH_S2_o_square_adder_sum_l_s[5]), .B
       (n_220), .S0 (n_239), .Y (n_242));
  XNOR2X2 g6225__8246(.A (n_77), .B (n_216), .Y (n_241));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[13].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_225), .Q
       (DATA_PATH_S1_o_square_s[13]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[11].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_227), .Q
       (DATA_PATH_S1_o_square_s[11]));
  MX2X1 g6217__7098(.A (n_14), .B (n_221), .S0 (n_239), .Y (n_240));
  MX2X1 g6216__6131(.A (DATA_PATH_S1_o_square_s[15]), .B (n_217), .S0
       (n_239), .Y (n_238));
  MX2X1 g6191__1881(.A (DATA_PATH_S1_o_square_s[12]), .B (n_214), .S0
       (n_239), .Y (n_237));
  MX2X1 g6201__5115(.A (DATA_PATH_S1_o_square_s[14]), .B (n_223), .S0
       (n_256), .Y (n_236));
  NOR2X6 g6228__7482(.A (n_202), .B (n_218), .Y (n_235));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg_array[4].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_215), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[4]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[10].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_222), .Q
       (DATA_PATH_S1_o_square_s[10]));
  CLKXOR2X1 g6219__4733(.A (DATA_PATH_S2_o_A_high_s[7]), .B (n_208), .Y
       (n_234));
  MX2X1 g6221__6161(.A (n_52), .B (n_206), .S0 (n_256), .Y (n_233));
  INVX3 g6200(.A (n_231), .Y (n_232));
  OAI2BB2X4 g6232__9315(.A0N (n_289), .A1N (n_228), .B0 (n_289), .B1
       (n_228), .Y (n_230));
  AOI21X4 g6203__9945(.A0 (n_203), .A1 (n_190), .B0 (n_212), .Y
       (n_231));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_209), .Q
       (DATA_PATH_S1_o_root_s[2]));
  MX2X1 g6208__2883(.A (DATA_PATH_S1_o_square_s[11]), .B (n_200), .S0
       (n_256), .Y (n_227));
  OAI2BB1X4 g6242__2346(.A0N (n_201), .A1N (n_194), .B0 (n_179), .Y
       (n_226));
  MX2X1 g6224__1666(.A (DATA_PATH_S1_o_square_s[13]), .B (n_193), .S0
       (n_239), .Y (n_225));
  OAI21X4 g6202__7410(.A0 (n_189), .A1 (n_219), .B0 (n_210), .Y
       (n_224));
  CLKXOR2X1 g6226__6417(.A (DATA_PATH_S2_o_A_high_s[5]), .B (n_178), .Y
       (n_223));
  MX2X1 g6227__5477(.A (n_325), .B (n_176), .S0 (n_239), .Y (n_222));
  CLKXOR2X1 g6233__2398(.A (n_118), .B (n_183), .Y (n_221));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg_array[3].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_199), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[3]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[9].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_198), .Q
       (DATA_PATH_S1_o_square_s[9]));
  XNOR2X1 g6212__5107(.A (n_204), .B (n_219), .Y (n_220));
  AOI2BB1X4 g6236__6260(.A0N (n_181), .A1N (n_163), .B0 (n_192), .Y
       (n_218));
  CLKXOR2X1 g6244__4319(.A (DATA_PATH_S2_o_A_high_s[6]), .B (n_207), .Y
       (n_217));
  OAI21X4 g6245__8428(.A0 (n_160), .A1 (n_284), .B0 (n_175), .Y
       (n_216));
  MX2X1 g6210__5526(.A (DATA_PATH_S2_o_square_adder_sum_l_s[4]), .B
       (n_188), .S0 (n_239), .Y (n_215));
  CLKXOR2X1 g6211__6783(.A (DATA_PATH_S2_o_A_high_s[3]), .B (n_185), .Y
       (n_214));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_191), .Q
       (DATA_PATH_S1_o_root_s[1]));
  AOI211X4 g6238__3680(.A0 (n_290), .A1 (n_195), .B0 (n_59), .C0
       (n_196), .Y (n_213));
  OAI21X4 g6237__1617(.A0 (n_211), .A1 (n_210), .B0 (n_95), .Y (n_212));
  MX2X1 g6241__2802(.A (n_41), .B (n_168), .S0 (n_239), .Y (n_209));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg_array[2].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_174), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[2]));
  NAND2X2 g6247__1705(.A (DATA_PATH_S2_o_A_high_s[6]), .B (n_207), .Y
       (n_208));
  CLKXOR2X1 g6243__5122(.A (n_182), .B (n_170), .Y (n_206));
  AOI21X4 g6192__8246(.A0 (n_204), .A1 (n_203), .B0 (n_167), .Y
       (n_205));
  NAND2X4 g6265__7098(.A (n_187), .B (n_201), .Y (n_202));
  CLKXOR2X1 g6231__6131(.A (DATA_PATH_S2_o_A_high_s[2]), .B (n_184), .Y
       (n_200));
  MX2X1 g6229__1881(.A (DATA_PATH_S2_o_square_adder_sum_l_s[3]), .B
       (n_156), .S0 (n_256), .Y (n_199));
  MX3XL g6251__5115(.A (n_367), .B (n_368), .C
       (DATA_PATH_S1_o_square_s[9]), .S0 (n_110), .S1 (n_244), .Y
       (n_198));
  NOR2X4 g6249__7482(.A (n_196), .B (n_195), .Y (n_228));
  OAI21X4 g6266__4733(.A0 (n_115), .A1 (n_186), .B0 (n_172), .Y
       (n_194));
  CLKXOR2X1 g6253__6161(.A (DATA_PATH_S2_o_A_high_s[4]), .B (n_177), .Y
       (n_193));
  OAI21X4 g6252__9315(.A0 (n_162), .A1 (n_161), .B0 (n_173), .Y
       (n_192));
  CLKXOR2X1 g6269__9945(.A (n_12), .B (n_164), .Y (n_191));
  NOR2X4 g6256__2883(.A (n_211), .B (n_189), .Y (n_190));
  XNOR2X1 g6234__2346(.A (n_140), .B (n_69), .Y (n_188));
  AOI2BB1X4 g6289__1666(.A0N (DATA_PATH_S1_o_input_s[8]), .A1N (n_113),
       .B0 (n_186), .Y (n_187));
  CLKAND2X2 g6239__7410(.A (DATA_PATH_S2_o_A_high_s[2]), .B (n_184), .Y
       (n_185));
  OAI21X2 g6254__6417(.A0 (n_182), .A1 (n_169), .B0 (n_146), .Y
       (n_183));
  AOI2BB1X2 g6255__5477(.A0N (n_85), .A1N (n_79), .B0 (n_158), .Y
       (n_181));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_165), .Q
       (DATA_PATH_S1_o_root_s[0]));
  AOI21X2 g6258__2398(.A0 (n_84), .A1 (n_171), .B0 (n_138), .Y (n_179));
  CLKAND2X2 g6261__5107(.A (DATA_PATH_S2_o_A_high_s[4]), .B (n_177), .Y
       (n_178));
  CLKXOR2X1 g6270__6260(.A (n_362), .B (n_148), .Y (n_176));
  NOR2X4 g6257__4319(.A (n_80), .B (n_196), .Y (n_175));
  MX2X1 g6267__8428(.A (n_144), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[2]), .S0 (n_247), .Y
       (n_174));
  INVX3 g6220(.A (n_203), .Y (n_219));
  CLKAND2X6 g6262__5526(.A (n_16), .B (n_177), .Y (n_207));
  AOI21X4 g6292__6783(.A0 (DATA_PATH_S1_o_input_s[7]), .A1 (n_307), .B0
       (n_154), .Y (n_173));
  AOI21X2 g6287__3680(.A0 (DATA_PATH_S1_o_input_s[11]), .A1 (n_151),
       .B0 (n_152), .Y (n_172));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[10].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_141), .Q
       (DATA_PATH_S1_o_input_s[10]));
  NOR2BX1 g6259__1617(.AN (n_169), .B (n_135), .Y (n_170));
  XNOR2X1 g6268__2802(.A (n_107), .B (n_136), .Y (n_168));
  AOI21X4 g6260__1705(.A0 (n_167), .A1 (n_166), .B0 (n_103), .Y
       (n_210));
  NOR3X8 g6272__5122(.A (n_169), .B (n_119), .C (n_182), .Y (n_195));
  OAI21X4 g6235__8246(.A0 (n_68), .A1 (n_139), .B0 (n_67), .Y (n_203));
  ADDHX1 g6308__7098(.A (n_357), .B (en_pipe_s), .CO (n_164), .S
       (n_165));
  OR2X6 g6311__6131(.A (n_162), .B (n_83), .Y (n_163));
  OA22X4 g6288__1881(.A0 (n_348), .A1 (n_102), .B0 (n_282), .B1 (n_18),
       .Y (n_161));
  NAND2X2 g6290__5115(.A (n_159), .B (n_229), .Y (n_160));
  AOI21X2 g6291__7482(.A0 (n_322), .A1 (n_87), .B0 (n_88), .Y (n_158));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_127), .Q
       (DATA_PATH_S1_o_input_s[6]));
  INVX1 g6304(.A (n_253), .Y (n_157));
  NAND2X4 g6295__4733(.A (n_166), .B (n_204), .Y (n_189));
  NOR2X6 g6297__6161(.A (n_364), .B (n_147), .Y (n_184));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_124), .Q
       (DATA_PATH_S1_o_input_s[1]), .QN (UNCONNECTED0));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[15].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_128), .Q
       (DATA_PATH_S1_o_input_s[15]), .QN (UNCONNECTED1));
  OR2X4 g6296__9315(.A (n_61), .B (n_145), .Y (n_196));
  CLKAND2X6 g6299__9945(.A (n_91), .B (n_131), .Y (n_177));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[11].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_121), .Q
       (DATA_PATH_S1_o_input_s[11]));
  XNOR2X1 g6264__2883(.A (n_142), .B (n_101), .Y (n_156));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[9].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_123), .Q
       (DATA_PATH_S1_o_input_s[9]));
  NAND3X8 g6350__2346(.A (n_36), .B (n_54), .C (n_89), .Y (n_186));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_122), .Q
       (DATA_PATH_S1_o_input_s[0]));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[13].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_111), .Q
       (DATA_PATH_S1_o_input_s[13]), .QN (UNCONNECTED2));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[8].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_126), .Q
       (DATA_PATH_S1_o_input_s[8]), .QN (UNCONNECTED3));
  DFFRX4 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[14].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_116), .Q
       (DATA_PATH_S1_o_input_s[14]), .QN (UNCONNECTED4));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[12].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_134), .Q
       (DATA_PATH_S1_o_input_s[12]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_125), .Q
       (DATA_PATH_S1_o_input_s[7]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_120), .Q
       (DATA_PATH_S1_o_input_s[2]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_117), .Q
       (DATA_PATH_S1_o_input_s[3]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_129), .Q
       (DATA_PATH_S1_o_input_s[4]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_132), .Q
       (DATA_PATH_S1_o_input_s[5]));
  DFFRHQX8 \CONTROL_PATH_CurrentState_reg[1] (.RN (rst_n), .CK (clk),
       .D (n_112), .Q (mux_root_s));
  ADDHX2 g6309__1666(.A (DATA_PATH_S1_o_square_s[8]), .B (n_47), .CO
       (n_155), .S (n_253));
  AOI2BB1X4 g6310__7410(.A0N (DATA_PATH_S1_o_input_s[7]), .A1N (n_153),
       .B0 (n_352), .Y (n_154));
  AOI2BB1X4 g6312__6417(.A0N (DATA_PATH_S1_o_input_s[11]), .A1N
       (n_151), .B0 (DATA_PATH_S1_o_square_s[11]), .Y (n_152));
  INVX1 g6303(.A (n_166), .Y (n_150));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_70), .Q
       (DATA_PATH_S2_o_A_high_s[7]));
  DFFSHQX8 DATA_PATH_PIPELINE_STAGE2_ready_reg_sig_q_reg(.SN (rst_n),
       .CK (clk), .D (n_90), .Q (ready_o));
  INVX2 g6305(.A (n_149), .Y (n_211));
  NAND2X8 g6298__5477(.A (n_30), .B (n_106), .Y (n_169));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_92), .Q
       (DATA_PATH_S2_o_A_high_s[6]));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_75), .Q
       (DATA_PATH_S2_o_A_high_s[1]));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_74), .Q
       (DATA_PATH_S2_o_A_high_s[0]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_71), .Q
       (DATA_PATH_S2_o_A_high_s[5]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_81), .Q
       (DATA_PATH_S2_o_A_high_s[3]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_76), .Q
       (DATA_PATH_S1_o_square_s[3]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_65), .Q
       (DATA_PATH_S1_o_square_s[6]));
  INVX1 g6331(.A (n_147), .Y (n_148));
  INVX1 g6353(.A (n_145), .Y (n_146));
  AO21X1 g6367__2398(.A0 (n_355), .A1 (n_329), .B0 (n_142), .Y (n_144));
  MX2X1 g6342__5107(.A (n_51), .B (valor_i[10]), .S0 (n_133), .Y
       (n_141));
  INVX1 g6246(.A (n_139), .Y (n_140));
  AOI21X2 g6333__6260(.A0 (n_17), .A1 (n_55), .B0 (n_137), .Y (n_138));
  NOR3X6 g6351__4319(.A (n_38), .B (n_46), .C (n_137), .Y (n_171));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[8].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_62), .Q
       (DATA_PATH_S1_o_square_s[8]));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE2_B_high_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_78), .Q
       (DATA_PATH_S2_o_B_high_s[0]));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_72), .Q
       (DATA_PATH_S2_o_A_high_s[4]), .QN (UNCONNECTED5));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_73), .Q
       (DATA_PATH_S2_o_A_high_s[2]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_63), .Q
       (DATA_PATH_S1_o_square_s[2]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_93), .Q
       (DATA_PATH_S1_o_square_s[7]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_64), .Q
       (DATA_PATH_S1_o_square_s[5]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_66), .Q
       (DATA_PATH_S1_o_square_s[4]));
  ADDHX1 g6307__8428(.A (n_23), .B (n_341), .CO (n_135), .S (n_136));
  MX2X1 g6346__5526(.A (DATA_PATH_S1_o_input_s[12]), .B (valor_i[12]),
       .S0 (n_133), .Y (n_134));
  MX2X1 g6332__6783(.A (DATA_PATH_S1_o_input_s[5]), .B (valor_i[5]),
       .S0 (n_133), .Y (n_132));
  NOR3X4 g6334__3680(.A (n_365), .B (n_21), .C (n_109), .Y (n_131));
  MX2X1 g6335__1617(.A (DATA_PATH_S1_o_input_s[4]), .B (valor_i[4]),
       .S0 (n_133), .Y (n_129));
  MX2X1 g6336__2802(.A (DATA_PATH_S1_o_input_s[15]), .B (valor_i[15]),
       .S0 (n_133), .Y (n_128));
  MX2X1 g6337__1705(.A (n_28), .B (valor_i[6]), .S0 (n_133), .Y
       (n_127));
  MX2X1 g6338__5122(.A (DATA_PATH_S1_o_input_s[8]), .B (valor_i[8]),
       .S0 (n_133), .Y (n_126));
  MX2X1 g6339__8246(.A (DATA_PATH_S1_o_input_s[7]), .B (valor_i[7]),
       .S0 (n_133), .Y (n_125));
  MX2X1 g6340__7098(.A (DATA_PATH_S1_o_input_s[1]), .B (valor_i[1]),
       .S0 (n_133), .Y (n_124));
  MX2X1 g6341__6131(.A (n_114), .B (valor_i[9]), .S0 (n_133), .Y
       (n_123));
  MX2X1 g6343__1881(.A (DATA_PATH_S1_o_input_s[0]), .B (valor_i[0]),
       .S0 (n_133), .Y (n_122));
  MX2X1 g6344__5115(.A (DATA_PATH_S1_o_input_s[11]), .B (valor_i[11]),
       .S0 (n_133), .Y (n_121));
  MX2X1 g6345__7482(.A (DATA_PATH_S1_o_input_s[2]), .B (valor_i[2]),
       .S0 (n_133), .Y (n_120));
  INVX2 g6302(.A (n_118), .Y (n_119));
  MX2X1 g6347__4733(.A (DATA_PATH_S1_o_input_s[3]), .B (valor_i[3]),
       .S0 (n_133), .Y (n_117));
  MX2X1 g6349__6161(.A (DATA_PATH_S1_o_input_s[14]), .B (valor_i[14]),
       .S0 (n_133), .Y (n_116));
  AOI22X2 g6363__9315(.A0 (n_7), .A1 (n_114), .B0
       (DATA_PATH_S1_o_input_s[8]), .B1 (n_113), .Y (n_115));
  OAI2BB1X1 g6366__9945(.A0N (N_s), .A1N (n_256), .B0 (n_335), .Y
       (n_112));
  MX2X1 g6348__2883(.A (n_292), .B (valor_i[13]), .S0 (n_133), .Y
       (n_111));
  NOR2X1 g6373__2346(.A (n_105), .B (n_109), .Y (n_110));
  INVX1 g6375(.A (n_159), .Y (n_108));
  INVX1 g6398(.A (n_106), .Y (n_107));
  AOI2BB1X4 g6352__1666(.A0N (n_369), .A1N (n_109), .B0 (n_105), .Y
       (n_147));
  OAI21X4 g6369__7410(.A0 (DATA_PATH_S1_o_input_s[7]), .A1 (n_353), .B0
       (n_60), .Y (n_162));
  AOI2BB1X4 g6271__6417(.A0N (n_99), .A1N (n_142), .B0 (n_100), .Y
       (n_139));
  AOI2BB1X4 g6393__5477(.A0N (DATA_PATH_S1_o_square_s[7]), .A1N
       (DATA_PATH_S1_o_root_s[5]), .B0 (n_94), .Y (n_149));
  NOR2X4 g6371__2398(.A (n_342), .B (n_39), .Y (n_145));
  NOR2X8 g6395__5107(.A (n_22), .B (n_103), .Y (n_166));
  CLKAND2X2 g6394__6260(.A (n_35), .B (n_58), .Y (n_229));
  AOI21X4 g6358__4319(.A0 (DATA_PATH_S1_o_input_s[4]), .A1 (n_283), .B0
       (DATA_PATH_S1_o_input_s[5]), .Y (n_102));
  NOR2X1 g6370__8428(.A (n_100), .B (n_99), .Y (n_101));
  INVX1 g6455(.A (n_96), .Y (n_98));
  BUFX6 g6456(.A (n_96), .Y (root_o[6]));
  INVX2 g6306(.A (n_94), .Y (n_95));
  MX2X1 g6354__5526(.A (DATA_PATH_S2_o_square_adder_sum_l_s[7]), .B
       (n_352), .S0 (n_244), .Y (n_93));
  MX2X1 g6355__6783(.A (DATA_PATH_S1_o_square_s[15]), .B
       (DATA_PATH_S2_o_A_high_s[6]), .S0 (n_244), .Y (n_92));
  NAND2X2 g6356__3680(.A (n_369), .B (n_32), .Y (n_91));
  MX2X1 g6357__1617(.A (n_336), .B (ready_o), .S0 (n_247), .Y (n_90));
  NAND2X4 g6409__2802(.A (n_326), .B (n_50), .Y (n_89));
  AOI21X2 g6359__1705(.A0 (DATA_PATH_S1_o_input_s[2]), .A1 (n_331), .B0
       (DATA_PATH_S1_o_input_s[3]), .Y (n_88));
  NAND3X4 g6360__5122(.A (DATA_PATH_S1_o_input_s[3]), .B
       (DATA_PATH_S1_o_input_s[2]), .C (n_331), .Y (n_87));
  NOR3X2 g6361__8246(.A (DATA_PATH_S1_o_input_s[0]), .B
       (DATA_PATH_S1_o_input_s[1]), .C (n_359), .Y (n_85));
  AO22X1 g6362__7098(.A0 (n_292), .A1 (n_45), .B0
       (DATA_PATH_S1_o_input_s[12]), .B1 (n_56), .Y (n_84));
  OAI22X1 g6364__6131(.A0 (DATA_PATH_S1_o_input_s[5]), .A1 (n_349), .B0
       (DATA_PATH_S1_o_input_s[4]), .B1 (n_280), .Y (n_83));
  MX2X1 g6388__1881(.A (DATA_PATH_S1_o_square_s[12]), .B
       (DATA_PATH_S2_o_A_high_s[3]), .S0 (n_244), .Y (n_81));
  AOI2BB1X1 g6365__5115(.A0N (n_25), .A1N (n_11), .B0 (n_340), .Y
       (n_80));
  OAI22X2 g6368__7482(.A0 (DATA_PATH_S1_o_input_s[3]), .A1 (n_323), .B0
       (DATA_PATH_S1_o_input_s[2]), .B1 (n_331), .Y (n_79));
  CLKAND2X6 g6413__4733(.A (DATA_PATH_S1_o_root_s[1]), .B
       (DATA_PATH_S1_o_root_s[0]), .Y (n_106));
  MX2X1 g6383__6161(.A (root_o[7]), .B (DATA_PATH_S2_o_B_high_s[0]),
       .S0 (n_247), .Y (n_78));
  XNOR2X1 g6390__9315(.A (n_339), .B (root_o[7]), .Y (n_77));
  MX2X1 g6376__9945(.A (DATA_PATH_S2_o_square_adder_sum_l_s[3]), .B
       (n_322), .S0 (n_244), .Y (n_76));
  MX2X1 g6377__2883(.A (n_325), .B (n_361), .S0 (n_244), .Y (n_75));
  MX2X1 g6378__2346(.A (DATA_PATH_S1_o_square_s[9]), .B
       (DATA_PATH_S2_o_A_high_s[0]), .S0 (n_247), .Y (n_74));
  MX2X1 g6379__1666(.A (DATA_PATH_S1_o_square_s[11]), .B
       (DATA_PATH_S2_o_A_high_s[2]), .S0 (n_244), .Y (n_73));
  MX2X1 g6380__7410(.A (DATA_PATH_S1_o_square_s[13]), .B
       (DATA_PATH_S2_o_A_high_s[4]), .S0 (n_244), .Y (n_72));
  MX2X1 g6381__6417(.A (DATA_PATH_S1_o_square_s[14]), .B
       (DATA_PATH_S2_o_A_high_s[5]), .S0 (n_247), .Y (n_71));
  MX2X1 g6382__5477(.A (DATA_PATH_S1_o_square_s[16]), .B
       (DATA_PATH_S2_o_A_high_s[7]), .S0 (n_247), .Y (n_70));
  NAND2BX1 g6372__2398(.AN (n_68), .B (n_67), .Y (n_69));
  MX2X1 g6384__5107(.A (DATA_PATH_S2_o_square_adder_sum_l_s[4]), .B
       (n_282), .S0 (n_244), .Y (n_66));
  MX2X1 g6385__6260(.A (DATA_PATH_S2_o_square_adder_sum_l_s[6]), .B
       (n_286), .S0 (n_244), .Y (n_65));
  MX2X1 g6386__4319(.A (DATA_PATH_S2_o_square_adder_sum_l_s[5]), .B
       (n_348), .S0 (n_244), .Y (n_64));
  MX2X1 g6387__8428(.A (DATA_PATH_S2_o_square_adder_sum_l_s[2]), .B
       (n_328), .S0 (n_244), .Y (n_63));
  MX2X1 g6389__5526(.A (DATA_PATH_S2_o_square_adder_sum_l_s[8]), .B
       (DATA_PATH_S1_o_square_s[8]), .S0 (n_244), .Y (n_62));
  NOR2X4 g6392__6783(.A (n_27), .B (n_61), .Y (n_118));
  CLKMX2X3 g6396__3680(.A (n_344), .B (mux_root_s), .S0
       (DATA_PATH_S1_o_root_s[3]), .Y (n_182));
  MXI2X2 g6391__1617(.A (n_344), .B (mux_root_s), .S0
       (DATA_PATH_S1_o_root_s[6]), .Y (n_159));
  NOR2X6 g6374__2802(.A (n_29), .B (n_167), .Y (n_204));
  NAND2X2 g6408__1705(.A (n_286), .B (n_48), .Y (n_60));
  INVX2 g6417(.A (n_58), .Y (n_59));
  OR2X1 g6420__5122(.A (DATA_PATH_S1_o_input_s[12]), .B (n_56), .Y
       (n_57));
  NAND2X1 g6421__8246(.A (DATA_PATH_S1_o_input_s[14]), .B (n_37), .Y
       (n_55));
  NAND2X2 g6424__7098(.A (DATA_PATH_S1_o_square_s[11]), .B (n_6), .Y
       (n_54));
  BUFX6 g6460(.A (n_52), .Y (root_o[3]));
  INVX1 g6441(.A (n_50), .Y (n_51));
  NOR2X4 g6430__6131(.A (n_351), .B (n_34), .Y (n_94));
  NOR2X6 g6431__1881(.A (n_287), .B (n_0), .Y (n_103));
  NOR2X4 g6429__5115(.A (n_48), .B (DATA_PATH_S1_o_square_s[6]), .Y
       (n_153));
  BUFX2 g6457(.A (n_47), .Y (n_96));
  NOR2X4 g6427__7482(.A (DATA_PATH_S1_o_input_s[15]), .B (n_2), .Y
       (n_137));
  NOR2X8 g6426__4733(.A (n_10), .B (DATA_PATH_S1_o_square_s[10]), .Y
       (n_151));
  NOR2X4 g6404__6161(.A (DATA_PATH_S1_o_input_s[13]), .B (n_45), .Y
       (n_46));
  BUFX6 g6468(.A (n_43), .Y (root_o[5]));
  BUFX6 g6472(.A (n_41), .Y (root_o[2]));
  INVX2 g6479(.A (n_256), .Y (n_40));
  NOR2X6 g6407__9315(.A (DATA_PATH_S1_o_root_s[2]), .B (n_24), .Y
       (n_39));
  NOR2X4 g6401__9945(.A (n_37), .B (DATA_PATH_S1_o_input_s[14]), .Y
       (n_38));
  NAND2X2 g6402__2883(.A (DATA_PATH_S1_o_square_s[9]), .B (n_26), .Y
       (n_36));
  NAND2X4 g6403__2346(.A (n_346), .B (n_34), .Y (n_35));
  BUFX2 g6478(.A (n_256), .Y (n_249));
  INVX3 g6397(.A (n_32), .Y (n_105));
  DFFRX2 \CONTROL_PATH_CurrentState_reg[0] (.RN (rst_n), .CK (clk), .D
       (n_335), .Q (en_pipe_s), .QN (UNCONNECTED6));
  OR2X6 g6418__1666(.A (DATA_PATH_S1_o_root_s[2]), .B (mux_root_s), .Y
       (n_30));
  NOR2X2 g6419__7410(.A (DATA_PATH_S1_o_square_s[5]), .B
       (DATA_PATH_S1_o_root_s[3]), .Y (n_29));
  INVX1 g6483(.A (n_48), .Y (n_28));
  NOR2X4 g6422__6417(.A (DATA_PATH_S1_o_root_s[4]), .B (mux_root_s), .Y
       (n_27));
  NAND2X4 g6410__5477(.A (DATA_PATH_S1_o_root_s[2]), .B (n_279), .Y
       (n_67));
  NOR2X2 g6425__2398(.A (DATA_PATH_S1_o_square_s[4]), .B
       (DATA_PATH_S1_o_root_s[2]), .Y (n_68));
  NAND2X4 g6432__5107(.A (mux_root_s), .B (DATA_PATH_S1_o_root_s[5]),
       .Y (n_58));
  AND2X6 g6433__6260(.A (DATA_PATH_S1_o_root_s[4]), .B (mux_root_s), .Y
       (n_61));
  INVX2 g6438(.A (n_26), .Y (n_114));
  BUFX2 g6458(.A (n_25), .Y (n_47));
  BUFX2 g6461(.A (n_24), .Y (n_52));
  BUFX2 g6473(.A (n_23), .Y (n_41));
  NOR2X6 g6415__4319(.A (DATA_PATH_S1_o_root_s[0]), .B
       (DATA_PATH_S1_o_square_s[2]), .Y (n_142));
  NOR2X4 g6414__8428(.A (DATA_PATH_S2_o_B_high_s[0]), .B
       (DATA_PATH_S2_o_A_high_s[0]), .Y (n_109));
  INVX3 g6476(.A (n_247), .Y (n_239));
  INVX3 g6480(.A (n_244), .Y (n_256));
  NOR2X4 g6423__5526(.A (DATA_PATH_S1_o_square_s[6]), .B
       (DATA_PATH_S1_o_root_s[4]), .Y (n_22));
  NAND2X6 g6405__6783(.A (DATA_PATH_S2_o_A_high_s[2]), .B
       (DATA_PATH_S2_o_A_high_s[3]), .Y (n_21));
  NAND2X1 g6400__3680(.A (DATA_PATH_S1_o_input_s[4]), .B
       (DATA_PATH_S1_o_input_s[5]), .Y (n_18));
  NAND2BX2 g6399__1617(.AN (DATA_PATH_S1_o_square_s[15]), .B
       (DATA_PATH_S1_o_input_s[15]), .Y (n_17));
  AND2X1 g6406__2802(.A (DATA_PATH_S2_o_A_high_s[5]), .B
       (DATA_PATH_S2_o_A_high_s[4]), .Y (n_16));
  BUFX6 g6452(.A (n_14), .Y (root_o[4]));
  BUFX6 g6493(.A (n_12), .Y (root_o[1]));
  BUFX2 g6469(.A (n_11), .Y (n_43));
  NAND2X6 g6412__1705(.A (DATA_PATH_S2_o_B_high_s[0]), .B
       (DATA_PATH_S2_o_A_high_s[0]), .Y (n_32));
  NOR2X6 g6411__5122(.A (DATA_PATH_S1_o_square_s[3]), .B
       (DATA_PATH_S1_o_root_s[1]), .Y (n_99));
  BUFX3 g6442(.A (n_10), .Y (n_50));
  BUFX2 g6481(.A (n_244), .Y (n_251));
  CLKAND2X3 g6428__8246(.A (DATA_PATH_S1_o_square_s[3]), .B
       (DATA_PATH_S1_o_root_s[1]), .Y (n_100));
  AND2X6 g6434__7098(.A (DATA_PATH_S1_o_square_s[5]), .B
       (DATA_PATH_S1_o_root_s[3]), .Y (n_167));
  NOR2X6 g6435__6131(.A (n_337), .B (en_pipe_s), .Y (n_133));
  INVX1 g6445(.A (DATA_PATH_S1_o_square_s[9]), .Y (n_7));
  INVX2 g6485(.A (DATA_PATH_S1_o_input_s[11]), .Y (n_6));
  INVX1 g6437(.A (DATA_PATH_S2_o_square_adder_sum_l_s[7]), .Y (n_5));
  INVX2 g6444(.A (DATA_PATH_S1_o_square_s[12]), .Y (n_56));
  BUFX6 g6459(.A (DATA_PATH_S1_o_root_s[6]), .Y (n_25));
  INVX2 g6486(.A (DATA_PATH_S1_o_square_s[13]), .Y (n_45));
  INVX2 g6447(.A (DATA_PATH_S1_o_square_s[8]), .Y (n_113));
  BUFX2 g6494(.A (DATA_PATH_S1_o_root_s[1]), .Y (n_12));
  INVX3 g6439(.A (DATA_PATH_S1_o_input_s[9]), .Y (n_26));
  CLKINVX4 g6482(.A (en_pipe_s), .Y (n_244));
  INVX1 g6436(.A (DATA_PATH_S2_o_square_adder_sum_l_s[8]), .Y (n_4));
  INVX2 g6487(.A (DATA_PATH_S1_o_square_s[15]), .Y (n_2));
  INVX1 g6490(.A (root_o[7]), .Y (n_1));
  INVX3 g6451(.A (DATA_PATH_S1_o_root_s[4]), .Y (n_0));
  INVX3 g6488(.A (DATA_PATH_S1_o_square_s[14]), .Y (n_37));
  INVX2 g6440(.A (DATA_PATH_S1_o_square_s[16]), .Y (n_250));
  BUFX6 g6462(.A (DATA_PATH_S1_o_root_s[3]), .Y (n_24));
  CLKINVX8 g6471(.A (DATA_PATH_S1_o_root_s[5]), .Y (n_34));
  CLKINVX6 g6443(.A (DATA_PATH_S1_o_input_s[10]), .Y (n_10));
  BUFX2 g6470(.A (DATA_PATH_S1_o_root_s[5]), .Y (n_11));
  BUFX2 g6453(.A (DATA_PATH_S1_o_root_s[4]), .Y (n_14));
  BUFX2 g6474(.A (DATA_PATH_S1_o_root_s[2]), .Y (n_23));
  CLKINVX4 g6484(.A (DATA_PATH_S1_o_input_s[6]), .Y (n_48));
  INVX3 g6477(.A (en_pipe_s), .Y (n_247));
  ADDHX2 g6556__1881(.A (n_171), .B (n_57), .CO (n_201), .S
       (UNCONNECTED7));
  CLKINVX4 fopt(.A (n_280), .Y (n_279));
  CLKINVX4 fopt1(.A (DATA_PATH_S1_o_square_s[4]), .Y (n_280));
  CLKINVX3 fopt2(.A (n_283), .Y (n_282));
  CLKINVX8 fopt3(.A (DATA_PATH_S1_o_square_s[4]), .Y (n_283));
  CLKINVX6 fopt6557(.A (n_195), .Y (n_284));
  CLKINVX8 fopt6558(.A (n_287), .Y (n_286));
  CLKINVX6 fopt6559(.A (DATA_PATH_S1_o_square_s[6]), .Y (n_287));
  BUFX6 fopt6560(.A (n_290), .Y (n_289));
  BUFX6 fopt6561(.A (n_229), .Y (n_290));
  BUFX6 fopt6562(.A (DATA_PATH_S1_o_input_s[13]), .Y (n_292));
  BUFX3 fopt6567(.A (n_153), .Y (n_307));
  CLKINVX3 fopt6572(.A (n_323), .Y (n_322));
  CLKINVX4 fopt6573(.A (DATA_PATH_S1_o_square_s[3]), .Y (n_323));
  BUFX6 fopt6574(.A (n_326), .Y (n_325));
  BUFX6 fopt6575(.A (DATA_PATH_S1_o_square_s[10]), .Y (n_326));
  CLKINVX2 fopt6576(.A (n_330), .Y (n_328));
  CLKINVX8 fopt6577(.A (n_330), .Y (n_329));
  BUFX6 fopt6578(.A (n_331), .Y (n_330));
  CLKINVX6 fopt6579(.A (DATA_PATH_S1_o_square_s[2]), .Y (n_331));
  BUFX6 fopt6580(.A (n_336), .Y (n_335));
  BUFX6 fopt6581(.A (n_338), .Y (n_336));
  CLKINVX8 fopt6582(.A (n_338), .Y (n_337));
  BUFX6 fopt6583(.A (n_339), .Y (n_338));
  BUFX6 fopt4(.A (n_340), .Y (n_339));
  CLKINVX8 fopt5(.A (n_341), .Y (n_340));
  CLKINVX6 fopt6(.A (n_342), .Y (n_341));
  CLKINVX4 fopt7(.A (mux_root_s), .Y (n_342));
  CLKINVX4 fopt8(.A (mux_root_s), .Y (n_344));
  CLKINVX3 fopt9(.A (mux_root_s), .Y (n_346));
  CLKINVX3 fopt6584(.A (n_349), .Y (n_348));
  CLKINVX8 fopt6585(.A (DATA_PATH_S1_o_square_s[5]), .Y (n_349));
  CLKINVX8 fopt6586(.A (DATA_PATH_S1_o_square_s[7]), .Y (n_351));
  CLKINVX3 fopt6587(.A (n_353), .Y (n_352));
  CLKINVX4 fopt6588(.A (DATA_PATH_S1_o_square_s[7]), .Y (n_353));
  CLKINVX6 fopt6589(.A (n_358), .Y (n_355));
  BUFX16 fopt6590(.A (n_357), .Y (root_o[0]));
  CLKINVX3 fopt6591(.A (n_358), .Y (n_357));
  BUFX6 fopt6592(.A (n_359), .Y (n_358));
  CLKINVX4 fopt6593(.A (DATA_PATH_S1_o_root_s[0]), .Y (n_359));
  CLKINVX2 fopt6594(.A (n_363), .Y (n_361));
  CLKINVX6 fopt6595(.A (n_363), .Y (n_362));
  BUFX6 fopt6596(.A (n_364), .Y (n_363));
  BUFX6 fopt6597(.A (n_365), .Y (n_364));
  CLKINVX8 fopt6598(.A (DATA_PATH_S2_o_A_high_s[1]), .Y (n_365));
  CLKINVX2 fopt6599(.A (n_367), .Y (n_366));
  CLKINVX6 fopt6600(.A (n_368), .Y (n_367));
  BUFX6 fopt6601(.A (n_369), .Y (n_368));
  CLKINVX8 fopt6602(.A (DATA_PATH_S2_o_square_adder_co_l_s), .Y
       (n_369));
endmodule

