
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep  8 2025 01:08:18 -03 (Sep  8 2025 04:08:18 UTC)

// Verification Directory fv/square_root_pipe 

module square_root_pipe(valor_i, clk, rst_n, ready_o, root_o);
  input [15:0] valor_i;
  input clk, rst_n;
  output ready_o;
  output [7:0] root_o;
  wire [15:0] valor_i;
  wire clk, rst_n;
  wire ready_o;
  wire [7:0] root_o;
  wire [1:0] CONTROL_PATH_CurrentState;
  wire N_s, UNCONNECTED, UNCONNECTED0, n_0, n_1, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  assign ready_o = 1'b0;
  DFFRHQX8 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_29), .Q (root_o[6]));
  DFFRHQX8 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_28), .Q (root_o[7]));
  DFFRHQX8 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_27), .Q (root_o[5]));
  XNOR2X1 g742__2398(.A (root_o[6]), .B (n_24), .Y (n_29));
  XNOR2X1 g743__5107(.A (root_o[7]), .B (n_26), .Y (n_28));
  DFFRHQX8 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_23), .Q (root_o[4]));
  CLKXOR2X1 g745__6260(.A (root_o[5]), .B (n_25), .Y (n_27));
  NAND2X1 g749__4319(.A (n_14), .B (n_25), .Y (n_26));
  NAND2X1 g750__8428(.A (n_13), .B (n_25), .Y (n_24));
  XNOR2X1 g748__5526(.A (root_o[4]), .B (n_22), .Y (n_23));
  DFFRHQX8 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_21), .Q (root_o[3]));
  NOR2X2 g751__6783(.A (n_3), .B (n_22), .Y (n_25));
  DFFRHQX8 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_17), .Q (root_o[1]));
  DFFRHQX8 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_19), .Q (root_o[2]));
  XNOR2X1 g753__3680(.A (root_o[3]), .B (n_20), .Y (n_21));
  DFFRHQX1 \CONTROL_PATH_CurrentState_reg[1] (.RN (rst_n), .CK (clk),
       .D (n_18), .Q (CONTROL_PATH_CurrentState[1]));
  OR2X1 g758__1617(.A (n_7), .B (n_20), .Y (n_22));
  XNOR2X1 g757__2802(.A (root_o[2]), .B (n_16), .Y (n_19));
  DFFRX2 \CONTROL_PATH_CurrentState_reg[0] (.RN (rst_n), .CK (clk), .D
       (n_15), .Q (CONTROL_PATH_CurrentState[0]), .QN (UNCONNECTED));
  OAI2BB1X1 g762__1705(.A0N (CONTROL_PATH_CurrentState[0]), .A1N (n_9),
       .B0 (n_8), .Y (n_18));
  CLKXOR2X1 g754__5122(.A (root_o[1]), .B (n_11), .Y (n_17));
  DFFRHQX8 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_12), .Q (root_o[0]));
  OR2X1 g763__8246(.A (n_5), .B (n_16), .Y (n_20));
  OAI2BB1X1 g764__7098(.A0N (N_s), .A1N (CONTROL_PATH_CurrentState[0]),
       .B0 (n_10), .Y (n_15));
  AND2X1 g760__6131(.A (n_13), .B (n_4), .Y (n_14));
  ADDHX1 g759__1881(.A (root_o[0]), .B (n_10), .CO (n_11), .S (n_12));
  NAND2X1 g771__5115(.A (N_s), .B (CONTROL_PATH_CurrentState[1]), .Y
       (n_9));
  MX2X1 g766__7482(.A (n_8), .B (n_1), .S0 (n_6), .Y (n_16));
  CLKXOR2X1 g767__4733(.A (root_o[3]), .B (n_6), .Y (n_7));
  XNOR2X1 g765__6161(.A (n_6), .B (root_o[5]), .Y (n_13));
  CLKXOR2X1 g768__9315(.A (root_o[2]), .B (n_6), .Y (n_5));
  XNOR2X1 g769__9945(.A (n_6), .B (root_o[6]), .Y (n_4));
  CLKXOR2X1 g770__2883(.A (n_6), .B (root_o[4]), .Y (n_3));
  DFFSRX1 DATA_PATH_PIPELINE_STAGE2_N_reg_sig_q_reg(.RN (rst_n), .SN
       (n_0), .CK (clk), .D (1'b0), .Q (UNCONNECTED0), .QN (N_s));
  NAND2X2 g773__2346(.A (CONTROL_PATH_CurrentState[1]), .B (n_1), .Y
       (n_8));
  OR2X1 g774__1666(.A (CONTROL_PATH_CurrentState[1]), .B
       (CONTROL_PATH_CurrentState[0]), .Y (n_10));
  CLKAND2X2 g775__7410(.A (root_o[1]), .B (root_o[0]), .Y (n_6));
  INVXL g776(.A (rst_n), .Y (n_0));
  INVX2 g777(.A (CONTROL_PATH_CurrentState[0]), .Y (n_1));
endmodule

