
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 15 2025 22:32:33 -03 (Sep 16 2025 01:32:33 UTC)

// Verification Directory fv/Square_root 

module DataPath(clk, rst_n, input_i, root_o, ready_o, wr_input_i,
     en_pipe_i, ready_i, mux_root_i, N_o);
  input clk, rst_n, wr_input_i, en_pipe_i, ready_i, mux_root_i;
  input [15:0] input_i;
  output [7:0] root_o;
  output ready_o, N_o;
  wire clk, rst_n, wr_input_i, en_pipe_i, ready_i, mux_root_i;
  wire [15:0] input_i;
  wire [7:0] root_o;
  wire ready_o, N_o;
  wire [16:0] S1_input_ext_s;
  wire [15:0] S1_o_input_s;
  wire [16:0] S1_o_square_s;
  wire [7:0] S1_o_root_s;
  wire [11:0] S2_o_A_s;
  wire [11:0] S2_o_B_s;
  wire [3:0] S2_o_root_h_s;
  wire [3:0] S2_o_root_s;
  wire [4:0] S2_o_square_s;
  wire [7:0] S3_o_A_s;
  wire [7:0] S3_o_B_s;
  wire [8:0] S3_o_square_s;
  wire [3:0] S4_o_A_s;
  wire [12:0] S4_o_square_s;
  wire S1_N_s, S2_o_co_root_s, S2_o_co_square_s, S3_o_co_square_s,
       S4_o_co_square_s, n_0, n_7, n_8;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_92, n_93, n_94, n_95, n_96, n_97, n_98;
  wire n_99, n_100, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_140, n_141, n_142, n_143, n_144, n_145, n_146;
  wire n_147, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179, n_180, n_181, n_182, n_183, n_184, n_185, n_186;
  wire n_187, n_188, n_189, n_190, n_191, n_192, n_193, n_194;
  wire n_195, n_196, n_197, n_198, n_199, n_200, n_201, n_202;
  wire n_203, n_221, n_222, n_223, n_224, n_225, n_226, n_229;
  wire n_235, n_236, n_238, n_239, n_246, n_247, n_248, n_249;
  wire n_250, n_273, n_274, n_275, n_276, n_277, n_278, n_279;
  wire n_280, n_281, n_282, n_283, n_284, n_285, n_286, n_287;
  wire n_288, n_289, n_290, n_291, n_293, n_294, n_295, n_297;
  wire n_298, n_299, n_301, n_302;
  assign S1_input_ext_s[16] = 1'b0;
  Comparator COMPARATOR(.A_i ({S1_input_ext_s[16], S1_o_input_s[15:1],
       S1_input_ext_s[0]}), .B_i (S1_o_square_s), .A_less_than_B_o
       (S1_N_s));
  INVX1 g2108(.A (S1_o_input_s[14]), .Y (n_250));
  INVX1 g2124(.A (S1_o_input_s[3]), .Y (n_249));
  INVX1 g2125(.A (S1_o_input_s[2]), .Y (n_248));
  INVX1 g2126(.A (S1_o_input_s[1]), .Y (n_247));
  INVX1 g2127(.A (S1_input_ext_s[0]), .Y (n_246));
  INVX1 g2109(.A (S1_o_input_s[13]), .Y (n_239));
  INVX1 g2110(.A (S1_o_input_s[12]), .Y (n_238));
  INVX1 g2107(.A (S1_o_input_s[15]), .Y (n_236));
  INVX1 g2121(.A (S1_o_input_s[4]), .Y (n_235));
  INVX1 g2115(.A (S1_o_input_s[11]), .Y (n_229));
  INVX1 g2116(.A (S1_o_input_s[10]), .Y (n_226));
  INVX1 g2117(.A (S1_o_input_s[9]), .Y (n_225));
  INVX1 g2118(.A (S1_o_input_s[8]), .Y (n_224));
  INVX1 g2104(.A (S1_o_input_s[7]), .Y (n_223));
  INVX1 g2119(.A (S1_o_input_s[6]), .Y (n_222));
  INVX1 g2120(.A (S1_o_input_s[5]), .Y (n_221));
  DFFSHQX4 PIPELINE_STAGE1_S1_root_reg_Reg_Root_S1_inst_0_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_21), .Q (S1_o_root_s[0]));
  DFFRHQX4
       \PIPELINE_STAGE1_S1_root_reg_reg_array[1].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_59), .Q (S1_o_root_s[1]));
  DFFRHQX4
       \PIPELINE_STAGE1_S1_root_reg_reg_array[2].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_50), .Q (S1_o_root_s[2]));
  DFFRHQX4
       \PIPELINE_STAGE1_S1_root_reg_reg_array[3].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_45), .Q (S1_o_root_s[3]));
  DFFRHQX8
       \PIPELINE_STAGE1_S1_root_reg_reg_array[4].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_165), .Q (root_o[4]));
  DFFRHQX8
       \PIPELINE_STAGE1_S1_root_reg_reg_array[5].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_182), .Q (root_o[5]));
  DFFRHQX8
       \PIPELINE_STAGE1_S1_root_reg_reg_array[6].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_185), .Q (root_o[6]));
  DFFRHQX8
       \PIPELINE_STAGE1_S1_root_reg_reg_array[7].Reg_Root_S1_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_187), .Q (root_o[7]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_36), .Q (S1_input_ext_s[0]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_37), .Q (S1_o_input_s[1]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[2].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_35), .Q (S1_o_input_s[2]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_34), .Q (S1_o_input_s[3]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[4].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_33), .Q (S1_o_input_s[4]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[5].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_32), .Q (S1_o_input_s[5]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[6].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_31), .Q (S1_o_input_s[6]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[7].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_30), .Q (S1_o_input_s[7]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[8].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_29), .Q (S1_o_input_s[8]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[9].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_28), .Q (S1_o_input_s[9]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[10].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_27), .Q (S1_o_input_s[10]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[11].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_26), .Q (S1_o_input_s[11]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[12].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_25), .Q (S1_o_input_s[12]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[13].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_24), .Q (S1_o_input_s[13]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[14].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_23), .Q (S1_o_input_s[14]));
  DFFRHQX1 \PIPELINE_STAGE1_input_reg_reg[15].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_22), .Q (S1_o_input_s[15]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_44), .Q (S1_o_square_s[0]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_43), .Q (S1_o_square_s[1]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[2].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_62), .Q (S1_o_square_s[2]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_38), .Q (S1_o_square_s[3]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[4].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_108), .Q (S1_o_square_s[4]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[5].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_107), .Q (S1_o_square_s[5]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[6].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_106), .Q (S1_o_square_s[6]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[7].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_104), .Q (S1_o_square_s[7]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[8].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_100), .Q (S1_o_square_s[8]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[9].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_98), .Q (S1_o_square_s[9]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[10].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_94), .Q (S1_o_square_s[10]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[11].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_92), .Q (S1_o_square_s[11]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[12].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_88), .Q (S1_o_square_s[12]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[13].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_142), .Q (S1_o_square_s[13]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[14].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_162), .Q (S1_o_square_s[14]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[15].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_179), .Q (S1_o_square_s[15]));
  DFFRHQX1 \PIPELINE_STAGE1_square_reg_reg[16].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_186), .Q (S1_o_square_s[16]));
  DFFRHQX1 PIPELINE_STAGE2_Co_Square_S2_reg_sig_q_reg(.RN (rst_n), .CK
       (clk), .D (n_170), .Q (S2_o_co_square_s));
  DFFRHQX1 PIPELINE_STAGE2_N_S2_reg_sig_q_reg(.RN (rst_n), .CK (clk),
       .D (n_73), .Q (N_o));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_72), .Q (S2_o_A_s[0]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_84), .Q (S2_o_A_s[1]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[2].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_68), .Q (S2_o_A_s[2]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_39), .Q (S2_o_A_s[3]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[4].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_61), .Q (S2_o_A_s[4]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[5].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_60), .Q (S2_o_A_s[5]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[6].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_58), .Q (S2_o_A_s[6]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[7].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_57), .Q (S2_o_A_s[7]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[8].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_56), .Q (S2_o_A_s[8]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[9].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_55), .Q (S2_o_A_s[9]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[10].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_54), .Q (S2_o_A_s[10]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_A_high_S2_reg_reg[11].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_53), .Q (S2_o_A_s[11]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_B_high_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_52), .Q (S2_o_B_s[0]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_B_high_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_51), .Q (S2_o_B_s[1]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_B_high_reg_reg[2].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_49), .Q (S2_o_B_s[2]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_B_high_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_48), .Q (S2_o_B_s[3]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_B_high_reg_reg[4].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_47), .Q (S2_o_root_h_s[2]));
  DFFRHQX1 \PIPELINE_STAGE2_S2_B_high_reg_reg[5].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_46), .Q (S2_o_B_s[5]));
  DFFRHQX1 PIPELINE_STAGE2_S2_Co_Root_reg_sig_q_reg(.RN (rst_n), .CK
       (clk), .D (n_166), .Q (S2_o_co_root_s));
  DFFSHQX1 PIPELINE_STAGE2_S2_root_reg_Reg_Root_S2_1_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_141), .Q (S2_o_root_s[1]));
  DFFRHQX1 PIPELINE_STAGE2_S2_root_reg_Reg_Root_S2_2_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_154), .Q (S2_o_root_s[2]));
  DFFRHQX1 PIPELINE_STAGE2_S2_root_reg_Reg_Root_S2_3_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_171), .Q (S2_o_root_s[3]));
  DFFSHQX1 PIPELINE_STAGE2_square_sum_S2_reg_RegSumLow_0_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_42), .Q (S2_o_square_s[0]));
  DFFRHQX1 PIPELINE_STAGE2_square_sum_S2_reg_RegSumLow_1_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_41), .Q (S2_o_square_s[1]));
  DFFRHQX1 PIPELINE_STAGE2_square_sum_S2_reg_RegSumLow_2_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_40), .Q (S2_o_square_s[2]));
  DFFSHQX1 PIPELINE_STAGE2_square_sum_S2_reg_RegSumLow_3_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_140), .Q (S2_o_square_s[3]));
  DFFRHQX1 PIPELINE_STAGE2_square_sum_S2_reg_RegSumLow_4_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_160), .Q (S2_o_square_s[4]));
  DFFRHQX1 PIPELINE_STAGE3_Co_Square_S3_reg_sig_q_reg(.RN (rst_n), .CK
       (clk), .D (n_203), .Q (S3_o_co_square_s));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_105), .Q (S3_o_A_s[0]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_103), .Q (S3_o_A_s[1]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[2].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_102), .Q (S3_o_A_s[2]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_101), .Q (S3_o_A_s[3]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[4].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_99), .Q (S3_o_A_s[4]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[5].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_97), .Q (S3_o_A_s[5]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[6].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_96), .Q (S3_o_A_s[6]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_A_high_S2_reg_reg[7].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_95), .Q (S3_o_A_s[7]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_B_high_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_93), .Q (S3_o_B_s[0]));
  DFFRHQX1 \PIPELINE_STAGE3_S3_B_high_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_91), .Q (S3_o_B_s[1]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_0_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_90), .Q (S3_o_square_s[0]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_1_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_89), .Q (S3_o_square_s[1]));
  DFFSHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_2_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_87), .Q (S3_o_square_s[2]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_3_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_86), .Q (S3_o_square_s[3]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_4_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_85), .Q (S3_o_square_s[4]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_5_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_161), .Q (S3_o_square_s[5]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_6_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_184), .Q (S3_o_square_s[6]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_7_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_196), .Q (S3_o_square_s[7]));
  DFFRHQX1 PIPELINE_STAGE3_square_sum_S3_reg_RegSumLow_8_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_202), .Q (S3_o_square_s[8]));
  DFFRHQX1 PIPELINE_STAGE4_Co_Square_S4_reg_sig_q_reg(.RN (rst_n), .CK
       (clk), .D (n_197), .Q (S4_o_co_square_s));
  DFFRHQX1 \PIPELINE_STAGE4_S3_A_high_S2_reg_reg[0].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_82), .Q (S4_o_A_s[0]));
  DFFRHQX1 \PIPELINE_STAGE4_S3_A_high_S2_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_80), .Q (S4_o_A_s[1]));
  DFFRHQX1 \PIPELINE_STAGE4_S3_A_high_S2_reg_reg[2].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_79), .Q (S4_o_A_s[2]));
  DFFRHQX1 \PIPELINE_STAGE4_S3_A_high_S2_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_78), .Q (S4_o_A_s[3]));
  DFFSHQX8 PIPELINE_STAGE4_S4_ready_reg_sig_q_reg(.SN (rst_n), .CK
       (clk), .D (n_77), .Q (ready_o));
  DFFSHQX1 PIPELINE_STAGE4_square_sum_S4_reg_RegSumLow_0_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_76), .Q (S4_o_square_s[0]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[1].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_83), .Q (S4_o_square_s[1]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[2].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_81), .Q (S4_o_square_s[2]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[3].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_75), .Q (S4_o_square_s[3]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[4].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_74), .Q (S4_o_square_s[4]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[5].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_110), .Q (S4_o_square_s[5]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[6].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_71), .Q (S4_o_square_s[6]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[7].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_70), .Q (S4_o_square_s[7]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[8].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_69), .Q (S4_o_square_s[8]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[9].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_163), .Q (S4_o_square_s[9]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[10].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_183), .Q (S4_o_square_s[10]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[11].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_195), .Q (S4_o_square_s[11]));
  DFFRHQX1
       \PIPELINE_STAGE4_square_sum_S4_reg_reg_array[12].S4_square_reg_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_198), .Q (S4_o_square_s[12]));
  MX2X1 g4923__2398(.A (S3_o_co_square_s), .B (n_201), .S0 (en_pipe_i),
       .Y (n_203));
  MX2X1 g4924__5107(.A (S3_o_square_s[8]), .B (n_200), .S0 (en_pipe_i),
       .Y (n_202));
  OR2X1 g4926__6260(.A (n_122), .B (n_199), .Y (n_201));
  ADDHX1 g4927__4319(.A (n_123), .B (n_193), .CO (n_199), .S (n_200));
  MX2X1 g4928__8428(.A (S4_o_square_s[12]), .B (n_194), .S0
       (en_pipe_i), .Y (n_198));
  OAI2BB1X1 g4932__5526(.A0N (S4_o_co_square_s), .A1N (n_7), .B0
       (n_192), .Y (n_197));
  MX2X1 g4933__6783(.A (S3_o_square_s[7]), .B (n_190), .S0 (en_pipe_i),
       .Y (n_196));
  MX2X1 g4934__3680(.A (S4_o_square_s[11]), .B (n_188), .S0
       (en_pipe_i), .Y (n_195));
  CLKXOR2X1 g4935__1617(.A (S3_o_A_s[3]), .B (n_191), .Y (n_194));
  OR2X1 g4936__2802(.A (n_127), .B (n_189), .Y (n_193));
  NAND3X1 g4937__1705(.A (S3_o_A_s[3]), .B (en_pipe_i), .C (n_191), .Y
       (n_192));
  ADDHX1 g4938__5122(.A (n_128), .B (n_180), .CO (n_189), .S (n_190));
  ADDHX1 g4939__8246(.A (S3_o_A_s[2]), .B (n_181), .CO (n_191), .S
       (n_188));
  MX2X1 g4944__7098(.A (n_178), .B (root_o[7]), .S0 (n_7), .Y (n_187));
  MX2X1 g4945__6131(.A (S1_o_square_s[16]), .B (n_177), .S0
       (en_pipe_i), .Y (n_186));
  MX2X1 g4949__1881(.A (n_174), .B (root_o[6]), .S0 (n_7), .Y (n_185));
  MX2X1 g4950__5115(.A (S3_o_square_s[6]), .B (n_168), .S0 (en_pipe_i),
       .Y (n_184));
  MX2X1 g4951__7482(.A (S4_o_square_s[10]), .B (n_176), .S0
       (en_pipe_i), .Y (n_183));
  MX2X1 g4952__4733(.A (root_o[5]), .B (n_169), .S0 (en_pipe_i), .Y
       (n_182));
  OR2X1 g4953__6161(.A (n_120), .B (n_175), .Y (n_181));
  AO21X1 g4954__9315(.A0 (n_134), .A1 (n_158), .B0 (n_129), .Y (n_180));
  MX2X1 g4955__9945(.A (S1_o_square_s[15]), .B (n_173), .S0
       (en_pipe_i), .Y (n_179));
  CLKXOR2X1 g4956__2883(.A (n_20), .B (n_167), .Y (n_178));
  CLKXOR2X1 g4957__2346(.A (S4_o_A_s[3]), .B (n_172), .Y (n_177));
  ADDHX1 g4958__1666(.A (n_121), .B (n_153), .CO (n_175), .S (n_176));
  CLKXOR2X1 g4960__7410(.A (n_131), .B (n_164), .Y (n_174));
  ADDHX1 g4962__6417(.A (S4_o_A_s[2]), .B (n_150), .CO (n_172), .S
       (n_173));
  MX2X1 g4968__5477(.A (S2_o_root_s[3]), .B (n_156), .S0 (en_pipe_i),
       .Y (n_171));
  MX2X1 g4969__2398(.A (S2_o_co_square_s), .B (n_155), .S0 (en_pipe_i),
       .Y (n_170));
  CLKXOR2X1 g4970__5107(.A (n_66), .B (n_157), .Y (n_169));
  CLKXOR2X1 g4971__6260(.A (n_134), .B (n_158), .Y (n_168));
  AOI211XL g4972__4319(.A0 (n_131), .A1 (n_159), .B0 (n_117), .C0
       (n_111), .Y (n_167));
  MX2X1 g4974__8428(.A (S2_o_co_root_s), .B (n_143), .S0 (en_pipe_i),
       .Y (n_166));
  MX2X1 g4975__5526(.A (root_o[4]), .B (n_145), .S0 (en_pipe_i), .Y
       (n_165));
  OR2X1 g4977__6783(.A (n_111), .B (n_159), .Y (n_164));
  MX2X1 g4978__3680(.A (S4_o_square_s[9]), .B (n_147), .S0 (en_pipe_i),
       .Y (n_163));
  MX2X1 g4979__1617(.A (S1_o_square_s[14]), .B (n_151), .S0
       (en_pipe_i), .Y (n_162));
  MX2X1 g4980__2802(.A (S3_o_square_s[5]), .B (n_138), .S0 (en_pipe_i),
       .Y (n_161));
  MX2X1 g4981__1705(.A (n_149), .B (S2_o_square_s[4]), .S0 (n_7), .Y
       (n_160));
  NOR2X1 g4982__5122(.A (n_124), .B (n_152), .Y (n_157));
  NOR2BX1 g4983__8246(.AN (n_152), .B (n_66), .Y (n_159));
  OR2X1 g4984__7098(.A (n_112), .B (n_137), .Y (n_158));
  OAI2BB1X1 g4985__6131(.A0N (mux_root_i), .A1N (n_135), .B0 (n_144),
       .Y (n_156));
  OR2X1 g4986__1881(.A (n_118), .B (n_148), .Y (n_155));
  MX2X1 g4987__5115(.A (S2_o_root_s[2]), .B (n_139), .S0 (en_pipe_i),
       .Y (n_154));
  OR2X1 g4988__7482(.A (n_115), .B (n_146), .Y (n_153));
  ADDHX1 g4989__4733(.A (S4_o_A_s[1]), .B (n_113), .CO (n_150), .S
       (n_151));
  ADDHX1 g4990__6161(.A (n_19), .B (n_119), .CO (n_148), .S (n_149));
  ADDHX1 g4991__9315(.A (S3_o_co_square_s), .B (n_116), .CO (n_146), .S
       (n_147));
  ADDHX1 g4992__9945(.A (S2_o_co_root_s), .B (n_125), .CO (n_152), .S
       (n_145));
  AOI31X1 g4996__2883(.A0 (n_133), .A1 (n_64), .A2 (n_65), .B0 (n_136),
       .Y (n_144));
  OAI31X1 g4997__2346(.A0 (n_63), .A1 (n_132), .A2 (n_65), .B0 (n_67),
       .Y (n_143));
  MX2X1 g4998__1666(.A (S1_o_square_s[13]), .B (n_114), .S0
       (en_pipe_i), .Y (n_142));
  MX2X1 g4999__7410(.A (S2_o_root_s[1]), .B (n_126), .S0 (en_pipe_i),
       .Y (n_141));
  MX2X1 g5000__6417(.A (S2_o_square_s[3]), .B (n_109), .S0 (en_pipe_i),
       .Y (n_140));
  XNOR2X1 g5001__5477(.A (n_133), .B (n_63), .Y (n_139));
  CLKXOR2X1 g5002__2398(.A (S2_o_co_square_s), .B (n_130), .Y (n_138));
  AND2X1 g5003__5107(.A (S2_o_co_square_s), .B (n_130), .Y (n_137));
  AOI211XL g5004__6260(.A0 (n_295), .A1 (n_64), .B0 (mux_root_i), .C0
       (n_65), .Y (n_136));
  XNOR2X1 g5005__4319(.A (n_290), .B (n_65), .Y (n_135));
  INVX1 g5006(.A (n_133), .Y (n_132));
  ADDHX1 g5007__8428(.A (S2_o_B_s[1]), .B (S2_o_A_s[1]), .CO (n_129),
       .S (n_134));
  ADDHX1 g5008__5526(.A (S2_o_B_s[2]), .B (S2_o_A_s[2]), .CO (n_127),
       .S (n_128));
  ADDHX1 g5009__6783(.A (n_294), .B (n_8), .CO (n_133), .S (n_126));
  ADDHX1 g5010__3680(.A (S2_o_B_s[2]), .B (mux_root_i), .CO (n_124), .S
       (n_125));
  ADDHX1 g5011__1617(.A (S2_o_B_s[3]), .B (S2_o_A_s[3]), .CO (n_122),
       .S (n_123));
  ADDHX1 g5012__2802(.A (S3_o_B_s[1]), .B (S3_o_A_s[1]), .CO (n_120),
       .S (n_121));
  ADDHX1 g5013__1705(.A (S1_o_square_s[4]), .B (n_293), .CO (n_118), .S
       (n_119));
  ADDHX1 g5014__5122(.A (S2_o_root_h_s[2]), .B (mux_root_i), .CO
       (n_117), .S (n_131));
  ADDHX1 g5015__8246(.A (S3_o_B_s[0]), .B (S3_o_A_s[0]), .CO (n_115),
       .S (n_116));
  ADDHX1 g5016__7098(.A (S4_o_A_s[0]), .B (S4_o_co_square_s), .CO
       (n_113), .S (n_114));
  ADDHX1 g5017__6131(.A (S2_o_A_s[0]), .B (S2_o_B_s[0]), .CO (n_112),
       .S (n_130));
  MX2X1 g5102__1881(.A (S4_o_square_s[5]), .B (S3_o_square_s[5]), .S0
       (en_pipe_i), .Y (n_110));
  OAI2BB1X1 g5103__5115(.A0N (S1_o_square_s[3]), .A1N (n_301), .B0
       (n_19), .Y (n_109));
  MX2X1 g5104__7482(.A (S1_o_square_s[4]), .B (S4_o_square_s[4]), .S0
       (en_pipe_i), .Y (n_108));
  MX2X1 g5105__4733(.A (S1_o_square_s[5]), .B (S4_o_square_s[5]), .S0
       (en_pipe_i), .Y (n_107));
  MX2X1 g5106__6161(.A (S1_o_square_s[6]), .B (S4_o_square_s[6]), .S0
       (en_pipe_i), .Y (n_106));
  MX2X1 g5107__9315(.A (S3_o_A_s[0]), .B (S2_o_A_s[4]), .S0
       (en_pipe_i), .Y (n_105));
  MX2X1 g5108__9945(.A (S1_o_square_s[7]), .B (S4_o_square_s[7]), .S0
       (en_pipe_i), .Y (n_104));
  MX2X1 g5109__2883(.A (S3_o_A_s[1]), .B (S2_o_A_s[5]), .S0
       (en_pipe_i), .Y (n_103));
  MX2X1 g5110__2346(.A (S3_o_A_s[2]), .B (S2_o_A_s[6]), .S0
       (en_pipe_i), .Y (n_102));
  MX2X1 g5111__1666(.A (S3_o_A_s[3]), .B (S2_o_A_s[7]), .S0
       (en_pipe_i), .Y (n_101));
  MX2X1 g5112__7410(.A (S1_o_square_s[8]), .B (S4_o_square_s[8]), .S0
       (en_pipe_i), .Y (n_100));
  MX2X1 g5113__6417(.A (S3_o_A_s[4]), .B (S2_o_A_s[8]), .S0
       (en_pipe_i), .Y (n_99));
  MX2X1 g5114__5477(.A (S1_o_square_s[9]), .B (S4_o_square_s[9]), .S0
       (en_pipe_i), .Y (n_98));
  MX2X1 g5115__2398(.A (S3_o_A_s[5]), .B (S2_o_A_s[9]), .S0
       (en_pipe_i), .Y (n_97));
  MX2X1 g5116__5107(.A (S3_o_A_s[6]), .B (S2_o_A_s[10]), .S0
       (en_pipe_i), .Y (n_96));
  MX2X1 g5117__6260(.A (S3_o_A_s[7]), .B (S2_o_A_s[11]), .S0
       (en_pipe_i), .Y (n_95));
  MX2X1 g5118__4319(.A (S1_o_square_s[10]), .B (S4_o_square_s[10]), .S0
       (en_pipe_i), .Y (n_94));
  MX2X1 g5119__8428(.A (S3_o_B_s[0]), .B (S2_o_root_h_s[2]), .S0
       (en_pipe_i), .Y (n_93));
  MX2X1 g5120__5526(.A (S1_o_square_s[11]), .B (S4_o_square_s[11]), .S0
       (en_pipe_i), .Y (n_92));
  MX2X1 g5121__6783(.A (S3_o_B_s[1]), .B (S2_o_B_s[5]), .S0
       (en_pipe_i), .Y (n_91));
  MX2X1 g5122__3680(.A (S3_o_square_s[0]), .B (S2_o_square_s[0]), .S0
       (en_pipe_i), .Y (n_90));
  MX2X1 g5123__1617(.A (S3_o_square_s[1]), .B (S2_o_square_s[1]), .S0
       (en_pipe_i), .Y (n_89));
  MX2X1 g5124__2802(.A (S1_o_square_s[12]), .B (S4_o_square_s[12]), .S0
       (en_pipe_i), .Y (n_88));
  MX2X1 g5125__1705(.A (S3_o_square_s[2]), .B (S2_o_square_s[2]), .S0
       (en_pipe_i), .Y (n_87));
  MX2X1 g5126__5122(.A (S3_o_square_s[3]), .B (S2_o_square_s[3]), .S0
       (en_pipe_i), .Y (n_86));
  MX2X1 g5127__8246(.A (S3_o_square_s[4]), .B (S2_o_square_s[4]), .S0
       (en_pipe_i), .Y (n_85));
  MX2X1 g5128__7098(.A (S2_o_A_s[1]), .B (S1_o_square_s[6]), .S0
       (en_pipe_i), .Y (n_84));
  MX2X1 g5129__6131(.A (S4_o_square_s[1]), .B (S3_o_square_s[1]), .S0
       (en_pipe_i), .Y (n_83));
  MX2X1 g5130__1881(.A (S4_o_A_s[0]), .B (S3_o_A_s[4]), .S0
       (en_pipe_i), .Y (n_82));
  MX2X1 g5131__5115(.A (S4_o_square_s[2]), .B (S3_o_square_s[2]), .S0
       (en_pipe_i), .Y (n_81));
  MX2X1 g5132__7482(.A (S4_o_A_s[1]), .B (S3_o_A_s[5]), .S0
       (en_pipe_i), .Y (n_80));
  MX2X1 g5133__4733(.A (S4_o_A_s[2]), .B (S3_o_A_s[6]), .S0
       (en_pipe_i), .Y (n_79));
  MX2X1 g5134__6161(.A (S4_o_A_s[3]), .B (S3_o_A_s[7]), .S0
       (en_pipe_i), .Y (n_78));
  MX2X1 g5135__9315(.A (ready_o), .B (ready_i), .S0 (en_pipe_i), .Y
       (n_77));
  MX2X1 g5136__9945(.A (S4_o_square_s[0]), .B (S3_o_square_s[0]), .S0
       (en_pipe_i), .Y (n_76));
  MX2X1 g5137__2883(.A (S4_o_square_s[3]), .B (S3_o_square_s[3]), .S0
       (en_pipe_i), .Y (n_75));
  MX2X1 g5138__2346(.A (S4_o_square_s[4]), .B (S3_o_square_s[4]), .S0
       (en_pipe_i), .Y (n_74));
  MX2X1 g5139__1666(.A (N_o), .B (S1_N_s), .S0 (en_pipe_i), .Y (n_73));
  MX2X1 g5140__7410(.A (S2_o_A_s[0]), .B (S1_o_square_s[5]), .S0
       (en_pipe_i), .Y (n_72));
  MX2X1 g5141__6417(.A (S4_o_square_s[6]), .B (S3_o_square_s[6]), .S0
       (en_pipe_i), .Y (n_71));
  MX2X1 g5142__5477(.A (S4_o_square_s[7]), .B (S3_o_square_s[7]), .S0
       (en_pipe_i), .Y (n_70));
  MX2X1 g5143__2398(.A (S4_o_square_s[8]), .B (S3_o_square_s[8]), .S0
       (en_pipe_i), .Y (n_69));
  MX2X1 g5144__5107(.A (S2_o_A_s[2]), .B (S1_o_square_s[7]), .S0
       (en_pipe_i), .Y (n_68));
  OAI21X1 g5145__6260(.A0 (n_290), .A1 (n_298), .B0 (mux_root_i), .Y
       (n_67));
  AOI2BB1X1 g5146__4319(.A0N (S2_o_B_s[2]), .A1N (S2_o_B_s[3]), .B0
       (n_8), .Y (n_111));
  INVX1 g5147(.A (n_64), .Y (n_63));
  MX2X1 g5148__8428(.A (S1_o_square_s[2]), .B (S4_o_square_s[2]), .S0
       (en_pipe_i), .Y (n_62));
  MX2X1 g5149__5526(.A (S2_o_A_s[4]), .B (S1_o_square_s[9]), .S0
       (en_pipe_i), .Y (n_61));
  MX2X1 g5150__6783(.A (S2_o_A_s[5]), .B (S1_o_square_s[10]), .S0
       (en_pipe_i), .Y (n_60));
  MX2X1 g5151__3680(.A (n_293), .B (S2_o_root_s[1]), .S0 (en_pipe_i),
       .Y (n_59));
  MX2X1 g5152__1617(.A (S2_o_A_s[6]), .B (S1_o_square_s[11]), .S0
       (en_pipe_i), .Y (n_58));
  MX2X1 g5153__2802(.A (S2_o_A_s[7]), .B (S1_o_square_s[12]), .S0
       (en_pipe_i), .Y (n_57));
  MX2X1 g5154__1705(.A (S2_o_A_s[8]), .B (S1_o_square_s[13]), .S0
       (en_pipe_i), .Y (n_56));
  MX2X1 g5155__5122(.A (S2_o_A_s[9]), .B (S1_o_square_s[14]), .S0
       (en_pipe_i), .Y (n_55));
  MX2X1 g5156__8246(.A (S2_o_A_s[10]), .B (S1_o_square_s[15]), .S0
       (en_pipe_i), .Y (n_54));
  MX2X1 g5157__7098(.A (S2_o_A_s[11]), .B (S1_o_square_s[16]), .S0
       (en_pipe_i), .Y (n_53));
  MX2X1 g5158__6131(.A (S2_o_B_s[0]), .B (n_289), .S0 (en_pipe_i), .Y
       (n_52));
  MX2X1 g5159__1881(.A (S2_o_B_s[1]), .B (n_297), .S0 (en_pipe_i), .Y
       (n_51));
  MX2X1 g5160__5115(.A (n_289), .B (S2_o_root_s[2]), .S0 (en_pipe_i),
       .Y (n_50));
  MX2X1 g5161__7482(.A (S2_o_B_s[2]), .B (root_o[4]), .S0 (en_pipe_i),
       .Y (n_49));
  MX2X1 g5162__4733(.A (S2_o_B_s[3]), .B (root_o[5]), .S0 (en_pipe_i),
       .Y (n_48));
  MX2X1 g5163__6161(.A (S2_o_root_h_s[2]), .B (root_o[6]), .S0
       (en_pipe_i), .Y (n_47));
  MX2X1 g5164__9315(.A (S2_o_B_s[5]), .B (root_o[7]), .S0 (en_pipe_i),
       .Y (n_46));
  MX2X1 g5165__9945(.A (n_297), .B (S2_o_root_s[3]), .S0 (en_pipe_i),
       .Y (n_45));
  MX2X1 g5166__2883(.A (S1_o_square_s[0]), .B (S4_o_square_s[0]), .S0
       (en_pipe_i), .Y (n_44));
  MX2X1 g5167__2346(.A (S1_o_square_s[1]), .B (S4_o_square_s[1]), .S0
       (en_pipe_i), .Y (n_43));
  MX2X1 g5168__1666(.A (S2_o_square_s[0]), .B (S1_o_square_s[0]), .S0
       (en_pipe_i), .Y (n_42));
  MX2X1 g5169__7410(.A (S2_o_square_s[1]), .B (S1_o_square_s[1]), .S0
       (en_pipe_i), .Y (n_41));
  MX2X1 g5170__6417(.A (S2_o_square_s[2]), .B (S1_o_square_s[2]), .S0
       (en_pipe_i), .Y (n_40));
  MX2X1 g5171__5477(.A (S2_o_A_s[3]), .B (S1_o_square_s[8]), .S0
       (en_pipe_i), .Y (n_39));
  MX2X1 g5172__2398(.A (S1_o_square_s[3]), .B (S4_o_square_s[3]), .S0
       (en_pipe_i), .Y (n_38));
  OAI22X4 g5173__5107(.A0 (n_247), .A1 (wr_input_i), .B0 (n_0), .B1
       (n_274), .Y (n_37));
  OAI22X4 g5174__6260(.A0 (n_246), .A1 (wr_input_i), .B0 (n_0), .B1
       (n_273), .Y (n_36));
  OAI22X4 g5175__4319(.A0 (n_248), .A1 (wr_input_i), .B0 (n_0), .B1
       (n_275), .Y (n_35));
  OAI22X4 g5176__8428(.A0 (n_249), .A1 (wr_input_i), .B0 (n_0), .B1
       (n_276), .Y (n_34));
  OAI22X4 g5177__5526(.A0 (n_235), .A1 (wr_input_i), .B0 (n_0), .B1
       (n_277), .Y (n_33));
  OAI22X4 g5178__6783(.A0 (n_221), .A1 (wr_input_i), .B0 (n_0), .B1
       (n_278), .Y (n_32));
  OAI22X4 g5179__3680(.A0 (n_222), .A1 (wr_input_i), .B0 (n_0), .B1
       (n_279), .Y (n_31));
  OAI22X4 g5180__1617(.A0 (n_223), .A1 (wr_input_i), .B0 (n_0), .B1
       (n_280), .Y (n_30));
  OAI22X4 g5181__2802(.A0 (n_224), .A1 (wr_input_i), .B0 (n_0), .B1
       (n_281), .Y (n_29));
  OAI22X4 g5182__1705(.A0 (n_225), .A1 (wr_input_i), .B0 (n_0), .B1
       (n_282), .Y (n_28));
  OAI22X4 g5183__5122(.A0 (n_226), .A1 (wr_input_i), .B0 (n_0), .B1
       (n_283), .Y (n_27));
  OAI22X4 g5184__8246(.A0 (n_229), .A1 (wr_input_i), .B0 (n_0), .B1
       (n_284), .Y (n_26));
  OAI22X4 g5185__7098(.A0 (n_238), .A1 (wr_input_i), .B0 (n_0), .B1
       (n_285), .Y (n_25));
  OAI22X4 g5186__6131(.A0 (n_239), .A1 (wr_input_i), .B0 (n_0), .B1
       (n_286), .Y (n_24));
  OAI22X4 g5187__1881(.A0 (n_250), .A1 (wr_input_i), .B0 (n_0), .B1
       (n_287), .Y (n_23));
  OAI22X4 g5188__5115(.A0 (n_236), .A1 (wr_input_i), .B0 (n_0), .B1
       (n_288), .Y (n_22));
  XNOR2X1 g5189__7482(.A (n_301), .B (n_7), .Y (n_21));
  XNOR2X1 g5190__4733(.A (S2_o_B_s[5]), .B (mux_root_i), .Y (n_20));
  XNOR2X1 g5191__6161(.A (S2_o_B_s[3]), .B (mux_root_i), .Y (n_66));
  XNOR2X1 g5192__9315(.A (n_299), .B (mux_root_i), .Y (n_65));
  XNOR2X1 g5193__9945(.A (n_291), .B (n_8), .Y (n_64));
  OR2X1 g5194__2883(.A (S1_o_square_s[3]), .B (n_302), .Y (n_19));
  INVX3 g5205(.A (mux_root_i), .Y (n_8));
  INVX3 g5206(.A (en_pipe_i), .Y (n_7));
  CLKINVX6 g5213(.A (wr_input_i), .Y (n_0));
  CLKINVX6 fopt(.A (input_i[0]), .Y (n_273));
  CLKINVX6 fopt5214(.A (input_i[1]), .Y (n_274));
  CLKINVX6 fopt5215(.A (input_i[2]), .Y (n_275));
  CLKINVX6 fopt5216(.A (input_i[3]), .Y (n_276));
  CLKINVX6 fopt5217(.A (input_i[4]), .Y (n_277));
  CLKINVX6 fopt5218(.A (input_i[5]), .Y (n_278));
  CLKINVX6 fopt5219(.A (input_i[6]), .Y (n_279));
  CLKINVX6 fopt5220(.A (input_i[7]), .Y (n_280));
  CLKINVX6 fopt5221(.A (input_i[8]), .Y (n_281));
  CLKINVX6 fopt5222(.A (input_i[9]), .Y (n_282));
  CLKINVX6 fopt5223(.A (input_i[10]), .Y (n_283));
  CLKINVX6 fopt5224(.A (input_i[11]), .Y (n_284));
  CLKINVX6 fopt5225(.A (input_i[12]), .Y (n_285));
  CLKINVX6 fopt5226(.A (input_i[13]), .Y (n_286));
  CLKINVX6 fopt5227(.A (input_i[14]), .Y (n_287));
  CLKINVX6 fopt5228(.A (input_i[15]), .Y (n_288));
  CLKBUFX3 fopt5229(.A (n_290), .Y (n_289));
  BUFX6 fopt1(.A (n_291), .Y (n_290));
  CLKBUFX3 fopt2(.A (root_o[2]), .Y (n_291));
  BUFX20 fopt3(.A (S1_o_root_s[2]), .Y (root_o[2]));
  CLKBUFX3 fopt5230(.A (n_294), .Y (n_293));
  CLKBUFX3 fopt5231(.A (n_295), .Y (n_294));
  CLKBUFX3 fopt5232(.A (root_o[1]), .Y (n_295));
  BUFX20 fopt5233(.A (S1_o_root_s[1]), .Y (root_o[1]));
  CLKBUFX3 fopt5234(.A (n_298), .Y (n_297));
  CLKBUFX3 fopt5235(.A (n_299), .Y (n_298));
  CLKBUFX3 fopt5236(.A (root_o[3]), .Y (n_299));
  BUFX20 fopt5237(.A (S1_o_root_s[3]), .Y (root_o[3]));
  CLKBUFX3 fopt5238(.A (n_302), .Y (n_301));
  CLKBUFX3 fopt5239(.A (root_o[0]), .Y (n_302));
  BUFX20 fopt5240(.A (S1_o_root_s[0]), .Y (root_o[0]));
endmodule

module Square_root(valor_i, clk, rst_n, ready_o, root_o);
  input [15:0] valor_i;
  input clk, rst_n;
  output ready_o;
  output [7:0] root_o;
  wire [15:0] valor_i;
  wire clk, rst_n;
  wire ready_o;
  wire [7:0] root_o;
  wire [2:0] CONTROL_PATH_CurrentState;
  wire N_s, en_pipe_s, mux_root_s, n_0, n_1, n_2, n_3, n_4;
  wire n_5, ready_s, wr_input_s;
  DataPath DATA_PATH(.clk (clk), .rst_n (rst_n), .input_i (valor_i),
       .root_o (root_o), .ready_o (ready_o), .wr_input_i (wr_input_s),
       .en_pipe_i (en_pipe_s), .ready_i (ready_s), .mux_root_i
       (mux_root_s), .N_o (N_s));
  OR2X6 g118__2346(.A (CONTROL_PATH_CurrentState[0]), .B (n_5), .Y
       (en_pipe_s));
  OR2X1 g119__1666(.A (CONTROL_PATH_CurrentState[2]), .B
       (CONTROL_PATH_CurrentState[0]), .Y (ready_s));
  NOR2BX1 g120__7410(.AN (mux_root_s), .B
       (CONTROL_PATH_CurrentState[2]), .Y (n_5));
  NOR2X4 g121__6417(.A (mux_root_s), .B (CONTROL_PATH_CurrentState[0]),
       .Y (wr_input_s));
  DFFRHQX4 \CONTROL_PATH_CurrentState_reg[1] (.RN (rst_n), .CK (clk),
       .D (n_4), .Q (mux_root_s));
  OAI21X1 g141__5477(.A0 (CONTROL_PATH_CurrentState[2]), .A1 (n_3), .B0
       (n_0), .Y (n_4));
  DFFRHQX1 \CONTROL_PATH_CurrentState_reg[0] (.RN (rst_n), .CK (clk),
       .D (n_2), .Q (CONTROL_PATH_CurrentState[0]));
  AOI21X1 g143__2398(.A0 (CONTROL_PATH_CurrentState[0]), .A1 (N_s), .B0
       (mux_root_s), .Y (n_3));
  DFFRHQX1 \CONTROL_PATH_CurrentState_reg[2] (.RN (rst_n), .CK (clk),
       .D (n_1), .Q (CONTROL_PATH_CurrentState[2]));
  NOR2X1 g145__5107(.A (mux_root_s), .B (CONTROL_PATH_CurrentState[2]),
       .Y (n_2));
  INVX1 g146(.A (n_0), .Y (n_1));
  NAND2BX1 g147__6260(.AN (CONTROL_PATH_CurrentState[0]), .B
       (mux_root_s), .Y (n_0));
endmodule

