
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep  8 2025 01:38:05 -03 (Sep  8 2025 04:38:05 UTC)

// Verification Directory fv/square_root_pipe 

module square_root_pipe(valor_i, clk, rst_n, ready_o, root_o);
  input [15:0] valor_i;
  input clk, rst_n;
  output ready_o;
  output [7:0] root_o;
  wire [15:0] valor_i;
  wire clk, rst_n;
  wire ready_o;
  wire [7:0] root_o;
  wire [7:0] DATA_PATH_S2_o_square_adder_sum_l_s;
  wire [16:0] DATA_PATH_S1_o_square2_s;
  wire [16:0] DATA_PATH_S1_o_square1_s;
  wire [1:0] CONTROL_PATH_CurrentState;
  wire [7:0] DATA_PATH_S1_o_root_s;
  wire [8:0] DATA_PATH_S2_o_A_high_s;
  wire [15:0] DATA_PATH_S1_o_input_s;
  wire [8:0] DATA_PATH_S2_o_B_high_s;
  wire DATA_PATH_S1_o_wr_square_s, DATA_PATH_S2_o_square_adder_co_l_s,
       N_s, UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3;
  wire UNCONNECTED4, UNCONNECTED5, UNCONNECTED6, UNCONNECTED7,
       UNCONNECTED8, UNCONNECTED9, UNCONNECTED10, UNCONNECTED11;
  wire UNCONNECTED12, UNCONNECTED13, UNCONNECTED14, UNCONNECTED15, n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_33, n_34, n_37, n_39;
  wire n_40, n_42, n_43, n_44, n_45, n_46, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_147, n_148, n_149, n_150, n_151, n_152, n_153;
  wire n_154, n_155, n_156, n_157, n_158, n_159, n_160, n_161;
  wire n_162, n_163, n_164, n_165, n_166, n_167, n_168, n_169;
  wire n_170, n_171, n_172, n_173, n_174, n_175, n_176, n_177;
  wire n_178, n_179, n_180, n_181, n_182, n_183, n_184, n_185;
  wire n_186, n_187, n_188, n_189, n_190, n_191, n_192, n_193;
  wire n_194, n_195, n_196, n_197, n_198, n_199, n_200, n_201;
  wire n_202, n_203, n_204, n_205, n_206, n_207, n_208, n_209;
  wire n_210, n_211, n_212, n_213, n_214, n_215, n_216, n_217;
  wire n_218, n_219, n_220, n_221, n_222, n_223, n_224, n_225;
  wire n_226, n_227, n_228, n_229, n_230, n_231, n_232, n_233;
  wire n_234, n_235, n_236, n_237, n_238, n_239, n_240, n_241;
  wire n_242, n_243, n_244, n_245, n_246, n_247, n_248, n_249;
  wire n_250, n_251, n_252, n_253, n_254, n_255, n_256, n_257;
  wire n_258, n_259, n_260, n_261, n_262, n_263, n_264, n_265;
  wire n_266, n_267, n_268, n_269, n_270, n_271, n_272, n_273;
  wire n_274, n_275, n_276, n_277, n_278, n_279, n_280, n_281;
  wire n_282, n_283, n_284, n_285, n_286, n_287, n_288, n_289;
  wire n_290, n_291, n_292, n_293, n_294, n_295, n_296, n_297;
  wire n_298, n_299, n_300, n_301, n_302, n_303, n_304, n_305;
  wire n_306, n_307, n_308, n_309, n_310, n_311, n_312, n_313;
  wire n_314, n_315, n_316, n_317, n_318, n_319, n_320, n_321;
  wire n_322, n_323, n_324, n_325, n_326, n_327, n_328, n_330;
  wire n_331, n_332, n_333, n_334, n_335, n_336, n_337, n_338;
  wire n_339, n_340, n_341, n_342, n_343, n_344, n_345, n_346;
  wire n_347, n_348, n_349, n_350, n_351, n_352, n_353, n_354;
  wire n_355, n_357, n_358, n_359, n_360, n_361, n_362, n_363;
  wire n_364, n_365, n_366, n_367, n_368, n_369, n_370, n_371;
  wire n_372, n_373, n_374, n_375, n_377, n_378, n_379, n_380;
  wire n_381, n_382, n_383, n_384, n_385, n_386, n_387, n_388;
  wire n_389, n_390, n_391, n_392, n_393, n_394, n_395, n_396;
  wire n_397, n_398, n_399, n_400, n_401, n_402, n_403, n_404;
  wire n_405, n_406, n_407, n_408, n_409, n_410, n_411, n_430;
  wire n_431, n_432, n_433, n_435, n_436, n_438, n_439, ready_s;
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_411), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[7]));
  DFFRHQX1 DATA_PATH_PIPELINE_STAGE2_N_reg_sig_q_reg(.RN (rst_n), .CK
       (clk), .D (n_410), .Q (N_s));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_409), .Q (root_o[7]));
  OAI21X4 g10161__2398(.A0 (n_317), .A1 (n_404), .B0 (n_408), .Y
       (n_411));
  NAND2X4 g10186__5107(.A (n_400), .B (n_407), .Y (n_410));
  CLKXOR2X1 g10173__6260(.A (root_o[7]), .B (n_405), .Y (n_409));
  DFFRHQX2 DATA_PATH_PIPELINE_STAGE2_Co_reg_sig_q_reg(.RN (rst_n), .CK
       (clk), .D (n_406), .Q (DATA_PATH_S2_o_square_adder_co_l_s));
  AOI21X4 g10174__4319(.A0 (n_352), .A1 (n_388), .B0 (n_232), .Y
       (n_408));
  NOR2X4 g10203__8428(.A (n_393), .B (n_403), .Y (n_407));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_402), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[6]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_401), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[5]));
  NAND2X4 g10182__5526(.A (n_386), .B (n_361), .Y (n_406));
  DFFRHQX2
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[11].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_390), .Q
       (DATA_PATH_S1_o_square2_s[11]));
  DFFRHQX2
       \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[11].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_394), .Q
       (DATA_PATH_S1_o_square1_s[11]));
  AOI2BB1X4 g10209__6783(.A0N (n_273), .A1N (n_349), .B0 (n_381), .Y
       (n_405));
  NOR2X2 g10184__3680(.A (n_350), .B (n_387), .Y (n_404));
  NOR3X4 g10215__1617(.A (n_379), .B (n_364), .C (n_392), .Y (n_403));
  MXI3X1 g10162__2802(.A (n_265), .B (n_303), .C (n_7), .S0 (n_343),
       .S1 (n_362), .Y (n_402));
  OAI21X4 g10187__1705(.A0 (n_292), .A1 (n_438), .B0 (n_378), .Y
       (n_401));
  NOR2X6 g10205__5122(.A (n_375), .B (n_380), .Y (n_400));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_382), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[3]));
  CLKMX2X3 g10175__8246(.A (DATA_PATH_S1_o_square2_s[15]), .B (n_384),
       .S0 (n_397), .Y (n_399));
  OAI2BB1X1 g10156__7098(.A0N (n_397), .A1N (n_395), .B0 (n_34), .Y
       (n_398));
  OAI2BB1X1 g10157__6131(.A0N (CONTROL_PATH_CurrentState[1]), .A1N
       (n_395), .B0 (n_62), .Y (n_396));
  OAI2BB2X2 g10190__1881(.A0N (DATA_PATH_S1_o_square1_s[11]), .A1N
       (n_397), .B0 (n_397), .B1 (n_389), .Y (n_394));
  NOR2X4 g10214__5115(.A (n_336), .B (n_392), .Y (n_393));
  OAI2BB1X4 g10176__7482(.A0N (DATA_PATH_S1_o_square1_s[13]), .A1N
       (n_397), .B0 (n_374), .Y (n_391));
  OAI2BB2X2 g10195__4733(.A0N (DATA_PATH_S1_o_square2_s[11]), .A1N
       (CONTROL_PATH_CurrentState[1]), .B0
       (CONTROL_PATH_CurrentState[1]), .B1 (n_389), .Y (n_390));
  CLKINVX8 g10196(.A (n_387), .Y (n_388));
  NAND2X4 g10207__6161(.A (n_347), .B (n_439), .Y (n_386));
  CLKMX2X3 g10177__9315(.A (DATA_PATH_S1_o_square1_s[15]), .B (n_384),
       .S0 (CONTROL_PATH_CurrentState[1]), .Y (n_385));
  OAI2BB1X4 g10178__9945(.A0N (DATA_PATH_S1_o_square2_s[13]), .A1N
       (CONTROL_PATH_CurrentState[1]), .B0 (n_373), .Y (n_383));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[16].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_369), .Q
       (DATA_PATH_S1_o_square2_s[16]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[16].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_371), .Q
       (DATA_PATH_S1_o_square1_s[16]));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[10].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_366), .Q
       (DATA_PATH_S1_o_square1_s[10]), .QN (UNCONNECTED));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_370), .Q
       (DATA_PATH_S1_o_root_s[6]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_363), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[4]));
  OAI22X4 g10224__2883(.A0 (n_164), .A1 (n_344), .B0 (n_19), .B1
       (n_190), .Y (n_382));
  OAI21X4 g10212__2346(.A0 (n_132), .A1 (n_348), .B0 (n_281), .Y
       (n_381));
  NOR3X4 g10245__1666(.A (n_379), .B (n_334), .C (n_338), .Y (n_380));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[12].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_359), .Q
       (DATA_PATH_S1_o_square2_s[12]));
  DFFRHQX8 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_354), .Q
       (DATA_PATH_S1_o_root_s[3]));
  AOI21X4 g10204__7410(.A0 (n_298), .A1 (n_342), .B0 (n_172), .Y
       (n_378));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[12].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_360), .Q
       (DATA_PATH_S1_o_square1_s[12]));
  NOR2X8 g10198__6417(.A (n_346), .B (n_377), .Y (n_387));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_357), .Q
       (DATA_PATH_S1_o_root_s[5]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_353), .Q
       (DATA_PATH_S1_o_root_s[4]));
  OAI31X4 g10211__5477(.A0 (n_316), .A1 (n_304), .A2 (n_379), .B0
       (n_224), .Y (n_375));
  NAND2X6 g10183__2398(.A (CONTROL_PATH_CurrentState[1]), .B (n_372),
       .Y (n_374));
  NAND2X8 g10185__5107(.A (n_397), .B (n_372), .Y (n_373));
  MX2X1 g10221__6260(.A (DATA_PATH_S1_o_square1_s[16]), .B (n_368), .S0
       (CONTROL_PATH_CurrentState[1]), .Y (n_371));
  MXI3X1 g10189__4319(.A (n_201), .B (n_169), .C (n_89), .S0 (n_288),
       .S1 (n_355), .Y (n_370));
  MX2X1 g10226__8428(.A (DATA_PATH_S1_o_square2_s[16]), .B (n_368), .S0
       (n_397), .Y (n_369));
  OAI2BB2X4 g10191__5526(.A0N (DATA_PATH_S1_o_square2_s[10]), .A1N
       (CONTROL_PATH_CurrentState[1]), .B0
       (CONTROL_PATH_CurrentState[1]), .B1 (n_365), .Y (n_367));
  OAI2BB2X4 g10192__6783(.A0N (DATA_PATH_S1_o_square1_s[10]), .A1N
       (n_397), .B0 (n_397), .B1 (n_365), .Y (n_366));
  NAND2X4 g10259__3680(.A (n_335), .B (n_345), .Y (n_364));
  OAI21X4 g10193__1617(.A0 (n_362), .A1 (n_332), .B0 (n_233), .Y
       (n_363));
  NAND2X6 g10237__2802(.A (n_339), .B (n_337), .Y (n_392));
  OA21X2 g10213__1705(.A0 (n_325), .A1 (n_351), .B0 (n_326), .Y
       (n_361));
  OAI2BB1X1 g10225__5122(.A0N (CONTROL_PATH_CurrentState[1]), .A1N
       (n_358), .B0 (n_59), .Y (n_360));
  OAI2BB1X1 g10227__8246(.A0N (n_397), .A1N (n_358), .B0 (n_42), .Y
       (n_359));
  MXI2X4 g10208__7098(.A (DATA_PATH_S2_o_A_high_s[7]), .B (n_1), .S0
       (n_312), .Y (n_384));
  AOI2BB1X2 g10228__6131(.A0N (n_45), .A1N (n_330), .B0 (n_331), .Y
       (n_389));
  NOR2X8 g10218__1881(.A (n_432), .B (n_341), .Y (n_377));
  CLKMX2X3 g10206__5115(.A (n_309), .B (root_o[5]), .S0 (n_355), .Y
       (n_357));
  CLKMX2X3 g10194__7482(.A (n_314), .B (n_80), .S0 (n_240), .Y (n_354));
  CLKMX2X3 g10241__4733(.A (n_55), .B (n_318), .S0 (n_319), .Y (n_353));
  NOR2X4 g10234__6161(.A (n_351), .B (n_350), .Y (n_352));
  CLKINVX4 g10256(.A (n_348), .Y (n_349));
  CLKXOR2X2 g10179__9315(.A (DATA_PATH_S2_o_A_high_s[6]), .B (n_340),
       .Y (n_395));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_333), .Q
       (DATA_PATH_S1_o_root_s[1]));
  NOR2X4 g10247__9945(.A (n_346), .B (n_351), .Y (n_347));
  CLKAND2X2 g10276__2883(.A (n_259), .B (n_315), .Y (n_345));
  XNOR2X2 g10275__2346(.A (n_220), .B (n_290), .Y (n_344));
  OAI21X4 g10230__1666(.A0 (n_245), .A1 (n_431), .B0 (n_301), .Y
       (n_343));
  INVX2 g10232(.A (n_341), .Y (n_342));
  NOR2X8 g10231__7410(.A (n_313), .B (n_340), .Y (n_372));
  DFFRX2
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[9].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_310), .Q
       (DATA_PATH_S1_o_square2_s[9]), .QN (UNCONNECTED0));
  AOI2BB1X4 g10258__6417(.A0N (n_293), .A1N (n_289), .B0 (n_321), .Y
       (n_339));
  INVX2 g10255(.A (n_337), .Y (n_338));
  NAND3X4 g10248__5477(.A (n_294), .B (n_302), .C (n_335), .Y (n_336));
  NOR2X6 g10264__2398(.A (n_197), .B (n_322), .Y (n_348));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_320), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[2]));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[9].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_307), .Q
       (DATA_PATH_S1_o_square1_s[9]), .QN (UNCONNECTED1));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_308), .Q
       (DATA_PATH_S1_o_root_s[2]));
  OAI2BB1X4 g10268__5107(.A0N (n_199), .A1N (n_323), .B0 (n_335), .Y
       (n_334));
  CLKXOR2X1 g10282__6260(.A (n_196), .B (n_282), .Y (n_333));
  XNOR2X2 g10222__4319(.A (n_250), .B (n_430), .Y (n_332));
  NOR3X4 g10240__8428(.A (n_328), .B (n_330), .C (n_327), .Y (n_331));
  NOR2X8 g10236__5526(.A (n_249), .B (n_431), .Y (n_341));
  XNOR2X2 g10229__6783(.A (n_328), .B (n_327), .Y (n_365));
  MXI2X2 g10260__3680(.A (n_285), .B
       (DATA_PATH_S2_o_square_adder_co_l_s), .S0 (n_226), .Y (n_326));
  CLKINVX4 g10257(.A (n_325), .Y (n_350));
  DFFRHQX2
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[8].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_297), .Q
       (DATA_PATH_S1_o_square2_s[8]));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[8].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_296), .Q
       (DATA_PATH_S1_o_square1_s[8]));
  OAI2BB2X4 g10262__1617(.A0N (DATA_PATH_S2_o_A_high_s[8]), .A1N
       (n_324), .B0 (n_324), .B1 (DATA_PATH_S2_o_A_high_s[8]), .Y
       (n_368));
  AOI21X4 g10263__2802(.A0 (n_323), .A1 (n_255), .B0 (n_257), .Y
       (n_337));
  NOR2X6 g10269__1705(.A (n_192), .B (n_256), .Y (n_322));
  OAI21X4 g10277__5122(.A0 (n_284), .A1 (n_234), .B0 (n_188), .Y
       (n_321));
  CLKMX2X3 g10278__8246(.A (DATA_PATH_S2_o_square_adder_sum_l_s[2]), .B
       (n_222), .S0 (n_319), .Y (n_320));
  XNOR2X1 g10281__7098(.A (n_193), .B (n_212), .Y (n_318));
  OR2X1 g10270__6131(.A (n_362), .B (n_305), .Y (n_317));
  INVX2 g10303(.A (n_335), .Y (n_316));
  AOI31X4 g10304__1881(.A0 (DATA_PATH_S1_o_input_s[2]), .A1 (n_436),
       .A2 (n_206), .B0 (n_157), .Y (n_315));
  CLKXOR2X1 g10223__5115(.A (n_171), .B (n_219), .Y (n_314));
  NOR2X4 g10233__7482(.A (DATA_PATH_S2_o_A_high_s[5]), .B (n_311), .Y
       (n_313));
  NAND2X4 g10235__4733(.A (n_105), .B (n_311), .Y (n_312));
  CLKMX2X3 g10244__6161(.A (DATA_PATH_S1_o_square2_s[9]), .B (n_306),
       .S0 (n_397), .Y (n_310));
  CLKXOR2X1 g10239__9315(.A (n_287), .B (n_242), .Y (n_309));
  MX2X1 g10242__9945(.A (n_195), .B (n_231), .S0 (n_319), .Y (n_308));
  CLKMX2X3 g10243__2883(.A (DATA_PATH_S1_o_square1_s[9]), .B (n_306),
       .S0 (CONTROL_PATH_CurrentState[1]), .Y (n_307));
  CLKAND2X6 g10238__2346(.A (DATA_PATH_S2_o_A_high_s[5]), .B (n_311),
       .Y (n_340));
  AOI2BB1X4 g10283__1666(.A0N (DATA_PATH_S2_o_A_high_s[4]), .A1N
       (n_330), .B0 (n_311), .Y (n_358));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_248), .Q
       (DATA_PATH_S2_o_A_high_s[6]));
  NAND2X8 g10273__7410(.A (n_319), .B (n_305), .Y (n_351));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[8].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_246), .Q
       (DATA_PATH_S2_o_A_high_s[8]));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_267), .Q
       (DATA_PATH_S1_o_input_s[5]), .QN (UNCONNECTED2));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_277), .Q
       (DATA_PATH_S1_o_input_s[4]), .QN (UNCONNECTED3));
  AOI2BB1X4 g10267__6417(.A0N (DATA_PATH_S1_o_input_s[12]), .A1N
       (n_122), .B0 (n_264), .Y (n_304));
  AOI21X4 g10265__5477(.A0 (n_299), .A1 (n_303), .B0 (n_209), .Y
       (n_325));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_251), .Q
       (DATA_PATH_S2_o_A_high_s[3]));
  DFFSHQX8 DATA_PATH_PIPELINE_STAGE2_ready_reg_sig_q_reg(.SN (rst_n),
       .CK (clk), .D (n_274), .Q (ready_o));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_283), .Q
       (DATA_PATH_S1_o_root_s[0]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[14].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_275), .Q
       (DATA_PATH_S1_o_input_s[14]));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[15].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_279), .Q
       (DATA_PATH_S1_o_input_s[15]), .QN (UNCONNECTED4));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_276), .Q
       (DATA_PATH_S1_o_input_s[3]), .QN (UNCONNECTED5));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[8].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_270), .Q
       (DATA_PATH_S1_o_input_s[8]), .QN (UNCONNECTED6));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[9].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_266), .Q
       (DATA_PATH_S1_o_input_s[9]), .QN (UNCONNECTED7));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[10].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_262), .Q
       (DATA_PATH_S1_o_input_s[10]), .QN (UNCONNECTED8));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_271), .Q
       (DATA_PATH_S1_o_input_s[2]), .QN (UNCONNECTED9));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_252), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[0]));
  INVX3 g10266(.A (n_302), .Y (n_379));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[12].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_258), .Q
       (DATA_PATH_S1_o_input_s[12]));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[11].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_261), .Q
       (DATA_PATH_S1_o_input_s[11]), .QN (UNCONNECTED10));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[13].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_268), .Q
       (DATA_PATH_S1_o_input_s[13]), .QN (UNCONNECTED11));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_280), .Q
       (DATA_PATH_S1_o_input_s[6]), .QN (UNCONNECTED12));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_247), .Q
       (DATA_PATH_S2_o_A_high_s[5]));
  DFFRHQX8 DATA_PATH_PIPELINE_STAGE1_wr_square_s_reg_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_272), .Q (DATA_PATH_S1_o_wr_square_s));
  DFFRHQX8 \CONTROL_PATH_CurrentState_reg[1] (.RN (rst_n), .CK (clk),
       .D (n_254), .Q (CONTROL_PATH_CurrentState[1]));
  AOI21X4 g10307__2398(.A0 (n_300), .A1 (n_191), .B0 (n_299), .Y
       (n_301));
  CLKAND2X2 g10309__5107(.A (n_227), .B (n_291), .Y (n_298));
  MX2X1 g10279__6260(.A (DATA_PATH_S1_o_square2_s[8]), .B (n_295), .S0
       (n_397), .Y (n_297));
  MX2X1 g10280__4319(.A (DATA_PATH_S1_o_square1_s[8]), .B (n_295), .S0
       (CONTROL_PATH_CurrentState[1]), .Y (n_296));
  OR3X4 g10305__8428(.A (n_156), .B (n_204), .C (n_293), .Y (n_294));
  OR2X1 g10289__5526(.A (n_278), .B (n_291), .Y (n_292));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_236), .Q
       (DATA_PATH_S1_o_input_s[0]), .QN (UNCONNECTED13));
  NAND2X6 g10274__6783(.A (n_159), .B (n_263), .Y (n_302));
  NAND2X6 g10272__3680(.A (n_303), .B (n_291), .Y (n_346));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_213), .Q
       (DATA_PATH_S2_o_A_high_s[2]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_225), .Q
       (DATA_PATH_S2_o_A_high_s[7]));
  NOR2X4 g10372__1617(.A (n_243), .B (n_229), .Y (n_290));
  AOI31X4 g10312__2802(.A0 (DATA_PATH_S1_o_input_s[4]), .A1 (n_174),
       .A2 (n_203), .B0 (n_184), .Y (n_289));
  AOI211X4 g10261__1705(.A0 (n_287), .A1 (n_208), .B0 (n_131), .C0
       (n_166), .Y (n_288));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_235), .Q
       (DATA_PATH_S1_o_input_s[1]), .QN (UNCONNECTED14));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE2_B_high_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_239), .Q
       (DATA_PATH_S2_o_B_high_s[0]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_215), .Q
       (DATA_PATH_S2_o_A_high_s[0]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_214), .Q
       (DATA_PATH_S2_o_A_high_s[1]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE2_B_high_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_241), .Q
       (DATA_PATH_S2_o_B_high_s[1]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_216), .Q
       (DATA_PATH_S2_o_A_high_s[4]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_237), .Q
       (DATA_PATH_S1_o_input_s[7]));
  NOR2X6 g10318__5122(.A (n_200), .B (n_238), .Y (n_335));
  ADDHX4 g10286__8246(.A (root_o[5]), .B (n_284), .CO (n_285), .S
       (n_305));
  ADDHX1 g10320__7098(.A (n_86), .B (n_281), .CO (n_282), .S (n_283));
  MX2X1 g10417__6131(.A (DATA_PATH_S1_o_input_s[6]), .B (valor_i[6]),
       .S0 (n_355), .Y (n_280));
  MX2X1 g10422__1881(.A (DATA_PATH_S1_o_input_s[15]), .B (valor_i[15]),
       .S0 (n_278), .Y (n_279));
  MX2X1 g10425__5115(.A (DATA_PATH_S1_o_input_s[4]), .B (valor_i[4]),
       .S0 (n_355), .Y (n_277));
  MX2X1 g10426__7482(.A (DATA_PATH_S1_o_input_s[3]), .B (valor_i[3]),
       .S0 (n_260), .Y (n_276));
  MX2X1 g10427__4733(.A (DATA_PATH_S1_o_input_s[14]), .B (valor_i[14]),
       .S0 (n_269), .Y (n_275));
  OAI2BB1X1 g10429__6161(.A0N (ready_o), .A1N (n_278), .B0 (n_273), .Y
       (n_274));
  OAI2BB1X1 g10430__9315(.A0N (DATA_PATH_S1_o_wr_square_s), .A1N
       (n_278), .B0 (n_253), .Y (n_272));
  MX2X1 g10431__9945(.A (DATA_PATH_S1_o_input_s[2]), .B (valor_i[2]),
       .S0 (n_278), .Y (n_271));
  MX2X1 g10432__2883(.A (DATA_PATH_S1_o_input_s[8]), .B (valor_i[8]),
       .S0 (n_269), .Y (n_270));
  MX2X1 g10433__2346(.A (DATA_PATH_S1_o_input_s[13]), .B (valor_i[13]),
       .S0 (n_278), .Y (n_268));
  MX2X1 g10434__1666(.A (DATA_PATH_S1_o_input_s[5]), .B (valor_i[5]),
       .S0 (n_269), .Y (n_267));
  MX2X1 g10436__7410(.A (DATA_PATH_S1_o_input_s[9]), .B (valor_i[9]),
       .S0 (n_269), .Y (n_266));
  INVX1 g10284(.A (n_303), .Y (n_265));
  INVX2 g10285(.A (n_263), .Y (n_264));
  MX2X1 g10438__6417(.A (DATA_PATH_S1_o_input_s[10]), .B (valor_i[10]),
       .S0 (n_355), .Y (n_262));
  MX2X1 g10440__5477(.A (DATA_PATH_S1_o_input_s[11]), .B (valor_i[11]),
       .S0 (n_260), .Y (n_261));
  OR2X1 g10287__2398(.A (n_205), .B (n_189), .Y (n_259));
  MX2X1 g10441__5107(.A (DATA_PATH_S1_o_input_s[12]), .B (valor_i[12]),
       .S0 (n_278), .Y (n_258));
  AOI21X4 g10288__6260(.A0 (n_163), .A1 (n_160), .B0 (n_211), .Y
       (n_257));
  NAND2X8 g10308__4319(.A (n_202), .B (n_194), .Y (n_256));
  OAI21X4 g10310__8428(.A0 (n_198), .A1 (n_155), .B0 (n_183), .Y
       (n_255));
  NAND2X1 g10390__5526(.A (n_253), .B (n_244), .Y (n_254));
  MX2X1 g10368__6783(.A (n_148), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[0]), .S0 (n_278), .Y
       (n_252));
  MX2X1 g10367__3680(.A (n_151), .B (n_44), .S0 (n_278), .Y (n_251));
  NOR2X2 g10327__1617(.A (n_249), .B (n_433), .Y (n_250));
  MX2X1 g10359__2802(.A (n_101), .B (DATA_PATH_S2_o_A_high_s[6]), .S0
       (n_355), .Y (n_248));
  MX2X1 g10361__1705(.A (n_100), .B (DATA_PATH_S2_o_A_high_s[5]), .S0
       (n_355), .Y (n_247));
  OAI2BB1X1 g10355__5122(.A0N (DATA_PATH_S2_o_A_high_s[8]), .A1N
       (n_355), .B0 (n_223), .Y (n_246));
  OR2X2 g10364__8246(.A (n_210), .B (n_249), .Y (n_245));
  DFFRHQX4 \CONTROL_PATH_CurrentState_reg[0] (.RN (rst_n), .CK (clk),
       .D (n_244), .Q (ready_s));
  OAI21X4 g10317__7098(.A0 (n_179), .A1 (n_243), .B0 (n_228), .Y
       (n_286));
  NOR2X6 g10253__6131(.A (n_53), .B (n_187), .Y (n_327));
  NAND2X6 g10314__1881(.A (n_106), .B (n_330), .Y (n_324));
  CLKAND2X6 g10316__5115(.A (DATA_PATH_S2_o_A_high_s[4]), .B (n_330),
       .Y (n_311));
  NAND2X4 g10271__7482(.A (n_207), .B (n_165), .Y (n_242));
  MX2X1 g10418__4733(.A (root_o[7]), .B (DATA_PATH_S2_o_B_high_s[1]),
       .S0 (n_240), .Y (n_241));
  MX2X1 g10419__6161(.A (n_88), .B (DATA_PATH_S2_o_B_high_s[0]), .S0
       (n_240), .Y (n_239));
  NOR2X4 g10358__9315(.A (n_117), .B (n_230), .Y (n_238));
  MX2X1 g10435__9945(.A (DATA_PATH_S1_o_input_s[7]), .B (valor_i[7]),
       .S0 (n_240), .Y (n_237));
  MX2X1 g10437__2883(.A (DATA_PATH_S1_o_input_s[0]), .B (valor_i[0]),
       .S0 (n_240), .Y (n_236));
  MX2X1 g10439__2346(.A (DATA_PATH_S1_o_input_s[1]), .B (valor_i[1]),
       .S0 (n_240), .Y (n_235));
  NOR2X8 g10324__1666(.A (DATA_PATH_S1_o_input_s[7]), .B (n_180), .Y
       (n_234));
  NAND2X2 g10453__7410(.A (DATA_PATH_S2_o_square_adder_sum_l_s[4]), .B
       (n_161), .Y (n_233));
  AND2X1 g10459__6417(.A (n_355), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[7]), .Y (n_232));
  CLKXOR2X1 g10306__5477(.A (n_218), .B (n_217), .Y (n_231));
  XNOR2X2 g10315__2398(.A (n_186), .B (n_127), .Y (n_306));
  NOR2X6 g10290__5107(.A (n_230), .B (n_137), .Y (n_263));
  INVX1 g10379(.A (n_228), .Y (n_229));
  NOR2X4 g10325__6260(.A (n_226), .B (n_433), .Y (n_227));
  MX2X1 g10351__4319(.A (DATA_PATH_S2_o_A_high_s[7]), .B (n_143), .S0
       (n_319), .Y (n_225));
  AND2X1 g10354__8428(.A (n_223), .B (n_182), .Y (n_224));
  OAI21X4 g10357__5526(.A0 (n_87), .A1 (n_435), .B0 (n_220), .Y
       (n_222));
  AOI21X4 g10251__6783(.A0 (n_218), .A1 (n_217), .B0 (n_130), .Y
       (n_219));
  MX2X1 g10363__3680(.A (DATA_PATH_S2_o_A_high_s[4]), .B (n_158), .S0
       (n_319), .Y (n_216));
  MX2X1 g10369__1617(.A (n_142), .B (DATA_PATH_S2_o_A_high_s[0]), .S0
       (n_240), .Y (n_215));
  MX2X1 g10370__2802(.A (n_145), .B (DATA_PATH_S2_o_A_high_s[1]), .S0
       (n_240), .Y (n_214));
  MX2X1 g10371__1705(.A (DATA_PATH_S2_o_A_high_s[2]), .B (n_150), .S0
       (n_173), .Y (n_213));
  NOR2X4 g10374__5122(.A (n_133), .B (n_181), .Y (n_212));
  NOR2X4 g10375__8246(.A (n_153), .B (n_211), .Y (n_323));
  NOR2X4 g10342__7098(.A (n_299), .B (n_210), .Y (n_291));
  NOR2X8 g10377__6131(.A (n_209), .B (n_168), .Y (n_303));
  CLKINVX6 g10302(.A (n_207), .Y (n_208));
  INVX3 g10414(.A (n_205), .Y (n_206));
  INVX2 g10415(.A (n_203), .Y (n_204));
  CLKAND2X6 g10423__1881(.A (n_218), .B (n_201), .Y (n_202));
  OAI2BB1X4 g10362__5115(.A0N (DATA_PATH_S1_o_input_s[15]), .A1N
       (n_178), .B0 (n_140), .Y (n_200));
  AOI2BB1X1 g10360__7482(.A0N (DATA_PATH_S1_o_input_s[8]), .A1N
       (n_154), .B0 (n_198), .Y (n_199));
  NAND2X2 g10311__4733(.A (n_125), .B (n_136), .Y (n_197));
  NAND2X8 g10401__6161(.A (n_196), .B (n_146), .Y (n_228));
  OAI21X2 g10473__9315(.A0 (n_90), .A1 (N_s), .B0 (n_281), .Y (n_244));
  NOR2X8 g10408__9945(.A (n_195), .B (n_141), .Y (n_249));
  CLKAND2X6 g10352__2883(.A (n_193), .B (n_170), .Y (n_194));
  NAND2X4 g10323__2346(.A (n_217), .B (n_287), .Y (n_192));
  INVX2 g10380(.A (n_210), .Y (n_191));
  INVX2 g10550(.A (n_278), .Y (n_190));
  OAI22X4 g10350__1666(.A0 (n_27), .A1 (n_147), .B0
       (DATA_PATH_S1_o_input_s[2]), .B1 (n_221), .Y (n_189));
  NAND3X2 g10321__7410(.A (DATA_PATH_S1_o_input_s[6]), .B
       (DATA_PATH_S1_o_input_s[7]), .C (n_185), .Y (n_188));
  NOR2X4 g10353__6417(.A (n_126), .B (n_186), .Y (n_187));
  OAI22X4 g10373__5477(.A0 (DATA_PATH_S1_o_input_s[7]), .A1 (n_138),
       .B0 (DATA_PATH_S1_o_input_s[6]), .B1 (n_185), .Y (n_293));
  CLKXOR2X1 g10376__2398(.A (DATA_PATH_S2_o_square_adder_co_l_s), .B
       (n_124), .Y (n_295));
  BUFX2 g10547(.A (n_355), .Y (n_362));
  NOR2X8 g10378__5107(.A (n_104), .B (n_149), .Y (n_330));
  CLKAND2X2 g10421__6260(.A (DATA_PATH_S1_o_input_s[5]), .B (n_177), .Y
       (n_184));
  NAND2X4 g10420__4319(.A (DATA_PATH_S1_o_input_s[9]), .B (n_144), .Y
       (n_183));
  NAND2X1 g10455__8428(.A (N_s), .B (n_113), .Y (n_182));
  NOR2X6 g10424__5526(.A (n_114), .B (n_129), .Y (n_181));
  AND2X6 g10446__6783(.A (DATA_PATH_S1_o_input_s[6]), .B (n_185), .Y
       (n_180));
  INVX2 g10416(.A (n_179), .Y (n_220));
  NOR2X6 g10406__3680(.A (DATA_PATH_S1_o_input_s[15]), .B (n_178), .Y
       (n_230));
  CLKAND2X6 g10402__1617(.A (n_40), .B (n_176), .Y (n_243));
  OR2X6 g10448__2802(.A (DATA_PATH_S1_o_input_s[5]), .B (n_177), .Y
       (n_203));
  INVX2 g10552(.A (n_281), .Y (n_260));
  NOR2X4 g10447__1705(.A (DATA_PATH_S1_o_input_s[11]), .B (n_162), .Y
       (n_211));
  NOR2X4 g10443__5122(.A (n_167), .B (n_185), .Y (n_209));
  NOR2X6 g10445__8246(.A (DATA_PATH_S1_o_input_s[3]), .B (n_176), .Y
       (n_205));
  NOR2X4 g10411__7098(.A (n_175), .B (n_177), .Y (n_299));
  CLKAND2X6 g10410__6131(.A (n_175), .B (n_177), .Y (n_210));
  NOR2X4 g10412__1881(.A (n_46), .B (n_174), .Y (n_300));
  CLKINVX6 g10548(.A (n_173), .Y (n_355));
  AND2X1 g10456__5115(.A (n_226), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[5]), .Y (n_172));
  INVX2 g10482(.A (n_170), .Y (n_171));
  INVX1 g10484(.A (n_201), .Y (n_169));
  CLKAND2X2 g10389__7482(.A (n_167), .B (n_185), .Y (n_168));
  CLKINVX3 g10319(.A (n_165), .Y (n_166));
  INVX1 g10542(.A (n_319), .Y (n_164));
  NAND2X4 g10387__4733(.A (DATA_PATH_S1_o_input_s[11]), .B (n_162), .Y
       (n_163));
  INVX1 g10546(.A (n_173), .Y (n_161));
  NAND2X4 g10386__6161(.A (DATA_PATH_S1_o_input_s[10]), .B (n_152), .Y
       (n_160));
  OAI21X4 g10365__9315(.A0 (n_15), .A1 (n_158), .B0 (n_119), .Y
       (n_159));
  AND2X2 g10381__9945(.A (DATA_PATH_S1_o_input_s[3]), .B (n_176), .Y
       (n_157));
  NOR2X2 g10382__2883(.A (DATA_PATH_S1_o_input_s[4]), .B (n_174), .Y
       (n_156));
  NAND2X4 g10384__2346(.A (DATA_PATH_S1_o_input_s[8]), .B (n_154), .Y
       (n_155));
  NOR2X4 g10385__1666(.A (DATA_PATH_S1_o_input_s[10]), .B (n_152), .Y
       (n_153));
  NAND2X6 g10313__7410(.A (n_128), .B (n_115), .Y (n_207));
  INVX2 g10543(.A (n_319), .Y (n_269));
  CLKINVX6 g10551(.A (n_281), .Y (n_278));
  INVX1 g10485(.A (n_162), .Y (n_151));
  INVXL g10479(.A (n_152), .Y (n_150));
  NOR2X4 g10428__6417(.A (n_139), .B (n_109), .Y (n_149));
  INVX1 g10478(.A (n_147), .Y (n_148));
  CLKINVX4 g10490(.A (n_176), .Y (n_146));
  INVX1 g10477(.A (n_144), .Y (n_145));
  INVX1 g10480(.A (n_178), .Y (n_143));
  INVX1 g10483(.A (n_154), .Y (n_142));
  CLKINVX4 g10489(.A (n_174), .Y (n_141));
  NAND2X2 g10442__5477(.A (n_140), .B (n_82), .Y (n_223));
  CLKAND2X3 g10444__2398(.A (n_24), .B (n_108), .Y (n_198));
  NOR2X4 g10409__5107(.A (n_123), .B (n_139), .Y (n_186));
  NOR3X8 g10449__6260(.A (n_48), .B (n_121), .C (n_120), .Y (n_179));
  DFFRX2
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[4].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_110), .Q
       (DATA_PATH_S1_o_square2_s[4]), .QN (UNCONNECTED15));
  CLKINVX6 g10488(.A (n_138), .Y (n_284));
  BUFX3 g10545(.A (n_226), .Y (n_240));
  CLKINVX8 g10544(.A (n_226), .Y (n_319));
  OAI22X4 g10366__4319(.A0 (DATA_PATH_S1_o_input_s[14]), .A1 (n_116),
       .B0 (DATA_PATH_S1_o_input_s[13]), .B1 (n_118), .Y (n_137));
  AOI2BB1X4 g10322__8428(.A0N (n_66), .A1N (n_26), .B0 (n_134), .Y
       (n_136));
  AOI2BB1X4 g10503__5526(.A0N (DATA_PATH_S1_o_root_s[3]), .A1N (n_135),
       .B0 (n_91), .Y (n_170));
  DFFRHQX2
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[7].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_111), .Q
       (DATA_PATH_S1_o_square2_s[7]));
  DFFRHQX2
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[6].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_95), .Q
       (DATA_PATH_S1_o_square2_s[6]));
  AOI2BB1X4 g10501__6783(.A0N (DATA_PATH_S1_o_root_s[4]), .A1N (n_135),
       .B0 (n_94), .Y (n_193));
  DFFRHQX2
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[3].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_103), .Q
       (DATA_PATH_S1_o_square2_s[3]));
  DFFRHQX2
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[5].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_96), .Q
       (DATA_PATH_S1_o_square2_s[5]));
  DFFRHQX2
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[2].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_102), .Q
       (DATA_PATH_S1_o_square2_s[2]));
  NOR2X6 g10326__3680(.A (n_134), .B (n_133), .Y (n_165));
  OR2X1 g10575__1617(.A (n_112), .B (CONTROL_PATH_CurrentState[1]), .Y
       (n_253));
  INVX2 g10631(.A (n_132), .Y (n_273));
  AOI2BB1X4 g10511__2802(.A0N (DATA_PATH_S1_o_root_s[5]), .A1N (n_135),
       .B0 (n_131), .Y (n_287));
  INVX3 g10549(.A (n_226), .Y (n_173));
  AOI2BB1X4 g10505__1705(.A0N (DATA_PATH_S1_o_root_s[6]), .A1N (n_135),
       .B0 (n_92), .Y (n_201));
  AOI2BB1X4 g10510__5122(.A0N (DATA_PATH_S1_o_root_s[2]), .A1N (n_135),
       .B0 (n_130), .Y (n_217));
  CLKINVX8 g10553(.A (n_226), .Y (n_281));
  CLKINVX4 g10450(.A (n_128), .Y (n_129));
  INVX1 g10452(.A (n_126), .Y (n_127));
  INVX2 g10451(.A (n_133), .Y (n_125));
  NOR2X1 g10470__8246(.A (n_123), .B (n_99), .Y (n_124));
  INVX1 g10481(.A (n_158), .Y (n_122));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_77), .Q
       (DATA_PATH_S1_o_square1_s[5]));
  AOI2BB1X4 g10498__7098(.A0N (n_5), .A1N (DATA_PATH_S1_o_wr_square_s),
       .B0 (n_63), .Y (n_147));
  NOR2X4 g10497__6131(.A (n_52), .B (n_70), .Y (n_144));
  NOR2X6 g10500__1881(.A (n_50), .B (n_56), .Y (n_178));
  NOR2X4 g10475__5115(.A (n_121), .B (n_120), .Y (n_221));
  AOI2BB1X4 g10504__7482(.A0N (n_11), .A1N
       (DATA_PATH_S1_o_wr_square_s), .B0 (n_58), .Y (n_154));
  AOI2BB1X4 g10506__4733(.A0N (n_8), .A1N (DATA_PATH_S1_o_wr_square_s),
       .B0 (n_68), .Y (n_162));
  NOR2X4 g10499__6161(.A (n_57), .B (n_65), .Y (n_152));
  NOR2X8 g10509__9315(.A (n_61), .B (n_83), .Y (n_185));
  INVX12 g10554(.A (n_140), .Y (n_226));
  NAND2X2 g10388__9945(.A (DATA_PATH_S1_o_input_s[13]), .B (n_118), .Y
       (n_119));
  NAND2X2 g10383__2883(.A (DATA_PATH_S1_o_input_s[14]), .B (n_116), .Y
       (n_117));
  NOR2X6 g10356__2346(.A (n_54), .B (n_114), .Y (n_115));
  INVX2 g10555(.A (n_140), .Y (n_113));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_75), .Q
       (DATA_PATH_S1_o_square1_s[3]));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_74), .Q
       (DATA_PATH_S1_o_square1_s[0]));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_78), .Q
       (DATA_PATH_S1_o_square1_s[2]));
  DFFSHQX2
       DATA_PATH_PIPELINE_STAGE1_square2_reg_RegSquare2_0_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_76), .Q (DATA_PATH_S1_o_square2_s[0]));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_79), .Q
       (DATA_PATH_S1_o_square1_s[6]));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_73), .Q
       (DATA_PATH_S1_o_square1_s[7]));
  INVX2 g10632(.A (n_112), .Y (n_132));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_51), .Q
       (DATA_PATH_S1_o_square1_s[4]));
  AOI2BB1X4 g10512__1666(.A0N (n_21), .A1N (n_107), .B0 (n_81), .Y
       (n_138));
  NOR2X8 g10515__7410(.A (n_71), .B (n_60), .Y (n_176));
  NOR2X8 g10513__6417(.A (n_67), .B (n_72), .Y (n_174));
  NOR2X8 g10514__5477(.A (n_69), .B (n_64), .Y (n_177));
  MX2X1 g10495__2398(.A (DATA_PATH_S1_o_square2_s[7]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[7]), .S0 (n_397), .Y
       (n_111));
  MX2X1 g10457__5107(.A (DATA_PATH_S1_o_square2_s[4]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[4]), .S0 (n_397), .Y
       (n_110));
  NAND2X4 g10458__6260(.A (n_98), .B (n_49), .Y (n_109));
  AOI21X4 g10460__4319(.A0 (n_10), .A1 (n_107), .B0
       (DATA_PATH_S1_o_input_s[9]), .Y (n_108));
  NAND2X8 g10462__8428(.A (n_97), .B (n_25), .Y (n_104));
  MX2X1 g10463__5526(.A (DATA_PATH_S1_o_square2_s[3]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[3]), .S0 (n_397), .Y
       (n_103));
  MX2X1 g10468__6783(.A (DATA_PATH_S1_o_square2_s[2]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[2]), .S0 (n_397), .Y
       (n_102));
  INVX1 g10487(.A (n_116), .Y (n_101));
  INVX1 g10486(.A (n_118), .Y (n_100));
  NOR2X6 g10472__3680(.A (n_99), .B (n_4), .Y (n_139));
  NAND2X8 g10471__1617(.A (n_33), .B (n_84), .Y (n_128));
  NAND2X4 g10476__2802(.A (n_98), .B (n_97), .Y (n_126));
  NOR2X6 g10474__1705(.A (n_28), .B (n_93), .Y (n_133));
  MX2X1 g10454__5122(.A (DATA_PATH_S1_o_square2_s[5]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[5]), .S0 (n_397), .Y
       (n_96));
  MX2X1 g10496__8246(.A (DATA_PATH_S1_o_square2_s[6]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[6]), .S0 (n_397), .Y
       (n_95));
  NOR2X4 g10534__7098(.A (n_2), .B (n_93), .Y (n_94));
  NOR2X6 g10562__6131(.A (n_37), .B (n_29), .Y (n_92));
  NOR2X4 g10569__1881(.A (n_3), .B (n_93), .Y (n_91));
  INVX1 g10630(.A (n_85), .Y (n_90));
  INVX1 g10609(.A (n_88), .Y (n_89));
  INVX1 g10605(.A (n_86), .Y (n_87));
  INVX2 g10633(.A (n_85), .Y (n_112));
  NOR2X6 g10576__5115(.A (n_14), .B (n_93), .Y (n_134));
  NOR2X8 g10577__7482(.A (n_6), .B (n_30), .Y (n_130));
  NOR2X4 g10572__4733(.A (n_0), .B (n_84), .Y (n_131));
  CLKMX2X3 g10502__6161(.A (DATA_PATH_S1_o_square2_s[12]), .B
       (DATA_PATH_S1_o_square1_s[12]), .S0 (n_107), .Y (n_158));
  OR2X6 g10578__9315(.A (CONTROL_PATH_CurrentState[1]), .B (n_39), .Y
       (n_140));
  CLKAND2X6 g10528__9945(.A (DATA_PATH_S1_o_square1_s[6]), .B (n_107),
       .Y (n_83));
  MX2X1 g10491__2883(.A (DATA_PATH_S1_o_square1_s[16]), .B
       (DATA_PATH_S1_o_square2_s[16]), .S0
       (DATA_PATH_S1_o_wr_square_s), .Y (n_82));
  NOR2X2 g10557__2346(.A (n_17), .B (DATA_PATH_S1_o_wr_square_s), .Y
       (n_81));
  INVX1 g10625(.A (n_175), .Y (n_80));
  MX2X1 g10464__1666(.A (DATA_PATH_S1_o_square1_s[6]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[6]), .S0
       (CONTROL_PATH_CurrentState[1]), .Y (n_79));
  MX2X1 g10465__7410(.A (DATA_PATH_S1_o_square1_s[2]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[2]), .S0
       (CONTROL_PATH_CurrentState[1]), .Y (n_78));
  MX2X1 g10466__6417(.A (DATA_PATH_S1_o_square1_s[5]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[5]), .S0
       (CONTROL_PATH_CurrentState[1]), .Y (n_77));
  MX2X1 g10467__5477(.A (DATA_PATH_S2_o_square_adder_sum_l_s[0]), .B
       (DATA_PATH_S1_o_square2_s[0]), .S0
       (CONTROL_PATH_CurrentState[1]), .Y (n_76));
  MX2X1 g10469__2398(.A (DATA_PATH_S1_o_square1_s[3]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[3]), .S0
       (CONTROL_PATH_CurrentState[1]), .Y (n_75));
  MX2X1 g10492__5107(.A (DATA_PATH_S1_o_square1_s[0]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[0]), .S0
       (CONTROL_PATH_CurrentState[1]), .Y (n_74));
  MX2X1 g10494__6260(.A (DATA_PATH_S1_o_square1_s[7]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[7]), .S0
       (CONTROL_PATH_CurrentState[1]), .Y (n_73));
  AND2X6 g10527__4319(.A (DATA_PATH_S1_o_square1_s[4]), .B (n_107), .Y
       (n_72));
  NOR2X4 g10526__8428(.A (n_23), .B (n_107), .Y (n_71));
  CLKAND2X3 g10525__5526(.A (DATA_PATH_S1_o_square1_s[9]), .B (n_107),
       .Y (n_70));
  NOR2X6 g10520__6783(.A (n_20), .B (n_107), .Y (n_69));
  NOR2X6 g10521__3680(.A (n_18), .B (n_107), .Y (n_68));
  NOR2BX4 g10522__1617(.AN (DATA_PATH_S1_o_square2_s[4]), .B (n_107),
       .Y (n_67));
  BUFX2 g10634(.A (n_66), .Y (n_85));
  MXI2X4 g10508__2802(.A (DATA_PATH_S1_o_square1_s[14]), .B
       (DATA_PATH_S1_o_square2_s[14]), .S0
       (DATA_PATH_S1_o_wr_square_s), .Y (n_116));
  INVX2 g10518(.A (n_114), .Y (n_218));
  MXI2X4 g10507__1705(.A (DATA_PATH_S1_o_square1_s[13]), .B
       (DATA_PATH_S1_o_square2_s[13]), .S0
       (DATA_PATH_S1_o_wr_square_s), .Y (n_118));
  AND2X4 g10556__5122(.A (DATA_PATH_S1_o_square1_s[10]), .B (n_107), .Y
       (n_65));
  CLKAND2X6 g10533__8246(.A (DATA_PATH_S1_o_square1_s[5]), .B (n_107),
       .Y (n_64));
  NOR2X4 g10535__7098(.A (n_9), .B (n_107), .Y (n_63));
  NAND2X1 g10558__6131(.A (DATA_PATH_S1_o_square1_s[14]), .B (n_397),
       .Y (n_62));
  NOR2X6 g10561__1881(.A (n_12), .B (n_107), .Y (n_61));
  CLKAND2X6 g10564__5115(.A (DATA_PATH_S1_o_square1_s[3]), .B (n_107),
       .Y (n_60));
  NAND2X1 g10565__7482(.A (DATA_PATH_S1_o_square1_s[12]), .B (n_397),
       .Y (n_59));
  NOR2X2 g10568__4733(.A (n_16), .B (n_107), .Y (n_58));
  NOR2BX2 g10570__6161(.AN (DATA_PATH_S1_o_square2_s[10]), .B (n_107),
       .Y (n_57));
  CLKAND2X3 g10530__9315(.A (DATA_PATH_S1_o_square1_s[15]), .B (n_107),
       .Y (n_56));
  INVX1 g10616(.A (n_167), .Y (n_55));
  NOR2X4 g10560__9945(.A (DATA_PATH_S1_o_root_s[4]), .B (n_135), .Y
       (n_54));
  INVX2 g10517(.A (n_98), .Y (n_53));
  NOR2X2 g10529__2883(.A (n_13), .B (n_107), .Y (n_52));
  MX2X1 g10493__2346(.A (DATA_PATH_S1_o_square1_s[4]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[4]), .S0
       (CONTROL_PATH_CurrentState[1]), .Y (n_51));
  NOR2BX4 g10531__1666(.AN (DATA_PATH_S1_o_square2_s[15]), .B (n_107),
       .Y (n_50));
  NOR2X6 g10574__7410(.A (n_22), .B (n_107), .Y (n_121));
  INVX4 g10516(.A (n_49), .Y (n_123));
  BUFX2 g10606(.A (n_48), .Y (n_86));
  BUFX2 g10610(.A (root_o[6]), .Y (n_88));
  CLKAND2X6 g10573__6417(.A (DATA_PATH_S1_o_square1_s[2]), .B (n_107),
       .Y (n_120));
  CLKINVX3 g10621(.A (n_46), .Y (n_195));
  INVX1 g10601(.A (n_44), .Y (n_45));
  CLKAND2X2 g10559__5477(.A (DATA_PATH_S2_o_A_high_s[7]), .B
       (DATA_PATH_S2_o_A_high_s[4]), .Y (n_43));
  NAND2X1 g10563__2398(.A (DATA_PATH_S1_o_square2_s[12]), .B
       (CONTROL_PATH_CurrentState[1]), .Y (n_42));
  CLKINVX6 g10613(.A (n_40), .Y (root_o[1]));
  INVX2 g10636(.A (n_135), .Y (n_39));
  CLKINVX3 g10622(.A (root_o[2]), .Y (n_46));
  CLKINVX6 g10611(.A (n_37), .Y (root_o[6]));
  INVX2 g10607(.A (n_31), .Y (n_48));
  NOR2X6 g10536__5107(.A (DATA_PATH_S2_o_B_high_s[0]), .B
       (DATA_PATH_S2_o_A_high_s[0]), .Y (n_99));
  CLKAND2X2 g10537__6260(.A (DATA_PATH_S2_o_A_high_s[6]), .B
       (DATA_PATH_S2_o_A_high_s[5]), .Y (n_105));
  NAND2X6 g10539__4319(.A (DATA_PATH_S2_o_B_high_s[0]), .B
       (DATA_PATH_S2_o_A_high_s[0]), .Y (n_49));
  OR2X6 g10538__8428(.A (DATA_PATH_S2_o_B_high_s[1]), .B
       (DATA_PATH_S2_o_A_high_s[1]), .Y (n_97));
  INVX2 g10626(.A (root_o[3]), .Y (n_175));
  NAND2X8 g10541__5526(.A (DATA_PATH_S1_o_root_s[1]), .B
       (DATA_PATH_S1_o_root_s[0]), .Y (n_114));
  INVX2 g10617(.A (root_o[4]), .Y (n_167));
  NAND2X1 g10566__6783(.A (DATA_PATH_S1_o_square2_s[14]), .B
       (CONTROL_PATH_CurrentState[1]), .Y (n_34));
  NAND2X6 g10567__3680(.A (DATA_PATH_S1_o_root_s[3]), .B
       (DATA_PATH_S1_o_root_s[2]), .Y (n_33));
  CLKINVX6 g10604(.A (n_31), .Y (root_o[0]));
  CLKINVX8 g10639(.A (n_135), .Y (n_30));
  CLKINVX6 g10629(.A (n_135), .Y (n_29));
  NOR2X4 g10532__1617(.A (DATA_PATH_S1_o_root_s[3]), .B
       (DATA_PATH_S1_o_root_s[2]), .Y (n_28));
  OR2X1 g10571__2802(.A (DATA_PATH_S1_o_input_s[1]), .B
       (DATA_PATH_S1_o_input_s[0]), .Y (n_27));
  NOR2X2 g10519__1705(.A (DATA_PATH_S1_o_root_s[6]), .B
       (DATA_PATH_S1_o_root_s[5]), .Y (n_26));
  CLKAND2X3 g10523__5122(.A (DATA_PATH_S2_o_A_high_s[2]), .B
       (DATA_PATH_S2_o_A_high_s[3]), .Y (n_25));
  NAND2BX1 g10524__8246(.AN (DATA_PATH_S1_o_square2_s[9]), .B
       (DATA_PATH_S1_o_wr_square_s), .Y (n_24));
  INVX3 g10635(.A (n_135), .Y (n_66));
  INVX2 g10614(.A (n_40), .Y (n_196));
  CLKINVX8 g10638(.A (n_135), .Y (n_84));
  NAND2X8 g10540__7098(.A (DATA_PATH_S2_o_B_high_s[1]), .B
       (DATA_PATH_S2_o_A_high_s[1]), .Y (n_98));
  CLKINVX12 g10637(.A (n_135), .Y (n_93));
  INVX2 g10600(.A (DATA_PATH_S1_o_square2_s[3]), .Y (n_23));
  INVX2 g10594(.A (DATA_PATH_S1_o_square2_s[2]), .Y (n_22));
  INVX1 g10599(.A (DATA_PATH_S1_o_square2_s[7]), .Y (n_21));
  INVX2 g10580(.A (DATA_PATH_S1_o_square2_s[5]), .Y (n_20));
  INVX1 g10586(.A (DATA_PATH_S2_o_square_adder_sum_l_s[3]), .Y (n_19));
  INVX2 g10579(.A (DATA_PATH_S1_o_square2_s[11]), .Y (n_18));
  INVX2 g10598(.A (DATA_PATH_S1_o_square1_s[7]), .Y (n_17));
  INVX2 g10581(.A (DATA_PATH_S1_o_square2_s[8]), .Y (n_16));
  INVX2 g10585(.A (DATA_PATH_S1_o_input_s[12]), .Y (n_15));
  INVX2 g10620(.A (DATA_PATH_S1_o_root_s[4]), .Y (n_14));
  INVX2 g10587(.A (DATA_PATH_S1_o_square2_s[9]), .Y (n_13));
  BUFX2 g10602(.A (DATA_PATH_S2_o_A_high_s[3]), .Y (n_44));
  BUFX16 g10618(.A (DATA_PATH_S1_o_root_s[4]), .Y (root_o[4]));
  INVX3 g10608(.A (DATA_PATH_S1_o_root_s[0]), .Y (n_31));
  INVX2 g10590(.A (DATA_PATH_S2_o_A_high_s[2]), .Y (n_328));
  CLKINVX16 g10640(.A (ready_s), .Y (n_135));
  CLKINVX4 g10641(.A (CONTROL_PATH_CurrentState[1]), .Y (n_397));
  CLKINVX20 g10593(.A (DATA_PATH_S1_o_wr_square_s), .Y (n_107));
  INVX2 g10595(.A (DATA_PATH_S1_o_square2_s[6]), .Y (n_12));
  INVX1 g10597(.A (DATA_PATH_S1_o_square1_s[8]), .Y (n_11));
  INVX2 g10584(.A (DATA_PATH_S1_o_square1_s[9]), .Y (n_10));
  INVX2 g10583(.A (DATA_PATH_S1_o_square2_s[0]), .Y (n_9));
  INVX1 g10596(.A (DATA_PATH_S1_o_square1_s[11]), .Y (n_8));
  INVX1 g10603(.A (DATA_PATH_S2_o_square_adder_sum_l_s[6]), .Y (n_7));
  INVX2 g10624(.A (DATA_PATH_S1_o_root_s[2]), .Y (n_6));
  INVX1 g10582(.A (DATA_PATH_S1_o_square1_s[0]), .Y (n_5));
  INVX3 g10588(.A (DATA_PATH_S2_o_square_adder_co_l_s), .Y (n_4));
  INVX2 g10628(.A (DATA_PATH_S1_o_root_s[3]), .Y (n_3));
  INVX2 g10619(.A (DATA_PATH_S1_o_root_s[4]), .Y (n_2));
  INVX1 g10589(.A (DATA_PATH_S2_o_A_high_s[7]), .Y (n_1));
  INVX2 g10591(.A (DATA_PATH_S1_o_root_s[5]), .Y (n_0));
  INVX3 g10612(.A (DATA_PATH_S1_o_root_s[6]), .Y (n_37));
  BUFX12 g10627(.A (DATA_PATH_S1_o_root_s[3]), .Y (root_o[3]));
  BUFX12 g10623(.A (DATA_PATH_S1_o_root_s[2]), .Y (root_o[2]));
  INVX2 g10615(.A (DATA_PATH_S1_o_root_s[1]), .Y (n_40));
  BUFX6 g10592(.A (DATA_PATH_S1_o_root_s[5]), .Y (root_o[5]));
  INVX2 fopt(.A (n_431), .Y (n_430));
  CLKINVX8 fopt1(.A (n_286), .Y (n_431));
  BUFX6 fopt10722(.A (n_433), .Y (n_432));
  BUFX6 fopt10723(.A (n_300), .Y (n_433));
  BUFX6 fopt10724(.A (n_436), .Y (n_435));
  BUFX6 fopt10725(.A (n_221), .Y (n_436));
  CLKINVX4 fopt10726(.A (n_439), .Y (n_438));
  INVX2 fopt10727(.A (n_377), .Y (n_439));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[14].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_398), .Q
       (DATA_PATH_S1_o_square2_s[14]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[14].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_396), .Q
       (DATA_PATH_S1_o_square1_s[14]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[10].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_367), .Q
       (DATA_PATH_S1_o_square2_s[10]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[15].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_385), .Q
       (DATA_PATH_S1_o_square1_s[15]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[15].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_399), .Q
       (DATA_PATH_S1_o_square2_s[15]));
  CLKAND2X4 g10747__6131(.A (n_105), .B (n_43), .Y (n_106));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[13].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_383), .Q
       (DATA_PATH_S1_o_square2_s[13]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[13].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_391), .Q
       (DATA_PATH_S1_o_square1_s[13]));
endmodule

