
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep  9 2025 14:05:51 -03 (Sep  9 2025 17:05:51 UTC)

// Verification Directory fv/square_root_pipe 

module square_root_pipe(valor_i, clk, rst_n, ready_o, root_o);
  input [15:0] valor_i;
  input clk, rst_n;
  output ready_o;
  output [7:0] root_o;
  wire [15:0] valor_i;
  wire clk, rst_n;
  wire ready_o;
  wire [7:0] root_o;
  wire [7:0] DATA_PATH_S2_o_square_adder_sum_l_s;
  wire [16:0] DATA_PATH_S1_o_square1_s;
  wire [16:0] DATA_PATH_S1_o_square2_s;
  wire [8:0] DATA_PATH_S2_o_A_high_s;
  wire [7:0] DATA_PATH_S1_o_root_s;
  wire [15:0] DATA_PATH_S1_o_input_s;
  wire [1:0] CONTROL_PATH_CurrentState;
  wire [8:0] DATA_PATH_S2_o_B_high_s;
  wire DATA_PATH_S1_o_wr_square_s, DATA_PATH_S2_o_square_adder_co_l_s,
       N_s, UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3;
  wire UNCONNECTED4, UNCONNECTED5, UNCONNECTED6, UNCONNECTED7,
       UNCONNECTED8, UNCONNECTED9, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_35, n_37, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_114, n_115, n_116, n_117;
  wire n_118, n_119, n_120, n_121, n_122, n_123, n_124, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_132, n_133;
  wire n_134, n_135, n_136, n_137, n_139, n_140, n_141, n_142;
  wire n_143, n_144, n_145, n_146, n_147, n_148, n_149, n_150;
  wire n_151, n_152, n_153, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_169, n_170, n_171, n_172, n_173, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_180, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_207, n_208, n_209, n_210, n_211, n_212, n_213, n_214;
  wire n_215, n_216, n_217, n_218, n_219, n_220, n_221, n_222;
  wire n_223, n_224, n_225, n_226, n_227, n_228, n_229, n_230;
  wire n_231, n_232, n_233, n_234, n_235, n_236, n_237, n_238;
  wire n_239, n_240, n_241, n_242, n_243, n_244, n_245, n_246;
  wire n_247, n_248, n_249, n_250, n_251, n_252, n_253, n_254;
  wire n_255, n_256, n_257, n_258, n_259, n_260, n_261, n_262;
  wire n_263, n_264, n_265, n_266, n_267, n_268, n_269, n_270;
  wire n_271, n_272, n_273, n_274, n_275, n_276, n_277, n_278;
  wire n_279, n_280, n_281, n_282, n_283, n_284, n_285, n_286;
  wire n_287, n_288, n_289, n_290, n_291, n_292, n_293, n_294;
  wire n_295, n_296, n_297, n_298, n_299, n_300, n_301, n_302;
  wire n_303, n_304, n_305, n_306, n_307, n_308, n_309, n_310;
  wire n_311, n_312, n_313, n_314, ready_s;
  DFFRHQX1 DATA_PATH_PIPELINE_STAGE2_Co_reg_sig_q_reg(.RN (rst_n), .CK
       (clk), .D (n_314), .Q (DATA_PATH_S2_o_square_adder_co_l_s));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_313), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[7]));
  DFFRHQX1 DATA_PATH_PIPELINE_STAGE2_N_reg_sig_q_reg(.RN (rst_n), .CK
       (clk), .D (n_312), .Q (N_s));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[16].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_309), .Q
       (DATA_PATH_S1_o_square1_s[16]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[16].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_310), .Q
       (DATA_PATH_S1_o_square2_s[16]));
  MX2X1 g6416__2398(.A (DATA_PATH_S2_o_square_adder_co_l_s), .B
       (n_299), .S0 (n_311), .Y (n_314));
  MX3X1 g6418__5107(.A (n_298), .B (n_219), .C
       (DATA_PATH_S2_o_square_adder_sum_l_s[7]), .S0 (n_297), .S1
       (n_229), .Y (n_313));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[15].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_306), .Q
       (DATA_PATH_S1_o_square2_s[15]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[15].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_301), .Q
       (DATA_PATH_S1_o_square1_s[15]));
  CLKMX2X3 g6464__6260(.A (N_s), .B (n_296), .S0 (n_311), .Y (n_312));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[12].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_305), .Q
       (DATA_PATH_S1_o_square2_s[12]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[12].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_303), .Q
       (DATA_PATH_S1_o_square1_s[12]));
  OAI22X2 g6421__4319(.A0 (n_307), .A1 (n_308), .B0 (n_152), .B1
       (n_66), .Y (n_310));
  OAI22X2 g6422__8428(.A0 (n_67), .A1 (n_308), .B0 (n_153), .B1
       (n_307), .Y (n_309));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_295), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[6]));
  MX2X1 g6427__5526(.A (DATA_PATH_S1_o_square2_s[15]), .B (n_300), .S0
       (n_304), .Y (n_306));
  MX2X1 g6434__6783(.A (DATA_PATH_S1_o_square2_s[12]), .B (n_302), .S0
       (n_304), .Y (n_305));
  DFFRHQX8 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_294), .Q (root_o[7]));
  MX2X1 g6435__3680(.A (DATA_PATH_S1_o_square1_s[12]), .B (n_302), .S0
       (n_285), .Y (n_303));
  MX2X1 g6425__1617(.A (DATA_PATH_S1_o_square1_s[15]), .B (n_300), .S0
       (n_307), .Y (n_301));
  OAI21X2 g6420__2802(.A0 (n_298), .A1 (n_297), .B0 (n_224), .Y
       (n_299));
  NAND2X4 g6478__1705(.A (n_169), .B (n_290), .Y (n_296));
  MX2X1 g6430__5122(.A (DATA_PATH_S2_o_square_adder_sum_l_s[6]), .B
       (n_284), .S0 (n_311), .Y (n_295));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[14].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_287), .Q
       (DATA_PATH_S1_o_square1_s[14]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[14].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_288), .Q
       (DATA_PATH_S1_o_square2_s[14]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[11].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_293), .Q
       (DATA_PATH_S1_o_square1_s[11]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[11].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_292), .Q
       (DATA_PATH_S1_o_square2_s[11]));
  XNOR2X1 g6428__8246(.A (DATA_PATH_S2_o_A_high_s[8]), .B (n_289), .Y
       (n_308));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[13].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_283), .Q
       (DATA_PATH_S1_o_square1_s[13]));
  XNOR2X1 g6466__7098(.A (root_o[7]), .B (n_280), .Y (n_294));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[13].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_282), .Q
       (DATA_PATH_S1_o_square2_s[13]));
  MX2X1 g6445__6131(.A (DATA_PATH_S1_o_square1_s[11]), .B (n_291), .S0
       (n_307), .Y (n_293));
  MX2X1 g6446__1881(.A (DATA_PATH_S1_o_square2_s[11]), .B (n_291), .S0
       (n_304), .Y (n_292));
  NAND2X4 g6483__5115(.A (n_254), .B (n_276), .Y (n_290));
  OA21X1 g6442__7482(.A0 (DATA_PATH_S2_o_A_high_s[4]), .A1 (n_269), .B0
       (n_266), .Y (n_302));
  AOI2BB1X2 g6441__4733(.A0N (DATA_PATH_S2_o_A_high_s[7]), .A1N
       (n_277), .B0 (n_289), .Y (n_300));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_275), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[5]));
  MX2X1 g6440__6161(.A (DATA_PATH_S1_o_square2_s[14]), .B (n_286), .S0
       (n_304), .Y (n_288));
  MX2X1 g6439__9315(.A (DATA_PATH_S1_o_square1_s[14]), .B (n_286), .S0
       (n_285), .Y (n_287));
  NOR2X4 g6436__9945(.A (n_215), .B (n_274), .Y (n_297));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[10].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_271), .Q
       (DATA_PATH_S1_o_square2_s[10]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[10].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_272), .Q
       (DATA_PATH_S1_o_square1_s[10]));
  DFFRHQX8 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_279), .Q (root_o[6]));
  DFFRHQX8 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_278), .Q (root_o[5]));
  XNOR2X1 g6447__2883(.A (n_222), .B (n_273), .Y (n_284));
  MX2X1 g6456__2346(.A (DATA_PATH_S1_o_square1_s[13]), .B (n_281), .S0
       (n_307), .Y (n_283));
  MX2X1 g6457__1666(.A (DATA_PATH_S1_o_square2_s[13]), .B (n_281), .S0
       (n_304), .Y (n_282));
  OAI2BB1X2 g6480__7410(.A0N (ready_s), .A1N (n_267), .B0 (n_268), .Y
       (n_280));
  MX2X1 g6477__6417(.A (root_o[6]), .B (n_263), .S0 (n_311), .Y
       (n_279));
  MX2X1 g6488__5477(.A (root_o[5]), .B (n_260), .S0 (n_311), .Y
       (n_278));
  CLKAND2X6 g6443__2398(.A (DATA_PATH_S2_o_A_high_s[7]), .B (n_277), .Y
       (n_289));
  OAI21X4 g6493__5107(.A0 (n_250), .A1 (n_261), .B0 (n_248), .Y
       (n_276));
  MX2X1 g6451__6260(.A (DATA_PATH_S2_o_square_adder_sum_l_s[5]), .B
       (n_259), .S0 (n_311), .Y (n_275));
  NOR2X6 g6450__4319(.A (n_223), .B (n_273), .Y (n_274));
  MX2X1 g6461__8428(.A (DATA_PATH_S1_o_square1_s[10]), .B (n_270), .S0
       (n_285), .Y (n_272));
  MX2X1 g6462__5526(.A (DATA_PATH_S1_o_square2_s[10]), .B (n_270), .S0
       (n_304), .Y (n_271));
  ADDHX1 g6452__6783(.A (DATA_PATH_S2_o_A_high_s[3]), .B (n_262), .CO
       (n_269), .S (n_291));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_264), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[4]));
  CLKXOR2X1 g6458__3680(.A (DATA_PATH_S2_o_A_high_s[6]), .B (n_265), .Y
       (n_286));
  OA21X1 g6489__1617(.A0 (ready_s), .A1 (n_267), .B0 (n_311), .Y
       (n_268));
  AOI21X2 g6471__2802(.A0 (n_6), .A1 (n_266), .B0 (n_265), .Y (n_281));
  NOR2X4 g6455__1705(.A (n_159), .B (n_257), .Y (n_273));
  CLKAND2X6 g6463__5122(.A (DATA_PATH_S2_o_A_high_s[6]), .B (n_265), .Y
       (n_277));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[4].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_258), .Q (DATA_PATH_S1_o_root_s[4]),
       .QN (UNCONNECTED));
  MX2X1 g6470__8246(.A (DATA_PATH_S2_o_square_adder_sum_l_s[4]), .B
       (n_240), .S0 (n_311), .Y (n_264));
  XNOR2X1 g6498__7098(.A (n_249), .B (n_237), .Y (n_263));
  AOI2BB1X1 g6479__6131(.A0N (DATA_PATH_S2_o_A_high_s[2]), .A1N
       (n_252), .B0 (n_262), .Y (n_270));
  OA21X4 g6508__1881(.A0 (n_242), .A1 (n_234), .B0 (n_233), .Y (n_261));
  XNOR2X1 g6502__5115(.A (n_216), .B (n_235), .Y (n_260));
  XNOR2X1 g6467__7482(.A (n_256), .B (n_255), .Y (n_259));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[3].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_253), .Q (DATA_PATH_S1_o_root_s[3]),
       .QN (UNCONNECTED0));
  MX2X1 g6487__4733(.A (n_37), .B (n_227), .S0 (n_311), .Y (n_258));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[9].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_245), .Q
       (DATA_PATH_S1_o_square2_s[9]));
  CLKAND2X6 g6481__6161(.A (DATA_PATH_S2_o_A_high_s[5]), .B (n_251), .Y
       (n_265));
  NOR2BX4 g6468__9315(.AN (n_256), .B (n_255), .Y (n_257));
  AOI2BB1X2 g6527__9945(.A0N (n_177), .A1N (n_247), .B0 (n_246), .Y
       (n_254));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[9].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_244), .Q
       (DATA_PATH_S1_o_square1_s[9]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_241), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[3]));
  MX2X1 g6496__2883(.A (n_35), .B (n_218), .S0 (n_311), .Y (n_253));
  CLKAND2X2 g6485__2346(.A (DATA_PATH_S2_o_A_high_s[2]), .B (n_252), .Y
       (n_262));
  INVX2 g6482(.A (n_251), .Y (n_266));
  OR2X1 g6526__1666(.A (n_228), .B (n_232), .Y (n_250));
  AOI21X2 g6500__7410(.A0 (n_249), .A1 (n_236), .B0 (n_124), .Y
       (n_267));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_230), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[2]));
  AOI2BB1X2 g6531__6417(.A0N (DATA_PATH_S1_o_input_s[12]), .A1N
       (n_176), .B0 (n_247), .Y (n_248));
  OAI2BB1X2 g6533__5477(.A0N (DATA_PATH_S1_o_input_s[15]), .A1N
       (n_220), .B0 (n_221), .Y (n_246));
  MX2X1 g6491__2398(.A (DATA_PATH_S1_o_square2_s[9]), .B (n_243), .S0
       (n_304), .Y (n_245));
  MX2X1 g6490__5107(.A (DATA_PATH_S1_o_square1_s[9]), .B (n_243), .S0
       (n_285), .Y (n_244));
  NOR2X4 g6484__6260(.A (n_41), .B (n_226), .Y (n_251));
  AOI21X4 g6474__4319(.A0 (n_239), .A1 (n_238), .B0 (n_213), .Y
       (n_255));
  OAI22X4 g6525__8428(.A0 (n_210), .A1 (n_212), .B0 (n_172), .B1
       (n_197), .Y (n_242));
  MX2X1 g6499__5526(.A (DATA_PATH_S2_o_square_adder_sum_l_s[3]), .B
       (n_211), .S0 (n_311), .Y (n_241));
  CLKXOR2X1 g6497__6783(.A (n_239), .B (n_238), .Y (n_240));
  NOR2X1 g6510__3680(.A (n_123), .B (n_236), .Y (n_237));
  OR3X1 g6513__1617(.A (n_74), .B (n_185), .C (n_206), .Y (n_235));
  AOI21X2 g6520__2802(.A0 (n_202), .A1 (n_175), .B0 (n_225), .Y
       (n_234));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[8].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_217), .Q
       (DATA_PATH_S2_o_A_high_s[8]));
  AOI2BB1X2 g6532__1705(.A0N (DATA_PATH_S1_o_input_s[8]), .A1N (n_164),
       .B0 (n_231), .Y (n_233));
  NOR2X2 g6530__5122(.A (n_165), .B (n_231), .Y (n_232));
  MX2X1 g6528__8246(.A (n_194), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[2]), .S0 (n_229), .Y
       (n_230));
  OAI21X2 g6534__7098(.A0 (n_173), .A1 (n_201), .B0 (n_200), .Y
       (n_228));
  XNOR2X1 g6501__6131(.A (n_179), .B (n_187), .Y (n_227));
  INVX2 g6492(.A (n_226), .Y (n_252));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_208), .Q
       (DATA_PATH_S2_o_A_high_s[7]));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_207), .Q
       (DATA_PATH_S1_o_root_s[2]));
  NAND2X2 g6554__1881(.A (n_171), .B (n_209), .Y (n_225));
  INVX1 g6539(.A (n_214), .Y (n_224));
  INVX2 g6536(.A (n_222), .Y (n_223));
  OAI21X2 g6555__5115(.A0 (DATA_PATH_S1_o_input_s[15]), .A1 (n_220),
       .B0 (n_192), .Y (n_221));
  INVX2 g6538(.A (n_219), .Y (n_298));
  NOR2X6 g6494__7482(.A (n_52), .B (n_184), .Y (n_226));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[1].dffn_sig_q_reg (.RN
       (rst_n), .CK (clk), .D (n_203), .Q (DATA_PATH_S1_o_root_s[1]),
       .QN (UNCONNECTED1));
  OAI21X4 g6562__4733(.A0 (DATA_PATH_S1_o_input_s[14]), .A1 (n_155),
       .B0 (n_193), .Y (n_247));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_188), .Q
       (DATA_PATH_S2_o_A_high_s[6]));
  XNOR2X1 g6507__6161(.A (n_186), .B (n_168), .Y (n_218));
  MX2X1 g6603__9315(.A (n_170), .B (DATA_PATH_S2_o_A_high_s[8]), .S0
       (n_229), .Y (n_217));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[8].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_181), .Q
       (DATA_PATH_S1_o_square1_s[8]));
  DFFRHQX1
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[8].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_182), .Q
       (DATA_PATH_S1_o_square2_s[8]));
  NOR2X4 g6512__9945(.A (n_216), .B (n_205), .Y (n_236));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_190), .Q
       (DATA_PATH_S2_o_A_high_s[4]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_198), .Q
       (DATA_PATH_S2_o_A_high_s[0]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_189), .Q
       (DATA_PATH_S2_o_A_high_s[5]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_191), .Q
       (DATA_PATH_S2_o_A_high_s[1]));
  ADDHX1 g6540__2883(.A (n_20), .B (n_196), .CO (n_215), .S (n_222));
  ADDHX1 g6543__2346(.A (root_o[5]), .B (n_195), .CO (n_214), .S
       (n_219));
  ADDHX2 g6541__1666(.A (n_11), .B (n_136), .CO (n_213), .S (n_239));
  AOI21X2 g6557__7410(.A0 (n_149), .A1 (n_125), .B0 (n_88), .Y (n_212));
  XNOR2X1 g6529__6417(.A (n_204), .B (n_135), .Y (n_211));
  INVX2 g6589(.A (n_209), .Y (n_210));
  NAND2X6 g6560__5477(.A (n_163), .B (n_174), .Y (n_231));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_167), .Q
       (DATA_PATH_S2_o_A_high_s[2]));
  MX2X1 g6612__2398(.A (n_156), .B (DATA_PATH_S2_o_A_high_s[7]), .S0
       (n_229), .Y (n_208));
  MX2X1 g6516__5107(.A (n_154), .B (n_33), .S0 (n_229), .Y (n_207));
  INVX1 g6519(.A (n_205), .Y (n_206));
  XNOR2X1 g6509__6260(.A (n_63), .B (n_183), .Y (n_243));
  OAI21X4 g6505__4319(.A0 (n_204), .A1 (n_134), .B0 (n_71), .Y (n_238));
  DFFRHQX4 DATA_PATH_PIPELINE_STAGE1_wr_square_s_reg_sig_q_reg(.RN
       (rst_n), .CK (clk), .D (n_161), .Q (DATA_PATH_S1_o_wr_square_s));
  CLKXOR2X1 g6535__8428(.A (n_50), .B (n_139), .Y (n_203));
  NAND2X2 g6559__5526(.A (n_158), .B (n_83), .Y (n_202));
  NOR2X4 g6565__6783(.A (DATA_PATH_S1_o_input_s[11]), .B (n_199), .Y
       (n_201));
  NAND2X2 g6566__3680(.A (DATA_PATH_S1_o_input_s[11]), .B (n_199), .Y
       (n_200));
  MX2X1 g6605__1617(.A (n_133), .B (DATA_PATH_S2_o_A_high_s[0]), .S0
       (n_229), .Y (n_198));
  OA21X1 g6591__2802(.A0 (n_25), .A1 (n_196), .B0 (n_195), .Y (n_197));
  NAND2BX1 g6597__1705(.AN (n_204), .B (n_151), .Y (n_194));
  AOI2BB1X4 g6601__5122(.A0N (DATA_PATH_S1_o_input_s[15]), .A1N
       (n_192), .B0 (n_147), .Y (n_193));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_A_high_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_143), .Q
       (DATA_PATH_S2_o_A_high_s[3]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_sum_low_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_142), .Q
       (DATA_PATH_S2_o_square_adder_sum_l_s[0]));
  MX2X1 g6606__8246(.A (n_162), .B (DATA_PATH_S2_o_A_high_s[1]), .S0
       (n_229), .Y (n_191));
  MX2X1 g6609__7098(.A (n_137), .B (DATA_PATH_S2_o_A_high_s[4]), .S0
       (n_229), .Y (n_190));
  MX2X1 g6610__6131(.A (n_130), .B (DATA_PATH_S2_o_A_high_s[5]), .S0
       (n_229), .Y (n_189));
  MX2X1 g6611__1881(.A (n_160), .B (DATA_PATH_S2_o_A_high_s[6]), .S0
       (n_229), .Y (n_188));
  AOI21X1 g6518__5115(.A0 (n_186), .A1 (n_178), .B0 (n_185), .Y
       (n_187));
  NOR2X4 g6511__7482(.A (n_64), .B (n_183), .Y (n_184));
  MX2X1 g6515__4733(.A (DATA_PATH_S1_o_square2_s[8]), .B (n_180), .S0
       (n_304), .Y (n_182));
  MX2X1 g6517__6161(.A (DATA_PATH_S1_o_square1_s[8]), .B (n_180), .S0
       (n_285), .Y (n_181));
  NAND3X6 g6521__9315(.A (n_186), .B (n_179), .C (n_178), .Y (n_205));
  NOR2X6 g6613__9945(.A (n_150), .B (n_145), .Y (n_209));
  AOI22X1 g6599__2883(.A0 (DATA_PATH_S1_o_input_s[13]), .A1 (n_146),
       .B0 (DATA_PATH_S1_o_input_s[12]), .B1 (n_176), .Y (n_177));
  OAI21X2 g6556__2346(.A0 (n_114), .A1 (n_157), .B0 (n_132), .Y
       (n_175));
  AOI22X4 g6590__1666(.A0 (n_5), .A1 (n_173), .B0 (n_141), .B1 (n_166),
       .Y (n_174));
  AOI21X2 g6593__7410(.A0 (DATA_PATH_S1_o_input_s[6]), .A1 (n_144), .B0
       (n_78), .Y (n_172));
  AOI2BB1X4 g6594__6417(.A0N (DATA_PATH_S1_o_input_s[4]), .A1N (n_148),
       .B0 (n_126), .Y (n_171));
  INVX1 g6689(.A (n_169), .Y (n_170));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_root_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_140), .Q
       (DATA_PATH_S1_o_root_s[0]));
  NOR2X1 g6522__5477(.A (n_61), .B (n_178), .Y (n_168));
  MX2X1 g6607__2398(.A (n_166), .B (DATA_PATH_S2_o_A_high_s[2]), .S0
       (n_229), .Y (n_167));
  AOI22X2 g6600__5107(.A0 (DATA_PATH_S1_o_input_s[9]), .A1 (n_129), .B0
       (DATA_PATH_S1_o_input_s[8]), .B1 (n_164), .Y (n_165));
  NAND2BX4 g6621__6260(.AN (DATA_PATH_S1_o_input_s[9]), .B (n_162), .Y
       (n_163));
  OAI2BB1X1 g6649__4319(.A0N (n_92), .A1N (n_229), .B0 (n_127), .Y
       (n_161));
  NOR2BX2 g6639__8428(.AN (DATA_PATH_S1_o_input_s[14]), .B (n_160), .Y
       (n_220));
  DFFRHQX1 \CONTROL_PATH_CurrentState_reg[1] (.RN (rst_n), .CK (clk),
       .D (n_128), .Q (CONTROL_PATH_CurrentState[1]));
  ADDHX1 g6542__5526(.A (n_18), .B (n_87), .CO (n_159), .S (n_256));
  AO21X1 g6596__6783(.A0 (DATA_PATH_S1_o_input_s[3]), .A1 (n_131), .B0
       (n_157), .Y (n_158));
  INVX1 g6696(.A (n_192), .Y (n_156));
  INVX1 g6695(.A (n_160), .Y (n_155));
  XNOR2X1 g6558__3680(.A (n_121), .B (n_32), .Y (n_154));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_93), .Q
       (DATA_PATH_S1_o_input_s[1]), .QN (UNCONNECTED2));
  OA22X1 g6699__1617(.A0 (n_62), .A1 (n_153), .B0 (n_91), .B1 (n_152),
       .Y (n_169));
  DFFRX2
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[6].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_98), .Q
       (DATA_PATH_S1_o_square2_s[6]), .QN (UNCONNECTED3));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_106), .Q
       (DATA_PATH_S1_o_square1_s[6]), .QN (UNCONNECTED4));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[2].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_102), .Q
       (DATA_PATH_S1_o_square2_s[2]));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_118), .Q
       (DATA_PATH_S1_o_input_s[0]), .QN (UNCONNECTED5));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_115), .Q
       (DATA_PATH_S1_o_input_s[2]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_79), .Q
       (DATA_PATH_S1_o_input_s[7]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_99), .Q
       (DATA_PATH_S1_o_square1_s[4]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_107), .Q
       (DATA_PATH_S1_o_square1_s[3]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_96), .Q
       (DATA_PATH_S1_o_square1_s[5]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[4].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_108), .Q
       (DATA_PATH_S1_o_square2_s[4]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_95), .Q
       (DATA_PATH_S1_o_square1_s[0]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[8].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_86), .Q
       (DATA_PATH_S1_o_input_s[8]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[4].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_85), .Q
       (DATA_PATH_S1_o_input_s[4]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[9].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_77), .Q
       (DATA_PATH_S1_o_input_s[9]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[14].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_111), .Q
       (DATA_PATH_S1_o_input_s[14]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[12].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_116), .Q
       (DATA_PATH_S1_o_input_s[12]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[13].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_113), .Q
       (DATA_PATH_S1_o_input_s[13]));
  DFFRHQX4 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[3].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_112), .Q
       (DATA_PATH_S1_o_input_s[3]));
  OR2X1 g6655__2802(.A (n_42), .B (n_157), .Y (n_151));
  NOR2X4 g6644__1705(.A (n_21), .B (n_122), .Y (n_150));
  CLKAND2X2 g6623__5122(.A (DATA_PATH_S1_o_input_s[4]), .B (n_148), .Y
       (n_149));
  NOR2X2 g6620__8246(.A (DATA_PATH_S1_o_input_s[13]), .B (n_146), .Y
       (n_147));
  NOR2X4 g6619__7098(.A (DATA_PATH_S1_o_input_s[6]), .B (n_144), .Y
       (n_145));
  MX2X1 g6608__6131(.A (n_173), .B (DATA_PATH_S2_o_A_high_s[3]), .S0
       (n_229), .Y (n_143));
  MX2X1 g6604__1881(.A (n_70), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[0]), .S0 (n_229), .Y
       (n_142));
  DFFSHQX2
       DATA_PATH_PIPELINE_STAGE1_square2_reg_RegSquare2_0_sig_q_reg(.SN
       (rst_n), .CK (clk), .D (n_101), .Q
       (DATA_PATH_S1_o_square2_s[0]));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[3].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_100), .Q
       (DATA_PATH_S1_o_square2_s[3]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[10].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_119), .Q
       (DATA_PATH_S1_o_input_s[10]));
  DFFRHQX2 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[2].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_103), .Q
       (DATA_PATH_S1_o_square1_s[2]));
  DFFRHQX2
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[7].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_97), .Q
       (DATA_PATH_S1_o_square2_s[7]));
  NOR2X6 g6635__5115(.A (n_141), .B (n_166), .Y (n_199));
  DFFSHQX8 DATA_PATH_PIPELINE_STAGE2_ready_reg_sig_q_reg(.SN (rst_n),
       .CK (clk), .D (n_84), .Q (ready_o));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_square1_reg_reg[7].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_94), .Q
       (DATA_PATH_S1_o_square1_s[7]), .QN (UNCONNECTED6));
  DFFRHQX4
       \DATA_PATH_PIPELINE_STAGE1_square2_reg_reg_array[5].RegSquare2_inst_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_105), .Q
       (DATA_PATH_S1_o_square2_s[5]));
  NOR2X6 g6523__7482(.A (n_53), .B (n_90), .Y (n_183));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[5].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_82), .Q
       (DATA_PATH_S1_o_input_s[5]));
  DFFRHQX8 \DATA_PATH_PIPELINE_STAGE2_B_high_reg_reg[0].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_109), .Q
       (DATA_PATH_S2_o_B_high_s[0]));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE2_B_high_reg_reg[1].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_80), .Q
       (DATA_PATH_S2_o_B_high_s[1]));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[6].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_81), .Q
       (DATA_PATH_S1_o_input_s[6]), .QN (UNCONNECTED7));
  DFFRX2 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[11].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_117), .Q
       (DATA_PATH_S1_o_input_s[11]), .QN (UNCONNECTED8));
  DFFRHQX1 \DATA_PATH_PIPELINE_STAGE1_input_reg_reg[15].dffn_sig_q_reg
       (.RN (rst_n), .CK (clk), .D (n_110), .Q
       (DATA_PATH_S1_o_input_s[15]));
  ADDHX1 g6564__4733(.A (root_o[0]), .B (n_311), .CO (n_139), .S
       (n_140));
  INVX1 g6692(.A (n_176), .Y (n_137));
  CLKINVX2 g6697(.A (n_148), .Y (n_136));
  INVX1 g6537(.A (n_134), .Y (n_135));
  INVX1 g6691(.A (n_164), .Y (n_133));
  OA22X1 g6598__6161(.A0 (n_15), .A1 (n_69), .B0
       (DATA_PATH_S1_o_input_s[3]), .B1 (n_131), .Y (n_132));
  INVX1 g6694(.A (n_146), .Y (n_130));
  INVX3 g6693(.A (n_129), .Y (n_162));
  INVX2 g6669(.A (n_144), .Y (n_196));
  NAND2X1 g6645__9315(.A (n_120), .B (n_127), .Y (n_128));
  INVX2 g6616(.A (n_125), .Y (n_126));
  OR2X1 g6602__9945(.A (n_72), .B (n_123), .Y (n_124));
  CLKXOR2X1 g6561__2883(.A (DATA_PATH_S2_o_square_adder_co_l_s), .B
       (n_89), .Y (n_180));
  INVX2 g6698(.A (n_122), .Y (n_195));
  AOI22X4 g6711__2346(.A0 (n_47), .A1 (DATA_PATH_S1_o_square1_s[15]),
       .B0 (n_59), .B1 (DATA_PATH_S1_o_square2_s[15]), .Y (n_192));
  OAI2BB1X4 g6710__1666(.A0N (n_68), .A1N
       (DATA_PATH_S1_o_square1_s[14]), .B0 (n_65), .Y (n_160));
  CLKAND2X3 g6579__7410(.A (n_31), .B (n_121), .Y (n_178));
  DFFRHQX4 \CONTROL_PATH_CurrentState_reg[0] (.RN (rst_n), .CK (clk),
       .D (n_120), .Q (ready_s));
  MX2X1 g6657__6417(.A (DATA_PATH_S1_o_input_s[10]), .B (valor_i[10]),
       .S0 (n_229), .Y (n_119));
  MX2X1 g6658__5477(.A (DATA_PATH_S1_o_input_s[0]), .B (valor_i[0]),
       .S0 (n_229), .Y (n_118));
  MX2X1 g6659__2398(.A (DATA_PATH_S1_o_input_s[11]), .B (valor_i[11]),
       .S0 (n_229), .Y (n_117));
  MX2X1 g6660__5107(.A (DATA_PATH_S1_o_input_s[12]), .B (valor_i[12]),
       .S0 (n_229), .Y (n_116));
  MX2X1 g6661__6260(.A (n_114), .B (valor_i[2]), .S0 (n_229), .Y
       (n_115));
  MX2X1 g6662__4319(.A (DATA_PATH_S1_o_input_s[13]), .B (valor_i[13]),
       .S0 (n_229), .Y (n_113));
  MX2X1 g6663__8428(.A (DATA_PATH_S1_o_input_s[3]), .B (valor_i[3]),
       .S0 (n_229), .Y (n_112));
  MX2X1 g6664__5526(.A (DATA_PATH_S1_o_input_s[14]), .B (valor_i[14]),
       .S0 (n_229), .Y (n_111));
  MX2X1 g6665__6783(.A (DATA_PATH_S1_o_input_s[15]), .B (valor_i[15]),
       .S0 (n_229), .Y (n_110));
  MX2X1 g6666__3680(.A (root_o[6]), .B (DATA_PATH_S2_o_B_high_s[0]),
       .S0 (n_229), .Y (n_109));
  MX2X1 g6670__1617(.A (DATA_PATH_S1_o_square2_s[4]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[4]), .S0 (n_304), .Y
       (n_108));
  MX2X1 g6672__2802(.A (DATA_PATH_S2_o_square_adder_sum_l_s[3]), .B
       (DATA_PATH_S1_o_square1_s[3]), .S0 (n_304), .Y (n_107));
  MX2X1 g6673__1705(.A (DATA_PATH_S2_o_square_adder_sum_l_s[6]), .B
       (DATA_PATH_S1_o_square1_s[6]), .S0 (n_104), .Y (n_106));
  MX2X1 g6674__5122(.A (DATA_PATH_S1_o_square2_s[5]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[5]), .S0 (n_104), .Y
       (n_105));
  MX2X1 g6675__8246(.A (DATA_PATH_S2_o_square_adder_sum_l_s[2]), .B
       (DATA_PATH_S1_o_square1_s[2]), .S0 (n_104), .Y (n_103));
  MX2X1 g6676__7098(.A (DATA_PATH_S1_o_square2_s[2]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[2]), .S0 (n_304), .Y
       (n_102));
  MX2X1 g6677__6131(.A (DATA_PATH_S1_o_square2_s[0]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[0]), .S0 (n_304), .Y
       (n_101));
  MX2X1 g6678__1881(.A (DATA_PATH_S1_o_square2_s[3]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[3]), .S0 (n_104), .Y
       (n_100));
  MX2X1 g6679__5115(.A (DATA_PATH_S2_o_square_adder_sum_l_s[4]), .B
       (DATA_PATH_S1_o_square1_s[4]), .S0 (n_304), .Y (n_99));
  MX2X1 g6680__7482(.A (DATA_PATH_S1_o_square2_s[6]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[6]), .S0 (n_104), .Y
       (n_98));
  MX2X1 g6681__4733(.A (DATA_PATH_S1_o_square2_s[7]), .B
       (DATA_PATH_S2_o_square_adder_sum_l_s[7]), .S0 (n_104), .Y
       (n_97));
  MX2X1 g6682__6161(.A (DATA_PATH_S2_o_square_adder_sum_l_s[5]), .B
       (DATA_PATH_S1_o_square1_s[5]), .S0 (n_104), .Y (n_96));
  MX2X1 g6683__9315(.A (DATA_PATH_S2_o_square_adder_sum_l_s[0]), .B
       (DATA_PATH_S1_o_square1_s[0]), .S0 (n_304), .Y (n_95));
  MX2X1 g6684__9945(.A (DATA_PATH_S2_o_square_adder_sum_l_s[7]), .B
       (DATA_PATH_S1_o_square1_s[7]), .S0 (n_104), .Y (n_94));
  MX2X1 g6656__2883(.A (DATA_PATH_S1_o_input_s[1]), .B (valor_i[1]),
       .S0 (n_229), .Y (n_93));
  INVX1 g6770(.A (n_91), .Y (n_92));
  CLKAND2X3 g6592__2346(.A (DATA_PATH_S2_o_square_adder_co_l_s), .B
       (n_89), .Y (n_90));
  NOR2BX2 g6622__1666(.AN (DATA_PATH_S1_o_input_s[5]), .B (n_87), .Y
       (n_88));
  MX2X1 g6643__7410(.A (DATA_PATH_S1_o_input_s[8]), .B (valor_i[8]),
       .S0 (n_229), .Y (n_86));
  MX2X1 g6646__6417(.A (DATA_PATH_S1_o_input_s[4]), .B (valor_i[4]),
       .S0 (n_229), .Y (n_85));
  OAI2BB1X1 g6648__5477(.A0N (ready_o), .A1N (n_229), .B0 (n_73), .Y
       (n_84));
  OA22X1 g6595__2398(.A0 (n_14), .A1 (n_131), .B0 (n_22), .B1
       (DATA_PATH_S1_o_input_s[3]), .Y (n_83));
  MX2X1 g6650__5107(.A (DATA_PATH_S1_o_input_s[5]), .B (valor_i[5]),
       .S0 (n_229), .Y (n_82));
  MX2X1 g6651__6260(.A (DATA_PATH_S1_o_input_s[6]), .B (valor_i[6]),
       .S0 (n_229), .Y (n_81));
  MX2X1 g6652__4319(.A (root_o[7]), .B (DATA_PATH_S2_o_B_high_s[1]),
       .S0 (n_229), .Y (n_80));
  MX2X1 g6653__8428(.A (n_78), .B (valor_i[7]), .S0 (n_229), .Y (n_79));
  MX2X1 g6654__5526(.A (DATA_PATH_S1_o_input_s[9]), .B (valor_i[9]),
       .S0 (n_229), .Y (n_77));
  XNOR2X2 g6614__6783(.A (n_19), .B (n_131), .Y (n_134));
  MXI2X4 g6706__3680(.A (DATA_PATH_S1_o_square1_s[9]), .B
       (DATA_PATH_S1_o_square2_s[9]), .S0 (n_76), .Y (n_129));
  NAND2X6 g6636__1617(.A (n_7), .B (n_87), .Y (n_125));
  NOR2X6 g6715__2802(.A (n_55), .B (n_43), .Y (n_122));
  CLKMX2X3 g6702__1705(.A (DATA_PATH_S1_o_square1_s[10]), .B
       (DATA_PATH_S1_o_square2_s[10]), .S0 (n_76), .Y (n_166));
  MXI2X2 g6704__5122(.A (DATA_PATH_S1_o_square1_s[8]), .B
       (DATA_PATH_S1_o_square2_s[8]), .S0 (n_75), .Y (n_164));
  NOR2X4 g6714__8246(.A (n_39), .B (n_56), .Y (n_148));
  MXI2X2 g6705__7098(.A (DATA_PATH_S1_o_square1_s[12]), .B
       (DATA_PATH_S1_o_square2_s[12]), .S0 (n_75), .Y (n_176));
  NOR2X8 g6688__6131(.A (n_57), .B (n_60), .Y (n_144));
  AOI22X4 g6709__1881(.A0 (n_58), .A1 (DATA_PATH_S1_o_square1_s[13]),
       .B0 (n_40), .B1 (DATA_PATH_S1_o_square2_s[13]), .Y (n_146));
  NOR2X8 g6713__5115(.A (n_46), .B (n_45), .Y (n_157));
  ADDHX2 g6617__7482(.A (n_73), .B (DATA_PATH_S1_o_root_s[4]), .CO
       (n_74), .S (n_179));
  ADDHX1 g6618__4733(.A (n_73), .B (root_o[6]), .CO (n_72), .S (n_249));
  OR2X1 g6647__6161(.A (n_29), .B (n_131), .Y (n_71));
  INVX1 g6690(.A (n_69), .Y (n_70));
  MX2X1 g6685__9315(.A (n_27), .B (n_4), .S0 (ready_s), .Y (n_120));
  OAI21X4 g6667__9945(.A0 (ready_s), .A1 (n_23), .B0 (n_54), .Y
       (n_123));
  CLKMX2X3 g6707__2883(.A (DATA_PATH_S1_o_square2_s[11]), .B
       (DATA_PATH_S1_o_square1_s[11]), .S0 (n_68), .Y (n_173));
  INVX1 g6780(.A (n_307), .Y (n_67));
  INVX1 g6778(.A (n_285), .Y (n_66));
  NAND2X4 g6733__2346(.A (n_75), .B (DATA_PATH_S1_o_square2_s[14]), .Y
       (n_65));
  INVX2 g6615(.A (n_63), .Y (n_64));
  INVX2 g6771(.A (n_62), .Y (n_91));
  AOI2BB1X4 g6712__1666(.A0N (DATA_PATH_S1_o_root_s[2]), .A1N (n_73),
       .B0 (n_61), .Y (n_121));
  CLKAND2X6 g6721__7410(.A (DATA_PATH_S1_o_square1_s[6]), .B (n_28), .Y
       (n_60));
  INVX2 g6767(.A (n_58), .Y (n_59));
  NOR2X6 g6726__6417(.A (n_68), .B (n_1), .Y (n_57));
  NOR2X4 g6723__5477(.A (n_9), .B (n_44), .Y (n_56));
  NOR2X6 g6725__2398(.A (n_68), .B (n_3), .Y (n_55));
  INVX2 g6668(.A (n_54), .Y (n_185));
  AOI2BB1X4 g6708__5107(.A0N (DATA_PATH_S2_o_B_high_s[0]), .A1N
       (DATA_PATH_S2_o_A_high_s[0]), .B0 (n_53), .Y (n_89));
  OAI22X2 g6703__6260(.A0 (n_73), .A1 (root_o[5]), .B0 (ready_s), .B1
       (n_2), .Y (n_216));
  AOI22X4 g6700__4319(.A0 (DATA_PATH_S1_o_square1_s[0]), .A1 (n_51),
       .B0 (DATA_PATH_S1_o_square2_s[0]), .B1 (n_13), .Y (n_69));
  AOI2BB1X4 g6701__8428(.A0N (DATA_PATH_S2_o_B_high_s[1]), .A1N
       (DATA_PATH_S2_o_A_high_s[1]), .B0 (n_52), .Y (n_63));
  CLKMX2X3 g6687__5526(.A (DATA_PATH_S1_o_square2_s[5]), .B
       (DATA_PATH_S1_o_square1_s[5]), .S0 (n_51), .Y (n_87));
  INVX1 g6748(.A (n_48), .Y (n_50));
  CLKINVX6 g6749(.A (n_48), .Y (root_o[1]));
  INVX2 g6769(.A (n_75), .Y (n_47));
  AND2X6 g6731__6783(.A (DATA_PATH_S1_o_square2_s[2]), .B (n_24), .Y
       (n_46));
  NOR2X4 g6719__3680(.A (n_44), .B (n_0), .Y (n_45));
  CLKAND2X3 g6722__1617(.A (DATA_PATH_S1_o_square1_s[7]), .B (n_68), .Y
       (n_43));
  BUFX2 g6772(.A (n_75), .Y (n_62));
  OR2X1 g6736__2802(.A (n_73), .B (n_26), .Y (n_127));
  CLKMX2X3 g6716__1705(.A (n_73), .B (ready_s), .S0
       (DATA_PATH_S1_o_root_s[3]), .Y (n_186));
  INVX2 g6779(.A (n_104), .Y (n_285));
  INVX2 g6781(.A (n_104), .Y (n_307));
  INVX1 g6792(.A (n_30), .Y (n_42));
  NAND3X2 g6671__5122(.A (DATA_PATH_S2_o_A_high_s[4]), .B
       (DATA_PATH_S2_o_A_high_s[3]), .C (DATA_PATH_S2_o_A_high_s[2]),
       .Y (n_41));
  INVX2 g6766(.A (n_68), .Y (n_40));
  NOR2X4 g6720__8246(.A (n_8), .B (n_51), .Y (n_39));
  BUFX6 g6756(.A (n_37), .Y (root_o[4]));
  BUFX6 g6768(.A (n_68), .Y (n_58));
  NOR2X4 g6735__7098(.A (ready_s), .B (n_10), .Y (n_61));
  MXI2X4 g6717__6131(.A (DATA_PATH_S1_o_square1_s[3]), .B
       (DATA_PATH_S1_o_square2_s[3]), .S0 (DATA_PATH_S1_o_wr_square_s),
       .Y (n_131));
  CLKINVX8 g6728(.A (n_311), .Y (n_229));
  BUFX6 g6753(.A (n_35), .Y (root_o[3]));
  BUFX6 g6797(.A (n_33), .Y (root_o[2]));
  INVX1 g6718(.A (n_31), .Y (n_32));
  BUFX6 g6793(.A (n_30), .Y (root_o[0]));
  OAI21X4 g6686__1881(.A0 (DATA_PATH_S1_o_root_s[2]), .A1
       (DATA_PATH_S1_o_root_s[3]), .B0 (n_73), .Y (n_54));
  BUFX2 g6750(.A (n_29), .Y (n_48));
  CLKINVX6 g6764(.A (n_28), .Y (n_76));
  CLKINVX4 g6773(.A (n_68), .Y (n_75));
  BUFX3 g6782(.A (n_27), .Y (n_104));
  INVX3 g6776(.A (n_26), .Y (n_304));
  NAND2X1 g6724__5115(.A (DATA_PATH_S1_o_input_s[7]), .B
       (DATA_PATH_S1_o_input_s[6]), .Y (n_25));
  CLKINVX4 g6762(.A (n_51), .Y (n_24));
  NOR2X4 g6730__7482(.A (DATA_PATH_S1_o_root_s[4]), .B (root_o[5]), .Y
       (n_23));
  BUFX2 g6743(.A (n_22), .Y (n_114));
  AND2X6 g6734__4733(.A (DATA_PATH_S2_o_B_high_s[0]), .B
       (DATA_PATH_S2_o_A_high_s[0]), .Y (n_53));
  BUFX2 g6745(.A (n_21), .Y (n_78));
  BUFX2 g6794(.A (n_16), .Y (n_30));
  CLKINVX6 g6761(.A (n_51), .Y (n_44));
  BUFX2 g6757(.A (n_20), .Y (n_37));
  BUFX2 g6751(.A (n_19), .Y (n_29));
  BUFX2 g6754(.A (n_18), .Y (n_35));
  INVX1 g6795(.A (n_16), .Y (n_17));
  OR2X1 g6729__6161(.A (DATA_PATH_S1_o_input_s[1]), .B
       (DATA_PATH_S1_o_input_s[0]), .Y (n_15));
  AND2X1 g6732__9315(.A (DATA_PATH_S1_o_input_s[2]), .B
       (DATA_PATH_S1_o_input_s[3]), .Y (n_14));
  CLKINVX6 g6765(.A (n_13), .Y (n_28));
  BUFX2 g6777(.A (n_12), .Y (n_26));
  AND2X1 g6727__9945(.A (DATA_PATH_S1_o_root_s[0]), .B
       (DATA_PATH_S1_o_root_s[1]), .Y (n_31));
  INVX2 g6783(.A (n_12), .Y (n_27));
  AND2X4 g6737__2883(.A (DATA_PATH_S2_o_B_high_s[1]), .B
       (DATA_PATH_S2_o_A_high_s[1]), .Y (n_52));
  BUFX2 g6798(.A (n_11), .Y (n_33));
  CLKINVX12 g6774(.A (n_13), .Y (n_68));
  OR2X4 g6738__2346(.A (ready_s), .B (CONTROL_PATH_CurrentState[1]), .Y
       (n_311));
  INVX2 g6800(.A (DATA_PATH_S1_o_root_s[2]), .Y (n_10));
  INVX2 g6789(.A (DATA_PATH_S1_o_square1_s[4]), .Y (n_9));
  INVX2 g6741(.A (DATA_PATH_S1_o_square2_s[4]), .Y (n_8));
  INVX2 g6742(.A (DATA_PATH_S1_o_input_s[5]), .Y (n_7));
  INVX1 g6791(.A (DATA_PATH_S2_o_A_high_s[5]), .Y (n_6));
  INVX2 g6747(.A (DATA_PATH_S1_o_input_s[11]), .Y (n_5));
  BUFX2 g6744(.A (DATA_PATH_S1_o_input_s[2]), .Y (n_22));
  BUFX2 g6746(.A (DATA_PATH_S1_o_input_s[7]), .Y (n_21));
  INVX2 g6786(.A (DATA_PATH_S1_o_square2_s[16]), .Y (n_152));
  BUFX2 g6755(.A (DATA_PATH_S1_o_root_s[3]), .Y (n_18));
  BUFX2 g6799(.A (DATA_PATH_S1_o_root_s[2]), .Y (n_11));
  INVX2 g6787(.A (DATA_PATH_S1_o_square1_s[16]), .Y (n_153));
  INVX1 g6788(.A (N_s), .Y (n_4));
  INVX2 g6785(.A (DATA_PATH_S1_o_square2_s[7]), .Y (n_3));
  INVX2 g6759(.A (root_o[5]), .Y (n_2));
  INVX2 g6740(.A (DATA_PATH_S1_o_square2_s[6]), .Y (n_1));
  INVX2 g6739(.A (DATA_PATH_S1_o_square1_s[2]), .Y (n_0));
  BUFX2 g6796(.A (DATA_PATH_S1_o_root_s[0]), .Y (n_16));
  INVX2 g6790(.A (DATA_PATH_S1_o_input_s[10]), .Y (n_141));
  BUFX2 g6784(.A (CONTROL_PATH_CurrentState[1]), .Y (n_12));
  INVX2 g6752(.A (DATA_PATH_S1_o_root_s[1]), .Y (n_19));
  BUFX2 g6758(.A (DATA_PATH_S1_o_root_s[4]), .Y (n_20));
  BUFX6 g6775(.A (DATA_PATH_S1_o_wr_square_s), .Y (n_13));
  CLKINVX8 g6763(.A (DATA_PATH_S1_o_wr_square_s), .Y (n_51));
  CLKINVX8 g6760(.A (ready_s), .Y (n_73));
  ADDHX4 g6882__1666(.A (n_17), .B (n_157), .CO (n_204), .S
       (UNCONNECTED9));
endmodule

